### ISSUE TITLE
Block with negative width & height crashes the compiler

### ISSUE THREAD

**Issue by johannes-wolf** [typst/typst#5486] opened 2024-11-27 22:33 UTC
### Description

The following code crashes the compiler:
```
#block(width: -1cm, height: -1cm, [Test])
```

Log:
```
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9:
assertion failed: min <= max
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-11-28 00:28
Duplicate of https://github.com/typst/typst/issues/5262

**Closed by Enivex** 2024-11-28 00:28 UTC
Labels: bug
