### ISSUE TITLE
Localized Number Display

### ISSUE THREAD

**Issue by ju6ge** [typst/typst#3152] opened 2024-01-08 13:43 UTC
### Description

Hey Guys,

first of all thanks for creating typst ;)

Anyway maybe I am missing something but I could not find it in the docs and also no related issues. I am trying to display all numbers in a document according to the locale. Meaning I have tried the following. 

```typst
#set text(lang: "de",region: "DE")
1.2
```
I would expect the output to in the final document to look like this: 1,2. Since in Germany that is how you write floating point numbers.  

Is there something like this?

### Use Case

Usecase described above.

**Comment by mkpoli** [comment] 2024-01-08 15:14
Duplicate of #1093, #448

**Closed** 2024-01-08 15:31 UTC
Labels: feature request
