### ISSUE TITLE
typst uses other font that specified despite using fallback: false 

### ISSUE THREAD

**Issue by JeyRunner** [typst/typst#2917] opened 2023-12-11 18:25 UTC
### Description

When specifying the font `Roboto` with the option `fallback: false` while having both fonts `Roboto` and `Roboto Condensed` installed on the system the wrong font `Roboto Condensed` is selected.

Code to reproduce:
```typst
#text(
  font: "Roboto",
  fallback: false
)[
  This is Roboto!
]
```
The embedded font in the pdf is `SUIXSO+RobotoCondensed-Regular`.

When `Roboto Condensed`  is removed from the system typst uses the correct font  `Roboto` (embedded font in the pdf is `SUIXSO+Roboto-Regular`).

When both are installed on the system the output of `fc-list : | grep Roboto` is:
```bash
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Thin.ttf: Roboto,Roboto Thin:style=Thin,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-MediumItalic.ttf: Roboto,Roboto Medium:style=Medium Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-Italic.ttf: Roboto Condensed:style=Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-Bold.ttf: Roboto Condensed:style=Bold
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-Medium.ttf: Roboto Condensed,Roboto Condensed Medium:style=Medium,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-ThinItalic.ttf: Roboto,Roboto Thin:style=Thin Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-LightItalic.ttf: Roboto,Roboto Light:style=Light Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-BoldItalic.ttf: Roboto Condensed:style=Bold Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-LightItalic.ttf: Roboto Condensed,Roboto Condensed Light:style=Light Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Italic.ttf: Roboto:style=Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-BlackItalic.ttf: Roboto,Roboto Black:style=Black Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-Light.ttf: Roboto Condensed,Roboto Condensed Light:style=Light,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-MediumItalic.ttf: Roboto Condensed,Roboto Condensed Medium:style=Medium Italic,Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Medium.ttf: Roboto,Roboto Medium:style=Medium,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Bold.ttf: Roboto:style=Bold
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Black.ttf: Roboto,Roboto Black:style=Black,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Light.ttf: Roboto,Roboto Light:style=Light,Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-Regular.ttf: Roboto:style=Regular
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/Roboto-BoldItalic.ttf: Roboto:style=Bold Italic
/usr/share/fonts/truetype/roboto/unhinted/RobotoCondensed-Regular.ttf: Roboto Condensed:style=Regular
```

At the same time, typst does not seem to differentiate between the two fonts:
```bash
typst fonts | grep Roboto    # when both fonts are installed
> Roboto
```

Also forcing typst to first look at the specific folder of one of the fonts does not change the list of discovered fonts.
Both seem to be interpreted as `Roboto`:
```bash
# folder with RobotoCondensed
typst fonts --font-path /usr/share/fonts/truetype/roboto/unhinted/ | grep Roboto
> Roboto

# folder with Roboto
typst fonts --font-path /usr/share/fonts/truetype/roboto/unhinted/RobotoTTF | grep Roboto
> Roboto
```

Used system: linux (22.04.1-Ubuntu)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment] 2023-12-12 04:39
I did some digging and it turns out the font selection is based on font family and font variant. Both `Roboto` and `Roboto Condensed`'s family name is "Roboto", as printed by the compiler. In fact, both fonts are registered in Typst's internal font book as
```
FontInfo { family: "Roboto", variant: Normal-400-FontStretch(1000), flags: FontFlags(0x0), coverage: Coverage(..) }
```
So Typst has no way to differentiate the two.

I think there's a bug in ttf_parser (a dependency of Typst) because it returns the same family name for the two font files, but with `fc-scan --format="%{family}\n" [path]` I can verify the family names are different. One is `Roboto Condensed` and one is simply `Roboto`.

**Comment by laurmaedje** [comment] 2023-12-12 10:14
> So Typst has no way to differentiate the two.

Typst differentiates between the two via `#set text(stretch: 75%)` (condensed) and `#set text(stretch: 100%)` (normal). Although I don't know why it would select Roboto Condensed here if both are available. Maybe the metadata of Roboto Condensed is wrong.

**Comment by laurmaedje** [comment] 2023-12-12 10:16
While I want to retain this capability, I do agree that the current font grouping results in problems in some cases, because fonts are just such as mess. Also see: https://github.com/typst/typst/issues/2098

**Comment by Enivex** [comment] 2023-12-12 11:22
This is a duplicate of https://github.com/typst/typst/issues/576 I think?

**Comment by JeyRunner** [comment] 2023-12-12 11:26
Thank you both for looking into this :)

Yes #2098 would solve the issue. Maybe it would be nice to have a separate field in `text` for the full family name, like `font-full-name`.

Meanwhile, this could be fixed by just adding a separate case for the Roboto font in `typographic_family` (note that I am new to the code base and not a rust expert...):
```rust
fn typographic_family(mut family: &str) -> &str {
    // ...
     // Trim style suffixes repeatedly.
    while trimmed.len() < len {
        len = trimmed.len();

        // Find style suffix.
        let mut t = trimmed;
        let mut shortened = false;
        while let Some(s) = SUFFIXES.iter().chain(extra).find_map(|s| {
                // dont't remove condensed from font 'Roboto Condensed'
                if t.contains("roboto") && s.contains("condensed") {
                    return None;
                }
                t.strip_suffix(s)
            }) {
            shortened = true;
            t = s;
        }
   // ...
```
But obviously, this is very hacky...

**Comment by laurmaedje** [comment] 2023-12-12 14:57
Closing in favor of https://github.com/typst/typst/issues/576

**Closed by laurmaedje** 2023-12-12 14:57 UTC
Labels: bug
