### ISSUE TITLE
`#show : set` cannot be overwritten

### ISSUE THREAD

**Issue by michalmoc** [typst/typst#3101] opened 2023-12-29 17:40 UTC
### Description

```
#show heading: set text(fill: red)
= aaaaa

#show heading: set text(fill: blue)
= bbbbb
```

I would expect the second call to #show to override the previous setting, but it is completely ignored. Both headings are rendered red.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-12-29 17:51
Duplicate of #351

**Closed** 2023-12-29 19:39 UTC
Labels: bug
