### ISSUE TITLE
Switching citation style resets numerical citation counter

### ISSUE THREAD

**Issue by lumpiluk** [typst/typst#1829] opened 2023-07-31 12:10 UTC
### Description

Calling `cite` first with `style: "numerical"`, then switching to `"chicago-author-date"`, and then switching back results in multiple entries with the same number in the bibliography.

I noticed this in #658 when I [tried to implement a workaround](https://github.com/typst/typst/issues/658#issuecomment-1646826343) for a LaTeX `\textcite{}`-equivalent in numerical citation style, which required calling `cite` both with `style: "numerical"` and `style: "chicago-author-date"`. A simpler example is attached.

### Reproduction URL

https://typst.app/project/rVrifpYGLJzg0Z_hiLhje9

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by joeldierkes** [comment] 2023-08-24 07:43
Possible duplicate of #1805.

**Closed** 2023-08-24 09:18 UTC
Labels: bug
