### ISSUE TITLE
Missing "note" Field in Bibliography Entries  Description

### ISSUE THREAD

**Issue by okatsn** [typst/typst#4615] opened 2024-07-25 02:29 UTC
### Description

I am experiencing an issue with Typst where the "note" field in my .bib file is not being displayed in the generated bibliography. I have confirmed that this issue is not related to my CSL file or the BibTeX entries, as the same .bib file with the same CSL style displays the "note" field correctly in other reference management tools.

Here is the script of `test.typ`:
```typst
#bibliography("test.bib", title: none, style: "ieee", full: true)
// I have tried many styles other than "ieee" that should print "note" for `@unpublished` entry.
// I have also tried customized CSL that should force "note" to show for any entry, but it didn't work (bibliography rendered without error but still missed the "note" contents). 
```

`test.bib`:
```bib
@unpublished{wuStochasticModelEarthquake2023,
  type = {preprint},
  title = {A {{Stochastic Model}} for {{Earthquake Rupture}}},
  author = {Wu, Tsung-Hsi and Chen, Chien-Chih},
  date = {2023-08-31},
  year = {2023},
  eprinttype = {In Review},
  doi = {10.21203/rs.3.rs-3301435/v1},
  url = {https://www.researchsquare.com/article/rs-3301435/v1},
  note = {Preprint. In Review.}, 
  pubstate = {prepublished}
}

@unpublished{chen2024informational,
  title  = {Informational analysis of experimental seismic slip rate history and implication for fault ruptures},
  author = {Chen, Hong-Jia and Wu, Tsung-Hsi and Chen, Chien-Chih and Kuo, Li-Wei and Telesca, Luciano and Lovallo, Michele},
  year   = {2024},
  note   = {In Preparation}
}
```

**Expected Behavior**:
The "note" field should be included and displayed in the bibliography entries.

**Actual Behavior**:
The "note" field is missing from the generated bibliography entries.

**Additional Information**:
    I have verified that the "note" field is displayed correctly with the same .bib file and CSL style using LaTeX with biblatex with biber backend. The issue appears to be specific to Typst's handling of the "note" field in .bib entries.

**Environment**:

    Typst version: 0.11.1
    Operating System: Ubuntu 20.04

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by flokl** [comment] 2024-07-25 16:17
Duplicate of https://github.com/typst/hayagriva/issues/91

**Closed** 2024-08-01 14:02 UTC
Labels: bug, duplicate
