### ISSUE TITLE
PR proposal: Balanced ragged text

### ISSUE THREAD

**Issue by egilll** [typst/typst#4235] opened 2024-05-23 13:56 UTC
Hi. I’d like to submit a PR that alters `layout/inline/mod.rs` to support balanced ragged text. While Typst does allow for Knuth-Plass to be used for ragged text, the current implementation does not take into account the glue stretchability at the end of the line, and `fn commit()`  does not allow non-justified text to expand slightly.

Here is a comparison, before:

<img src="https://github.com/typst/typst/assets/7021771/0d7ba715-8fa7-4179-a160-e0934314d088" width="600px">

And after:

<img src="https://github.com/typst/typst/assets/7021771/903f8638-637f-48cf-9abd-64d5e4862ca6" width="550px">

There are two options that I’d like to add to the parameter `#par(linebreaks: ())`:

* `raggedness` – Line-final glue stretchability. Larger values would result in more ragged text, lower values more balanced. This would only apply to non-justified text.
* `last-line-raggedness` – Paragraph-final glue stretchability. Low values would make the last line more balanced with the other lines, and a value of zero would be desirable for headings (see issue #2814). This would apply both to justified and non-justified text.

This change can either be implemented by simply adding these glue stretchability values to `line.stretchability()`, or, if we want to follow Knuth’s paper, by using negative glue, see [page 1139](http://www.eprg.org/G53DOC/pdfs/knuth-plass-breaking.pdf#page=21).

I’ve implemented the same functionality in JavaScript [here](https://github.com/egilll/tex-linebreak2) if you wish to see how these parameters can be used for different ragged-ness.

**Comment by Enter-tainer** [comment] 2024-05-24 06:01
cc @peng1999

**Comment by laurmaedje** [comment] 2024-07-16 16:45
Duplicate of https://github.com/typst/typst/issues/2814 I think. I'd be open to support, but I prefer the API in #2814.

**Closed by laurmaedje** 2024-07-16 16:45 UTC
Labels: feature request, text
