### ISSUE TITLE
翻译中文文档

### ISSUE THREAD

**Issue by Franklyzzm** [typst/typst#430] opened 2023-03-29 14:24 UTC
希望可以翻译一份中文文档，若可以，希望可以参与翻译中文文档。

**Comment by gwlester** [comment] 2023-03-29 16:21
I belive the above translates to:

> I hope that I can translate a Chinese document, and if possible, I hope to participate in the translation of Chinese documents.

**Comment by schuelermine** [comment] 2023-03-29 19:31
中国作品
然而，盲文（#lorem）不起作用
翻译：DeepL

**Comment by schuelermine** [comment] 2023-03-29 19:59
实际上，官方并不支持中文。
但它可以正常工作

**Comment by schuelermine** [comment] 2023-03-29 20:01
https://typst.app/project/r7M_Tbx0W0DgR8kuotwILk

**Comment by kais7206** [comment] 2023-03-30 08:23
> 希望可以翻译一份中文文档，若可以，希望可以参与翻译中文文档。

我也可以助一份力

**Comment by shuangsilab** [comment] 2023-03-31 07:44
Nice idea! But how to do it? Is the Docs open source? Or we just translate it on our own webpage.

**Comment by jianm-xs** [comment] 2023-03-31 12:43
> Nice idea! But how to do it? Is the Docs open source? Or we just translate it on our own webpage.

Maybe we can create a 'zh-cn' directory in 'docs' and add some routes

**Comment by reknih** [comment] 2023-04-05 07:48
Possibly a duplicate of #554

**Comment by jianm-xs** [comment] 2023-04-05 16:25
> Possibly a duplicate of #554? My Mandarin is bad.

Yes, these are two duplicate issues.

**Closed** 2023-04-06 11:25 UTC
Labels: docs, duplicate
