### ISSUE TITLE
Introspection within numbering, heading, or caption breaks references and outline

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#1057] opened 2023-05-01 12:39 UTC
### Description

Consider the following code:

```
#set heading(numbering: "1.1")

#show heading.where(level: 1): it => [
 #counter(figure).update(0)
 #it
]

#set figure(numbering: it => {
  locate(loc => {
    [#counter(heading).at(loc).at(0)-#it]
  })
})

= Heading 1

In @fig

= Heading 2

In @fig

#figure(
  [Hi there.],
  caption: [A curious figure.]
) <fig>
```

The output looks like this:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/47084093/235452459-f124e9b6-46e0-4d7e-aa1b-75769ef98d3c.png">

They both reference the same image, but if we reference it before the actual heading where the figure appears, the numbering will be off. I presume the issue is that the numbering function is evaluated separately for the reference instead of somehow finding out what the number of the actual heading is where the figure will appear.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-05-01 13:33
This is a tough one. I wonder if this is an issue with the introspector? It seems that the elements are being obtained in the outline code with the same location as the outline itself (and such location is not being updated)... @laurmaedje do you have any ideas that could point us towards a fix? I wonder if caching the location is viable? Or if we need to add some special trait to Outline in order to make the introspector consider it differently?

**Comment by laurmaedje** [comment] 2023-05-01 13:44
Well, the numbering function simply returns content, so this is in principle working as intended. If you'd use `styles` and `measure` there you would also expect to get the local styles, so here you get the local location. This particular use case is hard to achieve right now, but overall it's probably best served not by adapting the `numbering`, but by adapting the counter that should be used. The numbering is only for displaying the counter values. The true solution are relative counters that reset automatically (something like `counter(figure, base: heading)`).

**Comment by PgBiel** [comment] 2023-05-01 14:01
To be honest, I'd expect the title in the outline to have exactly the same text as the title/caption in the actual figure/heading; I can't really think of a situation where I'd want it to adapt specifically "for the outline". In other words, I think even for `styles` and other things I think this'd be a bit of unexpected behavior most of the time. Although, `locate` is really the worst offender here, as counters depend on it. Maybe there could be some way to toggle between the current behavior and somehow caching the location (which IMO should be the default, as most users expect the title or similar to remain constant).

Though, I agree there should be better solutions for this particular use-case, such as the relative counters you mention.

**Comment by laurmaedje** [comment] 2023-05-01 14:13
For styles, I think you'd want this, for example if your outline has a different font size. I agree that for `locate` it's a bit strange. I will think whether it's possible to change this without breaking everything fundamentally.

**Comment by ModProg** [comment] 2023-07-01 14:48
In case someone wants a workaround:
```rs
#let actual_figure = figure

#let figure(..args, label:none) = {
  locate(loc => {
      let chapter = counter(heading.where(level: 1)).at(loc).first()
      set actual_figure(numbering: it => box[#chapter.#it])
      [
        #actual_figure(..args)
        #label
      ]
    }
  )
}
```
can be used like
```rs
figure(image("..."), label: <the-label>)
```
label parameter is required because `locate` cannot be labeled.

In my usecase I wanted to reset the figure counter with every level 1 heading so I just have a show rule for heading that does that:
```rs
show heading.where(level: 1): it => {
  it
  counter(actual_figure.where(kind: image)).update(100)
}
```

obviously you can also use your own name like `chaptered_figure` instead of shadowing `figure`.

**Comment by cschreib-ibex** [comment] 2023-09-18 16:26
Thanks @ModProg for the workaround, it almost works perfectly. Unfortunately, if I change the heading numbering to `"A"` intead of `"1"`, the `chapter` is shown as a number in the figure reference. In other words, the chosen numbering function is not applied. I haven't been able to fix this by myself, since I can't find any documentation on how to access or call this function (related to this, where is the documentation for `heading.where(..)`?).

**Comment by JustForFun88** [comment] 2024-01-16 19:02
> Thanks @ModProg for the workaround, it almost works perfectly. Unfortunately, if I change the heading numbering to `"A"` intead of `"1"`, the `chapter` is shown as a number in the figure reference.

Here's another workaround that works if you change the heading numbering pattern. I made it for myself, so it is needed to configure separators if necessary.

```rust
// Set appropriate rules for heading
#set heading(numbering: "1.")

// This code update figure counter after all first level heading
#show heading: head => {
  if head.level == 1 {
    counter(figure.where(kind: table)).update(0);
    counter(figure.where(kind: image)).update(0);
  }
  head
}

// Making " — " as a separator between type of the caption and
// caption itself (for example: Table 1 — Some table)
#set figure.caption(separator: " — ");

// Figure function try to place whole table into
// one page, so this #show command fix it
#show figure.where(kind: table): fig => {
  align(left, strong(fig.caption))
  align(left, fig.body)
}

// This code update figure.caption printing
#show figure.caption: c => {
  let head_num = locate(loc => {
    // Find heading number
    let num = counter(heading).at(loc).first();
    // Find numbering pattern
    let pattern = query(
      selector(heading.where(level: 1)).before(loc),
      loc,
    ).last().numbering;
    // Fix number accoding to the pattern
    numbering(pattern, num).first()
  });
  
  let c = c.supplement + " " + head_num + "." + c.numbering + c.separator + c.body;
  [#c]
}

// This code update reference printing
#show ref: it => {
  let el = it.element
  if el != none and el.func() == figure {
    // Find heading number
    let head_num = counter(heading).at(el.location()).first();
    // Find numbering pattern
    let pattern = query(
      selector(heading.where(level: 1)).before(el.location()),
      el.location(),
    ).last().numbering;
    // Fix number accoding to the pattern
    let head_num = numbering(pattern, head_num).first();
    // Make a link
    link(el.location(), [#el.supplement #head_num.#el.numbering])
  } else {
    // Other references as usual.
    it
  }
}
```

**Comment by JustForFun88** [comment] 2024-01-17 10:56
> Thanks @ModProg for the workaround, it almost works perfectly. Unfortunately, if I change the heading numbering to `"A"` intead of `"1"`, the `chapter` is shown as a number in the figure reference.

Here is the corrected code that correctly handles numbering in headings and figures, and also works when changing the type of numbering. Code also woks with customized supplement for reference.

```rust
// Set appropriate rules for heading
#set heading(numbering: "1.")
// Separator between first level heading and figure
// number (for example Figure 1.1)
#let sep = ".";
// Making " — " as a separator between type of the caption and
// caption itself (for example: Table 1 — Some table)
#set figure.caption(separator: " — ");

// This code update figure counter after all first level heading
#show heading: head => {
    if head.level == 1 {
        counter(figure.where(kind: table)).update(0);
        counter(figure.where(kind: image)).update(0);
    }
    head
}

// Figure function try to place whole table into
// one page, so this #show command fix it
#show figure.where(kind: table): fig => {
    align(left, strong(fig.caption))
    align(left, fig.body)
}

// This code update figure.caption printing
#show figure.caption: cap => {
    let head_num = locate(loc => {
        // Find heading number
        let num = counter(heading).at(loc).first();
        // Find numbering pattern
        let pattern = query(
            selector(heading.where(level: 1)).before(loc),
            loc,
        ).last()
         .numbering;
        // Fix number accoding to the pattern with removing last
        // char if necessary (for example if pattern is "1.")
        numbering(pattern, num).trim(regex("\W|_"), at: end)
    });
    // Fix figure number accoding to the pattern with removing last
    // char if necessary (for example if pattern is "1.")
    let fig_num = locate(loc => {
        numbering(cap.numbering, cap.counter.at(loc).first())
            .trim(regex("\W|_"), at: end)
    });
    let c = cap.supplement + " " + head_num + sep + fig_num + cap.separator + cap.body;
    [#c]
}


// This code update reference printing
#show ref: it => {
    let el = it.element
    if el != none and el.func() == figure {
        let loc = el.location();
        // Find heading number
        let head_num = counter(heading).at(loc).first();
        // Find numbering pattern
        let pattern = query(
            selector(heading.where(level: 1)).before(loc),
            loc,
        ).last()
         .numbering;
        // Fix head number accoding to the pattern with removing last
        // char if necessary (for example if pattern is "1.")
        let head_num = numbering(pattern, head_num)
            .trim(regex("\W|_"), at: end);
        // Fix figure number accoding to the pattern with removing last
        // char if necessary (for example if pattern is "1.")
        let fig_num = numbering(el.numbering, el.counter.at(loc).first())
            .trim(regex("\W|_"), at: end);
        // Make a link with checking if we have customized supplement
        // or not
        if it.citation.supplement != none {
            link(loc, [#it.citation.supplement #head_num#sep#fig_num])
        } else {
            link(loc, [#el.supplement #head_num#sep#fig_num])
        }
    } else {
        // Other references as usual.
        it
    }
}
```

**Comment by laurmaedje** [comment] 2024-02-28 11:26
Fixed by https://github.com/typst/typst/pull/3497.

You can now just write:
```typ
#set heading(numbering: "1.1")

#show heading.where(level: 1): it => [
 #counter(figure).update(0)
 #it
]

#set figure(numbering: it => {
  [#counter(heading).display()-#it]
})

= Heading 1

In @fig

= Heading 2

In @fig

#figure(
  [Hi there.],
  caption: [A curious figure.]
) <fig>
```
The numbering will be executed with the correct context.

**Closed by laurmaedje** 2024-02-28 11:26 UTC
Labels: bug, introspection
