### ISSUE TITLE
Inconsistent Whitespace Trimming

### ISSUE THREAD

**Issue by knoellle** [typst/typst#1387] opened 2023-06-01 11:14 UTC
### Description

I want to have an inline `raw` block that conserves leading and trailing spaces.
I haven't found a way to do it but discovered that the automatic trimming seems inconsistent.

Small example of what I mean:

```
// works as expected, with both leading and trailing whitespace inside the raw block.
// the quotation marks are just to show the spacing,
1. "` abc `"

// add a box around `raw`
#show raw: it => box(
  fill: luma(200),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
  [#it]
)

// the trailing space disappears but the leading space remains
2. "` abc `"

// content blocks don't seem to trim spaces at all
3. "#[ abc ]"

// but when manually building a box with spaces in the body, both leading and trailing space disappears
// AFAIK this should be exactly what 2. expands to
4. #box(
  fill: luma(200),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
  [ abc ]
)
```

![image](https://github.com/typst/typst/assets/33729490/c0755d67-96cf-4f41-8cc2-33e286657bce)

### Reproduction URL

https://typst.app/project/r0sVyo1sIryTNvjAkNLYe0

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-06-01 13:13
Duplicate of #597.

**Closed by laurmaedje** 2023-06-01 13:13 UTC
Labels: bug
