### ISSUE TITLE
Negative block height causes compiler to crash

### ISSUE THREAD

**Issue by manuelVo** [typst/typst#5446] opened 2024-11-20 09:42 UTC
### Description

A block that ends up having a negative height causes the compiler to crash.

This is the code that can be used to reproduce the crash:
```typst
#block(height: -10cm)
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-11-20 11:07
Duplicate of
https://github.com/typst/typst/issues/5262

**Closed** 2024-11-20 11:07 UTC
Labels: bug, duplicate
