### ISSUE TITLE
Adding a '?' question mark like javascript for property existance checking

### ISSUE THREAD

**Issue by mgholam** [typst/typst#5245] opened 2024-10-19 03:27 UTC
### Description

Checking a property exists in a dictionary with '?' for a key that may or may not exist:
```
data.prop1? // prop1 may or may not exist (reading json for example)
```

### Use Case

It would be much easier to write, currently you have to write a lot of extra code to do so.

**Comment by PgBiel** [comment] 2024-10-19 04:12
Duplicate of https://github.com/typst/typst/issues/3937

> currently you have to write a lot of extra code to do so.

For the moment, you may use `data.at("prop1", default: none)` or `data.at("prop1", default: auto)` or some other default of choice.

**Closed by PgBiel** 2024-10-19 04:12 UTC
Labels: feature request
