### ISSUE TITLE
SVG with rectangle gird renders with incorrect gaps in PDF

### ISSUE THREAD

**Issue by szdytom** [typst/typst#4110] opened 2024-05-10 11:36 UTC
### Description

Render result on web app:

![image](https://github.com/typst/typst/assets/33175397/0d5313e8-c6d6-4e40-bef7-3f23d2950252)

Render result after exported to PDF:

![图片](https://github.com/typst/typst/assets/33175397/21aa1498-5831-440b-b006-459dd21aa891)

Exporting to PNG or SVG is ok for the case.

![SVG Example](https://github.com/typst/typst/assets/33175397/cf8c3e65-24f7-4550-b047-43d4a5f64324)

Code:

```typst
#box(image("pixel_avatar.svg"), width: 25%, stroke: 3pt + black)
```

### Reproduction URL

https://typst.app/project/rOYY1s8VfZkSsZ6EBz6mfx

### Operating system

Web app, Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2024-05-10 12:00
Duplicate of #3133. This is not a Typst issue, but an issue with whatever PDF viewer you are using (I presume either Apple Preview or Firefox)? It looks fine in Adobe Acrobat and Google Chrome. I have yet to see a SVG converter which does not produce such artifacts (I tried onlines ones as well as the "Save as PDF" feature in Google Chrome / Firefox), and they all have the same issue. So there isn't much we can do about this from our side, I'm afraid.

**Closed by LaurenzV** 2024-05-10 12:00 UTC
Labels: bug

**Comment by szdytom** [comment] 2024-05-11 09:26
I think it is a bug of [pdf.js](https://github.com/mozilla/pdf.js/), every app I can confirm not using a browser as PDF render looks fine.

**Comment by szdytom** [comment] 2024-05-11 09:31
Do you have any ideas on what kinds of svgs can lead to this bug and how to avoid it? Thanks a lot.

**Comment by LaurenzV** [comment] 2024-05-11 09:46
It seems to be vector graphics with many of adjacent squares. Since it's just squares, the best option is probably to turn (just the squares) it into a bitmap and then embed it into the SVG. I think this would solve it. But I haven't actually tried it.
