### ISSUE TITLE
Nested blocks with incompatible heights cause compiler crash

### ISSUE THREAD

**Issue by manuelVo** [typst/typst#5447] opened 2024-11-20 09:48 UTC
### Description

The compiler can be caused to crash by constructing a set of nested blocks that fulfil the following criteria:
- At least two inner blocks are nested into an outer block
- The outer block has an explicit height set
- The inner blocks have an explicit height set
- The sum of the heights of the inner blocks exceed the height of the outer block
- The sum of the heights of the inner blocks exceed the height of the page
- The height of the last inner block is the result of a calculation

This code can be used to reproduce the crash:
```typst
#{
  block(height: 50cm, {
    block(height: 100%)
    block(height: 100% - 1cm)
  })
}
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-11-20 11:08
Duplicate of https://github.com/typst/typst/issues/5262

**Closed by Enivex** 2024-11-20 11:08 UTC
Labels: bug
