### ISSUE TITLE
set default indentation for all first line of paragraphs

### ISSUE THREAD

**Issue by retsyo** [typst/typst#1070] opened 2023-05-02 11:19 UTC
### Description

https://typst.app/docs/reference/layout/par/ says 
```
first-line-indent
The indent the first line of a paragraph should have.

Only the first line of a consecutive paragraph will be indented (not the first one in a block or on the page).
```

is there a way to set all paragraphs have an indentation of 2 characters(2em?) by default? Thanks

p.s. It seems that we can add a title as following to solve the problem, but sometime the article to be written is not a full article, but is a fragment without title. So I think it is still desired feature to set default indentation for all first line of paragraphs.

<pre>
#set par(first-line-indent: 2em, justify: false)
#show par: set block(spacing: 0.65em)

#align(center, text(17pt)[
  *I am a title*
])

paragrah 1 with indentation of 2 characters in the first line.

paragrah 2 with indentation of 2 characters in the first line.

$ sin(theta) = y/sqrt(x^2+y^2) $,

#set par(first-line-indent: 0em, justify: false)

where, x is ..., y is ...

#set par(first-line-indent: 2em, justify: false)
paragrah 4 with indentation of 2 characters in the first line.
</pre>
 

### Use Case

For serious articles in Chinese, for example, book, journal article, dissertation and so on, two kinds of indentation are used mostly
- indentation of 2 characters are used for most of the time for the beginning of a paragraph
- no indentation is accepted if the paragraph is just a discussion/conclusion on formula just stated

![IMG_20230501_231558](https://user-images.githubusercontent.com/7960913/235652194-e1d1cca7-ed75-4ba9-a209-198428e42127.png)

**Comment by laurmaedje** [comment] 2023-05-02 11:56
Duplicate of #311.

**Closed by laurmaedje** 2023-05-02 11:56 UTC
Labels: feature request
