### ISSUE TITLE
Indentation spaces in raw blocks are trimmed/not selectable in PDF export

### ISSUE THREAD

**Issue by marcoscarpetta** [typst/typst#3667] opened 2024-03-14 14:31 UTC
### Description

# Description
Spaces in indented code blocks cannot be selected in the exported PDF file. For languages like Python, where indentation matters, this makes it awkward to copy and reuse code inserted in a PDF file, such as code in a programming guide.

# Minimum reproducible example
````typ
```py
for i in range(10):
    for j in range(10):
        print(i, j)
```
````

The exported PDF appears visually as expected, but indentation spaces are not selected and not copied:

![immagine](https://github.com/typst/typst/assets/1175582/2eb8d985-9de3-45cd-b218-55f0baba1609)

The copied/pasted text is:

```
for i in range(10):
for j in range(10):
print(i, j)
```

which isn't valid Python code.

### Operating system

Web app, Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-14 15:01
Duplicate of https://github.com/typst/typst/issues/671

**Closed by laurmaedje** 2024-03-14 15:01 UTC
Labels: bug
