### ISSUE TITLE
Line break in inline math causes its content to overflow

### ISSUE THREAD

**Issue by MaximeMulder** [typst/typst#2986] opened 2023-12-16 21:42 UTC
### Description

I don't exactly know how line breaks are supposed to behave inside inline math, but I found it surprising that the following code produces the following output.

```
#block($a \ b$, stroke:red)
```

![image](https://github.com/typst/typst/assets/23308005/cc96668c-3e52-4cff-99cc-bc9647b053c1)

Is this a bug or intended behaviour ?

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-12-16 22:13
Duplicate of https://github.com/typst/typst/issues/1028

**Closed by laurmaedje** 2023-12-16 22:13 UTC
Labels: bug
