### ISSUE TITLE
Typst don't apply `footnote` style when `text` is called before hand

### ISSUE THREAD

**Issue by FirelightFlagboy** [typst/typst#1622] opened 2023-06-30 09:35 UTC
### Description

Typst version: `0.5.0 (3a8b9cce)`

I'm trying to configure the style of the generate footnote, but it don't seems to work when I call `text` to set the style of a specific block of text.

Here is the minimal input where I'm able to have the issue.

```tyspt
#text(weight: "bold", size: 1.5em)[Styled title]

#show footnote.entry: set text(blue)
#show footnote: set text(red)

== Hello world

This is a simple String with a footnote#footnote[A footnote is a text that is put at the bottom of a page describing an element]
```

I expected the footnote text to be `blue` but it's not.

> The issue is gone when I remove the first line with `#text...`

Result in the following [test.pdf](https://github.com/typst/typst/files/11915114/test.pdf)

<details>

<summary>Generated Image</summary>

![test-1](https://github.com/typst/typst/assets/30697622/aaa7c720-b1f0-4d13-a775-aa7bc4b5ca06)

</details>

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-06-30 10:43
Duplicate of <https://github.com/typst/typst/issues/1467>

**Closed by laurmaedje** 2023-06-30 10:43 UTC
Labels: bug

**Comment by FirelightFlagboy** [comment] 2023-06-30 11:42
@laurmaedje By looking at the documentation <https://typst.app/docs/reference/meta/footnote/>

The information that the `#show footnote.entry` need to be at the top of the document is missing. (https://github.com/typst/typst/issues/1348#issuecomment-1566316463)

Could it be added ?
