### ISSUE TITLE
If the first page is an explicit `#page` call state and counter updates before it are ignored

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2172] opened 2023-09-17 15:14 UTC
### Description

Take a look at the following snippet:
```typst
#let number = counter("part-number")
#part_number.update(10)
#page[#number.display()]
```
The resulting document has only one page and the number is 0, when it should be 10. The same also happens with states.

My guess is that typst removes the first page if it only contains whitespace to not have an empty page before the first page it the document starts with an explicit `#page` call, though I have not verified if this is really what's happening.

If this is the reason possible solutions would be to either not threat state/counter updates as whitespace in this context (so the above snippet would start with an "empty" page containing only the update) or to automatically move the update into the page.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-09-18 09:44
Same as #2134, this was caused by #1929 and is unfortunately not fixed by #2141. Bit of a similar issue as the second snippet in https://github.com/typst/typst/pull/1929#issuecomment-1718332099. Like you said, the explicit `page` leads to stuff around it being deleted.

**Closed** 2024-08-26 17:23 UTC
Labels: bug, introspection
