### ISSUE TITLE
corefonts: black weight font variant is selected when regular weight was requested

### ISSUE THREAD

**Issue by mkroening** [typst/typst#3213] opened 2024-01-17 15:59 UTC
### Description

On Linux, with the core fonts for the Web installed with https://corefonts.sourceforge.net, Typst selects Arial Black, although Arial would be correct.

Dockerfile for reproduction:

```Dockerfile
FROM ghcr.io/typst/typst:latest

ENV TYPST_FONT_PATHS=/usr/share/fonts/truetype/msttcorefonts

RUN set -eux; \
    apk add --no-cache msttcorefonts-installer; \
    update-ms-fonts; \
    apk del --no-cache msttcorefonts-installer;
```

Typst file:

```typ
#text(font: "Arial", weight: "regular")[regular]

#text(font: "Arial", weight: "black")[black]
```

Typst falsely classifies `Arial_Black.ttf` as regular weight, resulting in both lines being written in Arial Black, when you compile this.

This issue does not occur on macOS with the natively installed Microsoft fonts.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-01-17 16:07
Duplicate of https://github.com/typst/typst/issues/576

**Comment by laurmaedje** [comment] 2024-01-17 16:15
Where can I get ahold of the raw Arial Black ttf file to inspect it?

**Comment by laurmaedje** [comment] 2024-01-17 16:36
Ok, I've managed to extract it. The OS/2 table of the font specifies a usWeightClass of 400, which is clearly wrong.

**Comment by mkroening** [comment] 2024-01-17 16:42
I suspected something like that, but was not familiar enough with fonts to confirm. I don't think, we should wait for this to be fixed upstream, since this the de-facto standard way of installing MS fonts on Linux since forever. That means an upstream fix would take years to reach users.

What do you think is the best way forward here?

**Comment by laurmaedje** [comment] 2024-01-17 16:46
I'm not sure. Perhaps there is no way but to ship exceptions, but if so, we should definitely apply them very carefully, e.g. maybe not for any font ending with "black", but rather specifically for Arial Black. I'll discuss this with @reknih.

**Comment by peng1999** [comment] 2024-01-18 05:26
Typst already have some ad-hoc exceptions for font names. Maybe we can generalize that and introduce a font map mechanism into typst. That can be a mapping embedded into typst binary like this:

```yaml
NewComputerModern08-Italic:
  - family: "New Comupter Modern"
NewComputerModern08-BookItalic:
  - family: "New Comupter Modern"
  - weight: 450
```

The keys correspond to the `FULL_NAME` record in the font file. Users encountering fonts with incorrect metadata can simply submit a pull request to update this file accordingly. For instance:

```yaml
"Arial Black":
  - family: Arial
  - weight: 900
```

In the future, we can offer an API that allows users to supply their own `fontmap.yaml`, which would override the default one built into Typst.

**Comment by laurmaedje** [comment] 2024-01-18 10:51
I wonder whether should just decide based on the FULL_NAME or perhaps also on the checksum. The problem with the latter is that some fonts will continue to retain their "wrong" metadata across multiple versions, so FULL_NAME is probably the better albeit less safe choice.

**Comment by mkroening** [comment] 2024-01-18 11:23
> I wonder whether should just decide based on the FULL_NAME or perhaps also on the checksum. The problem with the latter is that some fonts will continue to retain their "wrong" metadata across multiple versions, so FULL_NAME is probably the better albeit less safe choice.

I agree. Can I help with this in any way? Is someone experienced willing to work on this, or should I give this a go?

**Comment by laurmaedje** [comment] 2024-01-18 13:55
While this is sort of a dupe, I've reopened so that we can properly use it for further discussion and close it once we've implemented something to this effect.

**Comment by laurmaedje** [comment] 2024-01-18 18:21
> Typst uses (family, style, weight, stretch, size) 5-tuple to identify a font. 

> OpenType font formats also includes style and weight, but font designers make fonts without aware of the typst coordinate system. That's why typst is using a very hacking algorithm to calculate the correct family-coordinate of a font.

Typst only uses the first four, not the size for font selection. The family-style-weight-stretch coordinate system is pretty common, e.g. in CSS. It is not Typst-specific. The only thing that's specific is the (hacky) effort Typst makes to have a nicer family name and the few exceptions where Typst patches the metadata based on name.

> I think that is not optimal because when using FULL_NAME ... emph and strong will not work. 

That's a fair criticism.

> Thus I proposed another approach in https://github.com/typst/typst/issues/3213#issuecomment-1897824364: Design a systematic approach to map OpenType coordinate to the typst coordinate.

To be clear: I am not against adding a general exception mechanism. But as you said, it would require not just a list, but also an automatic produce to get a "nice" uniform family consisting of only fonts differing in style/weight/stretch from the available data in the font. In theory, font names could also be selected in such a way that this property is enforced for a given font set, but that might be weird because an existing font name might change when a new font is installed.

That's why I proposed doing something more predictable and mostly relying on TYPOGRAPHIC_FAMILY. I'd be all on board with a more systematic approach to map OpenType coordinate to the CSS coordinate system if we find a good one.

**Comment by mkroening** [comment] 2024-01-19 14:21
> Typst only uses the first four, not the size for font selection.

Wouldn't it make sense for Typst to also use size for font selection? New Computer Modern (and probably others) has different font files optimized for 8 point and 10 point sizes.

**Comment by reknih** [comment] 2024-01-19 14:29
Computer Modern is actually pretty unique in that respect. The differences in the two variants are due to the _Optical Size_ difference of the fonts, consisting of small weight and detail differences that make the fonts more legible at their respective sizes. Some modern font families include "Display" variants which are intended for display font sizes (>~18pt) but don't make such a clear distinction. Variable fonts have begun to ship the `opsz` variation axis for optical sizing. The [units on that scale are standardized](https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz) with regards to point size.

Typst does not yet support variable fonts (#185) but once we do, we should automatically adjust the `opsz` axis based on font size. In my opinion, support for legacy approaches for optical sizing (dedicated denominated fonts or Display variants) belongs in the same work package instead of here.

**Comment by peng1999** [comment] 2024-01-19 16:15
I implemented #3228. Feedback appreciated!

**Comment by peng1999** [comment] 2024-02-01 14:22
@mkroening #3228 Has been merged. Would you like to submit a PR to fix your Arial Black font issue?

**Comment by mkroening** [comment] 2024-02-01 19:20
> Ok, I've managed to extract it. The OS/2 table of the font specifies a usWeightClass of 400, which is clearly wrong.

@laurmaedje, can you point me to a tool that can be used to extract such information? I'd like my PR fixing this to be comprehensive for all corefonts.

**Comment by laurmaedje** [comment] 2024-02-01 19:32
I use opentype.js.org. You need the font inspector tab rather than the glyph inspector and then check the OS/2 table.

**Comment by mkroening** [comment] 2024-02-02 10:34
I just opened https://github.com/typst/typst/pull/3321.

**Closed** 2024-02-02 10:57 UTC
Labels: bug, duplicate
