### ISSUE TITLE
included SVGs not rendering correctly in macOS Preview and some printers

### ISSUE THREAD

**Issue by tpfx** [typst/typst#2922] opened 2023-12-12 13:02 UTC
### Description

If I include SVGs in my document the resulting PDF has missing elements in some svgs in macOS Preview and while printing with some printers. 

Example Code:
`#align(right, image(width: 70%, "brokenSVG1.svg"))`
`#align(center,image(width: 50%, "brokenSVG2.svg"))`

Used SVGs:

![brokenSVG1](https://github.com/typst/typst/assets/24574773/e2536686-9bd5-4b4e-943b-7a2d04a973aa)
![brokenSVG2](https://github.com/typst/typst/assets/24574773/3c25656c-7ab4-40c2-b95d-18a59e5c193d)

If opened in Inkscape and every browser they look like they should.

Resulting PDF:
[brokenSVGExample.pdf](https://github.com/typst/typst/files/13648309/brokenSVGExample.pdf)

How it looks in macOS-Preview and after printing (directly from the user interface of the printer, not via macOS):

<img width="677" alt="broken" src="https://github.com/typst/typst/assets/24574773/df8d4d88-abb9-4209-a362-309b1391ec1f">

While the problem here is more on the side of macOS-Preview and the printer, shouldn't typst produce PDFs that are as widely compatible as possible?

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2023-12-12 13:22
Will look into it.

**Comment by LaurenzV** [comment] 2023-12-12 13:45
I know what the issue is, I encountered the same problem with MacOS Preview when building the convert from SVG to PDF. I'm afraid it's hard to fix from our side (we could potentially work around it with some work, but it's still not going to fix the underlying issue, which is Apple's fault for not following the PDF specification, and not ours). However, for now you can work around it easily: Simply open your SVG and remove `clip-rule:evenodd;` from your SVGs at the very top, then it should work fine in Preview (and hopefully also printers):

<img width="706" alt="image" src="https://github.com/typst/typst/assets/47084093/9277a82b-ec21-4905-8f28-51cd3c2cabe3">

I hope that helps.

**Comment by LaurenzV** [comment] 2023-12-12 13:55
I would be curious to know what program you used to generate this SVG? I'm surprised that it uses `clip-rule:evenodd` in the first place.

**Comment by tpfx** [comment] 2023-12-12 16:09
Thank you, that solved the problem!

I used Affinity Designer 2. Time to open the next bug report, I guess.

I wonder if it could be worth it to implement a workaround in typst. While the macOS preview issue isn't that big of a deal (classic Apple ...), the printer thing is a bit more problematic, because sometimes you are stuck with only one way to print sth out. I'm a teacher and imagine my horror realizing 5 min before class that half of the worksheet is missing with no way of fixing it :D (jay, digitalization in german schools ...). While I know now what the issue is, most people won't. On the other hand, it is of course a lot of effort for such a little thing ...

**Comment by LaurenzV** [comment] 2023-12-12 16:43
> I used Affinity Designer 2. Time to open the next bug report, I guess.

It's not really a bug from their side, just some not-so-ideal output. I can maybe explain a bit what the problem is (but feel free to skip if you don't care, but might be useful for anyone who wants to tackle the problem in the future).

In SVG, there are two ways to define a clip path: You can use the "even odd" rule and the "non zero winding rule". These rules define which parts of the shape are considered to be on the inside of the shape, and which ones are on the outside. For example, if you have the following SVG:

```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <clipPath id="clip1">
        <path id="path1" d="M 100 15 l 50 160 l -130 -100 l 160 0 l -130 100 z"
              clip-rule="evenodd"/>
    </clipPath>
    <rect id="rect1" x="0" y="0" width="200" height="200" fill="green" clip-path="url(#clip1)"/>
</svg>
```

It will look like this:
<img width="647" alt="image" src="https://github.com/typst/typst/assets/47084093/962fb5ca-9237-4a6a-ac84-585bffe5d51a">

While if you remove the "evenodd", it will default to the non zero winding rule, in which case the result would look like this:
<img width="631" alt="image" src="https://github.com/typst/typst/assets/47084093/bf1c384a-78d9-4ff8-aa24-b0778b4faa91">

The thing is that PDF also has built-in support for clip paths, but you can only use the non zero winding rule. Because of this, many applications (including for example Latex will simply ignore the rule of the clip path and render it using the non zero winding rule. 

As a result of this, if I try embedding the above SVG into Latex, the result is wrong in all viewers. But I guess in practice the clip-rule evenodd isn't used at all, so no one really "cares" (in the case of your SVG it is used, but it actually doesn't produce any different output compared to when you would've used the non zero winding rule, so Latex will render your SVG fine. But the above SVG is not rendered correctly):
[latex-out.pdf](https://github.com/typst/typst/files/13650672/latex-out.pdf)

For me, correctness was the most important, which is why I made sure that this case is handled as well (with the unfortunate side effect that Preview has a bug and because of this won't display it properly). But it works fine in Chrome, Firefox, Adobe Acrobat, XPDF, and mupdf:
[typst-out.pdf](https://github.com/typst/typst/files/13650677/typst-out.pdf)

How did I do it? Basically, whenever I encounter a clip path, there are two options: If the clip path is "simple" (e.g. the rule is not evenodd, and there are some other conditions that need to be fulfilled), it is embedded as a normal clip path in PDF. If this is not the case, we fall back to simulating the clip path with soft masks, which is more complex but allows us to preserve the semantics of that feature. As far as I am aware, this is the only way to do it in PDF. But Preview doesn't interpret transformations with soft masks correctly, which is why the output gets messed up.

So an easy solution could be to just ignore the clip path rule in Typst too, which is something I'd like to avoid doing because... well, it's not correct. In my opinion the real issue is that Affinity Designer 2 for some reason decides to explicitly make the clip path use the `evenodd` rule even though in your case the result is exactly the same as using the non zero winding rule, which is the default, so yeah...

I won't explain the more complex approach to circumventing the problem as this requires some knowledge about how PDF works, but it would basically involve making the SVG converter more integrated with the Typst exporter, which does require some effort and I don't have the time to try working on it right now.

> While the macOS preview issue isn't that big of a deal (classic Apple ...), the printer thing is a bit more problematic, because sometimes you are stuck with only one way to print sth out.

Yeah, that's of course very understandable. But I do think that your SVG is an edge case because normally, a program wouldn't change the clip rule to evenodd if it doesn't actually need it... And if it does need it then, well, we are the only one who will produce correct output (I tried a lot of online converters and they all can't handle it correctly).

But I will leave this issue open for now, hopefully it can be fixed in the (near) future, but I don't know when.

**Comment by tpfx** [comment] 2023-12-12 16:58
Thx for the info! Yes, makes sense.

**Comment by laurmaedje** [comment] 2023-12-12 17:02
@LaurenzV how hard would it be to check whether nonzero and evenodd would behave identically and use nonzero in that case even if evenodd is specified?

**Comment by LaurenzV** [comment] 2023-12-12 17:26
Not sure to be honest, but it sounds like it would involve a lot of maths to determine whether the paths cross each other and in which way.  😅

**Comment by LaurenzV** [comment] 2023-12-12 17:41
@laurmaedje For your information, the more complex approach I was talking about is to write SVGs directly into the page content stream of Typst instead of linking it via an XObject. Because if I remember correctly, the problem was that transformations from the page stream are somehow not correctly applied if a soft mask is invoked inside of the XObject (although I'd have to double check to make sure), however, if we invoke the soft mask directly inside of the page stream, then it _should_ work. This means that it wouldn't work for clip paths _inside_ of other complex clip paths (because then we have the same problem that we need to create a new XObject anyway), but it _should_ at least work for top-level clip paths and soft masks, but not for deeply-nested ones, which I suppose should cover 99.9% percent of the cases.

But for this to work, we'd need some mechanism to allow svg2pdf to store new resources inside of the dictionary that is controlled by Typst (which at some point should exist anyway so that things like color spaces and eventually if we add selectable text to `svg2pdf` even fonts don't need to be written twice).

**Comment by LaurenzV** [comment] 2023-12-23 20:52
Good news, turns out that I remember it wrong and PDF actually does have support for evenodd clip paths. The reason I didn't include it is because it might not work properly with overlapping shapes, but we can at least support it if the clip path contains only a single element (which is the case here). Should be fixed in the next update.

**Closed** 2024-01-25 15:48 UTC
Labels: bug, svg
