### ISSUE TITLE
error[E0282]: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by dexhunter** [typst/typst#5037] opened 2024-09-26 04:28 UTC
### Description

I saw this error when trying to install typst-cli on my M3 macbook pro and I found the solution is to remove the `--locked` from the command line
```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/dex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

I think another solution is to update `time` to 0.3.36 as suggested [here](https://github.com/time-rs/time/issues/693)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-09-26 04:36
Duplicate of https://github.com/typst/typst/issues/4659

Please compile from the `0.11` branch (not the tag), which has the fix.

**Closed by PgBiel** 2024-09-26 04:36 UTC
Labels: bug
