### ISSUE TITLE
"typst watch" doesn't track files correctly

### ISSUE THREAD

**Issue by stevenskevin** [typst/typst#2601] opened 2023-11-07 01:38 UTC
### Description

In Typst 0.9.0, `typst watch` nondeterministically confuses different images when they're added to the document. 0.8.0 works correctly.

[Here's a Python script + example image files to demonstrate the problem.](https://github.com/typst/typst/files/13274289/demo.zip) This might not be a _minimal_ reproducible example, but since the behavior is semi-random, simplifying the script further makes it less likely to occur. The script does the following:

1. Makes a simple `file.typ`  that just contains "hello world", and asks you to launch `typst watch` on it before continuing.
2. Copies "imgs/a1.png" to "a.png".
3. Adds `a.png: #image("a.png", width: 50%)` to the end of the document.
4. Repeatedly replaces a.png with different images, "a2.png" through "a9.png".
5. Copies "imgs/b1.png" to "b.png".
6. Adds `b.png: #image("b.png", width: 50%)` to the end of the document.
7. Repeatedly replaces b.png with different images, "b2.png" through "b9.png".
8. Repeatedly replaces a.png with different images, "a1.png" through "a9.png".
9. Repeatedly replaces b.png with different images, "b1.png" through "b9.png".

It also makes an unimportant edit to the document between each image replacement to force typst to recompile, since otherwise it might not (even though it should, and does in 0.8.0).

The expected final result should be a PDF with a9.png on top and b9.png on bottom. The actual final result in Typst 0.9.0 can be any arbitrary combination of images, even ones that don't make any sense at all (e.g., b9.png on top and a9.png on bottom, or two copies of b9.png).

You can watch the PDF with a PDF viewer that supports auto-reloading to see intermediate outputs. They look correct in Typst 0.8.0, but exhibit random-looking behaviors in 0.9.0.

As a workaround, closing and relaunching `typst watch` will cause it to recompile the document correctly, at least until you start adding more images again.

I feel like the results _might_ vary according to your computer speed and/or how quickly the images are replaced, but that also might just be my imagination... it's hard to be sure since the behavior is different every time.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2023-11-07 06:01
I fail to reproduce "b on top and a on bottom" using the code on an arm64 macbook. maybe it is because m2pro is too fast? 

```
[13:59:43] compiled successfully in 4.67ms
```

**Comment by stevenskevin** [comment] 2023-11-07 07:32
Maybe. Before reporting, I tried it on both an underpowered tablet and a pretty fast (though not Apple Silicon fast) laptop, and got the same erratic behavior on both, so I don't think it's system-specific. It might be Linux-specific, though.

Example output screenshot:

<img src="https://github.com/typst/typst/assets/48657161/8b5168b5-f729-4a6c-ae5c-973cb4a9e806" width="200" />

**Comment by istudyatuni** [comment] 2023-11-07 08:56
Some time ago (somewhere around 0.7.0) I ran into a similar problem. I replaced a.png with b.png, but even on cold compilation the a.png was rendered. This only got fixed after renaming the image and renaming it back after a while. Unfortunately, I was unable to reproduce it

**Comment by aticu** [comment] 2023-11-13 14:36
I ran the script a couple of times and everything seems to work fine for me. However I do have a similar issue that I suspect has the same underlying cause.

I have a document where I import other typst files in the local directory. Since the 0.9.0 release `typst watch` frequently confuses the imported files for other imported files. This usually results in one file being imported twice, while another file is not imported. Depending on which file it happens to, this may result in errors for missing references or duplicated content. One time it also tried to use a document file as a png image and complained about a malformed png header.
I was witnessing this behavior on two different machines both running Arch Linux. The issue is always fixed by restarting `typst watch`.
The document I'm working on follows a structure like this:
```typst
= Heading 1
#include "section1.typ"

= Heading 2
#include "section2.typ"

= Heading 3
#include "section3.typ"
```

**Comment by laurmaedje** [comment] 2023-11-13 14:41
The CLI code was recently reworked to use file modification timestamps instead of reading and parsing all files from scratch everytime. Maybe there's a bug in there.

**Comment by Myriad-Dreamin** [comment] 2023-11-13 15:26
This is possibly caused by the unreliable `PathHash`. The underlying file handle may be reused by filesystem.

```rust
impl Hash for Handle {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.dev.hash(state);
        self.ino.hash(state);
    }
}
```

**Comment by Enter-tainer** [comment] 2023-11-13 15:41
same-file is designed to check if two file points to the same inode at some point and it only hash (dev, inode). 

So basically we are hashing inodes here. This is problematic because when you move/rename a file, only its name is changed, and its inode is left intact. Also, fs may recycle and reuse inodes. The correct solution should be hash the paths.

**Comment by laurmaedje** [comment] 2023-11-13 15:41
Right and previously all slots were cleared, so it didn't matter. But now, in a new compilation a file ID could resolve to a path hash that points to a slot for a different path from the previous compilation.

If this is the issue, mapping file IDs directly to path slots would probably fix it at the cost of not deduplicating symlinked files. Probably not too big of a deal in practice. Alternatively, the path hash could maybe incorporate the full canonicalized path instead of dev/ino?

**Comment by Atreyu-94** [comment] 2023-11-13 16:03
I was having a problem with loading images in version 0.8 as well.

In my case, when updating an image file, with the same name and the same extension, the rendered PDF was not updated, and I had to make some text modification to take it into account.

**Comment by laurmaedje** [comment] 2023-11-17 13:29
On Windows, one problem is that replacing an existing file doesn't change the creation date and retains the modification date of the original file. This means neither of the timestamps is up to date and Typst thinks the file didn't change. The access date does change, but I don't think it makes sense to use that.

I currently can't think of a solution for this other than memory-mapping/reading the file and computing a hash. 

On Unix the modification date does change, so there it's apparently another problem, probably the inodes thing.

**Comment by laurmaedje** [comment] 2023-11-17 15:16
I have created a PR which I hope fixes this. I would appreciate if folks could test it: https://github.com/typst/typst/pull/2706

**Comment by stevenskevin** [comment] 2023-11-17 21:30
> I currently can't think of a solution for this other than memory-mapping/reading the file and computing a hash.

I'll test the PR later today, but I'm curious if you've considered using first-class operating system APIs for tracking file modifications instead of doing everything manually? E.g. [inotify](https://en.wikipedia.org/wiki/Inotify) on Linux, [Directory Change Notifications](https://learn.microsoft.com/en-us/windows/win32/fileio/obtaining-directory-change-notifications) on Windows, [File System Events](https://developer.apple.com/documentation/coreservices/file_system_events) on macOS.

Additional thought: it'd be nice if someone made a crate to wrap all of those interfaces behind a cross-platform API, like the [`watchdog` module](https://pypi.org/project/watchdog/) for Python.

**Comment by laurmaedje** [comment] 2023-11-17 21:40
@stevenskevin We do use the [`notify`](https://docs.rs/notify/latest/notify/) crate, which wraps these APIs internally. However, we only use it to detect _whether_ to recompile, not to evict and update cached resources. Maybe it would be possible to use the events directly to decide what to retain. I'm not sure how hard it would be to get that to work correctly. That said, the hashing-based setup I've opted for now is probably not all that expensive in practice.

**Comment by stevenskevin** [comment] 2023-11-17 21:42
Hm, I see. Thanks.

**Comment by laurmaedje** [comment] 2023-11-17 21:43
The setup we have now is also in some sense more resilient because it wouldn't fail if a single event doesn't arrive correctly. Every recompile re-reads all relevant files, while keeping the processed data (syntax trees) intact based on hashes.

**Comment by laurmaedje** [comment] 2023-11-19 11:36
Fixed by https://github.com/typst/typst/pull/2706

**Closed by laurmaedje** 2023-11-19 11:36 UTC
Labels: bug, cli, urgent
