### ISSUE TITLE
Long tables header line repeating  feature  needed !

### ISSUE THREAD

**Issue by PEWOLO** [typst/typst#3222] opened 2024-01-19 05:18 UTC
Hey, Typst Team,

 I really enjoy the product and thank you so much for the this amazing work.
However, I have a suggestion to make though, that concerns  long tables that split over several pages.
 Is there a way to make the header line repeat at the top  of the  table for  each new page?
It would be super helpful to have this feature if you can implement it.

Thanks in advance!

**Comment by Enter-tainer** [comment] 2024-01-19 05:21
tablex can do this https://github.com/PgBiel/typst-tablex?tab=readme-ov-file#repeat-header-rows

Could you also edit the issue title and make it more informative?

**Comment by Enivex** [comment] 2024-01-19 10:01
Duplicate of https://github.com/typst/typst/issues/400

**Closed by Enivex** 2024-01-19 10:01 UTC
