### ISSUE TITLE
Use `table.header()` in table with only one column

### ISSUE THREAD

**Issue by lettuceDestroyer** [typst/typst#4021] opened 2024-04-26 12:06 UTC
### Discussed in https://github.com/typst/typst/discussions/4017

<div type='discussions-op-text'>

<sup>Originally posted by **lettuceDestroyer** April 26, 2024</sup>
I'm trying to create a table with repeating headers for a table that only has one column.

What I tried is this:
```typst
#let date = datetime.today().display()

#show table.header : it => strong(it)

#figure(
  align(center,
)[#table(
      columns: 1,
      align: left,
      inset: 6pt,
      table.header([Date],[Text 1], [Text 2]),
      [#date],
      [#lorem(15)],
      [#lorem(30)],
    )],
    caption: [Journal from #date]
)
```

Which resulted in this:
![image](https://github.com/typst/typst/assets/110594766/8a433c42-01a1-418f-bd37-b7eb49b830a8)

What I excepted was this:
![image](https://github.com/typst/typst/assets/110594766/5bf0cbe8-025d-4575-a5df-9e6a9d4620a9)</div>

One of the advantages of having this build in as a feature would be that, if implemented correctly, the table headers could be repeated in case there is a page break.

**Comment by laurmaedje** [comment] 2024-07-16 18:24
This seems very non-standard and niche, so I'll close this as out of scope for the time being.

**Closed by laurmaedje** 2024-07-16 18:24 UTC
Labels: feature request, layout

**Comment by Marcono1234** [comment] 2025-09-21 10:40
Sounds like this might be a duplicate of or closely related to #5375 (which is generally about having multiple headers, not specific to a one column table)
