### ISSUE TITLE
Add ability to format Typst file (source code)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2949] opened 2023-12-14 00:03 UTC
### Description

I have seen a few Typst formatters being developed, and I don't know which one to choose, probably should wait more for them to mature. But in the future a `typst fmt`/`typst format` subcommand should be added just like `cargo fmt`. In the meantime, it would be nice to at least be able to remove trailing whitespaces. The https://github.com/mhartington/formatter.nvim has a default all-filetype formatting that removes trailing whitespaces which is super useful.

The same goes for https://typst.app.

### Use Case

This will make code more readable, consistent with how things are declared/used, and also potentially decrease file size *for free* (if there are any trailing whitespaces).

**Comment by Dherse** [comment] 2023-12-14 00:12
Duplicate of #1772

**Closed by Dherse** 2023-12-14 00:12 UTC
Labels: feature request
