### ISSUE TITLE
Typst panics with `"failed to decode image (Format error decoding Png: Invalid PNG signature.)"`

### ISSUE THREAD

**Issue by mkorje** [typst/typst#4786] opened 2024-08-19 07:25 UTC
### Description

On [`main`](https://github.com/typst/typst/commit/eb0e0fec00e08c497a428d138c47a1235c89295f) when I try to compile the below Typst file to a PNG, Typst panics.

<details>
<summary>math-kerning.typ</summary>

```typst
#set page(width: 4cm, height: auto)
#show math.equation: set text(font: "Cambria Math")

$
  P_2 P^2 P_2^2 quad
  f_2 f^2 f_2^2 \
  A_2 A^2 A_2^2 quad
  F_2 F^2 F_2^2 \
  P_2 P^2 P_2^2 quad
  T_2 T^2 T_2^2 \
  V_2 V^2 V_2^2 quad
  W_2 W^2 W_2^2 \
  Y_2 Y^2 Y_2^2 quad
  upright(Y)_2 upright(Y)^2 upright(Y)_2^2 \
  Gamma_2 Gamma^2 Gamma_2^2 quad
  Delta_2 Delta^2 Delta_2^2 \
  Lambda_2 Lambda^2 Lambda_2^2 quad
  Rho_2 Rho^2 Rho_2^2 \
  Tau_2 Tau^2 Tau_2^2 quad
  Upsilon_2 Upsilon^2 Upsilon_2^2 \
  Psi_2 Psi^2 Psi_2^2 quad
  nabla_2 nabla^2 nabla_2^2 \
  italic(Gamma)_2 italic(Gamma)^2 italic(Gamma)_2^2 quad
  italic(Delta)_2 italic(Delta)^2 italic(Delta)_2^2 \
  italic(Lambda)_2 italic(Lambda)^2 italic(Lambda)_2^2 quad
  italic(Upsilon)_2 italic(Upsilon)^2 italic(Upsilon)_2^2 \
  italic(Psi)_2 italic(Psi)^2 italic(Psi)_2^2 quad
  ℘_2 ℘^2 ℘_2^2 \
  lambda_2 lambda^2 lambda_2^2 quad
  partial_2 partial^2 partial_2^2 \
$

$
  F_j quad
  y_A quad
  y_l quad y_y \
  V_a quad
  V_x^x quad
  attach(J, tl: 1, br: i) quad
  attach(A, tr: x, bl: x, br: x) \
  attach(cal(y), br: x, tl: i) quad
  xi_i^k quad
  attach(cal(A), tl: 2) quad
  attach(cal(A), tl: x) \
  attach(cal(J), br: A, bl: l) quad
  attach(cal(J), br: x, bl: 2) quad
  x_A quad
  x_x \
$

// Bugs in STIX Two Math font
$
  V_A quad cal(F)_j
$
```

</details>

```fish
❯ ../../typst/target/debug/typst c --font-path . math-kerning.typ math-kerning-cambria-new.png
thread 'main' panicked at crates/typst/src/text/font/color.rs:124:6:
called `Result::unwrap()` on an `Err` value: "failed to decode image (Format error decoding Png: Invalid PNG signature.)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>
<summary>backtrace</summary>

```fish
❯ RUST_BACKTRACE=1 ../../typst/target/debug/typst c --font-path . math-kerning.typ math-kerning-cambria-new.png
thread 'main' panicked at crates/typst/src/text/font/color.rs:124:6:
called `Result::unwrap()` on an `Err` value: "failed to decode image (Format error decoding Png: Invalid PNG signature.)"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.78.0-src/library/core/src/result.rs:1077:23
   4: typst::text::font::color::draw_raster_glyph
             at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:119:17
   5: typst::text::font::color::frame_for_glyph::{{closure}}
             at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:36:9
   6: comemo::cache::memoized
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
   7: typst::text::font::color::frame_for_glyph
             at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:27:1
   8: typst_render::text::render_text
             at /home/mkorje/repositories/typst/crates/typst-render/src/text.rs:28:31
   9: typst_render::render_frame
             at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:162:17
  10: typst_render::render_group
             at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:231:5
  11: typst_render::render_frame
             at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:159:17
  12: typst_render::render
             at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:39:5
  13: typst::compile::export_image_page
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:317:26
  14: typst::compile::export_image::{{closure}}
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:271:13
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:272:13
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:305:13
  17: core::option::Option<T>::map
             at /build/rustc-1.78.0-src/library/core/src/option.rs:1073:29
  18: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:26
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:9
  20: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.78.0-src/library/core/src/iter/adapters/take_while.rs:47:21
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:9
  22: alloc::vec::Vec<T,A>::extend_desugared
             at /build/rustc-1.78.0-src/library/alloc/src/vec/mod.rs:2988:35
  23: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /build/rustc-1.78.0-src/library/alloc/src/vec/spec_extend.rs:17:9
  24: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /build/rustc-1.78.0-src/library/alloc/src/vec/mod.rs:2962:9
  25: <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:130:18
  26: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:139:21
  27: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  28: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  29: rayon::iter::plumbing::Producer::fold_with
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:9
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:13
  31: rayon::iter::plumbing::bridge_producer_consumer
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  32: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  33: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/slice/mod.rs:826:9
  34: rayon::iter::plumbing::bridge
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:12
  35: <rayon::slice::Iter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/slice/mod.rs:802:9
  36: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  37: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:49:9
  38: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/while_some.rs:44:9
  39: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:588:28
  40: rayon::iter::from_par_iter::collect_extended
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:20:5
  41: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:33:9
  42: rayon::iter::ParallelIterator::collect
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  43: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/result.rs:125:14
  44: rayon::iter::ParallelIterator::collect
             at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  45: typst::compile::export_image
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:241:5
  46: typst::compile::export
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:156:13
  47: typst::compile::compile_once
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:103:13
  48: typst::compile::compile::{{closure}}
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:80:38
  49: typst::timings::Timer::record
             at /home/mkorje/repositories/typst/crates/typst-cli/src/timings.rs:48:23
  50: typst::compile::compile
             at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:80:5
  51: typst::dispatch
             at /home/mkorje/repositories/typst/crates/typst-cli/src/main.rs:53:38
  52: typst::main
             at /home/mkorje/repositories/typst/crates/typst-cli/src/main.rs:38:15
  53: core::ops::function::FnOnce::call_once
             at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

<details>
<summary>verbose backtrace</summary>

```fish
thread 'main' panicked at crates/typst/src/text/font/color.rs:124:6:
called `Result::unwrap()` on an `Err` value: "failed to decode image (Format error decoding Png: Invalid PNG signature.)"
stack backtrace:
   0:     0x55d7c00b11b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee93a2ee0c
2227c5
   1:     0x55d7c00fb03c - core::fmt::write::h7222d6bd37096f9b
   2:     0x55d7c00b09f5 - std::io::Write::write_fmt::hf5bd345a4857fa1f
   3:     0x55d7c00b0f84 - std::sys_common::backtrace::print::h87f644093c44c474
   4:     0x55d7c00c1ea3 - std::panicking::default_hook::{{closure}}::h54f259bcb3c96d54
   5:     0x55d7c00c1bfa - std::panicking::default_hook::h4e7363e714c56f43
   6:     0x55d7c00c232d - std::panicking::rust_panic_with_hook::h4be469481b88451f
   7:     0x55d7c00b1822 - std::panicking::begin_panic_handler::{{closure}}::h12fd05c40e3f67ec
   8:     0x55d7c00b13c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hda2ba2e5aeedda76
   9:     0x55d7c00c2024 - rust_begin_unwind
  10:     0x55d7be690285 - core::panicking::panic_fmt::h993794e49879741f
  11:     0x55d7be6901c3 - core::result::unwrap_failed::hb05442a284093f3a
  12:     0x55d7bece995a - core::result::Result<T,E>::unwrap::h164e7e13f56a84a4
                               at /build/rustc-1.78.0-src/library/core/src/result.rs:1077:23
  13:     0x55d7bece995a - typst::text::font::color::draw_raster_glyph::h8cd75f3e52b71fc9
                               at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:119:17
  14:     0x55d7beed0023 - typst::text::font::color::frame_for_glyph::{{closure}}::hb9766ee840451ed4
                               at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:36:9
  15:     0x55d7bee8e21c - comemo::cache::memoized::h9b4dfbcf1b0e7586
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cach
e.rs:61:18
  16:     0x55d7becef88e - typst::text::font::color::frame_for_glyph::h6c286d8cd52f51f2
                               at /home/mkorje/repositories/typst/crates/typst/src/text/font/color.rs:27:1
  17:     0x55d7be80dbc4 - typst_render::text::render_text::h66d717b408966606
                               at /home/mkorje/repositories/typst/crates/typst-render/src/text.rs:28:31
  18:     0x55d7be7f3782 - typst_render::render_frame::hf754b756127ee314
                               at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:162:17
  19:     0x55d7be7f414f - typst_render::render_group::h2ff2b5adea7112e5
                               at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:231:5
  20:     0x55d7be7f36f8 - typst_render::render_frame::hf754b756127ee314
                               at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:159:17
  21:     0x55d7be7f4920 - typst_render::render::hb36df703a9f5851d
                               at /home/mkorje/repositories/typst/crates/typst-render/src/lib.rs:39:5
  22:     0x55d7be72a501 - typst::compile::export_image_page::h7752206c332aacff
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:317:26
  23:     0x55d7be6dc78a - typst::compile::export_image::{{closure}}::hf1749ebb2f517311
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:271:13
  24:     0x55d7be6dbf62 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h78dc9814a4
952e25
                               at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:272:13
  25:     0x55d7be6dbfbf - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hcf2f
dd88a3e01cb2
                               at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:305:13
  26:     0x55d7be7913d8 - core::option::Option<T>::map::hd26e680002b4d91e
                               at /build/rustc-1.78.0-src/library/core/src/option.rs:1073:29
  27:     0x55d7be7913d8 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h79c2e8
0a8cb3a105
                               at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:26
  28:     0x55d7be790beb - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h1fbe9c
                               at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:9
  29:     0x55d7be6a057e - <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::
                               at /build/rustc-1.78.0-src/library/core/src/iter/adapters/take_while.rs:47:21
  30:     0x55d7be7912e3 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h694457
                               at /build/rustc-1.78.0-src/library/core/src/iter/adapters/map.rs:108:9
  31:     0x55d7be73b849 - alloc::vec::Vec<T,A>::extend_desugared::h9aaec45dff2c6c6a
                               at /build/rustc-1.78.0-src/library/alloc/src/vec/mod.rs:2988:35
  32:     0x55d7be74239a - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h457fb50f0fd0
                               at /build/rustc-1.78.0-src/library/alloc/src/vec/spec_extend.rs:17:9
  33:     0x55d7be70f1ea - <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend::he8e2ca59eb348f11
                               at /build/rustc-1.78.0-src/library/alloc/src/vec/mod.rs:2962:9
  34:     0x55d7be70f1ea - <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter::hd8
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  35:     0x55d7be795830 - <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Op
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  36:     0x55d7be6a4beb - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h959801a
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  37:     0x55d7be6a4d3e - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::ha4459cb
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  38:     0x55d7be6d519d - rayon::iter::plumbing::Producer::fold_with::h57615bf6e1ec31e5
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  39:     0x55d7be695573 - rayon::iter::plumbing::bridge_producer_consumer::helper::hc7b65a4d1ed58b0d
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  40:     0x55d7be694bc3 - rayon::iter::plumbing::bridge_producer_consumer::h503a339ff9d537da
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  41:     0x55d7be694a41 - <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::ca
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  42:     0x55d7be6d538c - <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer::h91a5d27554066
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/slic
  43:     0x55d7be695d25 - rayon::iter::plumbing::bridge::h1fc46b821f45cff9
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  44:     0x55d7be6d52ea - <rayon::slice::Iter<T> as rayon::iter::ParallelIterator>::drive_unindexed::hf556c09b20c69d54
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/slic
  45:     0x55d7be6a49f4 - <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed::hcd1a6f9b08fb6
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  46:     0x55d7be6a490a - <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed::h9232f2b73305c
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  47:     0x55d7be795e78 - <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed::h6e
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter
  48:     0x55d7be73f7f8 - rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend::h98a0ea2e0e5b3c59
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/extend.rs:588:28
  49:     0x55d7be70d8a9 - rayon::iter::from_par_iter::collect_extended::h20c96736a35f5604
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:20:5
  50:     0x55d7be73f6dd - rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter::h20286768f31f5a92
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:33:9
  51:     0x55d7be732113 - rayon::iter::ParallelIterator::collect::hcfde1930e9ddfcba
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  52:     0x55d7be732113 - rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter::h7a58f72cd993772c
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/result.rs:125:14
  53:     0x55d7be6a47dd - rayon::iter::ParallelIterator::collect::ha893cd0d9645eca1
                               at /home/mkorje/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  54:     0x55d7be72a333 - typst::compile::export_image::h877410e12cbc3685
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:241:5
  55:     0x55d7be72985e - typst::compile::export::h8276b7c19b5c8a74
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:156:13
  56:     0x55d7be72c432 - typst::compile::compile_once::h15c5a5d049c8dfed
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:103:13
  57:     0x55d7be6dc40f - typst::compile::compile::{{closure}}::h43018f7df08158c3
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:80:38
  58:     0x55d7be75c6c1 - typst::timings::Timer::record::h142f30cc1ac43de1
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/timings.rs:48:23
  59:     0x55d7be72955c - typst::compile::compile::had48abab1394e110
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/compile.rs:80:5
  60:     0x55d7be75f31c - typst::dispatch::h0a2aa7b2b37bcf11
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/main.rs:53:38
  61:     0x55d7be75ef43 - typst::main::h1a2d45ac0be925a9
                               at /home/mkorje/repositories/typst/crates/typst-cli/src/main.rs:38:15
  62:     0x55d7be76fe0b - core::ops::function::FnOnce::call_once::h617ca6cb9f1680f7
                               at /build/rustc-1.78.0-src/library/core/src/ops/function.rs:250:5
  63:     0x55d7be74d33e - std::sys_common::backtrace::__rust_begin_short_backtrace::h06d75750d16a09fd
                               at /build/rustc-1.78.0-src/library/std/src/sys_common/backtrace.rs:155:18
  64:     0x55d7be70d5d1 - std::rt::lang_start::{{closure}}::h568c7a781ee141e0
                               at /build/rustc-1.78.0-src/library/std/src/rt.rs:166:18
  65:     0x55d7c00c1f24 - std::panicking::try::h8ebc32e168e5ed61
  66:     0x55d7c00a520b - std::rt::lang_start_internal::h5dd16626185ad212
  67:     0x55d7be70d5aa - std::rt::lang_start::h5a81f8c9e733207f
                               at /build/rustc-1.78.0-src/library/std/src/rt.rs:165:17
  68:     0x55d7be75fabe - main
  69:     0x7fe68df4d14e - __libc_start_call_main
  70:     0x7fe68df4d209 - __libc_start_main@@GLIBC_2.34
  71:     0x55d7be690845 - _start
  72:                0x0 - <unknown>
```

</details>

The file successfully compiles when I use another font, for example `STIX Two Math` or the default math font.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by inferiorhumanorgans** [comment] 2024-08-20 05:06
Typst only supports PNG encoded raster glyphs.  Cambria Math stores its raster glyphs in the `EBDT` table in an unsupported format.

**Comment by inferiorhumanorgans** [comment] 2024-08-20 21:14
As for why Typst is preferring the bitmaps, when there are both raster and outline glyphs the raster glyps are preferred.  The right thing to do is likely to prefer the outline glyph.

**Comment by LaurenzV** [comment] 2024-08-21 12:41
> As for why Typst is preferring the bitmaps, when there are both raster and outline glyphs the raster glyps are preferred. The right thing to do is likely to prefer the outline glyph.

The only reason for this is that we want to use the bitmap version for emoji fonts (for example Noto Color Emoji) over the outlined versions. I didn't even know that there exist "outline fonts" that also provide bitmap versions of the glyphs. In reality what we probably should do is prefer bitmap glyphs for emoji characters, while preferring outline glyphs for all others.

**Comment by inferiorhumanorgans** [comment] 2024-08-21 20:39
Cambria Math (available from the PowerPoint Viewer installer) has 6 bitmap strikes included in addition to the outline glyphs.  From reading a bit more, it sounds like the bitmaps are to be preferred at those specific sizes.

I suppose that should be easy enough to test as the bitmap strikes are defined in terms of pixels per em (the list lives in `EBLC`).

Something like: use the bitmap if there's a bitmap strike at that size and there's a bitmap glyph in that strike.  Perhaps with the caveat that bitmaps should be preferred for all emoji characters?

There's also the issue of error handling.  While the SVG renderer returns `Option<()>` this never checked.  The raster function returns void.  It'd probably be good to return an Option all the way down instead of calling unwrap (e.g. if the bitmap data is corrupt).

**Comment by inferiorhumanorgans** [comment] 2024-08-25 21:08
This is a duplicate of #4335

**Closed** 2024-08-25 21:30 UTC
Labels: bug, crash, png
