### ISSUE TITLE
Inconsistent path handling between image source and Typst templates import

### ISSUE THREAD

**Issue by blackjyn** [typst/typst#3508] opened 2024-02-27 13:31 UTC
I have **main.typ** inside **chapter1** that uses **template.typ** and **fx.typ** outside the dir.

**fx.typ** cointains custom `imgX()` function that extends Typst's `image()`.

**template.typ** is just page template. 

the dir structure is like this below, you see **img1.png** and **img2.png** are both at the same dir with the **main.typ**

```cmd
workspace
+---part1
|   |   fx.typ
|   |   template.typ
|   |
|   \---chapter1
|           main.typ
|           img1.png
|           img2.png
```

And in the **main.typ** , I import the template and the fx by specifying **"../"** as they are located outside the **chapter1** folder.

For image, I just specify the name as they are in the same dir as the main file.

```js
#import "../template.typ": template
#show: template

#import "../fx.typ": imgoriginal

#imgX("img1.png")
#imgX("img2.png")
```

If I run this CMD from the chapter1 dir as the root:

```bash
~: workspace/part1/chapter1 typst w main.typ --root=.
```

of course I got: _**error: failed to load file (access denied)**_

And if I run this cmd from the part1 dir as the root:

```bash
~: workspace/part1 typst w chapter1/main.typ --root=.
```

,it said: _**error: file not found  (searched at workspace/part1/img1.png)**_

So , it seems for importing the templates / fxs it will be **relative to the source.typ**.

But for the image source it seems to be relative to `typst --root` location?  Or CMD invoked location?

for workaround, I then change the src to:

```js
#import "../template.typ": template
#show: template

#import "../fx.typ": imgoriginal

//change this : add "chapter1/" path
#imgX("chapter1/img1.png")
#imgX("chapter1/img2.png")
```

and then re-run this successfully.

```bash
~: workspace/part1 typst w chapter1/main.typ --root=.
```

well it got me confused and nonsense for me. 
Why should I mention the path for the image when it were clear they are at the same dir with the mainfile? 
at the other hand importing the templates and fxs feels more natural and common practice.

Thanks.

**Comment by laurmaedje** [comment] 2024-02-27 13:47
Duplicate of https://github.com/typst/typst/issues/971

**Closed by laurmaedje** 2024-02-27 13:47 UTC
