### ISSUE TITLE
Functions in #heading lead to empty PDF outline entries

### ISSUE THREAD

**Issue by sw-dbrown** [typst/typst#3764] opened 2024-03-22 16:04 UTC
### Description

Thank you for developing typst. While experimenting, I implemented basic support for language switching which I need for some documents. It works as intended (i.e. the correct heading text is placed in the PDF) but I noticed that there appears to be an issue with the PDF outline. Consider the following code:

```typst
#let langswitch(german, english) = {
context if text.lang == "de" {german} else {english}
}

#set text(lang: "en")

#heading(
    langswitch(
        "German content",
        "English content"
    )
)

Some content

#heading("It works here")

Some content
```

As shown in the screenshot of my PDF reader (`zathura`) below, the second PDF outline entry contains the expected content but the first entry (generated by `langswitch` function) is empty. I would have expected the first entry to contain "English content".

![demo](https://github.com/typst/typst/assets/56249462/7e5bb548-9a08-4af5-922e-a9b33bcbd22c)

Thanks for your time!

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-22 16:49
Duplicate of https://github.com/typst/typst/issues/3424

**Closed by laurmaedje** 2024-03-22 16:49 UTC
Labels: bug
