### ISSUE TITLE
CJK have some about aligned questions

### ISSUE THREAD

**Issue by supikachu** [typst/typst#3710] opened 2024-03-18 04:44 UTC
### Description

The Chinese font isn't aligned with the list number
![111.png](https://img2.imgtp.com/2024/03/18/V0QAFnWr.png)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2024-03-18 04:50
pls provide relevant code piece so we can reproduce and fix this

**Comment by supikachu** [comment] 2024-03-18 06:29
我的中文字体用的是方正书宋（字体链接：https://www.fonts.net.cn/font-31537398849.html），会出现上面图片中的问题；更改为思源宋体之后，就没有问题了

**Comment by Enter-tainer** [comment] 2024-03-18 06:32
> 我的中文字体用的是方正书宋（字体链接：https://www.fonts.net.cn/font-31537398849.html），会出现上面图片中的问题；更改为思源宋体之后，就没有问题了

translation for who might concern:

I'm using 方正书宋 font. And it has problem as the image above. After i switch to souce han serif, the problem is gone.

**Comment by balthild** [comment] 2024-04-07 01:44
I looks like that you are not just using `FZShuSong-Z01S`, but `Times New Roman` + `FZShuSong-Z01S`.

I guess that the cause may be:

1. The list numbering is aligned by the cap-height rather than the baseline.
2. FZShuSong-Z01S has a cap-height that is different from `Times New Roman`.
3. Coincidentally, Noto Serif CJK has a cap-height that roughly matches `Times New Roman`.

Test:

![图片](https://github.com/typst/typst/assets/2662758/016c2c43-925a-42d5-908f-2f00506d3820)

```typst
#set page(width: 20em, height: auto, margin: 1em)

#set text(
  size: 12pt,
  lang: "zh",
  font: ("Times New Roman", "Noto Serif CJK SC"),
  // The default value of `top-edge` is "cap-height"
)

// top-edge = cap-height, Noto Serif CJK
#box(fill: aqua, "1111") #box(fill: aqua, ".") #box(fill: aqua, "默认，Noto Serif CJK")
+ 测试文本
+ 测试文本

// top-edge = cap-height, FZShuSong-Z01S
#set text(font: ("Times New Roman", "FZShuSong-Z01S"))
#box(fill: aqua, "2222") #box(fill: aqua, ".") #box(fill: aqua, "默认，方正书宋")
+ 测试文本
+ 测试文本

// top-edge = a static length, FZShuSong-Z01S
#set text(top-edge: 0.9em)
#box(fill: aqua, "3333") #box(fill: aqua, ".") #box(fill: aqua, "固定 top-edge")
+ 测试文本
+ 测试文本
```

**Comment by laurmaedje** [comment] 2024-04-08 08:45
Duplicate of https://github.com/typst/typst/issues/1204

**Closed by laurmaedje** 2024-04-08 08:45 UTC
Labels: bug, text
