### ISSUE TITLE
Smart quotes breaking due to preceding slash

### ISSUE THREAD

**Issue by Biansky-Sophie** [typst/typst#3283] opened 2024-01-27 21:37 UTC
### Description

Smart quotes seem to break when there's a preceding symbol (e.g. slash). It can be prevented by putting a whitespace between the symbol and quotation mark. This doesn't look like correct behavior to me since you should, for example, be able to write something like
> The term originates from the Greek word "parallēlos"/"side by side".

<img width="346" alt="ss" src="https://github.com/typst/typst/assets/143814722/2e59c1ad-2318-4794-abdf-9dda7af67c08">

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-01-28 10:56
Duplicate of https://github.com/typst/typst/issues/1200

**Closed** 2024-01-28 10:56 UTC
Labels: bug, duplicate
