### ISSUE TITLE
Make PDF outline names include numbering

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#2306] opened 2023-10-03 21:02 UTC
### Description

For example suppose you just want numbers in your heading: `align(center, pad(heading(numbering: "1", "")))`. Then the title of the heading is technically blank. When the PDF is exported, these blank titles are copied into the outline.

Looking at how textbooks do things, I believe the correct implementation would be to make the PDF heading match the rendered title (i.e. it would be the concatenation of the numbering and title). This improves readability of your typical titles as a corollary fixes the issue with blank PDF outlines because they will still have numbers.

### Use Case

.

**Comment by deffi** [comment] 2023-11-28 15:55
Duplicate of #2416?

**Closed** 2023-11-28 16:19 UTC
Labels: feature request, pdf

**Comment by laurmaedje** [comment] 2023-11-28 18:06
My bad!
