### ISSUE TITLE
Space closes the file naming automatically.

### ISSUE THREAD

**Issue by Meistermagier** [typst/typst#1419] opened 2023-06-05 13:43 UTC
### Description

If I want to write a file name like "exercise 1.typ"  the web app will always proceed to finish the naming of the file and throw you out. 

### Browsers

Chrome

### OS

Windows

**Comment by laurmaedje** [comment] 2023-06-05 14:07
Duplicate of #1294

**Closed by laurmaedje** 2023-06-05 14:07 UTC
Labels: bug, web app
