### ISSUE TITLE
Inline math fragments are reversed while text is set to an RTL language

### ISSUE THREAD

**Issue by yonatanmgr** [typst/typst#3696] opened 2024-03-16 16:59 UTC
### Description

This source code:
`תהא סדרה $a_n$: $[a_n: 1, 1/2, 1/3, dots]$`
Produces this:
![image](https://github.com/typst/typst/assets/31913495/5826cc1f-c198-4204-bba6-0589840e71ee)

Instead of:
![image](https://github.com/typst/typst/assets/31913495/ddaaf803-3984-41dd-a49d-3f43bc6ab1c8)

My template contains the following set rule: `set text(font: "", lang: "he")`. Changing the language to `"en"` shows the brackets in the correct order (but messes up the rest of the document as it is written in Hebrew).

**This occurred only after the new update.**

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-16 17:07
Oh, that doesn't look good. I think it's a result of https://github.com/typst/typst/pull/2938.

**Comment by yonatanmgr** [comment] 2024-03-16 17:12
It seems to be not only brackets, but inline math in RTL as a whole:
A paragraph in 0.10.0:
![image](https://github.com/typst/typst/assets/31913495/fd9edd68-4d87-4e65-925f-83e3c2be3d94)

The same paragraph in 11.0.0:
![image](https://github.com/typst/typst/assets/31913495/5e775750-c04c-4278-9781-abf52f8e3727)

**Comment by laurmaedje** [comment] 2024-03-16 21:28
Yeah, previously an inline equation would be one atomic box. But now, it consists of multiple breakable parts and those are affected by BiDi reordering in unexpected ways. This piece of code might be a temporary workaround:
```typ
#show math.equation.where(block: false): it => box({
  set text(dir: ltr)
  it
})
```
("Might" because I'm not 100% sure how it should really look.)

**Comment by emilyyyylime** [comment] 2024-03-17 05:28
Generally `show math.equation: set text(lang: "en")` should give correct results

**Comment by laurmaedje** [comment] 2024-03-17 08:45
I tried that, but without the box, it didn't work.

**Comment by ocantor** [comment] 2024-03-17 12:43
Is there a way to disable line breaks in inline equations altogether (i.e. restore 0.10.0 behavior)? I personally prefer it over TeX's behavior in RTL documents, at least most of the time.

**Comment by laurmaedje** [comment] 2024-03-17 13:43
@ocantor `#show math.equation.where(block: false): box` should do the trick

**Comment by ocantor** [comment] 2024-03-17 14:05
`#show math.equation.where(block: false): box` disables line breaks without fixing the issue, your [workaround](#issuecomment-2002139696) disables line breaks and fixes the issue (which is what I wanted), and `show math.equation: set text(lang: "en")` doesn't seem to do anything. I wonder if there's a different workaround that fixes the issue without disabling line breaks.

**Comment by laurmaedje** [comment] 2024-03-17 14:26
> I wonder if there's a different workaround that fixes the issue without disabling line breaks.

I don't think that one exists.

**Comment by noamzaks** [comment] 2024-04-13 07:58
Does it even make sense to have a multi-line inline equation in RTL? (And not keep them as blocks for RTL)

As far as I know, all equations are LTR (even in RTL languages). Trying to break an LTR equation over RTL text will probably be very confusing for people.

Although this is the indeed default behavior in TeX.

**Comment by emilyyyylime** [comment] 2024-04-13 09:22
> Does it even make sense to have a multi-line inline equation in RTL? (And not keep them as blocks for RTL)

It can definitely make sense, though it can be confusing (though if you ask me not much more confusing than breaking equations in LTR text)

**Comment by Enivex** [comment] 2024-04-13 09:23
> Does it even make sense to have a multi-line inline equation in RTL? (And not keep them as blocks for RTL)
> 
> As far as I know, all equations are LTR (even in RTL languages). Trying to break an LTR equation over RTL text will probably be very confusing for people.
> 
> Although this is the indeed default behavior in TeX.

I'm not a fan of breaking inline equations even in LTR. It should be the absolute last resort.

**Comment by ezzobir** [comment] 2024-04-25 07:19
> Yeah, previously an inline equation would be one atomic box. But now, it consists of multiple breakable parts and those are affected by BiDi reordering in unexpected ways. This piece of code might be a temporary workaround:
> 
> ```typst
> #show math.equation.where(block: false): it => box({
>   set text(dir: ltr)
>   it
> })
> ```
> 
> ("Might" because I'm not 100% sure how it should really look.)

This work for me ( I use arabic language in my document )

**Comment by laurmaedje** [comment] 2024-05-16 14:43
I've opened #4150 to fix this by adding Unicode LTR embedding chars around equations. The original markup from this issue now produces this result:
![issue-3696-equation-rtl](https://github.com/typst/typst/assets/17899797/97600c48-a2c4-474f-bcbc-7a372464a074)
This is not exactly what @yonatanmgr showed as intended, but it's what the BiDi algorithm outputs and I _think_ it's technically correct? The `":"` and `" "` are weak chars, so they adopt the LTR-ness of the two surrounding equations. Any feedback from native speakers / BiDi experts on this?

**Comment by khaledhosny** [comment] 2024-05-16 14:48
You should try LRI (U+U+2066) instead of LRE: https://www.unicode.org/reports/tr9/tr9-46.html#Directional_Formatting_Characters

**Comment by laurmaedje** [comment] 2024-05-16 14:56
@khaledhosny Thanks for the pointer. Using LRI for equations indeed yields exactly the result @yonatanmgr wanted. 

We also use LRE on segments of text that have their direction specifically specified (e.g. `Hello #text(dir: ..)[..] World`). When the PR that implemented that landed, there was [a bit of discussion about LRE vs LRI](https://github.com/typst/typst/pull/3885/files#r1555723794). The problem there was that we individually isolated consecutive pieces of text instead of figuring out the longest subsequence with the same direction, and LRE seemed to handle that better. Do you happen to know whether that's a sensible usage of LRE or whether this should also be changed in some way?

**Comment by khaledhosny** [comment] 2024-05-16 15:25
Embedding control characters basically works as strong LTR/RTL characters, while isolates act as neutral characters.

(using ASCII hack syntax with lower case representing LTR and upper case representing RTL)

so

    ABC [LRE]a[PDF] [LRE]b[PDF] [LRE]c[PDF] DEF

would render as:

    FED a b c CBA

While:

    ABC [LRI]a[PDI] [LRI]b[PDI] [LRI]c[PDI] DEF

would render as:

    FED c b a CBA

I’d say the later is more desirable, since if one wants the whole embedded segment to be LTR, it should set direction to it as whole:

    ABC [LRI]a b c[PDI] DEF

Consider when there is punctuation between the segments:

    abc A, B, C def

This is certainly the more desirable rendering (which is what you get with isolates):

    FED c ,b ,a CBA

**Comment by laurmaedje** [comment] 2024-05-16 17:15
Okay, thanks for the detailed explanation, that definitely makes things clearer!

I'm still not 100% sure what's the right thing for Typst because of Typst's speciality that 
```typ
ABC #ltr[abc] DEF
``` 
and 
```typ
ABC #ltr[a]#ltr[b]#ltr[c] DEF
```
is effectively equivalent and indistinguishable (here `let ltr = text.with(dir: ltr)`). There is no distinction between setting the RTL style for segments individually or for a whole. So, I think in the context of Typst right now the LRE happens to sort of do the right thing / best we can.

The alternative would be to manually find consecutive segments and use LRI on them, but it seems to me that the effect would be quite similar to LRE, except perhaps for small differences in the effect on surrounding text / punctuation.

**Comment by khaledhosny** [comment] 2024-05-16 21:34
What about:

    ABC #ltr[a] #ltr[b] #ltr[c] DEF

is it the same as:

    ABC #ltr[a b c] DEF

?

**Comment by emilyyyylime** [comment] 2024-05-17 05:38
No, the spaces indeed are the substantive parts here.

**Closed** 2024-05-17 08:40 UTC
Labels: bug, math, urgent

**Comment by khaledhosny** [comment] 2024-05-17 13:42
Then if the original example here used LTR text segments instead of math, using LRE would give different output than the expected here, which is inconsistent. I think you should either used embedding or isolated control chars for both to have consistency in the output.

**Comment by laurmaedje** [comment] 2024-05-17 13:43
Probably the best would be to use LRI on automatically detected consecutive segments, then. We can look into that for the future.

**Comment by khaledhosny** [comment] 2024-05-17 13:44
Another option would be to follow CSS and provide control over this: https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi
