### ISSUE TITLE
More control over repeat sizing and spacing

### ISSUE THREAD

**Issue by lkndl** [typst/typst#2816] opened 2023-11-30 23:06 UTC
### Description

Currently `repeat` divides extra space between `n` repeat elements into `n-1` equally-sized pieces. There should be an option to not use the extra space of the parent element, i.e. stack to the left instead of justify; and ideally also a maximum width parameter that would allow `repeat` to be used without an explicitly-sized parent box.

### Reproduction URL
https://typst.app/project/r8n1E4ONWPQu3e3M7c6lcH

web app, on latest version of Typst

### Use Case

Alignment of spaced-out repeat elements in outline `fill` or any repeated use of `repeat` with the same element. 

![expand](https://github.com/typst/typst/assets/38729961/93f4ce85-9aa1-4a12-8d37-8456fc1c1fc9)

### Partial Fix
Here is a patch for the proposed `expand` flag, resulting in the good alignment in the bottom-most table of contents in the image above. I'm not up to `max-width` yet.

```patch
diff --git a/crates/typst/src/layout/repeat.rs b/crates/typst/src/layout/repeat.rs
index c733ea7d..d391a8db 100644
--- a/crates/typst/src/layout/repeat.rs
+++ b/crates/typst/src/layout/repeat.rs
@@ -32,6 +32,11 @@ pub struct RepeatElem {
     /// The content to repeat.
     #[required]
     pub body: Content,
+    // Whether to spread the available extra space
+    // smaller than one repeat element between them,
+    // or otherwise stack it on the right.
+    #[default(true)]
+    pub expand: bool,
 }
 
 impl Layout for RepeatElem {
@@ -46,13 +51,18 @@ impl Layout for RepeatElem {
         let piece = self.body().layout(engine, styles, pod)?.into_frame();
         let align = AlignElem::alignment_in(styles).resolve(styles);
 
-        let fill = regions.size.x;
+        let mut fill = regions.size.x;
         let width = piece.width();
         let count = (fill / width).floor();
         let remaining = fill % width;
-        let apart = remaining / (count - 1.0);
+        let mut apart = remaining / (count - 1.0);
 
-        let size = Size::new(regions.size.x, piece.height());
+        if !self.expand(styles) {
+            fill -= remaining;
+            apart = Abs::zero();
+        }
+
+        let size = Size::new(fill, piece.height());
 
         if !size.is_finite() {
             bail!(self.span(), "repeat with no size restrictions");
@@ -64,7 +74,7 @@ impl Layout for RepeatElem {
         }
 
         let mut offset = Abs::zero();
-        if count == 1.0 {
+        if count == 1.0 && self.expand(styles) {
             offset += align.x.position(remaining);
         }
 
```

**Comment by Enivex** [comment] 2023-12-01 10:57
I'll close this as a duplicate of https://github.com/typst/typst/issues/2713

**Closed by Enivex** 2023-12-01 10:57 UTC
Labels: feature request
