### ISSUE TITLE
Infinite lengths and values cause compiler panics on multiple occasions

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#1918] opened 2023-08-12 02:00 UTC
### Description

You can obtain an infinite length by using `layout()` in a page with `auto` width or height.
You can also obtain an infinite float with `float("inf")`.

With that said, using those in almost any way will cause a compiler panic (instead of a user-facing error, which would be more appropriate) - the stack traces below refer to commit https://github.com/typst/typst/commit/2f81089995c87efdbce6c94bb29647cd1f213cfd, but the panics occur in older versions as well:

1. With `grid` and other more "direct" ways of using `infpt` deriving from `layout`:
```js
#set page(width: auto, height: auto)

#layout(size => grid(columns: (size.width, size.height))[a][b][c][d])
```

<details>
<summary>Resulting panic stack trace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: size.is_finite()', crates/typst-library/src/layout/flow.rs:488:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: typst::doc::Frame::new
             at ~/.../typst/crates/typst/src/doc.rs:51:9
   4: typst_library::layout::flow::FlowLayouter::finish_region
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:488:26
   5: typst_library::layout::flow::FlowLayouter::finish
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:574:9
   6: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:83:9
   7: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
   8: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  11: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  12: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  13: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  14: typst_library::layout::Layout::measure
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:184:9
  15: typst_library::layout::grid::GridLayouter::measure_auto_row
             at ~/.../typst/crates/typst-library/src/layout/grid.rs:508:30
  16: typst_library::layout::grid::GridLayouter::layout_auto_row
             at ~/.../typst/crates/typst-library/src/layout/grid.rs:448:34
  17: typst_library::layout::grid::GridLayouter::layout
             at ~/.../typst/crates/typst-library/src/layout/grid.rs:293:33
  18: <typst_library::layout::grid::GridElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/grid.rs:123:12
  19: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  20: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  22: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  23: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  24: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  25: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  26: <typst_library::meta::context::LayoutElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/meta/context.rs:218:9
  27: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  28: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  30: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  31: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  32: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  33: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  34: typst_library::layout::flow::FlowLayouter::layout_multiple
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:323:24
  35: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:72:17
  36: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  37: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  40: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  41: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  42: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  43: typst_library::layout::page::PageElem::layout
             at ~/.../typst/crates/typst-library/src/layout/page.rs:358:26
  44: <typst_library::meta::document::DocumentElem as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/meta/document.rs:62:32
  45: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:136:13
  46: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  47: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  48: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  49: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  50: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:116:9
  51: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:143:9
  52: typst_library::items::{{closure}}
             at ~/.../typst/crates/typst-library/src/lib.rs:56:42
  53: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  54: typst::model::typeset::{{closure}}
             at ~/.../typst/crates/typst/src/model/mod.rs:75:22
  55: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  56: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  57: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  58: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  59: typst::model::typeset
             at ~/.../typst/crates/typst/src/model/mod.rs:37:1
  60: typst::compile
             at ~/.../typst/crates/typst/src/lib.rs:85:5
  61: typst::compile::compile_once
             at ~/.../typst/crates/typst-cli/src/compile.rs:50:18
  62: typst::compile::compile
             at ~/.../typst/crates/typst-cli/src/compile.rs:25:5
  63: typst::main
             at ~/.../typst/crates/typst-cli/src/main.rs:38:38
  64: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

2. With `line`:
```js
#set page(width: auto, height: auto)

#layout(size => line(length: size.width))
```

<details>
<summary>Resulting panic stack trace</summary>
<p>

```
thread 'main' panicked at 'float is NaN', crates/typst/src/geom/scalar.rs:54:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:2025:5
   5: core::option::Option<T>::expect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:913:21
   6: <typst::geom::scalar::Scalar as core::cmp::Ord>::cmp
             at ~/.../typst/crates/typst/src/geom/scalar.rs:54:9
   7: <typst::geom::abs::Abs as core::cmp::Ord>::cmp
             at ~/.../typst/crates/typst/src/geom/abs.rs:5:16
   8: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
   9: core::cmp::max_by
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/cmp.rs:1271:11
  10: core::cmp::Ord::max
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/cmp.rs:804:9
  11: typst::geom::axes::Axes<T>::max
             at ~/.../typst/crates/typst/src/geom/axes.rs:105:43
  12: <typst_library::visualize::line::LineElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/visualize/line.rs:115:20
  13: typst_library::layout::flow::FlowLayouter::layout_single
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:264:21
  14: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:59:17
  15: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  16: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  19: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  20: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  21: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  22: <typst_library::meta::context::LayoutElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/meta/context.rs:218:9
  23: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  24: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  26: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  27: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  28: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  29: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  30: typst_library::layout::flow::FlowLayouter::layout_multiple
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:323:24
  31: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:72:17
  32: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  33: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  36: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  37: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  38: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  39: typst_library::layout::page::PageElem::layout
             at ~/.../typst/crates/typst-library/src/layout/page.rs:358:26
  40: <typst_library::meta::document::DocumentElem as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/meta/document.rs:62:32
  41: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:136:13
  42: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  43: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  44: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  45: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  46: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:116:9
  47: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:143:9
  48: typst_library::items::{{closure}}
             at ~/.../typst/crates/typst-library/src/lib.rs:56:42
  49: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  50: typst::model::typeset::{{closure}}
             at ~/.../typst/crates/typst/src/model/mod.rs:75:22
  51: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  52: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  53: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  54: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  55: typst::model::typeset
             at ~/.../typst/crates/typst/src/model/mod.rs:37:1
  56: typst::compile
             at ~/.../typst/crates/typst/src/lib.rs:85:5
  57: typst::compile::compile_once
             at ~/.../typst/crates/typst-cli/src/compile.rs:50:18
  58: typst::compile::compile
             at ~/.../typst/crates/typst-cli/src/compile.rs:25:5
  59: typst::main
             at ~/.../typst/crates/typst-cli/src/main.rs:38:38
  60: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

3. With `polygon`:

```js
#set page(width: auto, height: auto)

#layout(size => polygon((0pt,0pt), (0pt, size.width)))
```

<details>
<summary>Resulting panic stack trace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: size.is_finite()', crates/typst-library/src/visualize/polygon.rs:65:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: typst::doc::Frame::new
             at ~/.../typst/crates/typst/src/doc.rs:51:9
   4: <typst_library::visualize::polygon::PolygonElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/visualize/polygon.rs:65:25
   5: typst_library::layout::flow::FlowLayouter::layout_single
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:264:21
   6: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:59:17
   7: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
   8: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  11: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  12: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  13: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  14: <typst_library::meta::context::LayoutElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/meta/context.rs:218:9
  15: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  16: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  19: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  20: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  21: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  22: typst_library::layout::flow::FlowLayouter::layout_multiple
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:323:24
  23: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/flow.rs:72:17
  24: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:218:13
  25: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  26: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  27: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  28: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  29: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:197:9
  30: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:226:24
  31: typst_library::layout::page::PageElem::layout
             at ~/.../typst/crates/typst-library/src/layout/page.rs:358:26
  32: <typst_library::meta::document::DocumentElem as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/meta/document.rs:62:32
  33: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached::{{closure}}
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:136:13
  34: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  35: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  36: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  37: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  38: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:116:9
  39: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root
             at ~/.../typst/crates/typst-library/src/layout/mod.rs:143:9
  40: typst_library::items::{{closure}}
             at ~/.../typst/crates/typst-library/src/lib.rs:56:42
  41: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  42: typst::model::typeset::{{closure}}
             at ~/.../typst/crates/typst/src/model/mod.rs:75:22
  43: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  44: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  45: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  46: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  47: typst::model::typeset
             at ~/.../typst/crates/typst/src/model/mod.rs:37:1
  48: typst::compile
             at ~/.../typst/crates/typst/src/lib.rs:85:5
  49: typst::compile::compile_once
             at ~/.../typst/crates/typst-cli/src/compile.rs:50:18
  50: typst::compile::compile
             at ~/.../typst/crates/typst-cli/src/compile.rs:25:5
  51: typst::main
             at ~/.../typst/crates/typst-cli/src/main.rs:38:38
  52: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</p>
</details>

4. Multiplying by certain units (but not `%` and `fr`):
```js
#(float("inf") * 1pt)
```

<details>
<summary>Resulting panic stack trace</summary>
<p>

```
thread 'main' panicked at 'float is NaN', crates/typst/src/geom/scalar.rs:41:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: <typst::geom::scalar::Scalar as core::cmp::PartialEq>::eq
             at ~/.../typst/crates/typst/src/geom/scalar.rs:41:9
   3: <typst::geom::em::Em as core::cmp::PartialEq>::eq
             at ~/.../typst/crates/typst/src/geom/em.rs:7:15
   4: typst::geom::Numeric::is_zero
             at ~/.../typst/crates/typst/src/geom/mod.rs:113:9
   5: <typst::geom::length::Length as core::fmt::Debug>::fmt
             at ~/.../typst/crates/typst/src/geom/length.rs:41:36
   6: <typst::eval::value::Value as core::fmt::Debug>::fmt
             at ~/.../typst/crates/typst/src/eval/value.rs:189:32
   7: <&T as core::fmt::Debug>::fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:2418:62
   8: core::fmt::write
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   9: core::fmt::Write::write_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:197:9
  10: typst::eval::value::Value::repr
             at ~/.../typst/crates/typst/src/eval/value.rs:145:9
  11: typst::eval::value::Value::display
             at ~/.../typst/crates/typst/src/eval/value.rs:168:29
  12: typst::eval::eval_markup
             at ~/.../typst/crates/typst/src/eval/mod.rs:411:35
  13: <typst_syntax::ast::Markup as typst::eval::Eval>::eval
             at ~/.../typst/crates/typst/src/eval/mod.rs:372:9
  14: typst::eval::eval::{{closure}}
             at ~/.../typst/crates/typst/src/eval/mod.rs:134:18
  15: comemo::cache::memoized::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:65:22
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  18: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.3.0/src/cache.rs:36:5
  19: typst::eval::eval
             at ~/.../typst/crates/typst/src/eval/mod.rs:91:1
  20: typst::compile
             at ~/.../typst/crates/typst/src/lib.rs:77:18
  21: typst::compile::compile_once
             at ~/.../typst/crates/typst-cli/src/compile.rs:50:18
  22: typst::compile::compile
             at ~/.../typst/crates/typst-cli/src/compile.rs:25:5
  23: typst::main
             at ~/.../typst/crates/typst-cli/src/main.rs:38:38
  24: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</p>
</details>

Overall, seems like the behavior is inconsistent; `inf` should either work properly (e.g. when multiplying above, which works for some units and doesn't for others), or cause errors ("don't use inf here"), instead of crashing the entire compiler.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment] 2023-09-23 04:52
4 is caused by multiplying inf by a length that has either zero absolute part or zero em part (`float("inf") * (1pt + 1em)` doesn’t crash), as `0 * inf` results in a NaN.

**Comment by laurmaedje** [comment] 2023-09-28 09:15
Some of these are fixed by https://github.com/typst/typst/pull/2215

**Comment by bluebear94** [comment] 2023-10-03 04:49
The other issues arise from trying to construct a `Frame` with infinite size. While we could handle case in places where `Frame::new` is called, I think it might be better to make `Frame::new` fallible to force callers to handle this case.

**Comment by tingerrr** [comment] 2023-12-12 12:06
Another example which produces `panicked at 'assertion failed: size.is_finite()'`:
```typst
#set page(height: auto)
#show enum: columns.with(2)

+ first
+ second #colbreak()
+ third
+ fourth
```

using the [typst-renderer bot](https://github.com/mattfbacon/typst-bot) with typst 0.10.0 70ca0d257bb4ba927f63260e20443f244e0bb58c.

**Comment by tingerrr** [comment] 2024-04-14 13:13
I just ran into this again when placing 2 images in a grid on an `auto`-sized page, using `0.11.0 (e6f7cc12)`.

```typst
#set page(width: auto, height: auto)

#grid(columns: 2,
  figure(image("a.jpg")),
  figure(image("b.jpg")),
)
```

This one is a little more problematic than the other ones, because no context is used.
It panics at `crates/typst/src/visualize/image/mod.rs:253:25` and can be fixed by passing `width: 100%` to one of the images.

I also noticed that
```typst
#set page(width: auto, height: auto)

#grid(columns: (40%, 40%),
  figure(image("a.jpg")),
  figure(image("b.jpg")),
)
```
simply shows no images at all, while not a panic, undoubtedly an error at least related to the infinite lengths.

**Comment by laurmaedje** [comment] 2024-10-08 16:37
Pasted all of the examples above into 0.12 Testing and got no crash, so I'll close this.

**Closed by laurmaedje** 2024-10-08 16:37 UTC
Labels: bug, layout, scripting
