### ISSUE TITLE
#datetime.today().display() prints 1980-01-01

### ISSUE THREAD

**Issue by jukremer** [typst/typst#5282] opened 2024-10-23 06:07 UTC
### Description

`#datetime.today().display()` prints 1980-01-01. 

As far as I can tell this is a new bug in 0.12.0. Only tried it on macOS.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by woerndl** [comment] 2024-10-23 07:14
I can't reproduce this on 14.6.1 and 0.12. Is there anything else noteworthy about the setup that could help investigate the problem further? Maybe macOS version, the way you compile and what else comes to mind that could be special.

**Comment by mohe2015** [comment] 2024-10-23 07:48
Nix? SOURCE_DATE_EPOCH set?

**Comment by jukremer** [comment] 2024-10-23 08:45
> Nix? SOURCE_DATE_EPOCH set?

Yes I'm using nix.

```
echo $SOURCE_DATE_EPOCH
315532800
```

Do I need to change this?

**Comment by Enter-tainer** [comment] 2024-10-23 10:26
https://github.com/typst/typst/blob/b8034a343831e8609aec2ec81eb7eeda57aa5d81/docs/changelog/0.12.0.md?plain=1#L319

**Comment by Enter-tainer** [comment] 2024-10-23 10:27
If you set SOURCE_DATE_EPOCH, typst will not read real world time to ensure the produced pdf is always identical

**Comment by LaurenzV** [comment] 2024-10-23 12:19
Guess we can close this then, since it's intended.

**Closed by LaurenzV** 2024-10-23 12:19 UTC
Labels: bug

**Comment by jukremer** [comment] 2024-10-23 12:21
Does anyone know why and where Nix sets this?

**Comment by PgBiel** [comment] 2024-10-23 13:02
> Does anyone know why and where Nix sets this?

As explained in https://github.com/typst/typst/issues/5282#issuecomment-2431667556, Nix sets this for maximum reproducibility, noting that one of the main goals of Nix is to ensure reproducible builds, and you can consider `typst compile` to be a "build", so producing the same PDF each time is very important.

As to where this is done, it appears that some Nix build environments do this automatically (e.g. `nix-shell` sets `SOURCE_DATE_EPOCH=1`). You can use `unset SOURCE_DATE_EPOCH`, as explained in the Nixpkgs reference manual: https://nixos.org/manual/nixpkgs/stable/#python-setup.py-bdist_wheel-cannot-create-.whl
