### ISSUE TITLE
Scroll on type should not react to collaborators

### ISSUE THREAD

**Issue by reknih** [typst/typst#1140] opened 2023-05-08 12:05 UTC
### Description

When a collaborator writes something, the preview shall not be scrolled. Reported via user feedback.

**Comment by reknih** [comment] 2023-05-15 15:13
I have difficulties reproducing this. Please report if you experience this issue.

**Comment by laurmaedje** [comment] 2023-07-30 21:14
Duplicate of https://github.com/typst/typst/issues/1588

**Closed by laurmaedje** 2023-07-30 21:14 UTC
Labels: bug, web app
