### ISSUE TITLE
Unknown sessions logged in

### ISSUE THREAD

**Issue by carlobrok** [typst/typst#1689] opened 2023-07-10 11:46 UTC
### Description

I was editing my project across multiple devices over a longer timespan. 
Currently there is only one device logged in, but in the top right the web app states that there are 3 open sessions.

![Screenshot 2023-07-10 133400](https://github.com/typst/typst/assets/44724164/40282b41-9309-42f4-8984-d9317d2b0d5a)

But in the left sidebar and inside the editor there are no markers showing where the other sessions are at the moment.
I don't know how to log out the other sessions.

I remember that i had session errors a few times, that required me to reload the project. Maybe the other sessions were not logged out properly when the error occoured?

### Browsers

Firefox

### OS

Windows

**Comment by LaurenzV** [comment] 2023-07-10 11:57
Duplicate of #1205. It's a known bug, sometimes sessions aren't closed properly, so that's why you see multiple active sessions on the top right.

**Closed** 2023-07-10 12:21 UTC
Labels: bug, duplicate, web app
