### ISSUE TITLE
Q: Full page width figures in a 2-column layout

### ISSUE THREAD

**Issue by 0x7CFE** [typst/typst#913] opened 2023-04-21 11:12 UTC
I'd like to know if it's possible to set up figures (or other elements) that would escape their immediate layout?

For example, for an especially wide image or table, so that it will "tear" columns near the place of its insertion and will occupy the whole page width.

**Comment by Enivex** [comment] 2023-04-21 11:14
Duplicate of https://github.com/typst/typst/issues/553

**Closed** 2023-04-21 11:51 UTC
Labels: duplicate
