### ISSUE TITLE
Invalid escape "\g" on raw syntaxes

### ISSUE THREAD

**Issue by flavio20002** [typst/typst#2202] opened 2023-09-21 11:57 UTC
### Description

The sublime syntax https://github.com/jonschlinkert/sublime-markdown-extended/blob/master/Syntaxes/Markdown%20Extended.sublime-syntax is not parsed by typst . The error is "invalid escape "\g""

### Reproduction URL

https://typst.app/project/w-2sqMyNWpgYl9Yeppy7pr

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-09-21 20:35
Duplicate of https://github.com/typst/typst/issues/1952

**Closed by Enivex** 2023-09-21 20:35 UTC
Labels: bug
