### ISSUE TITLE
Image size isn't honored

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2247] opened 2023-09-26 17:57 UTC
### Description

Look at this simple code in LaTeX:

```latex
\documentclass[a4paper]{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{./images/1024.png}
\includegraphics[scale=1]{./images/512.png}
\end{document}
```

And here is the output:

![image](https://github.com/typst/typst/assets/37143421/c99e752b-93d5-4f81-96f2-ebc2fa36e86c)

With image size honored in LaTeX, I can use other macros/packages to move/place images on a page with extreme precision! And all thanks to the real image size (and helpful EXIF tags). Now let's look at the Typst:

```typ
#image("./images/1024.png")
#image("./images/512.png")
```

And it spits out... Well, let's just say that both images are on separate pages with maximum available size (page margin constraints) and `fit` won't help.

This literally breaks my simple yet very precise position of images on a page (with LaTeX).

(PNG) images (that are exported in GIMP/Krita) have these tags:

```
Pixels Per Unit X               : 11811
Pixels Per Unit Y               : 11811
Pixel Units                     : meters
Image Size                      : 1024x1024
```

Which can be easily used for inserting correct-sized images into PDF documents of the known size.

<details><summary>images</summary>

![512.png](https://github.com/typst/typst/assets/37143421/e6eb289b-da35-4a82-b221-30b9c3eab904)
![1024.png](https://github.com/typst/typst/assets/37143421/9f47ea21-9855-4a44-a5c4-f17d09db2259)

</details>

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-09-28 09:11
Duplicate of https://github.com/typst/typst/issues/436

**Closed by laurmaedje** 2023-09-28 09:11 UTC
Labels: bug
