### ISSUE TITLE
Extra space at the beginning of the new line.

### ISSUE THREAD

**Issue by NoblFriend** [typst/typst#1970] opened 2023-08-21 22:18 UTC
### Description

In this case 
```
#set text(lang: "ru")
#set text(size : 14pt)
#set par (justify: true)

Астроном, наблюдая за Меркурием заметил, что сегодня и три дня назад его поверхностная яркость была абсолютно одинаковая. Считая, что его фаза в этот период времени была практически неизменной и равнялась 1. Определите возможное угловое перемещение по небу за эту неделю. Орбита Меркурия лежит в плоскости эклиптики.
```

there is an extra space in 4th rendered line.
<img width="490" alt="image" src="https://github.com/typst/typst/assets/32647360/7626063f-da7c-403a-befc-ffab4e6d912a">

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-08-21 23:14
Probably a duplicate of #1794.

**Closed** 2023-08-21 23:14 UTC
Labels: bug, text
