### ISSUE TITLE
Compiler crash if empty regex string

### ISSUE THREAD

**Issue by flavio20002** [typst/typst#1790] opened 2023-07-25 09:43 UTC
### Description

See Reproduction URL for an example. Plese note the || after END_VAR

`
  #show raw.where(lang: "iecst"): it => [
    #show regex("\b(VAR_GLOBAL|END_VAR||BOOL)\b") : keyword => text(weight:"bold", fill: blue, keyword)
    #it
  ]
`

In command line the error is **thread 'main' has overflowed its stack**

### Reproduction URL

https://typst.app/project/r5kj-bwO2h3aPpa9yx3rLx

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by user202729** [comment] 2023-07-25 11:25
Shorter code to reproduce:

```
#show "": []
a
```

Not sure why anyone would want to do this though...?

**Comment by Dherse** [comment] 2023-07-25 11:33
> Not sure why anyone would want to do this though...?

I think it's valid to want to do this while you're developing, like "I will add a regex" and save the file. You wouldn't expect this to cause a hard panic, at most an error displayed in the console.

In general, I would argue that you **never panic** even if the user is doing UB or writing erroneous code.

**Comment by flavio20002** [comment] 2023-07-25 12:04
If you are working with command line with autosaving, you must restart the tool at every crash. This is not convenient.

**Comment by user202729** [comment] 2023-07-25 13:13
Duplicate of #229

**Closed** 2023-08-08 12:42 UTC
Labels: bug
