### ISSUE TITLE
More Unicode Support

### ISSUE THREAD

**Issue by DuhPesky** [typst/typst#331] opened 2023-03-26 09:40 UTC
It would be nice if instead of typing RR, I could type \R and the unicode character is what actually shows or I can write \S and the proper sigma unicode shows. This is pretty common in certain theorem provers like Lean or Agda. It heavily reduces the noise on the screen and is immediately more readable than the alternative. Especially when working with a bunch of superscripts/subscripts.

So both ways would be possible to write, but something similar to the 2nd option is what would be allowed from this feature. This is just a trivial example, but for really dense math it would be way easier to read/write.
```
$ A = pi r#sub[1]^2 $
$ "area" = pi dot.op "radius"#sub[1]^2 $
$ cal(A) := { x in RR } $
```

```
$ A = 𝜋 r₁² $
$ "area" = 𝜋 dot.op "radius"₁² $
$ cal(A) := { x ∈ ℝ } $
```

**Comment by user202729** [comment] 2023-03-26 11:56
Duplicate of #92

**Closed** 2023-03-26 12:18 UTC
