### ISSUE TITLE
Use of labels in headings, plus an outline, breaks.

### ISSUE THREAD

**Issue by Quantumplation** [typst/typst#3266] opened 2024-01-26 07:25 UTC
### Description

Consider the following:

```typst
outline()

= Introduction <intro>

= Conclusion <conclusion>
As we stated in the @intro, ...
```

The `<intro>` label will get attached to the `Introduction`, but also get included in the generated outline. This means that when you link to it with `@intro`, it reports "`<intro>` occurs multiple times in the document". For a while this was very confusing, so perhaps a separate piece of work to highlight at least two of the occurences would be helpful.

However, it would be nice for `<label>s` to be filtered out of the generated outline.

Failing that, something like #1889 would also at least allow us to avoid this issue.

### Use Case

I can't think of a scenario where having the `<label>` in both cases would be useful, so perhaps this is better classified as a bug; but this would allow the inclusion of `<label>`s in headings, making them link-able from elsewhere in the document.

**Comment by laurmaedje** [comment] 2024-01-26 09:09
With this minimal example, I'm not able to reproduce it:
```typ
#set heading(numbering: "(1)")
#outline()

= Introduction <intro>

= Conclusion <conclusion>
As we stated in the @intro, ...
```

Are you sure that there isn't a faulty outline show rule at play that uses `element` instead of `element.body` or something like that?

**Comment by Quantumplation** [comment] 2024-01-26 16:19
@laurmaedje Try removing the `#set heading(..)` bit

**Comment by laurmaedje** [comment] 2024-01-26 16:21
If the headings aren't numbered, they can't be referenced because they are numbered by reference. However, that's not related to labels.

**Comment by Quantumplation** [comment] 2024-01-26 18:23
I think the confusion comes from me using the `@reference` shorthand, but the problem I'm encountering is indeed related to labels and links. It seems that `@reference` does something special when it comes to headings that I wasn't aware of, but let me explain using just normal labels and links.

In this example
```typst
#outline()

= Introduction

= Conclusion
See the introduction
```

The outline and headings work fine, and the contents generates links to the various headings correctly.

If I include a label, so that I can provide links to these sections in the body of the text, I get an error, stating that "label <intro> appears multiple times in the document".

```typst
#outline()

= Introduction #label("intro")

= Conclusion
See the #link(label("intro"))[introduction]
```

The problem becomes apparent when I print out a representation of the label instead of the label itself, and comment out the link:

```typst
#outline()

= Introduction #repr(label("intro"))

= Conclusion
See the // #link(label("intro"))[introduction]
```

In the rendered document, we see this:
![image](https://github.com/typst/typst/assets/49870/4b909f83-d90e-41c2-81f1-1c1eb08fad53)

So, the `outline` function is picking up the label from the heading, and including that, which indeed means that there are multiple instances of the same label, making it impossible to `#link` to the label.

I'm suggesting that either:
 - `outline` strips out any labels when rendering the outline, since that will always break the label
 - or (less ideal, but still workable) provide a way to specify an alternate heading for the purposes of `#outline`

Hopefully that's a bit clearer.

**Comment by laurmaedje** [comment] 2024-01-26 19:19
When using the label function after the heading the label is applied to the text _inside_ the heading. This is in contrast to what happens if you use the label syntax, which has a special case in the parser. This is a common cause of confusion and certainly not ideal, but it's unclear what to do about it because the parser doesn't know that it's a label, it could just as well be some function call that should legitimately be part of the heading.

To fix it, you need to add a newline between the heading and `#label` or use the label syntax.

**Comment by Quantumplation** [comment] 2024-01-26 19:38
Ah, ok; Perhaps an update to the error message would be helpful?

Is there a way to use the label syntax with a programmatic field? The reason I'm using the label fn is because I'm generating these headings in a helper function. Specifically, we're writing software audit reports, and have a helper function for each finding that templates out a section for each finding in a consistent way.

I didn't think the newline would work because I didn't think it would have anything to attach to, but I'll try that

**Comment by laurmaedje** [comment] 2024-01-26 19:45
The label syntax doesn't work with programmatic labels at the moment, so with newline is the only way.

**Comment by laurmaedje** [comment] 2024-02-04 11:32
I'll close this as "working as intended". Perhaps the diagnostic could be improved (although that's tricky). Alternatively, and this was discussed recently on Discord, it might be sensible to just not have automatic label attaching for programmatic labels at all and require those to use a dedicated function, method, whatever.

**Closed by laurmaedje** 2024-02-04 11:32 UTC
Labels: feature request

**Comment by Quantumplation** [comment] 2024-02-04 11:41
At the very least, having some indication of where two of the labels are would be helpful 😅 I was tearing my hair out because the label was very clearly only in the markup once, and it took some clever debugging to figure out the table of contents thing
