### ISSUE TITLE
Embed PDFs

### ISSUE THREAD

**Issue by michidk** [typst/typst#834] opened 2023-04-16 12:03 UTC
It would be great if there was a command to embed other PDF files similar to images.
That might even happen without rasterizing the PDF first, so that the PDF commands of the embedded pdf are directly imported into the typst output pdf.
In LaTeX this is possible using the [pdfpages](https://www.ctan.org/pkg/pdfpages) package.

**Comment by laurmaedje** [comment] 2023-04-16 12:39
Duplicate of #145.

**Closed by laurmaedje** 2023-04-16 12:39 UTC
