### ISSUE TITLE
Ending in whitespace breaks smartquotes

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1343] opened 2023-05-27 18:02 UTC
### Description

```
"This works"

" This works"

"This does not work "
```
results in
![image](https://github.com/typst/typst/assets/2191754/fd32af3d-fc12-4962-a94a-abe3a62f95ee)

where the last smart quote is flipped.

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment] 2023-05-27 18:32
I would suggest this is probably *correct* behavior. Smart quotes can only be so smart while still being sane. Quotes are not always matching pairs that you can assume the next one is the opposite direction.

If your input is dirty (as this appears to be) expect dirty output. The correct fix for this is to not have extraneous spaces in your input.

**Comment by Enivex** [comment] 2023-05-27 18:45
> I would suggest this is probably _correct_ behavior. Smart quotes can only be so smart while still being sane. Quotes are not always matching pairs that you can assume the next one is the opposite direction.
> 
> If your input is dirty (as this appears to be) expect dirty output. The correct fix for this is to not have extraneous spaces in your input.

I believe the spaces are _required_ in French actually (though I do not know French).

It could be a documentation issue then, as it's not exactly intuitive when whitespace isn't significant in other situations.

**Comment by alerque** [comment] 2023-05-27 18:59
French is a whole different kettle of fish and doesn't even typically use the same double quotes English uses. Also the spaces required inside its quotation marks should be thin spaces. You can't write an English string and test in an `en` locale setting and say it's broken for French.

The nested quotes example is also best typset in English with a thin space between the quotes, so `“He said, ‘Hello’ ”`. It does seem `typst` does not recognize the non breaking thin space in that scenario, so that would be something to fix.

**Comment by lynn** [comment] 2023-05-29 20:25
I think how this should work is that I input `"Hello"` or `"He said, 'Hello'"` without any extra spaces, and typst adds whatever thin spaces etc are appropriate for the locale. In fact this appears to be how it works already: see library/src/text/quotes.rs, or try

```
#text(lang: "fr")[ J'ai dit "Bonjour, 'monsieur'" ]
```

I'm inclined to agree with @alerque that smart quotes can't be expected to handle messy spaces on the inside of quotes in the _input_, and that this isn't really a bug.

**Comment by wlupton** [comment] 2023-08-02 18:00
Just to note that `" "` results in:

![Screenshot 2023-08-02 at 18 59 50](https://github.com/typst/typst/assets/8874729/de011449-dd75-4edd-bfcc-42de8350c4d0)

Can this really be correct?

**Comment by alerque** [comment] 2023-08-12 17:11
In isolation without further context of content or previous/following open/close statuses, the string `" "` is nonsensical and impossible to resolve to anything definitively correct. Smart quote algorithms rely on sequence info and proximity to other character classes and without those extra clues many situations are ambiguous with no way to really define what is correct.

**Comment by laurmaedje** [comment] 2023-11-14 21:06
Based on the conversation, I'm going to close this as 'working as intended'.

**Closed by laurmaedje** 2023-11-14 21:06 UTC
Labels: bug, text
