### ISSUE TITLE
Tracking: artifacts when rendering stroked paths with pdf.js

### ISSUE THREAD

**Issue by alexneufeld** [typst/typst#1611] opened 2023-06-29 06:18 UTC
### Description

When rendering curved paths, these strange wisps sometimes show up:
![image](https://github.com/typst/typst/assets/37948669/270f42fc-e989-442a-8343-d9ed4b097b95)
This seems to only occur when viewing the pdf using [pdf.js](https://github.com/mozilla/pdf.js) in (specific versions of?) Firefox.

Overriding typst's default behavior of using mitered path joins mitigates this issue.

example code (using typst-canvas):
```
#import "canvas.typ": canvas

#canvas({
  import "draw.typ": *
  // remove the explicit stroke settings to cause artifacts
  bezier((0, 0), (2, 0), (1, 1), stroke: (join: "round",))
  bezier((0, -1), (2, -1), (.5, -2), (1.5, 0), stroke: (join: "round",))
})
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by alexneufeld** [comment] 2023-06-29 06:19
see also: [https://github.com/mozilla/pdf.js/issues/16619](https://github.com/mozilla/pdf.js/issues/16619)

**Comment by LuxxxLucy** [comment] 2023-09-07 02:19
given the discussion https://github.com/mozilla/pdf.js/issues/16619#issuecomment-1677078317 it seems that this is a firefox issue, which is not fixable within pdf.js. And so the issue is closed. 


In this case, it seems to me that this problem should not be possible for typst to fix, nor it should be the duty/responsibility for typst. I suggest closing this issue.

**Comment by freundTech** [comment] 2023-09-09 16:26
> In this case, it seems to me that this problem should not be possible for typst to fix, nor it should be the duty/responsibility for typst. I suggest closing this issue.

I would disagree here. I think this could severely hinder adoption of Typst and therefor Typst should try to work around it at least until the bug is fixed in the oldest still supported Firefox Extended Support Release (ESR) version.

No one wants to typeset a professional document, possibly a scientific paper or thesis, only to then have it completely broken for a not insignificant part of the audience, which could possibly include reviewers.

The bug fix in Firefox seems to be scheduled for Firefox 119 (having missed the cutoff date for 118).

The current version of Firefox is 117 and the current ESR version is 115, which will be supported for around another year, at which point the workaround could probably be dropped.


In suggesting this I'm assuming that a workaround would be possible and not to costly, which I think is a fair assumption, as I've never encountered this bug in Firefox before and have used it as a pdf reader for multiple years. Similarly no-one seems to have reported this bug to Firefox before, until a Typst user found it.


Here is a screenshot from the CeTZ manual to show just how broken a document can look with just some graphs inserted: 
![Screenshot from 2023-09-09 17-20-56](https://github.com/typst/typst/assets/9515067/75c7dae2-dc5e-4e5e-9cd0-e30c5909cbb2)

**Comment by laurmaedje** [comment] 2023-09-09 16:52
If there's a good workaround, I would be totally fine with merging it. I won't have time to look into this myself though.

**Comment by LuxxxLucy** [comment] 2023-09-09 16:58
> The bug fix in Firefox seems to be scheduled for Firefox 119 (having missed the cutoff date for 118).
> 
> The current version of Firefox is 117 and the current ESR version is 115, which will be supported for around another year, at which point the workaround could probably be dropped.
> 
> In suggesting this I'm assuming that a workaround would be possible and not to costly, which I think is a fair assumption, as I've never encountered this bug in Firefox before and have used it as a pdf reader for multiple years. Similarly no-one seems to have reported this bug to Firefox before, until a Typst user found it.
> 
> Here is a screenshot from the CeTZ manual to show just how broken a document can look with just some graphs inserted: ![Screenshot from 2023-09-09 17-20-56](https://user-images.githubusercontent.com/9515067/266791750-75c7dae2-dc5e-4e5e-9cd0-e30c5909cbb2.png)

Thank you for putting it in necessary context. Now after reading it, I begin to think that we should figure out a workaround in typst, otherwise it might remain unsolved for a long time.  I will try to take a look.  

Meanwhile we need reopening the issue for tracking.

**Comment by freundTech** [comment] 2023-09-09 17:01
Would setting the default stroke join to `round` or `bevel` and adding a warning to the docs where the `miter` option is listed an acceptable solution?

The bug seems to only affect mitered paths.

**Comment by laurmaedje** [comment] 2023-09-09 17:11
@reknih

**Comment by LuxxxLucy** [comment] 2023-09-12 17:52
Here is my discovery:

1. The artifact can be reproduced. I tested multiple version of firefox, and have tweaked the typst and typst-canvas version (by commit id) for the last two months. The artifact can be observed.
2. The problem is indeed related to miter, but not necessarily just bezier curve. As ultimately a curve is passed down as a collection of line segment and then joined together, the artifact can also be observed when we write down a series of line segments, as in the case of typst-canvas plot.
```
#canvas({
  plot.plot(
  size: (3,3), x-tick-step: 1, axis-style: "left", {
    for i in range(0, 1) {
      plot.add(domain: (-4, 2),
        x => calc.exp(-(calc.pow(x + i, 1))),
        fill: false, style: tango,
        )
    }
  })
})
```

<img width="951" alt="Pasted Graphic 1" src="https://github.com/typst/typst/assets/19356905/0dd78c56-4e06-4708-bcfc-bf8df5cbb380">

So this means just tweaking the default option for bezier curve is not enough. 

I found that a simple solution would be setting the default miter limit value to a small value that, almost certainly, we would exceed the miter limit and then trigger bevel for the line segment join. This should be a straightforward work around. As see in PR #2116 

And then it would be fixed  
<img width="661" alt="image" src="https://github.com/typst/typst/assets/19356905/2601967d-b9c9-457e-86af-58dc6ca4f0a6">


I think for this bug, we will need input from different users in their respective platforms. So I suggest @freundTech @alexneufeld as well as people familiar with the typst-canvas repo @johannes-wolf (for the broken typst-canvas/manual.pdf in firefox as in the example above) to double check that the change actually fixes the problem.

**Comment by johannes-wolf** [comment] 2023-09-12 18:12
@LuxxxLucy Setting a `miter-limit` only fixes the "ray" artifacts, but in your example picture line endings are also rendered wrong.

**Comment by LuxxxLucy** [comment] 2023-09-12 18:20
> @LuxxxLucy Setting a `miter-limit` only fixes the "ray" artifacts, but in your example picture line endings/caps are also rendered wrong. (I personally suggest doing nothing and wait for Firefox to release their fix).

Oh sorry, This is because I tweaked the cetz code a little that I removed. I reverted those changes and now the images has been updated.

**Comment by LuxxxLucy** [comment] 2023-09-12 18:26
Another way to fix the ray artifact in the cetz manual is that we can increase the number of samples in `plot` from 100 to say, 10000, in this way we implicit makes it break the miter limit and thus would trigger bevel. But I am afraid that would not be a neat solution....

**Comment by johannes-wolf** [comment] 2023-09-12 18:27
Setting a `miter-limit` is problematic, esp. if it is small. Everything < sqrt(2) will give bad rectangular joins which is not acceptable I think.

**Comment by LuxxxLucy** [comment] 2023-09-12 18:47
After playing around with miter-limit, I begin to realize that this is indeed problematic that the visual result becomes very different.

**Comment by Enivex** [comment] 2023-10-10 09:59
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1841020 this is now fixed in Firefox nightly.

**Closed** 2023-10-10 09:59 UTC
Labels: bug, help wanted, visualize
