### ISSUE TITLE
Issue with Numbering Color Not Changing as Expected in Scope

### ISSUE THREAD

**Issue by ruziniuuuuu** [typst/typst#3336] opened 2024-02-04 03:32 UTC
### Description

When I set a text color within a scoped section, the color change is not applying to the bullet point numbering as I expected.

```typst
This is a black line.
- black line 1
- black line 2
#[
  // a scope which I wanna change the text color
  #set text(fill: red)
  - red line 1
  - red line 2
]
```
![image](https://github.com/typst/typst/assets/54934297/96dc020a-b842-4690-881b-7cf63675fce2)
I would expect that when changing the text color within a scoped section, the bullet point numbering would also change to the specified color.

When I uncomment the first two bullet points, the bullet numbering color changes to red, matching the newly uncommented text. This suggests that the coloring of bullet points may be linked to the state (commented or uncommented) of the text rather than the scoped color setting.

```typst
This is a black line.
// - black line 1
// - black line 2
#[
  // a scope which I wanna change the text color
  #set text(fill: red)
  - red line 1
  - red line 2
]
```
![image](https://github.com/typst/typst/assets/54934297/198f1c02-e604-4155-b68c-6e80538a615f)

So is there a way to ensure the bullet point numbering  color changes along with the text whinin the scope? Or could this be a bug in the compilation process of the editor?

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-02-04 08:53
Duplicate of https://github.com/typst/typst/issues/619

**Closed by laurmaedje** 2024-02-04 08:53 UTC
Labels: bug
