### ISSUE TITLE
Add Support for Initial Letters

### ISSUE THREAD

**Issue by Itschotsch** [typst/typst#4046] opened 2024-04-30 19:55 UTC
### Description

From [Wikipedia](https://en.wikipedia.org/wiki/Initial): "An initial is a letter at the beginning of a word, a chapter, or a paragraph that is larger than the rest of the text." Additionally, initials often have a different colour and font.
Examples from the [TeX StackExchange](https://tex.stackexchange.com/questions/769/how-can-i-create-documents-in-latex-using-a-calligraphic-first-letter-for-chapte):
![S](https://i.stack.imgur.com/LO87S.png)
![I](https://i.stack.imgur.com/GyVi9.png)
![L](https://i.stack.imgur.com/l9h5R.png)

### Use Case

Apart from marking the start of a new chapter, for example, initials are purely cosmetic.
Personally, I would like to use the feature for a (fiction) book layout.

**Comment by Enivex** [comment] 2024-04-30 20:00
Duplicate of https://github.com/typst/typst/issues/357

**Closed** 2024-04-30 20:01 UTC
Labels: duplicate, feature request
