### ISSUE TITLE
Evaluate Typst code in SVG images

### ISSUE THREAD

**Issue by SolidTux** [typst/typst#5482] opened 2024-11-27 08:54 UTC
### Description

Inkscape has the option to export the file as PDF+TeX which results in the text being handled by (La)TeX. Something similar would be great to have for Typst. One option that I could see is to have an optional switch resulting in text in a svg not being rendered as strings, but evaluated as typst code.

### Use Case

Design SVGs in other software and get a more coherent look and use Typst features like references in labels

**Comment by Dherse** [comment] 2024-11-27 09:04
Duplicate of #1417

**Closed** 2024-11-27 09:04 UTC
Labels: duplicate, feature request
