### ISSUE TITLE
Glyphs in fonts without an assigned unicode value

### ISSUE THREAD

**Issue by cskeeters** [typst/typst#5281] opened 2024-10-23 05:17 UTC
### Description

The font Novela Regular (free or paid version) comes with three ornaments named `fleuron001.ornm`, `fleuron002.ornm`, and `fleuron003.ornm`.  These three glyphs have no unicode value associated with them.  I confirmed this with Font Book (macOS), `fontforge` and `otfinfo -u`.  I reviewed the lookup tables in `fontforge` to see if the `ornm` feature (or any other) could somehow utilize those glyphs, but didn't see anything.

I asked the author if they had any guidance for getting this working and they said that they only support their use with illustrator by using the pictograms tab.

I wonder if it would be possible to have a method like `str.from-glyph(698)` or `str.from-glyph("fleuron001.ornm")` where the glyph id or name is referenced directly from the underlying font.

I don't know how common it is for fonts to have glyphs that are associated with no unicode value.  I kinda suspect this is more the font authors issue, but I thought I'd create an issue so the concern could be addressed, if possible.

<img width="362" alt="image" src="https://github.com/user-attachments/assets/966a079e-1c18-4695-852d-fb2abb058acd">

I was able to work around this issue with any of the following methods:
1) Open the font in `fontforge` and copy the glyph and paste it into a unicode spot.  For these, I used `\u{273E}`, `\u{273F}`, and `\u{2740}` since those are related to fleuron in unicode, but any unused value would work.
2) Export all glyphs as svg files and then use svgs as images.

```
mkdir -p svg
fontforge -lang=ff -c \
    'Open($1); SelectAll(); UnlinkReference(); Export("svg/%n-%e.svg");' \
    Novela-Regular.otf
```

These work, but are a bit of a hassle for those who just want to use the fonts as they are.

### Use Case

This will enable users to utilize glyphs in fonts that have no assigned unicode value.

**Comment by TS53** [comment] 2024-10-23 05:23
Glyph from Unicode Value: [`str.from-unicode`](https://typst.app/docs/reference/foundations/str/#definitions-from-unicode)
Glyph from Glyph Name: https://github.com/typst/typst/issues/4393

**Comment by PgBiel** [comment] 2024-10-23 05:29
Thanks @TS53. Closing as a duplicate of #4393

**Closed** 2024-10-23 05:29 UTC
Labels: feature request

**Comment by cskeeters** [comment] 2024-10-23 21:36
If anyone else wants to correct Novela specifically, they can use this.

https://github.com/cskeeters/novela-typst
