### ISSUE TITLE
Compiler crash in math mode

### ISSUE THREAD

**Issue by qguv** [typst/typst#5494] opened 2024-11-29 13:13 UTC
### Description

The following code crashes Typst 0.12.0: 

    $or med #h(1em)$ t

### Reproduction URL

https://typst.app/project/rh5mzYlxjD5jiMcRXcHlba

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-11-29 14:51
Duplicate of https://github.com/typst/typst/issues/5253

**Closed by laurmaedje** 2024-11-29 14:51 UTC
Labels: bug
