### ISSUE TITLE
In support of margin notes/captions/figures

### ISSUE THREAD

**Issue by mbaz** [typst/typst#3027] opened 2023-12-21 00:46 UTC
### Description

I'd like to cast my vote for margin notes support (and captions, and figures). The roadmap mentions "**maybe** margin notes", which gives me hope.

### Use Case

Some layouts, such as those espoused by Tufte (see [Tufte](https://ctan.org/pkg/tufte-latex?lang=en)), make heavy use of margin figures, captions and notes. I often use often in Latex, since I think it results in very pleasing documents where small figures and notes do not disturb the flow of the main text.

**Comment by CGMossa** [comment] 2023-12-21 01:20
I think this can be done in a package.

And there would be so many questions about how to do this anyways, that starting out in a package would most likely be very productive.

If you know someone that knows the ins and outs of that, then you can maybe suggest them to do such a project. The discord provides ample support to everyone.

**Comment by Enivex** [comment] 2023-12-21 14:02
Duplicate of https://github.com/typst/typst/issues/1337

**Closed by Enivex** 2023-12-21 14:02 UTC
Labels: feature request
