### ISSUE TITLE
Unicode superscript subscript not to be treated as identifiers in maths

### ISSUE THREAD

**Issue by lumi-a** [typst/typst#3280] opened 2024-01-27 11:42 UTC
### Description

I'm writing a package to solve #592 and #1840. In the current Typst version, `$aᵇ$` results in an "unknown variable" error, as `aᵇ` is treated as an identifier. 
To avoid having to type `a ᵇ` instead — regardless of whether Unicode superscript-/subscript support is implemented natively or just via a package — it'd be necessary to not treat `aᵇ` as a single identifier.

This would constitute a breaking change, but I suppose few people use Unicode superscript- and subscript characters in identifiers in math-mode.

### Use Case

If Unicode superscript-/subscript support is implemented, allowing `$aᵇ+5$` is an improvement over just allowing `$a ᵇ+5$` (both rendering like `$a^b + 5$`).

**Comment by Enter-tainer** [comment] 2024-01-27 12:08
making a package doesnt necessarily need this change. you can take a string as input

**Comment by lumi-a** [comment] 2024-01-29 21:00
That's a great idea, thank you! It's now implemented in the [`super-suboptimal`-package](https://github.com/typst/packages/tree/main/packages/preview/super-suboptimal/0.1.0).
Taking strings as an input unfortunately comes at the cost of syntax-highlighting (is it possible to have Typst syntax-highlighting in `raw`-blocks that don't have their `lang` set to `typst`?) and code suggestions, so splitting identifiers in maths would still be an improvement :)

**Comment by Trebor-Huang** [comment] 2024-02-15 03:47
I would like to suggest the opposite feature: allow all unicode sup/subscripts in variable names, which means forbidding the usage of `M₂` as mathematical formulas, and you have to write `M ₂` instead. This is because allowing `M₂` may create the illusion that `M₂ / 3` is handled the same as `M_2 / 3`, which it is not.

This also allows the code to use variable names like `M₂`, which looks better than `M2` imo, but that's a minor consideration.

**Comment by Enter-tainer** [comment] 2024-02-15 03:57
Identifier rule in typst is not defined randomly. typst follows [Unicode Standard Annex #31](https://www.unicode.org/reports/tr31/), which is a very comprehensive guideline.

- relevant code: https://github.com/typst/typst/blob/main/crates/typst-syntax/src/lexer.rs#L745-L755

**Comment by Trebor-Huang** [comment] 2024-02-15 04:01
Nonetheless we can forbid this usage which is unrelated to identifiers.

**Comment by laurmaedje** [comment] 2024-07-16 16:18
I would classify this as a duplicate of https://github.com/typst/typst/issues/592

**Closed by laurmaedje** 2024-07-16 16:18 UTC
Labels: feature request, math, syntax
