### ISSUE TITLE
Inline `cases` looks scuffed

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5332] opened 2024-10-30 04:02 UTC
### Description

Perhaps there are several issues hidden within this example. I'm not happy with how awful the math typesetting looks inside the `cases`. Without the hack at the top, I had to use all sort of spaces to make it at least bearable. I'm pretty sure it's the intended use case, but maybe the inline behavior was not implemented correctly?

```typ
#set scale(reflow: true)
#let var = text.with(font: "Libertinus Serif")
#let Num = var("Num")
#let Gr = var("Gr")
#let case = {
  set par(leading: 0.1em)
  show: scale.with(80%)
  $lr(size: #110%, \{
  #block($
    2 dot cos(2 dot (Gr dot t + Num)),& t in [0; pi],\
    3 dot cos(Gr dot t + Num),        & t in [pi; 2pi];$))$
}

Сигнал $f(t)$ задан в 256 точках отрезка $[0; 2pi]$ представляет собой сумму
// empty line to remove overlap
- периодической компоненты $p(t) = case$
- #lorem(10)

Сигнал $f(t)$ задан в 256 точках отрезка $[0; 2pi]$ представляет собой сумму
// empty line to remove overlap
- периодической компоненты $p(t) = cases(
    2 dot cos(2 dot (Gr dot t + Num))\, t in [0; pi]\,,
    3 dot cos(Gr dot t + Num)\,         t in [pi; 2pi]\;
)$
- #lorem(10)
```

![image](https://github.com/user-attachments/assets/476c34d9-05bd-43ac-a2da-cca75fd69855)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment] 2024-10-30 09:13
`cases` is fundamentally multi-line. It does not make sense to use it inline and expect a good-looking result imo.

**Comment by laurmaedje** [comment] 2024-10-30 09:53
I'm not sure what the bug here is tbh. What is expected vs seen?

**Comment by Andrew15-5** [comment] 2024-10-30 12:15
The hack/above is what I would prefer, but it also overlaps more, so I definitely have to insert a blank line. All symbols are evenly spaced, unlike the `cases()`.

**Comment by Andrew15-5** [comment] 2024-10-30 12:18
> `cases` is fundamentally multi-line. It does not make sense to use it inline and expect a good-looking result imo.

I would expect it to still work inline. It will be just taller and/or smaller in scale. Fractions are also fundamentally take 2 lines, but they look fine inline (I think they are just very small, which can be done to the `cases()`).

**Comment by laurmaedje** [comment] 2024-10-30 12:27
Ah, now I see. The uneven spacing between the symbols is a bit odd indeed. But it is not caused by cases. You get the same with `frac` instead of `cases`. The problem is the interaction of you how define the Num and Gr variables and cramped style. Typst retains the spaces around content it doesn't consider mathematical (e.g. text).

**Comment by Andrew15-5** [comment] 2024-10-30 12:48
I don't understand why it wouldn't retain the spaces around mathematical content, because in the hack it has spaces everywhere. The whole point in math mode is that all the spaces are added everywhere so it all look good. But it doesn't.

I also don't get if you are saying it's a bug or not.

Is there a workaround for the `cases` to look as good as the hack?

**Comment by Andrew15-5** [comment] 2024-10-30 13:13
Got it. Do you want to rename the issue then?

**Comment by laurmaedje** [comment] 2024-10-30 14:03
I wonder how this should be addressed. In principle, I think something needs to be changed in your document to (because right now Num and Gr _are text), but I'm not sure we have the correct primitives. This might fall under https://github.com/typst/typst/issues/1125.

**Comment by Enivex** [comment] 2024-10-30 14:23
Might want to add a math class to your variables.

**Comment by Andrew15-5** [comment] 2024-10-30 18:10
https://typst.app/docs/reference/math/class/

Maybe the documentation isn't great, but I'm reading that a variable should be `"normal"`, since it's not an "operator". But this value doesn't fix anything at all. Instead, vary, unary, binary can be used. But those are for operators like `+`.

<details><summary>code</summary>

```typ
#set scale(reflow: true)
#let var(v) = math.class("vary", text(font: "Libertinus Serif", v))
#let Num = var("Num")
#let Gr = var("Gr")
#let case = {
  set par(leading: 0.1em)
  show: scale.with(70%)
  $lr(size: #110%, \{
  #block($
    2 dot cos(2 dot (Gr dot t + Num)),& t in [0; pi],\
    3 dot cos(Gr dot t + Num),        & t in [pi; 2pi];$))$
}

Сигнал $f(t)$ задан в 256 точках отрезка $[0; 2pi]$ представляет собой сумму
// empty line to remove overlap
- периодической компоненты $p(t) = case$
- #lorem(10)

Сигнал $f(t)$ задан в 256 точках отрезка $[0; 2pi]$ представляет собой сумму
// empty line to remove overlap
- периодической компоненты $p(t) = cases(
    2 dot cos(2 dot (Gr dot t + Num))\, t in [0; pi]\,,
    3 dot cos(Gr dot t + Num)\, t in [pi; 2pi]\;
  ,

  )$
- #lorem(10)
```

</details>

![image](https://github.com/user-attachments/assets/ae071bdf-d095-40ec-b232-ed29820a2ebf)

Just for the context, here is the original thing:

![image](https://github.com/user-attachments/assets/8815a716-d39a-4ca8-ad8a-daa8ae773460)

<details><summary>creator & producer</summary>

Microsoft® Word 2019 (bleh)

</details>

So, I like it more now, because at least the no-spaces thing is consistent across the whole cases. But:
1. why do I have to use a for-"operator" class/where is the "variable" class?
2. I still 100% prefer the spaces-included version (which is also how the original looks).
3. I don't think the main issue is with text/markup font vs. math font (#1125) etc. My main problem is (from point 2) that regardless of which font/class is used, I want to have spaces, because it is more natural and more readable. It could be something like:

```typ
#show math.equation.where(block: false): set math.equation(please-add-spaces-when-inline: true)
// or
#set math.equation(please-add-spaces: true)
```

**Comment by laurmaedje** [comment] 2024-10-31 14:04
> why do I have to use a for-"operator" class/where is the "variable" class?

There is no variable class in Unicode. But Typst should still have some good way to configure this.

> I still 100% prefer the spaces-included version (which is also how the original looks). I don't think the main issue is with text/markup font vs. math font (https://github.com/typst/typst/issues/1125) etc. My main problem is (from point 2) that regardless of which font/class is used, I want to have spaces, because it is more natural and more readable. It could be something like:

The contents of inline cases don't have inline size, they have `script` size. In `script` size, spaces are omitted in the TeX math layout algorithm. There are various built-in assumptions about how math should be laid out in the algorithm and this is one of them. I'm not saying that it's the be-all-end-all of how it should be done, but that's the way it is at the moment.

**Comment by laurmaedje** [comment] 2024-11-01 20:13
I think this basically boils down to having a better way to indicate a variable in Typst code (#1125) + potentially having an option to have spacing around operators in script mode. The first already has an issue. For the second, I'm not sure whether we want to support this, but in any case it would make a more actionable issue than this one here. I'll close this one and defer to you whether you want the spaced script mode enough to open a separate feature request.

**Closed by laurmaedje** 2024-11-01 20:13 UTC
Labels: bug

**Comment by Andrew15-5** [comment] 2024-11-02 09:26
https://github.com/typst/typst/issues/5352
