### ISSUE TITLE
Introducce Syntax for Documenting user (and package author) defined functions.

### ISSUE THREAD

**Issue by Sinthoras7** [typst/typst#5094] opened 2024-10-02 08:06 UTC
### Description

When I use a function from the standard library (e.g. in the Web App) there are nice little hints in the autocompletion that tell me what the function does and what its arguments are and so on.

In other programming languages there is a syntax for documentation comments that then show up in the autocompetion or the hint when hovering. (E.g. in Fortran a normal comment is ! while a documentation comment is either !! or !>. So when you declare a variable and write a comment beginning with !! after it, then whenever the variable is sugested by autocompletion the comment shows up and tells you what the variable is about)

It would be nice to have that in Typst too.

### Use Case

This might be useful for all Typst users. Especially 
1. those who define a lot of functions and variables themself and can not keep in mind the syntax and meaning of  all of them
2. the users of functions that they have not written themself, especially
  a. users of packages
  b. users of code they got from friends, the internet, etc.

I believe (almost) all typst users fall into these groups and it would make editing typst easier and more enjoyable and it reduces the friction of using typst.

**Comment by mkorje** [comment] 2024-10-02 08:14
Duplicate of #2375 I believe.

**Closed** 2024-10-02 09:50 UTC
Labels: feature request

**Comment by Andrew15-5** [comment] 2024-10-02 11:48
This was mentioned in https://forum.typst.app/t/how-can-i-document-my-own-user-defined-functions-variables/839/5.

I believe this is not a duplicate as both issues have different goals. The linked issue wants to use doc strings to then generate a documentation/reference based on doc strings. Mainly, this should generate an HTML output. While this issue is about writing a doc string and then using it in an IDE (including the web app). Therefore, an `ide` label should be added and `duplicate` removed.

So while they both rely on some sort of official doc string syntax, the actual/total work that is needed to achieve each goal is completely different (if we exclude the first stage "add doc string").

Since tinymist already supports this feature, I think it is safe to say that it's easier to add this feature rather than https://github.com/typst/typst/issues/2375, which also implies supporting HTML export.

**Comment by laurmaedje** [comment] 2024-10-02 11:50
From the title, both are clearly about doc comments. Doc comments are involved in various different features, but having fine-grained issues for those when we don't even have doc comments yet feel premature to me.

**Comment by Andrew15-5** [comment] 2024-10-02 11:54
I guess until we introduce doc comments, this is true for the most part. But if so, we still have to keep in mind that these are different feature requests. IMO, having separate issues is easier to track later on, as you don't have to remember that it's not a "yet another duplicate" like the majority of other issues are.
