### ISSUE TITLE
Change `block`'s `radius` depending on the broken part (`breakable: true`)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2176] opened 2023-09-17 21:40 UTC
### Description

Right now, I can change the corners of the `block` with set rule or in the function call. But if the `block` is broken down into parts because of it being longer than 1 page, each part will have the same `radius` settings. With `tcolorbox` (LaTeX) I can make it so that the first part of the `block` will have only `top` round corners and the second part will have only `bottom` round corners. This will create an effect of seamlessness between pages (especially if `page(margin: 0pt)`). AFAIK, this is not possible right now (maybe with `locate`).

Here are: start, bottom page break, top page break, bottom page break, top page break, end of the long source code with `tcolorbox`:

3rd page:
![image](https://github.com/typst/typst/assets/37143421/205ba214-5b36-40e4-9226-e57982befc04)
![image](https://github.com/typst/typst/assets/37143421/973dedf7-3fb0-43e9-9d2a-7303d7f51384)

4th page:

![image](https://github.com/typst/typst/assets/37143421/f4457e32-c017-4aff-84c2-28a2cab75ece)
![image](https://github.com/typst/typst/assets/37143421/f56fd33f-4d22-4e68-b539-b8f51f9f533b)

5th page:

![image](https://github.com/typst/typst/assets/37143421/9952b472-1fe0-467e-b966-a1a78f7e0592)
![image](https://github.com/typst/typst/assets/37143421/3501b0d6-9511-4762-865b-5fb9482a1acc)

Note that where the break is happening there is no horizontal line (it sometimes appears, but ideally it never should appear), which makes the seamlessness effect to the perfection.

### Use Case

This feature will add customizability of each part of the `breakable` `block` (at least `radius` and maybe `stroke`).

**Comment by laurmaedje** [comment] 2023-09-18 09:46
Duplicate of #735.

See also: https://github.com/typst/typst/pull/1773 and https://github.com/typst/typst/pull/2014

**Closed by laurmaedje** 2023-09-18 09:46 UTC
Labels: feature request
