### ISSUE TITLE
`polygon` with `"parent"`-relative gradient doesn't work unless fully contained within its parent

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4820] opened 2024-08-23 22:11 UTC
### Description

I think this is best explained by the following example:

```typ
#let stops = (black, white)

#show: block.with(
  width: 10cm,
  height: 10cm,
  stroke: 1pt + purple,
  fill: gradient.radial(..stops),
)

#polygon(
  (5cm, 5cm),
  (5cm, 10cm),
  (14cm, 5cm),
  stroke: blue,
  fill: gradient.radial(..stops, relative: "parent"),
)
```

![The gradient on the polygon is not actually relative to the block.](https://github.com/user-attachments/assets/d5cf2cf2-5cd1-4faf-8565-44fd60f35bb3)

Note that the issue disappears when the polygon is contained within its parent:

![Same as above, but the the polygon is fully contained within the block. This time, the gradient on the polygon is relative to the block.](https://github.com/user-attachments/assets/24627744-6aa7-42da-abfd-a9f03a9e69d2)

Tested on 0.11.1.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment] 2024-08-23 22:45
Duplicate of #3932 (with patterns, but same underlying issue I think)

> Note that the issue disappears when the polygon is contained within its parent:

This is not always the case, see e.g. with
```typ
#polygon(
  (1cm, 1cm),
  (6cm, 2cm),
  (2cm, 6cm),
  stroke: blue,
  fill: gradient.radial(..stops, relative: "parent"),
)
```
![image](https://github.com/user-attachments/assets/416898a0-e68f-4c8e-b9d4-d70fec39cbd0)

**Comment by MDLC01** [comment] 2024-08-23 23:28
The issues are indeed similar. I will let more knowledgeable people close this one if it is really a duplicate.

**Closed** 2024-08-26 17:24 UTC
Labels: bug
