### ISSUE TITLE
Math equation overlap with `rect` or `table` when text size is increased

### ISSUE THREAD

**Issue by Entoryvekum** [typst/typst#3284] opened 2024-01-28 05:30 UTC
### Description

When text size is increased, math equation may overlap with surrounding `rect` or `table`

```typst
#set text(size: 22.5pt,font: ("Times New Roman"))

#rect[
  $mat(
    delim: "[",
    1,0,0,0,0,0;
    2,0,0,0,0,0;
    3,1,0,0,0,0;
    4,4,0,0,0,0;
    5,10,6,0,0,0;
    6,20,6,0,0,0;
  )$
]

#table[
  $1/q$,
  $e^e^e^e^e$
]
```
![图片](https://github.com/typst/typst/assets/20198566/a6a7a800-04de-428f-acf6-da2f0e3baf62)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2024-01-28 06:03
can you try displayed equation? by putting extra space in $

**Comment by laurmaedje** [comment] 2024-01-28 08:56
Duplicate of https://github.com/typst/typst/issues/1028

**Closed by laurmaedje** 2024-01-28 08:56 UTC
Labels: bug
