### ISSUE TITLE
Grouping of adjacent references

### ISSUE THREAD

**Issue by TimotheAlbouy** [typst/typst#4382] opened 2024-06-12 09:59 UTC
### Description

Since #1606 we can group adjacent citations: `@my-article-1 @my-article-2` yields "[1,2]".

But currently, this grouping does not work for references (Sections, Figures, ...): `@my-section-1 @my-section-2` yields "Section 1 Section 2".

What could be nice is to implement reference grouping so that one can fine-tune the appearance of adjacent references.

### Use Case

There could be a default behaviour for adjacent references, like in the cleveref package of LaTeX. For example, `@my-section-1 @my-section-2` would yield "Sections 1 and 2" (notice the plural form).

But it could also be good to have a way to override this default behaviour, using a show rule for instance. For example,  using an appropriate show rule, `@my-section-1 @my-section-2` would yield "Sections 1-2".

I know that there is still the workaround of using the `supplement` parameter of the [ref element](https://typst.app/docs/reference/model/ref/) (e.g. you can currently write `@my-section-1[Sections] @my-section-2[and]` to yield "Sections 1 and 2"), but having such syntax would relieve the end-user of specifying the desired appearance for each group of adjacent references.

**Comment by laurmaedje** [comment] 2024-07-16 16:50
Duplicate of https://github.com/typst/typst/issues/3404

**Closed by laurmaedje** 2024-07-16 16:50 UTC
Labels: feature request, model
