### ISSUE TITLE
automatic line break at inline math operators

### ISSUE THREAD

**Issue by gertjanvanzwieten** [typst/typst#2624] opened 2023-11-08 12:01 UTC
### Description

When a paragraph contains a long inline equation such as `$a + b + c + d + e + f + g + h$`, then current (0.9.0) typst behaviour is to introduce a line break before the equation if it does not fit the line in its entirety, regardless of the gap that this leaves behind.

```
This is a paragraph that contains |
the equation                      |
a + b + c + d + e + f + g + h and |
that does not break inline        |
equations.                        |
```

It would be nice if typst would facilitate automatic breaking inside the equation to achieve a more homogeneous paragraph layout.

```
This is a paragraph that contains |
the equation a + b + c + d + e +  |
f + g + h and that breaks inline  |
equations at operators.           |
```

It would seem that a change of this kind can be introduced in a backwards compatible fashion by adding an argument to the `math.equation` function to enable and possibly configure the breaking logic.

### Use Case

Inline mathematics tends to produce uneven line lengths in ragged paragraphs, or very large word spacing in justified paragraphs, if they are handled as unbreakable units. In many common situations this is greatly improved by allowing equations to break at appropriate points, such as after an operator. Currently, the only known way to produce the desired effect is to segment every equation manually, e.g. `$a +$$ b +$$ c +$$ d +$$ e +$$ f +$$ g +$$ h$`. However, this workaround comes at a considerable loss of readability.

**Comment by Enter-tainer** [comment] 2023-11-08 12:03
i remember there is an opening pr implementing this. But it is inactive for a while

**Comment by Enivex** [comment] 2023-11-08 12:04
Duplicate of https://github.com/typst/typst/issues/826

**Closed** 2023-11-08 12:04 UTC
Labels: duplicate, feature request
