### ISSUE TITLE
Math expressions in enum overflows into the previous item

### ISSUE THREAD

**Issue by nishanthkarthik** [typst/typst#3629] opened 2024-03-12 05:56 UTC
### Description

```typ
#let trs = math.sans("trs")
#let sz = math.sans("sz")
#let tr = math.sans[true]
#let fa = math.sans[false]
#let sc(x) = smallcaps(x)
#let iff = math.sans[if]
#let th = math.sans[then]
#let el = math.sans[else]

3. Random text

    + $trs(tr) <= sz(tr)$
    + $trs(fa) <= sz(fa)$ 
    + $forall r_1, r_2, r_3 in #sc[Term]. \
            trs(r_1) <= sz(r_1) and trs(r_2) <= sz(r_2) and trs(r_3) <= sz(r_3) \
            => trs(iff r_2 th r_2 el r_3) <= sz(iff r_2 th r_2 el r_3)$
```

![image](https://github.com/typst/typst/assets/7759435/f8ccbfb7-6baf-4373-bc2a-049a7e6a457e)

Expected: The first line of math expression on item 3 should align vertically with `3.`

### Reproduction URL

https://typst.app/project/raUG598Ng5WqooXZO8najJ

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by nishanthkarthik** [comment] 2024-03-12 06:01
Minor: Is the `forall` equation supposed to be broken into lines automatically by the compiler? Without manual line breaks, it overflows the page width.

![image](https://github.com/typst/typst/assets/7759435/ae555de8-a590-4ad2-a49b-821e8147f237)

**Comment by laurmaedje** [comment] 2024-03-12 10:32
Duplicate of https://github.com/typst/typst/issues/1028 (possibly also a bit of https://github.com/typst/typst/issues/1204).

Automatic line breaking for inline equations will be available with the upcoming release.

**Closed by laurmaedje** 2024-03-12 10:32 UTC
Labels: bug
