### ISSUE TITLE
Compiler Crash on Regex with \w or [] in #show regex block

### ISSUE THREAD

**Issue by frstrich** [typst/typst#1934] opened 2023-08-14 17:51 UTC
### Description

Using any of the following regexs, which shorten names to just the first (or any number of) character(s) crashes the compiler

```typst
#show regex("(Herrn?|Frau) [a-zA-Z]+"): name => {
  name.text.find(regex("(Herrn?|Frau) [A-Z]"))
} 


#show regex("(Herrn?|Frau) \w+"): name => {
  name.text.find(regex("(Herrn?|Frau) \w{2}"))
} 
```

This would be a small (not) working example:

```typst
#show regex("(Herrn?|Frau) [a-zA-Z]+"): name => {
    name.text.find(regex("(Herrn?|Frau) [a-zA-Z]+"))
}

Hallo Herr Adam, Herrn Brathering und Frau Cinsky
```

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by jannisko** [comment] 2023-08-16 18:40
This seems to be due to the show rule producing output, which is again matched by the rule.
I could reproduce this via:
```
#show "abc": "abc"

abc
```

So to fix yours, you could make sure you don't match on names, that have already been shortened:
```
#show regex("(Herrn?|Frau) [a-zA-Z]{2,}"): name => {
    name.text.find(regex("(Herrn?|Frau) [a-zA-Z]"))
}
```

**Comment by laurmaedje** [comment] 2023-08-19 15:59
Duplicate of #229.

**Closed by laurmaedje** 2023-08-19 15:59 UTC
Labels: bug
