### ISSUE TITLE
Single characters in math mode text operator

### ISSUE THREAD

**Issue by maximilianfellhuber** [typst/typst#3732] opened 2024-03-20 08:11 UTC
### Description

The text operator in math mode only works for strings with a minimum length of two:

`$ op("m")^3 $`

does not work, but

`$ op("cm")^3 $`

does. If this is intended, it should be documented I think.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by T0mstone** [comment] 2024-03-20 13:02
`op(upright("m"))` should work. This is due to math not actually distinguishing between `m` and `"m"`, see also #1125

**Comment by jbirnick** [comment] 2024-03-21 09:01
I just had the same issue and we had a discussion on the Discord. I think this behavior should be changed. (Also see the Discord post in`#support` for suggestions.)

**Comment by Enivex** [comment] 2024-03-21 12:27
Duplicate of https://github.com/typst/typst/issues/274

That being said, the post is misleading. `math.op` is doing what it's supposed to do. What you're presumably looking for is `upright`.

**Closed by Enivex** 2024-03-21 12:27 UTC
Labels: bug
