### ISSUE TITLE
Add "cancelto"  function like Latex

### ISSUE THREAD

**Issue by Oddball777** [typst/typst#5011] opened 2024-09-23 21:31 UTC
### Description

LaTeX provides the \cancelto command in math mode, which allows users to draw an arrow through an expression pointing to a value that the expression evaluates to (commonly 0 or 1). This is particularly useful for illustrating the cancellation of terms and the resulting value in mathematical derivations.
![Iz5tK](https://github.com/user-attachments/assets/a598b96f-a1f4-428f-9da4-a6d9116ac93f)

Typst currently provides a cancel function that strikes through a mathematical expression. However, it lacks the ability to include an arrow pointing to a target value, which indicates what the canceled term evaluates to.

One of the main difficulties with implementing this is the fact that Typst doesn't yet have (afaik) arrows, other than those in symbols which aren't very flexible. There is an issue for this (#1532) and I think that it would have to be addressed first.

### Use Case

In mathematical derivations, it's often necessary to illustrate the cancellation of terms and their resulting values to clarify complex equations and derivations. Simply crossing out a term can be unclear in many cases.

**Comment by Enivex** [comment] 2024-09-23 21:35
Duplicate of https://github.com/typst/typst/issues/3292

Note that LaTeX itself does not provide `\cancelto`, that's from the `cancel` package.

**Closed by Enivex** 2024-09-23 21:35 UTC
Labels: feature request
