### ISSUE TITLE
Theme-dependent default color value, so packages don't use hardcoded `black` as the default line/fill color

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3104] opened 2023-12-30 20:17 UTC
### Description

As discussed in Discord, nowadays authors of packages often set the default color of strokes, filles etc. to be `black`, while in most cases what they actually intended is "the foreground color". At the moment, using `black` as the default color is okay since the only current export format is PDF and PDF's background is almost always white.

However, this assumption will change when Typst supports [HTML export]([HTML output](https://github.com/typst/typst/issues/721)) format, where the background color could be black-ish (especially Dark Mode, if Typst wants to [support this trend](https://bootcamp.uxdesign.cc/the-rise-of-dark-mode-a-design-trend-thats-here-to-stay-fdcacc28bd30)) or other customizable theme color. Therefore, we need to provide a color value that is theme-aware, so that package authors can set the default stroke/fill color to this value, instead of hardcoding it to `black`.

👉 This might look a bit too ahead-thinking at the first glance, but in fact there's value to provide this feature early on. Otherwise, packages would be locked in the hardcoded `black` default color, and it would be a HUGE pain to ask third-party packages to migrate to theme-dependent default color later when Typst supports Dark Mode (or user-customizable themes).

---
🔔  Below is a _possible_ API proposal. There can be widely different ways to address the issue above. This proposal _is not tied_ to the issue in and of itself.

A possible API (thanks to @tingerrr) is
```typ
#set color(theme: (fg: black, bg: white))

#let draw-something(..., color:  color.theme("fg")) = { ... }  // A package function's implementation
```
`color.theme("fg")` will pick the `theme.fg` color customized above, and if it's missing or no theme was set, it defaults to `black`.

A detail worth noting is `color.theme()`'s computation needs to take `Location` into account, because the actual color value of the default color depends on where `draw-something()` is called in the user doc.

### Use Case

If one day Typst supports Dark Mode, packages that use `color.theme("fg")` (instead of hardcoded `black`) as the default color can still draw nicely. Otherwise, those packages would render bad, and therefore Dark Mode wouldn't be enabled after all, and the impression "Typst doesn't support Dark Mode nicely; let's use X instead" might ensue.

**Comment by Dherse** [comment] 2023-12-30 20:28
Couldn't just you do something like that yourself:
```ts
#let colors = (gf: white, bg: black)
```
Or do you mean that the advantage would be that it would work across packages? Because currently all packages have their own configuration interface. Additionally, I can see this opening the door for people requiring more colors such as "heading-#" and then "accent-#" which while great for templates, feels a bit out of scope for "main" typst.

I think that it would be better for templates to have a `theme` option that controls colors rather than having some built-in behaviour.

**Comment by Leedehai** [comment] 2023-12-30 20:32
> Or do you mean that the advantage would be that it would work across packages? Because currently all packages have their own configuration interface

Or, maybe just a `color(auto)` is fine. My point is Typst should probably offer a "default color" value the packages can use as their default color, so they don't hardcoded their default color to `black`, since asking packages to migrate later would be very hard (see the "Use Case" section above). As for the best way to achieve it, be it complex or trivial, is debatable.

**Comment by tingerrr** [comment] 2023-12-30 20:34
The idea in my proposal was that `color.theme("fg")` would resolve to a lazily evaluated color. But this makes things like `color.components()` inside `draw-something` be impossible without the use of a `loc` or later on without providing a context.

> Additionally, I can see this opening the door for people requiring more colors such as "heading-#" and then "accent-#" which while great for templates, feels a bit out of scope for "main" typst.

The original proposal by @Leedehai was to introduce some sort of constant that is theme-dependent like `color.fg`, but after some discussion we came to the conclusion that this would cause this to be too dark/light mode specific.

The problem is that you can't do this easily using set rules because trying to get the colors out of a state requires a `locate`, so rules which want to set the color of a table stroke can't be applied outside the `locate` callback.

I think this really hinges on contexts.

**Comment by Dherse** [comment] 2023-12-30 20:35
Mmh, I think I see what you mean, but again, I feel like it's a bit out of scope, get rules and custom elements should mostly cover that (I would think).

Following what I see on the Discord discussion (https://discord.com/channels/1054443721975922748/1088371867913572452/1190753173816742009 not one message in particular, just *a* message in the discussion), it could also be understood as having the ability in SVG and HTML export to have different colors based whether the user's theme is dark or bright in their viewer (browser) which could also be interested 🤔

**Comment by Dherse** [comment] 2023-12-30 20:36
> I think this really hinges on contexts.

@tingerrr Then we can agree that this could mostly be done with contexts and get/set rules?

**Comment by tingerrr** [comment] 2023-12-30 20:40
This would be kind of what the proposal does:
```typst
#let dark-mode = bool(sys.dark-mode)

#set color(theme: (fg: black, bg: white))
#set color(theme: (fg: white, bg: black)) if dark-mode

#set table(stroke: color.theme.fg)
#set text(fill: color.theme.fg)
#set page(fill: color.theme.bg)
```

The problem is that `stroke: context theme.` (assuming a regular state containing a dict of colors) would only work if we allow color to be a contextual value and not just a statically known color.

If color inherently was contextual like in the proposal, this wouldn't be an issue as it can be resolved late when a context is available.

**Comment by Complex2-Liu** [comment] 2023-12-31 07:58
Typst has the ability to load data from external TOML files!

```typst
// In "lib/themes.typ"

// The file "/config.toml" in the project root OVERRIDES the default "lib/config.toml"
#let config = deep-merge(toml("./config.toml"), toml("/config.toml"))
```

c.f. #1957 for the `deep-merge` function. TOML supports only a few data types like `string` or `integer`. Don't worry, we can [evaluate] it (or use other functions like `rgb()`):

```typst
// In "lib/colors.typ"

// convert the string type to color type
#let load-palette(dict) = {
  assert(type(dict) == dictionary, message: "dict must be a dictionary")

  let final = (:)
  for (k, v) in dict {
    let tmp = (:)
      for (x, y) in v {
        tmp.insert(x, rgb(y))
      }
    final.insert(k, tmp)
  }
  final
}

#import "./themes.typ": config

#let colors = load-palette(config.colors)
#let black = colors.fg.default
#let white = colors.bg.default
#let grey = colors.fg.muted
#let red = colors.fg.red
#let green = colors.fg.green
#let blue = colors.fg.blue
#let orange = colors.fg.orange
#let yellow = colors.fg.yellow
#let purple = colors.fg.purple
#let magenta = colors.fg.magenta
```

Now we can access these colors with ease:

```typst
// In "main.typ"

#import "lib/colors.typ": *

// Print available colors
#colors

#pagebreak()

#set page(
  width: 250mm, height: auto,
  margin: (x: 2cm, y: 1cm),
)

#align(center)[
  #text(size: 1.5em, font: "Noto Sans", weight: 575)[
    My Color Palette
  ]
]

#grid(
  columns: 3,
  rows: 3,
  row-gutter: 1em,
  column-gutter: 1fr,
  [`red    ` #red: ] + box(width: 2.5em, fill: red, outset: (y: 2pt), hide[TTTTTT]),
  [`gren   ` #green: ] + box(width: 2.5em, fill: green, outset: (y: 2pt), hide[TTTTTT]),
  [`blue   ` #blue: ] + box(width: 2.5em, fill: blue, outset: (y: 2pt), hide[TTTTTT]),
  [`orange ` #orange: ] + box(width: 2.5em, fill: orange, outset: (y: 2pt), hide[TTTTTT]),
  [`purple ` #purple: ] + box(width: 2.5em, fill: purple, outset: (y: 2pt), hide[TTTTTT]),
  [`yellow ` #yellow: ] + box(width: 2.5em, fill: yellow, outset: (y: 2pt), hide[TTTTTT]),
  [`black  ` #black: ] + box(width: 2.5em, fill: black, outset: (y: 2pt), hide[TTTTTT]),
  [`magenta` #magenta: ] + box(width: 2.5em, fill: magenta, outset: (y: 2pt), hide[TTTTTT]),
  [`grey   ` #grey: ] + box(width: 2.5em, fill: grey, outset: (y: 2pt), hide[TTTTTT]),
)
```

The result is as follows, where the color scheme defined in `lib/config.toml` is GitHub's Primer CSS:

![palette](https://github.com/typst/typst/assets/40851978/0a7f800e-2f84-49fa-8a2b-0b52e6324dfd)

One drawback is that now we have to put a `config.toml` in our project root, for otherwise we got an error `file not found` when compiling.

```toml
[colors]
# Customize your color here, override the "lib/config.toml"
# bg color ... border color ... gruvbox (vim) colorscheme ...

[colors.fg]
red = "#cc0000"
green = "#00cc00"
blue = "#0000cc"
```

[evaluate]: https://typst.app/docs/reference/foundations/eval/

**Comment by tingerrr** [comment] 2023-12-31 12:33
In the end, what we all want is to make it easier for a user to configure the theme of a document, not harder. We want to reduce boilerplate required to do this, by doing things like setting the default value a color/stroke parameter resolves to when it is set to `auto`.

I want to lay out the possibilities and their pros and cons:

## Lazy Colors
Colors are internally represented as either lazy or eager:
- If they are lazy, they require a context to resolve to an eager color
- If they are eager, they contain an actual color value the same way as before

### Pros
- Resolved by context, means it uses available styling system
  - set rules can be used to style individual parts of the document
  - Can be used across packages without a lot of extra work
- Can be done today, and can easily be adapted to fit into the context proposal

### Cons
- Colors may return errors on functions like `components` if they receive no `location` to provide the context in which the content is resolved, this could increase function coloring problem with respect to contexts
- Adds additional complexity to the color implementation
- May cause the package ecosystem to split in convention regarding color theme keys
- May set a precedent, motivating people to ask for features which really should be packages

## External files
As explained by @Complex2-Liu.

### Pros
- Typst is not responsible for a feature that seems out of scope
- No context is required to resolve colors
- Configuration is easy
- Can be done today
- Boilerplate can be extracted into a package

### Cons
- External files are required, a simple thing like setting a theme now requires more than the source file to render a document
- Hinges on error handling to not hamper ergonomics
- Themes cannot be overridden inside a scope using a set rule
- Regular users need to know both toml and typst to change a theme

## Theming Package
### Pros
- Typst is not responsible for a feature that seems out of scope
- May work better once custom types are available

### Cons
- As far as I can tell, not possible currently without changing all functions to allow resolving a color lazily (e.g `set text(fill: loc => theme.at(loc).fd)`)
- Even with the additional stopgap API, most of the work is still manually done by every user increasing boilerplate
- Other packages need to import this package to allow theme config, ecosystem split if another package does a similar thing but slightly different

## Manual Configuration
Declare a theme variable at the top level doc which is changed, use the variables in this dictionary for subsequent show and set rules. Similar to @Complex2-Liu's solution but without the use of external files.

### Pros
- Typst is not responsible for a feature that seems out of scope
- No context is required to resolve colors
- No external files are required

### Cons
- Requires more boilerplate which may end up creating yet another file to clean up the main document
- Manual setting of every value using a set rule once
- Manual setting of every changed value if theme is overridden for a scope
- Falls apart when theme is imported as mutability is no longer allowed without copying and reapplying rules, once again increasing boilerplate

**Comment by Complex2-Liu** [comment] 2023-12-31 15:20
> External files are required, a simple thing like setting a theme now requires more than the source file to render a document.

External file (the `config.toml` in the project root, not the package level one) can be optional if we can check the existence of a file, c.f. issue #2025 related to scripting.

I strongly recommend using external config files to configure things such as

```toml
fontsize = "11pt"

[document]
title = "Typst Awesome"
author = [
# "Chan TaiMan"
  "Complex2-Liu",
]
keywords = [
  "Mathematics",
  "Typst",
]
date = "none"
# date = "auto"

[text]
cjk-latin-spacing = "none"
```

**Comment by tingerrr** [comment] 2023-12-31 17:38
> I strongly recommend using external config files to configure things such as

Well, I strongly recommend against it for simply documents. Part of typst's appeal is that it will create no auxiliary files and require nothing but a single `typ` file to work. Another very important aspect is that a document compiles the same almost everywhere, although `sys.inputs` (#2481) and system fonts are partially points against this.

External files, especially with formats such as toml also come with ambiguity, is `author = "none"` the same as `set document(author: none)` or `set document(author: "none")`. This may seem pedantic, but "none" and "auto" are words that are valid inputs for string or even content parameters.

By using external files for configuration of something that is usually done in typst users now have to look at toml files and decipher whatever escaping mechanism we come up with to solve the previously mentioned problem.

Typst already gives us the tools to provide configuration using regular `typ` files, the usage toml for anything but package manifests makes no sense to me.

**Comment by uben0** [comment] 2024-02-18 20:15
As I'm not into Typst's compilation process, I don't understand the challenge that poses a *shared state* (global variable), but if this issue is solved, then may I suggest the following:

The simplest way of handling theming without introducing too many hazardous features to Typst, seems to be to rely on a optional argument each time:

```typst
#cetz.canvas(theme: ayu-mirage, {
    ...
})
```
But this would be annoying as the theme would have to be specified each time. What could solve this, is the ability for a function, when called, to automatically fill some of its arguments by querying the caller's context:

```typst
#let canvas(theme: context("theme")) = { ... }

#let theme = "whatever"

#canvas() // implicitly access variable "theme"
```

I'm not saying the API should look like that, this is particularly ugly and would cause poor error messages and confusion for the user. But I'm thinking in a dictionary called `context`, that is always implicitly passed as an argument:

```typst
#let f() = repr(context)
#f()
#context.a = 1
#f()
```
```
(:)
(a: 1)
```

**Comment by AxiomOfChoices** [comment] 2024-02-18 20:26
@uben0 Something almost exactly like this is [in the works](https://laurmaedje.github.io/posts/types-and-context/), or at least is already being considered.

**Comment by laurmaedje** [comment] 2024-02-18 20:34
> What could solve this, is the ability for a function, when called, to automatically fill some of its arguments by querying the caller's context

That's the idea of set rules.

```typ
#set canvas(theme: "whatever")
#canvas()
```

The limitation is just that set rules cannot be queried in user code currently, only by the compiler. The context proposal linked above is about how to make that possible.

**Comment by laurmaedje** [comment] 2024-02-28 11:30
I'll close this as resolved by https://github.com/typst/typst/pull/3497. With the new context system, package authors can access `text.fill` etc. and do stuff depending on it. With custom types and thus custom set rules, there'll be even more flexibility. So, I don't think we need any special compiler-side support for this.

**Closed by laurmaedje** 2024-02-28 11:30 UTC
Labels: feature request
