### ISSUE TITLE
Spacing on `$dots$` is off

### ISSUE THREAD

**Issue by kg583** [typst/typst#3498] opened 2024-02-26 17:54 UTC
### Description

The spacing on `$ x_1 dots x_k $` is asymmetric and, to be frank, bad. Using `#show sym.dots: math.class.with("punctuation")` fixes the asymmetry and brings the appearance closer to LaTeX's (though still lacking, as the dots are not evenly spread), though I wonder why that show rule would be necessary for `dots` in a math environment.

No show rule:
![image](https://github.com/typst/typst/assets/41345727/2e0af8b3-ef94-432c-b0a2-1c2fea78ae0e)

Show rule:
![image](https://github.com/typst/typst/assets/41345727/ef75648a-9939-40f1-b3aa-44ffb8404d15)

LaTeX:
![image](https://github.com/typst/typst/assets/41345727/1236316d-81c2-4edf-a85f-96a9a970e7f2)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-02-26 18:14
More appropriate comparison, both using New Computer Modern Math

Typst:
![image](https://github.com/typst/typst/assets/2191754/91a7647a-4110-4afd-9629-b53d0070e47c)

LuaLaTeX:
![image](https://github.com/typst/typst/assets/2191754/0d82d837-e38f-4837-bcdb-c1edd4f72e7c)

**Comment by Enivex** [comment] 2024-02-26 18:17
I'll close this as a duplicate of https://github.com/typst/typst/issues/880 though

**Closed by Enivex** 2024-02-26 18:17 UTC
Labels: bug
