### ISSUE TITLE
Incorrect Page Number Display

### ISSUE THREAD

**Issue by wzy1935** [typst/typst#3783] opened 2024-03-24 21:42 UTC
### Description

If a page has no content other than the heading, the page number will follow the style of the heading, which is not intended:

![image](https://github.com/typst/typst/assets/65799440/cef84750-5249-4633-bb3b-4708aa4de287)

Reproduction:

```typ
#set page(numbering: "1")

== Section A
#pagebreak()

== Section B
With text
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-03-24 21:44
Duplicate of #241

For now, you can add some empty content at the start and end of the page as a workaround.

**Closed** 2024-03-24 22:22 UTC
Labels: bug, duplicate
