### ISSUE TITLE
Unexpected linebreak in heading

### ISSUE THREAD

**Issue by tmistele** [typst/typst#4189] opened 2024-05-19 17:14 UTC
### Description

I tried the following code:

```typst
#set heading(numbering: "1.")
#set par(justify: true)

= Theory
```

It produces the following unexpected output (screenshot of the pdf created by `typst compile`)

![image](https://github.com/typst/typst/assets/29761456/cf015895-c2b7-4b58-8c32-b1494a18f1b6)

This is with version 0.11.1 (I think. `typst --version` says `typst 0.11.0 (4f8bbb01)`. I compiled myself from git). It seems to have worked with 0.11.0

![image](https://github.com/typst/typst/assets/29761456/72496b82-feeb-40ef-b19a-d4623403809a)

What is strange is that I cannot reproduce the issue in the typst web app with any version I try. Perhaps I'm doing something wrong.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-05-19 17:23
I can reproduce this. Presumably the cause is a commit not included in the 0.11.1 release.

**Comment by MDLC01** [comment] 2024-05-19 17:32
This seems related to #3398.

**Comment by tmistele** [comment] 2024-05-19 17:34
Fwiw, git bisect points to 6d0c159e97a9274fedcdd269b886385e987da6e0 for me

**Comment by haenoe** [comment] 2024-05-25 10:24
Hey, thanks for tagging me.
I did some basic triaging and it seems to me that the problem is in the laying out that the `BlockElem` performs.
The weird thing is [this commit](https://github.com/haenoe/typst/commit/43be544b75e42b9791cccde304106eb3719fdfc7#diff-41f7de922d0259d84b6b03c9799c65818a607d430f67084e6bc7f257c74f37b3R377) seems to fix that (in the very simple example provided above).
I will look more into it, any remarks are greatly appreciated :D

**Comment by laurmaedje** [comment] 2024-05-25 10:35
It's likely a problem with measurement and floating point. But the relevant code doesn't exist anymore on my layout refactoring branch, so probably not worth it to try and fix it there.

**Comment by haenoe** [comment] 2024-05-25 10:38
Yeah that is also what I suspected, thanks for validating :D
Just out of curiosity, what changes with the layout refactoring? Is the branch public? ^^'

**Comment by laurmaedje** [comment] 2024-05-25 12:24
It's not yet public, but I'll probably create a first PR soon-ish and describe things there.

**Comment by laurmaedje** [comment] 2024-07-04 14:13
Closing in favor of https://github.com/typst/typst/issues/3398 which is reproducible.

**Closed by laurmaedje** 2024-07-04 14:13 UTC
Labels: bug, layout

**Comment by Enivex** [comment] 2024-07-04 14:15
> Closing in favor of https://github.com/typst/typst/issues/3398 which is reproducible.

Is it the same issue? One seems to be s regression

**Comment by laurmaedje** [comment] 2024-07-04 14:25
Pretty sure it's the same cause.
