### ISSUE TITLE
Using linebreak in a linebreak show rule crashes the compiler

### ISSUE THREAD

**Issue by platformer** [typst/typst#541] opened 2023-04-03 07:45 UTC
If we have this show rule:

```
#show linebreak: linebreak()
```

or

```
#show linebreak: [\ ]
```

the file compiles successfully. But if the show rule is later invoked:

```
a\
b
```

the compiler will crash. Note that avoiding an explicit call to `linebreak` in the show rule still works:

```
#show linebreak: it => it

a\
b
```

The above compiles successfully.

**Comment by laurmaedje** [comment] 2023-04-03 21:30
Duplicate of #229.

**Closed by laurmaedje** 2023-04-03 21:30 UTC
