### ISSUE TITLE
Alignment points don't cross boundaries of surrounding elements

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4598] opened 2024-07-22 12:01 UTC
### Description

Consider the following piece of Typst code:

```typ
$
  1 & 2 3 \
  (1 & 2)
$
```

As expected, the alignment points are aligned properly:

![The alignment points are aligned properly.](https://github.com/user-attachments/assets/da06b391-b241-4b8b-9270-30eddea09f2e)

Now, let's add an attachment to the second line:

```typ
$
  1 & 2 3 \
  (1 & 2)_1
$
```

This messes up the alignment, because alignment points don't cross the boundaries of the `attach` element:

![The alignment point of the first line is aligned with the end of the second line.](https://github.com/user-attachments/assets/ba6e5b85-2887-4eaa-8e6d-26edf5b8fb9b)

I would expect alignment points to cross the boundaries of surrounding elements, when it makes sense (i.e., for any element that does not create multiple lines, such as `attach`, `overline`, `accent`, etc.).

Tested on 0.11.0 and 0.11.1.

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-07-22 12:02
Duplicate of https://github.com/typst/typst/issues/3034

**Closed** 2024-07-22 12:02 UTC
Labels: bug, duplicate

**Comment by MDLC01** [comment] 2024-07-22 12:04
Well, that was fast!
