### ISSUE TITLE
Line break in URL produces two different links

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#2587] opened 2023-11-04 19:15 UTC
### Description

URLs containing a line break have two different click areas, where one only links to the part before the line break. The web app jump feature does not seem to be affected by this.

```typ
#set page(width: 5cm, height: auto, margin: 1em)

https://github.com/typst/typst/issues/2586
```

Look at the bottom left corner in the following recording (PDF opened in Chrome):

https://github.com/typst/typst/assets/7191192/cfb463f3-9e8e-4b83-a6e6-d88fddbb3b0f

Edge does even worse, as the whole first line only links to the part before the line break.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-11-04 19:26
Can't reproduce on Firefox. Can reproduce on Chromium.

**Comment by PgBiel** [comment] 2023-11-04 19:28
Upon further analysis, I'd guess that Chromium's PDF reader automatically converts any text line containing `https://` into a link, suggesting there isn't much Typst can do, as seen with the document below:

```
#set page(width: 5cm, height: auto, margin: 1em)

https://github.com/typst/typst/issues/2586

`https://github.com/typst/typst/issues/2586`
```

which results in the PDF below:
![image](https://github.com/typst/typst/assets/9021226/60fc8a53-c5fa-4a4d-a562-160b8d88fbd8)


The `raw` element there doesn't contain any auto-generated link elements (so it's not clickable at all in Firefox). However, in Chromium, I can click the first line to go to github.com.
Not sure if there's any way to instruct Chromium's reader to inhibit this behavior.

**Comment by EpicEricEE** [comment] 2023-11-06 20:04
I filed a bug report in Chromium, maybe they will do something:
https://bugs.chromium.org/p/chromium/issues/detail?id=1499642

**Comment by laurmaedje** [comment] 2023-11-11 10:17
I don't think anything can be done from our side, so I'm gonna close this.

**Closed by laurmaedje** 2023-11-11 10:17 UTC
Labels: bug, pdf, text
