### ISSUE TITLE
first-line-indent does not indent the first paragraph in block

### ISSUE THREAD

**Issue by szdytom** [typst/typst#848] opened 2023-04-17 09:10 UTC
I know it is working as intended:

> Only the first line of a consecutive paragraph will be intended (_not the first one in a block or on the page_). --Typst Document

This is fine for many languages such as English, but Chinese users may find this unfriendly, for usually Chinese indents all paragraphs by 2em no matter whether it is the first in block or not. Please give an option to configure this.

**Comment by laurmaedje** [comment] 2023-04-17 17:55
Duplicate of #311. It's sadly somewhat hard to fix.

**Closed by laurmaedje** 2023-04-17 17:55 UTC
