### ISSUE TITLE
Balanced columns

### ISSUE THREAD

**Issue by michael-keyes** [typst/typst#934] opened 2023-04-22 15:00 UTC
Is there a way to use `#set page(columns: 2)` and `#set page(columns: 1)` without a page break?

**Comment by sroracle** [comment] 2023-04-22 15:50
Maybe not, but you can have different numbers of columns within separate containers on the same page. The function documentation page for columns shows an example of what you're asking using the box function. 

https://typst.app/docs/reference/layout/columns/

**Comment by michael-keyes** [comment] 2023-04-22 16:18
> Maybe not, but you can have different numbers of columns within separate containers on the same page. The function documentation page for columns shows an example of what you're asking using the box function.
> 
> https://typst.app/docs/reference/layout/columns/

I don't understand how to get the second column along side of it.

**Comment by sroracle** [comment] 2023-04-22 16:31
Maybe you can show an example of what you want? From what you originally said the example on that page seems like exactly what you need.

**Comment by michael-keyes** [comment] 2023-04-22 16:33
I simply would like to have single, full width columns and double columns on the same page, alternating as desired.

**Comment by Flightkick** [comment] 2023-05-03 15:07
This is kind of a bugger. Either there are unnecessary pagebreaks or you won't be able to call #pagebreak() from the content yourself because it's wrapped in a container.

Snippet in order to reproduce this behavior:
```
#let myfunction(
  doc,
) = {
  lorem(100)
  // ... content

  // Possible solution 1: Columns work but adds additional pagebreaks when `set` is used, allows #pagebreak() from content
  //   set page(columns: 2)
  //   doc
  //   set page(columns: 1)

  // Possible solution 2: Columns work but can't call #pagebreak() from content as it is inside a container
  //   columns(2, doc)
  
  // ... content
  lorem(100)
}

#show: doc => myfunction(doc)

#outline()
#pagebreak()

= Introduction
#lorem(100)
```

**Comment by reknih** [comment] 2023-05-09 09:49
This would be solved by offering a feature to balance columns automatically. Then, the columns container would be small automatically. This issue shall track this feature request from now on.

**Comment by reknih** [comment] 2023-05-09 09:50
My bad, this is now a duplicate of #466. Closing in favor of that issue.

**Closed by reknih** 2023-05-09 09:50 UTC
Labels: feature request, layout

**Comment by Flightkick** [comment] 2023-05-09 12:20
@reknih I'm trying to understand how this works and why that feature would solve this issue. If I may ask; would column balancing allow pagebreaks to be used inside containers and/or would it remove the extra pagebreaks when `set` is called to change the amount of columns?

Unrelated: Awesome project! Quite enjoyable to use and pretty straightforward. Thanks!
