### ISSUE TITLE
Math mode should not always inherit text-mode bold styling

### ISSUE THREAD

**Issue by kwshi** [typst/typst#3475] opened 2024-02-22 06:44 UTC
### Description

Sometimes, I include math expressions/equations within bolded text-- e.g., inside a section title, or inside a sentence that I want to emphasize. In LaTeX, the math font does not inherit bold from the surrounding text, but in Typst, it does:

- Typst:
  ```typst
  Blah blah, *it is really important to note that $x != y$*.
  ```
  ![image](https://github.com/typst/typst/assets/3887189/b16e766c-3c48-4c7b-a534-f3888a8bbe81)
- LaTeX:
  ```latex
  Blah blah, \textbf{it is really important to note that \(x\ne y\)}.
  ```
  ![image](https://github.com/typst/typst/assets/3887189/37ba61cc-fb13-4587-bbae-da43cc093d26)

I would like to request that Typst change its behavior to _not_ inherit bold styling in math equations from surrounding text.

### Use Case

Semantically this makes more sense, since styling in math expressions often convey/change the meaning (e.g., bolding is often used for vectors, etc.). Of course, I can manually break out of bold to insert the equation, then rebold, but that feels like a fairly clumsy solution. I think it would be better if there were some proper isolation between math- and text- mode font handling; in that respect, this issue may be related to #1125.

This issue is probably also related to #1162, though it's not the same issue. #1162 concerns _text within math_ getting incorrectly overridden with math styling; this issue concerns the opposite, of _math within text_ getting overridden with undesirable text styling. In both cases, the issue would probably be addressed by better isolation of math- and text- font handling.

**Comment by Enivex** [comment] 2024-02-22 09:35
Duplicate of https://github.com/typst/typst/issues/1155

**Closed by Enivex** 2024-02-22 09:35 UTC
Labels: feature request
