### ISSUE TITLE
Using a box for inline code with colored background causes uneven line spacing in paragraphs

### ISSUE THREAD

**Issue by SeSodesa** [typst/typst#3021] opened 2023-12-20 14:08 UTC
### Description

When using the show rule
```typst
show raw.where( block : false ) : it => {
	box(
		height : 1.1 * tunifontsize,
		inset : 0.2 * tunicodefontsize,
		fill : luma(230),
		baseline : 0.3 * tunicodefontsize,
		radius : 0.3 * tunicodefontsize,
		it
	)
}
```
to display inline code with a grayish background in typst version 0.10.0, the spacing between the paragraph lines becomes uneven, as can be seen in the following image.

<img width="1323" alt="Screenshot 2023-12-20 at 15 55 42" src="https://github.com/typst/typst/assets/19917000/f2c2de37-ad8f-4b74-8550-5efd55ff043a">

Removing the box from around the inline code with
```typst
show raw.where( block : false ) : it => it
```
results in the line spacing being fixed:

<img width="1320" alt="Screenshot 2023-12-20 at 15 55 58" src="https://github.com/typst/typst/assets/19917000/ab1160e8-fd50-4335-b4ce-d170e6188961">

Adjusting the height parameter does not seem to help in the case of using a box to create the colored background. Ideally, the box should not alter the line spacing inside paragraphs.

### Operating system

Web app, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment] 2023-12-20 14:13
I suggest using `outset` for y-spacing, as it doesn't affect layout:
```typ
box(
  ...
  inset: (x: 0.2 * tunicodefontsize),
  outset: (y: 0.2 * tunicodefontsize),
  ...
)
```

**Comment by SeSodesa** [comment] 2023-12-20 14:24
> I suggest using `outset` for y-spacing, as it doesn't affect layout:
> 
> ```typst
> #box(
>   ...
>   inset: (x: 0.2 * tunicodefontsize),
>   outset: (y: 0.2 * tunicodefontsize),
>   ...
> )
> ```

It seems I also need to remove `inset` entirely or set it to a very small value, or the y-spacing issue does not go away.

**Comment by SeSodesa** [comment] 2023-12-20 14:28
Also, the `outset` argument seems to cause the background box to overlap with surrounding text, completely hiding it. See the left parenthesis in the picture below:

<img width="1224" alt="Screenshot 2023-12-20 at 16 25 30" src="https://github.com/typst/typst/assets/19917000/b5ffa5c4-3df6-49de-83e1-34c195fb94d6">

**Comment by laurmaedje** [comment] 2023-12-20 14:28
You should use inset horizontally (because you want to add extra space), but outset vertically (because you don't want to affect line spacing).

**Comment by SeSodesa** [comment] 2023-12-20 14:38
Ah, right. Didn't see the dictionary there.

**Comment by laurmaedje** [comment] 2023-12-20 15:09
I'll close this as "working as intended then".

**Closed by laurmaedje** 2023-12-20 15:09 UTC
Labels: bug
