### ISSUE TITLE
Nix flake CI caching doesn't work

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#2047] opened 2023-08-30 15:34 UTC
The caching seems to work almost never and CI takes ~8mins instead of ~3mins everytime.

**Comment by jimvdl** [comment] 2023-08-31 08:45
I took the liberty of taking a peek at the logs (purely out of curiosity) and from what I can gather the caching _seems_ to work fine.

It pretty much has all of the dependencies pulled and built within a minute.. but then it starts building Typst itself and that's where it grinds to a crawling halt:

```
building '/nix/store/4an9yj25hvvs8si5i136a1irqwv3g3an-typst-0.7.0.drv'...
```

This final step takes 95% of the total build time to complete.

**Comment by laurmaedje** [comment] 2023-08-31 09:29
Is it compiling in debug or release mode?

**Comment by laurmaedje** [comment] 2023-08-31 10:16
That's probably the issue then.

**Comment by jimvdl** [comment] 2023-08-31 11:53
After further digging I found three things:
- It _does_ seem to be a cache problem, the debug output doesn't help much but I think it fetches a bunch of dependencies and builds all of them (including Typst) from scratch, hence the long build times.
- When you rerun a workflow the cache contains a Typst binary from the previous run and uses that so you go from ~8 minutes build time down to ~40 seconds. It seems to me it doesn't cache the compilation result of dependencies well so it can reuse them later when compiling Typst (like cargo test has with rust-cache)
- Adding `buildType = "debug"` in `flake.nix` didn't help much.

**Comment by PgBiel** [comment] 2023-09-01 17:24
As discussed on Discord, we could try using tools like [crane](https://github.com/ipetkov/crane) - which builds dependencies in a derivation which is separate from the main workspace derivation - or [crate2nix](https://github.com/kolloch/crate2nix) - which (if I understood correctly) builds each crate in a separate derivation, thus enabling more fine-grained caching.

As is, the problem is likely the usage of fenix without a tool similar to the two examples above, implying a full Rust rebuild on each change (I think `rust-cache` isn't aware of Nix).

**Comment by alerque** [comment] 2023-09-02 17:49
Commenting so I can be assigned to look into this (currently traveling).

**Closed** 2023-09-11 07:57 UTC
Labels: devops
