### ISSUE TITLE
Can't compile emojis and symbol locally. 

### ISSUE THREAD

**Issue by neuromaancer** [typst/typst#2291] opened 2023-10-02 14:07 UTC
### Description

Can't compile emojis and symbol. I think it works great in Web app, but not locally. 

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-10-02 14:14
Duplicate of https://github.com/typst/typst/issues/144?

**Closed** 2023-10-20 06:21 UTC
Labels: bug, duplicate, text
