### ISSUE TITLE
Give warning when font selection fails

### ISSUE THREAD

**Issue by Enter-tainer** [typst/typst#3347] opened 2024-02-05 05:41 UTC
### Description

Print a warning message when font selection fails or the fallback list is used up.

### Use Case

There are many new CJK users reporting that "typst's `#stong` & `#emph` doesn't work" because the font they used doesn't have a bold variant. I think it is better to give a clear warning message in such situation. We can produce warning message when:
1. user select a variable font(VF) #185
2. user provided font list is used up and we are using heuristic method to select font #2105
3. the font doesn't have a specific variant #725

This can help users diagnose the problem by themselves.

**Comment by Enivex** [comment] 2024-02-05 09:36
This is also the cause of _many_ questions on the Discord. Since `fallback: false` isn't the default, they don't even realize that fallback is happening.

**Comment by owiecc** [comment] 2024-02-05 10:26
Some documentation on font handling would be nice. What happens if font is not installed. Possible issues with same font but at different versions. What happens if symbols are missing. How to debug the issues. How to contribute exceptions.

**Comment by laurmaedje** [comment] 2024-02-05 10:30
Duplicate of https://github.com/typst/typst/issues/2818. Please post any ideas & proposals there.

**Closed by laurmaedje** 2024-02-05 10:30 UTC
Labels: feature request
