### ISSUE TITLE
Term list indentation inconsistent with bullet list and enum.

### ISSUE THREAD

**Issue by SebastianJL** [typst/typst#2503] opened 2023-10-27 11:42 UTC
### Description

`#term` seems to use the setting `#set par(first-line-indent: 10pt)` to indent the terms as if they where separate paragraphs.

```typst
#set par(first-line-indent: 10pt)

- List
- don't
- do
- this

+ Neither
+ do 
+ enums

/ But: terms.
/ Sadly: do.
/ And: I don't know why.

#set par(first-line-indent: 0pt)

/ Now: it.
/ Happens: no longer.
/ Hmm: I wonder why?
```

![image](https://github.com/typst/typst/assets/11479035/71c7fd6c-ee58-414f-9450-1c7050a4e6a7)

Image produced with the source code above and the following commands
```bash
$ cargo install --git https://github.com/typst/typst
....
$ typst --version
typst 0.8.0 (cbfd9884)
$ typst c example.typ
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-10-27 11:44
Possibly related https://github.com/typst/typst/issues/1955 ?

**Comment by SebastianJL** [comment] 2023-10-27 11:56
Maybe yes. But while I'm not sure if bullet lists *inside* of term lists should be a thing (as in #1955) this here seems to be a definite bug.

**Comment by Enivex** [comment] 2023-10-27 11:58
> But while I'm not sure if bullet lists inside of term lists should be a thing

Why not?

**Comment by SebastianJL** [comment] 2023-10-27 12:06
> > But while I'm not sure if bullet lists inside of term lists should be a thing
> 
> Why not?

Let's not discuss this here as it seems off topic. I know, I know, I brought it up.

**Comment by MDLC01** [comment] 2023-10-27 18:33
Looks like a duplicate of #1050, though

**Closed** 2023-10-27 18:51 UTC
Labels: bug, text

**Comment by SebastianJL** [comment] 2023-10-28 05:24
Thanks for identifying the duplicate♥️
