### ISSUE TITLE
Header inherits style from page elements

### ISSUE THREAD

**Issue by steven-jh-yan** [typst/typst#1127] opened 2023-05-07 00:00 UTC
### Description

When there is just one element in the body, the header's styling gets the style. Here are some examples. The attachments are  generated from the bot corner.
- When there's just one element, you get that behavior
  ```
  #set page(header:[head])
  _text_
  ```
  ![rendered-2 12 04 57 PM](https://user-images.githubusercontent.com/68593406/236651039-5147ad67-1dc6-4313-848b-a83c2e9a002b.png)

- When there's two, everything's good
  ```
  #set page(header:[head])
  _text_ text2
  ```
  ![rendered](https://user-images.githubusercontent.com/68593406/236651060-1eb40302-5b71-4e64-894f-1e7e5af515c7.png)

- When I wrap the single element directly as a call to `page()`, it works as expected
  ```
  #page(header:[head])[_text_]
  ```
  ![rendered-3](https://user-images.githubusercontent.com/68593406/236651070-52cebe14-ee54-4cc8-8e51-32dc15d95906.png)

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-05-07 08:35
Duplicate of #241.

**Closed by laurmaedje** 2023-05-07 08:35 UTC
Labels: bug
