### ISSUE TITLE
Wrong hyphenation with words containing apostrophe

### ISSUE THREAD

**Issue by tribut** [typst/typst#4067] opened 2024-05-04 15:29 UTC
### Description

Typst incorrectly hyphenates "hab's" as "ha-b's". Can also be observed at https://typst.app/tools/hyphenate/

```
#set text(lang: "de")
#set par(justify: true)
#set page(width: 4cm)
#{5 * [Ich hab's verstanden! ]}
```

![Screenshot from 2024-05-04 17-29-14](https://github.com/typst/typst/assets/719105/d3f78daf-0f43-44ff-93e2-ed727695af35)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by yuankunzhang** [comment] 2024-05-05 13:31
This seems to be an issue in [hypher](https://github.com/typst/hypher/), reproducible with the following code:

```rust
use hypher::{hyphenate, Lang};

fn main() {
    let syllables = hyphenate("hab's", Lang::German);
    assert_eq!(syllables.join("-"), "ha-b's");
}
```

**Comment by laurmaedje** [comment] 2024-05-07 12:58
Duplicate of https://github.com/typst/typst/issues/2168.

The problem isn't with hyper, but rather that only proper words should be given to it in the first place, not anything between two Unicode linebreak opportunities.

**Closed by laurmaedje** 2024-05-07 12:58 UTC
Labels: bug, text
