### ISSUE TITLE
Embed/Attach whole pages of PDF files

### ISSUE THREAD

**Issue by michaelaye** [typst/typst#4241] opened 2024-05-23 19:56 UTC
### Description

I would like to be able to import whole pages of a given PDF document at specific locations in the typst document.

### Use Case

Proposal writing!

For this, the LaTex package "pdfpages" was a joy to use, because I could create a pipeline that would glue all the relevant pages from the input files of my department into my proposal exactly where they should be.

That way, whenever I made a small correction in the science part of my proposal, I wouldn't need to manually glue the different PDFs together again, the latex compile would do it all for me.

**Comment by michaelaye** [comment] 2024-05-23 19:59
Ideally, it would be possible to add the correct page numbers of the outer document onto the imported PDF pages. For this, sometimes it might be necessary to stop the import at a given height, as to not have the old page number of the imported PDF page visible. pdfpages was supporting that, I believe.

**Comment by Enivex** [comment] 2024-05-23 20:06
Duplicate of https://github.com/typst/typst/issues/145

(It's not going to happen anytime soon)

**Closed** 2024-05-23 20:06 UTC
Labels: feature request

**Comment by michaelaye** [comment] 2024-05-23 20:09
I would have thought that embedding PDFs as figures is technically quite a different task than attaching/adding several pages from external PDF documents to the compiled document? Hence the new issue.

**Comment by Enivex** [comment] 2024-05-23 20:13
> I would have thought that embedding PDFs as figures is technically quite a different task than attaching/adding several pages from external PDF documents to the compiled document? Hence the new issue.

If PDF was the only output target, this would technically speaking be true. But it isn't, so both tasks boil down to having to render the PDF, which there is just no viable avenue for right now.
