### ISSUE TITLE
Support #pagebreaks when using columns

### ISSUE THREAD

**Issue by scholzdev** [typst/typst#3758] opened 2024-03-22 09:23 UTC
### Description

Currently you are not allowed to use a `#pagebreak()` when you use columns.

It would be super useful to support `#pagebreak()` right away instead of using multiple `#colbreak()`

According to @laurmaedje its a current limitation though

### Use Case

If you use a ieee template or any template that uses columns and you want certain section on new pages

**Comment by Enivex** [comment] 2024-03-22 09:31
Duplicate of https://github.com/typst/typst/issues/1278

**Closed** 2024-03-22 09:31 UTC
Labels: duplicate, feature request
