### ISSUE TITLE
Footnote linking to incorrect location after customization

### ISSUE THREAD

**Issue by martinstefanik** [typst/typst#4823] opened 2024-08-24 14:46 UTC
The footnote entry documentation (see [here](https://typst.app/docs/reference/model/footnote#definitions)) contains the following example:

```typst
#show footnote.entry: it => {
  let loc = it.note.location()
  numbering(
    "1: ",
    ..counter(footnote).at(loc),
  )
  it.note.body
}
```
The footnote mark links to the first page of the document instead of the footnote's text when the above configuration is used.

**Comment by EpicEricEE** [comment] 2024-08-24 15:52
Duplicate of #2430

**Closed** 2024-08-24 16:39 UTC
