### ISSUE TITLE
Enhance contributions by providing GitHub source links in the documentation

### ISSUE THREAD

**Issue by mst2k** [typst/typst#2644] opened 2023-11-10 22:07 UTC
### Description

This feature request addresses the current challenge of locating the source code for segments of the documentation and proposes adding direct links from each documentation segment to its corresponding source on GitHub. This enhancement aims to streamline the process of finding and understanding the source code, facilitating a more efficient and transparent documentation contribution workflow.

A similar approach can be seen in the [Rust analyzer documentation.](https://rust-analyzer.github.io//manual.html#open-docs)
In this context, it may be advisable to refer to the specific source file that contains the implementation details of an element, rather than to an arbitrary location. (Ty @tingerrr)

Furthermore, as of now, some parts of the documentation lack a direct 1:1 correspondence with their source, requiring consolidation from scattered files. To improve this, I propose streamlining each documentation page into a dedicated markdown file.

### Use Case

This feature would be beneficial as it simplifies the contribution process to the documentation. Adding direct links to the corresponding source code on GitHub from each documentation page would make it easier for contributors to understand the implementation details, fostering a more efficient and transparent collaboration. This enhancement aims to streamline the workflow, allowing contributors to seamlessly navigate between documentation and source code, thereby facilitating more precise and informed updates to the documentation.

**Comment by laurmaedje** [comment] 2023-11-10 23:10
I think adding source links is good and possible without moving any documentation. I disagree that the documentation pages should be moved into dedicated Markdown files. That's how it used to be and it was a large improvement to have the docs inline with the Rust definitions. Many parts of the docs are also heavily auto-generated from Rust type information.

**Comment by laurmaedje** [comment] 2024-04-13 10:28
Duplicate of https://github.com/typst/typst/issues/981

**Closed by laurmaedje** 2024-04-13 10:28 UTC
Labels: docs, feature request
