### ISSUE TITLE
Inconsistent height for superscripts in math mode

### ISSUE THREAD

**Issue by ItamarOlmert** [typst/typst#2170] opened 2023-09-16 19:16 UTC
### Description

Superscripts in math mode seem to have a different height, depending on whether they are attached to a single digit or more than one digit.
Consider `$ 1^2 11^2 $`. This produces the following output: 
![Screenshot 2023-09-16 182542](https://github.com/typst/typst/assets/29255731/c4c9e687-d3af-44d5-9c8a-ad4042dcd824)
The `2` in the `11^2` term is slightly higher than the `2` in the `1^2` term:
![Screenshot 2023-09-16 182542 edited](https://github.com/typst/typst/assets/29255731/fd8e123e-7fe4-4986-ac60-67aa8bf05ec9)
The same effect doesn't seem to occur with subscripts.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-09-16 20:29
Relevant: PR https://github.com/typst/typst/pull/1129 issue https://github.com/typst/typst/issues/539

@Leedehai

**Comment by EpicEricEE** [comment] 2024-05-01 08:42
I can't reproduce this anymore, it was probably fixed by #3059.

**Closed** 2024-05-01 08:56 UTC
Labels: bug, math
