### ISSUE TITLE
`ref` to figure with `placement` links to wrong part of the document

### ISSUE THREAD

**Issue by Blokyk** [typst/typst#5508] opened 2024-12-02 23:24 UTC
### Description

Trying to reference a reference with `placement != none` results in an hyperlink to the wrong part of the document: instead of linking to the final position of the figure, it will link to where it would have been if wasn't moved.

One way to reproduce this:
- Write *more* than a page of content
- In the middle of it, insert a big figure with `placement: top`; this should put the figure at begin of the current or next page
- Add a reference to that figure somewhere

-> That reference now points to the middle of the content where the `#figure` is, and not to the location where the figure was actually placed

### Reproduction URL

https://typst.app/project/rGtnce5oXKBNoJBWL55T33

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-12-04 03:01
Not a regression (also present in 0.11.1).

**Comment by laurmaedje** [comment] 2024-12-04 07:56
Duplicate of https://github.com/typst/typst/issues/4359

**Closed by laurmaedje** 2024-12-04 07:56 UTC
Labels: bug, needs-investigation
