### ISSUE TITLE
More flexible `lr` (3+ delimiters)

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#2010] opened 2023-08-26 06:01 UTC
### Description

I can see this being implemented in two main ways:
The first would be a new function, e.g. `delim`, that accepts arguments for delimiter(s), a separator, and an array / varargs for content. Example:
```
$delim("{", "|", (n, m) in ZZ^2, n < m and sum_(i=n)^m 1/i = X})$ \
// This would produce a similar result to the current (though admittedly hacky and awkward):
$lr(lr(\{ (n, m) in ZZ^2 space \|) space n < m and sum_(i=n)^m 1/i = X\} )$
```
This function could be easily already be implemented in native Typst simply enough, and though it's API is a little bulky, I find it's a great improvement over the alternative with nested `lr`s.
The latter, which I personally prefer, yet I can see how it might introduce some hurdles in development, would be to either modify `lr` itself, or create a similar function (perhaps `lcr` for left, centre, right or `lsr` for separator) to detect cases such as the above automatically, thereby allowing the simple and intuitive markup of `${(n, m) in ZZ^2 | n < m and sum_(i=n)^m 1/i = X}$` to produce the desirable result with the separator bar scaled together with the delimiting curly braces.

### Use Case

Some use cases would be the builder set notation as above, and augmented matrices with a separating bar as well, though I think even enumeration separators such as `,` and `;` would more often then not be more pleasing when scaled together with their surrounding braces. Though it's important to remember these incur a different spacing scheme around them.

**Comment by laurmaedje** [comment] 2023-08-26 06:57
I like the idea of a `mid()` function that you can call in `lr` to scale something up.

**Comment by emilyyyylime** [comment] 2023-08-27 18:05
that seems like a nice and simple-to-understand API, but I don't see how it fits into place with the rest of Typst's design; we don't really have any 'context-sensitive' functions like that anywhere else. What does `mid` do outside of `lr`? Does it find the closest pair? Is it a special-case compiler error? Maybe it's a no-op? What even is considered 'in' `lr`? Is at the syntax-tree level or at the level of concrete elements?

**Comment by laurmaedje** [comment] 2023-08-27 20:57
mid would simply scale up to the height of the surrounding math "group". lr makes a group, but if you're outside lr the group is the whole equation.

**Comment by laurmaedje** [comment] 2023-09-04 09:10
Duplicate of https://github.com/typst/typst/issues/240

**Closed by laurmaedje** 2023-09-04 09:10 UTC
Labels: feature request
