### ISSUE TITLE
Support for stdio and piping

### ISSUE THREAD

**Issue by alterae** [typst/typst#410] opened 2023-03-28 21:14 UTC
It would be handy if the Typst CLI supported input via stdin, and perhaps also output via stdout. 

**Usage example:**
```
$ command-that-outputs-typst-markup | typst > processed.pdf
```

**Comment by johannes-wolf** [comment] 2023-03-29 01:17
Outputting to stdout already works by passing `/dev/stdout` as output file.

**Comment by owiecc** [comment] 2023-05-10 07:31
Doesn't Windows [have pipes](https://superuser.com/questions/586331/when-did-the-windows-command-line-get-the-pipe)? Not sure how the web ties into this. Most web servers run on unix systems.

**Comment by Dherse** [comment] 2023-05-10 08:31
> Doesn't Windows [have pipes](https://superuser.com/questions/586331/when-did-the-windows-command-line-get-the-pipe)?

Windows does have pipes, I was answering to another comment suggesting passing `/dev/stdout` as the output file would work. Which is not something that you can do on Windows, however, having a `--stdout` could be done.

> Not sure how the web ties into this. Most web servers run on unix systems. 

The web system runs in WASM so there would be no stdout there anyway, this would be a CLI-only feature if it were to be implemented.

**Comment by pepa65** [comment] 2023-07-23 16:18
It would be great to be able to pipe/redirect into typst (preferably with the `-` syntax, like: `echo Test |typst - out.pdf`). Then you don't need to create an actual/virtual file to provide input.

**Comment by edgarogh** [comment] 2023-08-19 22:51
I kinda implemented [a fix](https://github.com/typst/typst/compare/main...edgarogh:typst:stdin-main-support). It's not super clean, conservatively only enables this special case on Unix, and doesn't care to check if `/dev/stdin` actually exists. If I can open a PR and/or fix a few things so it gets merged upstream, I'd gladly do so :wink:. For the time being, it suits _my own_ needs.

**Comment by Enter-tainer** [comment] 2024-02-05 05:58
Can you give a few use case when this is useful? I feel it is somehow strange because:
1. typst source file can import files in the same directory. what should we do if the file from stdin imports other files?
2. per #2894 we can already pass arbitrary data to cli using args. Do we still need accept input from stdin?

**Comment by Enter-tainer** [comment] 2024-02-05 06:00
One thing I can come up with is that when integrating typst-cli to other systems. If a) you don't want touch filesystem b) you can embed everything into a single typ file, you can use piping: sending data into stdin and receive from stdout.

**Comment by pepa65** [comment] 2024-02-05 06:32
What you would expect to normally work on Posix-type systems doesn't somehow. It enhances scriptability, it conforms to normal expectations. I don't know about Windows, but for all the rest this should be true.

**Comment by s-cerevisiae** [comment] 2024-02-05 17:23
@Enter-tainer I'm integrating typst with my Zola setup to render inline formulas and do complicated layouts. It involves hundreds of different, tiny inputs so I needed to create and delete that many temporary files before this.

For the two questions:
1. The current implementation treats current working directory as the project base to resolve relative imports, which is already the default when typst can't determine one.
2. Yes, afaik it's treated as data and not code. I don't want to abuse `eval` for that, which is strictly worse. (e.g. the error message will be unreadable)

**Comment by C0ffeeCode** [comment] 2024-02-23 20:29
Is there someone working on this?
I still have what I thought to include in #2894 but then did not.

**Comment by istudyatuni** [comment] 2024-04-01 21:05
I guess this can be closed now? @laurmaedje

**Closed** 2024-04-01 21:07 UTC
Labels: feature request, cli, good contribution

**Comment by pepa65** [comment] 2024-04-02 12:15
This now works: `echo Hallo |typst c - out.pdf`
This does not: `typst c <(echo Hallo) out.pdf`

**Comment by C0ffeeCode** [comment] 2024-04-02 18:13
Is it now possible to pipe data not as an input document but as an input variable?
For example, like `typst compile --input key_of_piped_data=[...]` whereas `[...]` is the data from the pipe.

**Comment by laurmaedje** [comment] 2024-04-03 08:11
@pepa65 

> This does not: `typst c <(echo Hallo) out.pdf`

It works on my machine (macOS). Could you clarify what exactly doesn't work?

@C0ffeeCode How exactly it works depends on your shell. In bash you can write:

```bash
typst compile file.typ --input val=$(echo "Hello")
```

**Comment by Apollo314** [comment] 2024-04-04 00:26
> Is it now possible to pipe data not as an input document but as an input variable? For example, like `typst compile --input key_of_piped_data=[...]` whereas `[...]` is the data from the pipe.

you could do

    typst compile --input key_of_piped_data="$(cat)" file.typ

**Comment by jakobjpeters** [comment] 2024-08-12 19:51
The linked PR only implemented reading from `stdin`, is there a problem with or reason not to write to `stdout`?

**Comment by laurmaedje** [comment] 2024-08-12 19:56
Stdout was also implemented, but in another PR: https://github.com/typst/typst/pull/3632

**Comment by jakobjpeters** [comment] 2024-08-12 20:01
> Stdout was also implemented, but in another PR: #3632

Awesome, thank you!

**Comment by pepa65** [comment] 2024-08-12 21:22
@laurmaedje 
> Could you clarify what exactly doesn't work?

`typst c <(echo Hallo) out.pdf`

`error: input file not found (searched at /dev/fd/63)`
(typst 0.11.1)

**Comment by laurmaedje** [comment] 2024-08-13 07:17
> This now works: `echo Hallo | typst c - out.pdf`
> This does not: `typst c <(echo Hallo) out.pdf`

Okay, yeah. I can reproduce it in Docker, so for some reason it fails on Linux but works on macOS. I'm not that knowledgeable w.r.t. piping on Linux, but I'll share this in #contributors on Discord. Maybe someone has an idea.

**Comment by alerque** [comment] 2024-08-13 08:06
The second form creates a temporary node that is a named pipe. Typst is handling input on STDIN as a stream, but it is trying to treat the file name given for the named pipe as a regular file, which is not possible (it is not seekable, it actually a stream because the app producing it (in this simple case `echo`) doesn't start doing any work until something starts reading from the pipe). An extra check is going to be required to handle named pipes vs. regular files. It looks like it's getting tripped up before even trying to open the file just trying to canonicalize the name.
