### ISSUE TITLE
Wrong hyphenation for short words like "types"

### ISSUE THREAD

**Issue by AnsgarLichter** [typst/typst#4135] opened 2024-05-14 15:43 UTC
### Description

I observed that typst uses a wrong hyphenation somestimes. In my current situation this looks as follows:
<img width="490" alt="image" src="https://github.com/typst/typst/assets/43957906/28d6e048-ea76-49cc-8693-8d236849cc3f">

[This](https://www.hyphenation24.com/word/types/) page says that the word `types` has only one syllable and should be therfore not separated. Nevertheless, if I try to set the hyphenation manually, this results in the following:
![image](https://github.com/typst/typst/assets/43957906/0c3494dd-bd0d-4153-aa04-53d3d72f929a)

I think this is related to the `.ABCDEF` because it includes `.` which stands for the end of a sentence normally but is needed as a name of the described type. 
I didn't find any option in the documentation to suppress or apply the hyphenation manually. Therefore, I think this is a bug. If I am wrong I am happy to convert this into a discussion.

Thanks in advance.

### Reproduction URL

https://typst.app/project/rbfMZZ5h4rQgrO5sRxvW0V

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2024-05-15 11:57
To surpress hyphenation, you can wrap the word in a `box`.

**Comment by laurmaedje** [comment] 2024-05-15 13:40
Duplicate of https://github.com/typst/typst/issues/2168

**Closed by laurmaedje** 2024-05-15 13:40 UTC
Labels: bug

**Comment by Enivex** [comment] 2024-05-15 13:43
> Duplicate of https://github.com/typst/typst/issues/2168

This is a word though, so maybe the issue title isn't quite accurate
