### ISSUE TITLE
Mutually recursive functions are impossible to write

### ISSUE THREAD

**Issue by H2CO3** [typst/typst#2250] opened 2023-09-27 09:14 UTC
### Description

Currently, it seems impossible to write mutually recursive functions, because the compiler is sensitive to the order to function definitions, and AFAICT there is no way to forward-declare a function. This appears to be an unfortunate side effect of functions being "just variables" (because in the case of variables, this order-sensitivity makes sense).

For example, the follwing code:

```
#let first(n) = {
    if n > 0 {
        second(n - 1);
    } else {
        [Ended in first]
    }
};
#let second(n) = {
    if n > 0 {
        first(n - 1);
    } else {
        [Ended in second]
    }
};
#first(10);                                                                                                  
```
produces the following error:

```
error: unknown variable: second
  ┌─ impossible.typ:3:8
  │
3 │         second(n - 1);
  │         ^^^^^^

help: error occurred in this call of function `first`
   ┌─ impossible.typ:15:1
   │
15 │ #first(10);
   │  ^^^^^^^^^
```

I need a pair of mutually recursive functions for rendering a tree of elements where every element is either a leaf (stand-alone data) or a container. I could work this around by inlining the definition of one function to the other, but it's not pretty.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-09-27 10:14
Duplicate of https://github.com/typst/typst/issues/744

**Closed by laurmaedje** 2023-09-27 10:14 UTC
Labels: bug
