### ISSUE TITLE
Citations in `hide` do not work

### ISSUE THREAD

**Issue by LarsKue** [typst/typst#622] opened 2023-04-06 08:07 UTC
See Title. I am using the typst.app web application. Here is the steps I took to reproduce:

1. Enter a bibtex-style citation into your refs.bib file.
2. Create a citation with `@citation`.
3. Create a bibliography with `#bibliography()`

Everything still works as normal up to this point.

4. Hide the citation with `#hide[]`.

The compiler now crashes with the error "Unexpected end of file." Note that using `#cite()` also does not work (here, the compiler does not crash, but I get the error "The bibliography does not contain this key")

[See here for a minimal example.](https://typst.app/project/rDfFdwEeNXkl5KQdEzSrfv)

My use case is that I am trying to automatically generate a list of sources for a presentation, without explicitly showing citations in the text.

**Comment by Enivex** [comment] 2023-04-06 08:29
While this is a bug, I feel like Typst should have something like the \nocite command in LaTeX to do what you're trying to accomplish. Printing some subset of bibliography without explicitly citing is very common in for instance presentations and resumes.

**Comment by giacomogallina** [comment] 2023-04-29 16:41
I wouldn't mind trying to solve this bug, but the compiler is pretty big and i'm a bit lost, does anyone have any ideas about where i could start looking? Or some general tips on debugging typst?

**Comment by LarsKue** [comment] 2023-04-29 16:48
@giacomogallina I am neither familiar with the compiler nor do I have capacity to work on this, but it seems like this is an issue with how citations/references are handled. If I were you I would try to start at [library/src/meta/reference.rs](https://github.com/typst/typst/blob/main/library/src/meta/reference.rs).

**Comment by giacomogallina** [comment] 2023-04-29 16:52
I was looking at library/src/meta/bibliography.rs, but i had missed reference.rs, thanks! By the way, i tried this example document:
```
#hide[@test]
#bibliography("test.bib")
```
and the compiler doesn't crash, instead it just prints a missing key error (if i inderstand correctly, when you tried an equivalent test, the compiler crashed, correct me if i'm wrong)

**Comment by laurmaedje** [comment] 2023-04-29 17:22
Hiding happens in src/doc.rs in Frame::meta. The problem is that hiding also removes the metadata from the frames which is needed for references to work. I think we should just not remove it. Not sure about other kinds of metadata like links, these should probably be removed when hidden.

**Comment by PgBiel** [comment] 2023-05-01 17:14
> By the way, i tried this example document:
> (...)
> and the compiler doesn't crash, instead it just prints a missing key error (if i inderstand correctly, when you tried an equivalent test, the compiler crashed, correct me if i'm wrong)

Yes, I believe the compiler crash was fixed in v0.3.0, thanks to #811. It was failing to display the bibliography not found error. Still, the error itself is still a bug.

**Closed** 2023-05-22 14:45 UTC
Labels: bug, meta

**Comment by flavio20002** [comment] 2023-08-02 10:15
Just to add that the my implementation of nocite is:

    #let nocite(citation) = {
      place(hide[#cite(citation)])
    }

place is for not affecting the layout, hide to now showing the citation
