### ISSUE TITLE
More powerful paragraph justification

### ISSUE THREAD

**Issue by diquah** [typst/typst#5547] opened 2024-12-07 22:51 UTC
### Description

Advanced typesetting software such as Adobe InDesign and Affinity Publisher give additional options for creating satisfying and even paragraph justifications. Other than dynamic spacing between words and hyphenation control, they offer individual letter spacing and glyph scaling. While these seem minor, they can be the make or break for including a single letter word in the line above or fitting a really long word into a line without having to introduce extra spacing.

This is discussed in more detail for LaTeX in [this post](https://tex.stackexchange.com/questions/401270/automatically-alter-letterspacing-intra-word-spacing-to-avoid-loose-lines-with):

![image](https://github.com/user-attachments/assets/af651abe-9db4-42ab-860f-8939190ef6a2)

![image](https://i.sstatic.net/JX1mz.gif)

### Use Case

Paragraph justification is a major feature used by almost every print medium: journals, articles, newspapers, etc. I think implementing this feature would lift a major roadblock for using Typst to publish quality prints, and increase its case for being the best way for writing large manuscripts while having effortless but powerful control over layout and styling.

**Comment by EpicEricEE** [comment] 2024-12-07 23:36
Possibly a duplicate of #4693

**Comment by diquah** [comment] 2024-12-08 03:17
@EpicEricEE I have read that issue and those associated with it. They specifically talk about improving the layout of overhangs (such as how superscripts and subscripts are considered when justifying text), whereas this issue is about better justification within the paragraph line by allowing scaling of glyphs and spacing between glyphs inside words.

These would be customizable amounts, but are generally within 2% as to keep firm word boundaries while giving the layout engine a little more agency in laying out blocks.

**Comment by Enivex** [comment] 2024-12-09 19:24
> @EpicEricEE I have read that issue and those associated with it. They specifically talk about improving the layout of overhangs (such as how superscripts and subscripts are considered when justifying text), whereas this issue is about better justification within the paragraph line by allowing scaling of glyphs and spacing between glyphs inside words.
> 
> These would be customizable amounts, but are generally within 2% as to keep firm word boundaries while giving the layout engine a little more agency in laying out blocks.

No, this is a duplicate of that issue.

**Closed by Enivex** 2024-12-09 19:24 UTC
Labels: feature request, layout, text
