### ISSUE TITLE
Misaligned superscripts and subscripts - part 2

### ISSUE THREAD

**Issue by ludwig-austermann** [typst/typst#2324] opened 2023-10-06 17:19 UTC
### Description

Similarly to #539, super- and subscripts are still misaligned, when using accents. Accents on variables are vastly used by mathematicians, such that changing this should impact many documents.

Take:
```typst
#set page(width: auto, height: auto, margin: 5pt)

#let modifications = (x => $#x$, x => $hat(#x)$, x => $macron(#x)$, x => $tilde(#x)$)
#for modification in modifications {
  let mod(x) = $med #modification($#x$)_1^1 $
  box(box(
    $e_1^1 #mod($x$) #mod($y$) #mod($delta$) #mod($beta$) #mod($mu$) #mod($lambda$) #mod($l$) #mod($M$) #mod($(x)$)$,
    stroke: red + 0.2pt
  ), inset: (top: 1.6pt, bottom: 2.6pt), stroke: orange + 0.2pt)
  linebreak()
}
```
resulting in

![subscripts](https://github.com/typst/typst/assets/12214171/5a7bf246-b602-4b38-8ed6-a4ea28deafde)

whereas similar latex code results in

![grafik](https://github.com/typst/typst/assets/12214171/0b5b9350-21df-489e-bd89-9b66d88581d7)

One notices, that in latex all super- and subscripts are aligned, whereas these change in typst with accents. Furthermore, the horizontal placement is also misaligned in typst, as can be seen with the ̀ M`.

(I am using typst 0.8.0)

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-10-14 22:28
Duplicate of https://github.com/typst/typst/issues/1672

**Closed by Enivex** 2023-10-14 22:28 UTC
Labels: bug, duplicate, math
