### ISSUE TITLE
Allow calling of functions within a dictionary

### ISSUE THREAD

**Issue by TimeTravelPenguin** [typst/typst#5395] opened 2024-11-09 12:21 UTC
### Description

Currently, if you have a dictionary `let foo = (bar: "baz")`, you can use `#foo.bar` to retrieve the result `baz`. However, we cannot have `let foo = (bar: () => "baz")` and use `#foo.bar()`. We are required to use `#(foo.bar)()`.

I request being able to call `#foo.bar()`.

### Use Case

My use case is that I wanted to implement some ad-hoc "objects".

To demonstrate, consider someone wanting to make a library for complex numbers.
```typ
#let new-complex(re, im) = {
  return (
    re: re,
    im: im,
    add: z => new-complex(re + z.re, im + z.im),
  )
}

#let z = new-complex(1, 2)
#let w = new-complex(3, 4)
#let x = (z.add)(w) // Would be nice to have z.add(w)
#repr(x) // result: (re: 4, im: 6, add: (..) => ..)
```

In my case, I would like to build a library to do some more advanced mathematics. Unfortunately, my ideal vision is not currently possible due to this limitation.

There are more advanced use cases, too. I realised this issue when I was attempting to implement a builder pattern. I was expecting to have something like:
```typ
#let builder = builder()
#builder.add_method("hello", () => "Hello, world!")
#let obj = builder.build()
#obj.hello()
```

This would be an interesting idea to play with, but without a flexible language, it is not really worth pursuing.

**Comment by laurmaedje** [comment] 2024-11-09 18:42
Duplicate of https://github.com/typst/typst/issues/976

**Closed by laurmaedje** 2024-11-09 18:42 UTC
Labels: feature request
