### ISSUE TITLE
lang: "fr" doesn't manage spaces before punctuation marks

### ISSUE THREAD

**Issue by louleke7** [typst/typst#4674] opened 2024-08-04 14:50 UTC
### Description

French "best practice" of typography requires "tall" punctuation marks (namely ! ? ; and : ) to be preceded by a fine unbreakable space (u202F) instead of a normal one (u0020) (or nothing at all). 
Currently, these two examples output the exact same results
```
This sentence has spaces ; and a semicolon.

This one has an exclamation mark without typing a space before!

It wouldn't look correct in french.
```
and 
```
#set text(lang: "fr")

This sentence has spaces ; and a semicolon.

This one has an exclamation mark without typing a space before!

It wouldn't look correct in french.
```
It would be nice if, when having `lang` set to "fr", such spaces (or lack thereof) are transparently replaced by the "correct" one, e.g. the above code (with `lang` set to "fr")  would output the bottom lines 
![Capture d’écran_2024-08-04_16-46-36](https://github.com/user-attachments/assets/d80f3dc3-3585-4a2c-8262-27c1c382eeae)

### Use Case

It would be very convenient for french users, having the punctuation mark that looks "correct" without having to input Unicode character via code-point. Modern editing/typesetting software generally handle that automatically.

Issue #4672 prevents a simple use of  `#show` and regexp to fix this easily.

**Comment by Enivex** [comment] 2024-08-04 15:03
Duplicate of https://github.com/typst/typst/issues/1920

(More or less)

**Closed by Enivex** 2024-08-04 15:03 UTC
Labels: feature request

**Comment by Thumuss** [comment] 2024-08-04 20:58
> Duplicate of #1920
> 
> (More or less)

It's really not the same because one is unbreakable space and the other is just an automatic space

**Comment by Enivex** [comment] 2024-08-04 21:03
> > Duplicate of #1920
> > 
> > (More or less)
> 
> It's really not the same because one is unbreakable quote and the other is just an automatic space

See the comment on that issue as well. I don't see a reason to have two separate issues here.

**Comment by Thumuss** [comment] 2024-08-04 21:04
> > > Duplicate of #1920
> > > (More or less)
> > 
> > 
> > It's really not the same because one is unbreakable quote and the other is just an automatic space
> 
> See the comment on that issue as well. I don't see a reason to have two separate issues here.

My bad, I get it!
