### ISSUE TITLE
`cargo install --locked typst-cli` fails to compile

### ISSUE THREAD

**Issue by jonathanbcarlson** [typst/typst#4659] opened 2024-08-02 22:18 UTC
### Description

Running: `cargo install --locked typst-cli` for `typst-cli v0.11.1` led to a compilation error caused by the `time` crate (version 0.3.34). See https://github.com/rust-lang/rust/pull/124736 for a fix for the same error.

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/jonathancarlson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling displaydoc v0.2.4
   Compiling icu_provider_macros v1.4.0
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `typst-cli v0.11.1`, intermediate artifacts can be found at `/var/folders/28/vrmpryz57ps7flcnckwkfg5w0000gn/T/cargo-installNQsHyN`.
```

If I run `cargo install typst-cli` it compiles successfully.

### Operating system

macOS

### Typst version

- [ ] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-08-03 00:05
Typst 0.11.1 cannot be built with Rust 1.80.0 or later due to a problem in the `time` dependency. You will have to either downgrade your Rust toolchain to 1.79.0 or change the `time` version in Cargo.toml ro 0.3.36.

**Comment by laurmaedje** [comment] 2024-08-05 09:59
Nothing we can do about this, so I'll close it.

**Comment by k0tran** [comment] 2024-08-08 12:12
@laurmaedje can we bump time version up to 0.3.36 in typst repo though? It would be nice

I've done this in [k0tran/typst](https://github.com/k0tran/typst), works for me.

**Comment by laurmaedje** [comment] 2024-08-08 12:38
It is already bumped in the lock file on main. The issue is specifically with 0.11.1, which we cannot change anymore. I guess we can also bump in Cargo.toml, but the current version contraint shouldn't prevent anybody from updating their dependency.

**Comment by PgBiel** [comment] 2024-08-08 17:41
We could consider bumping on the `0.11` branch so users who want to compile from source while sticking to 0.11.1 can still do so.

**Comment by laurmaedje** [comment] 2024-08-08 18:31
Yeah, we can do that

**Comment by laurmaedje** [comment] 2024-08-23 09:03
Done: https://github.com/typst/typst/commit/b49a8ffd505e05a2f24cf69c868215f72a833230

**Comment by laurmaedje** [comment] 2024-09-16 15:12
Reopening until Typst 0.12 is released.

**Closed** 2024-10-28 09:08 UTC
Labels: bug, devops
