### ISSUE TITLE
Chinese punctuation is placed at the beginning of the line in some cases

### ISSUE THREAD

**Issue by zz5840** [typst/typst#3082] opened 2023-12-27 11:49 UTC
### Description

![image](https://github.com/typst/typst/assets/16662647/65df21f1-e3f7-4b6d-9f9e-b184116b1c3d)

```
#set text(font: "Source Han Serif SC")

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abcd），松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abc0），松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（0000），松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（8888），松黃貫誰。
```

According to my tests, this problem occurs when the punctuation is after the parentheses and the last character in the parentheses is a number. I don't know if there are any other cases where this problem occurs.

Typst version: `typst 0.10.0 (70ca0d25)`

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2023-12-27 12:06
iirc typst use https://docs.rs/icu/latest/icu/segmenter/index.html to determine line break points. maybe an upstream issue

**Comment by YDX-2147483647** [comment] 2024-01-13 15:51
It is _Source Han Serif/Sans_-only?? `(@_@)`

```typst
#set page(height: auto)

#let fonts = ("Source Han Serif", "Source Han Sans", "STKaiti", "SimSum", "SimHei", "STLiti",)

#for f in fonts {
  set text(font: f)
  [
    = #f
     
    課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abcd），松黃貫誰。
     
    課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abc0），松黃貫誰。
     
    課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（0000），松黃貫誰。
     
    課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（8888），松黃貫誰。
  ]
}
```

![test](https://github.com/typst/typst/assets/73375426/35538c47-aa8e-48d9-8bf5-65a332d2b74c)

**Comment by Enter-tainer** [comment] 2024-01-13 15:55
IMO line break points shouldnt relate to font. maybe this is because these fonts have slightly different width so it is not reproduced

**Comment by zz5840** [comment] 2024-01-13 16:05
@YDX-2147483647 No, examples for PingFang SC and Microsoft Yahei are shown below.

![image](https://github.com/typst/typst/assets/16662647/4c7de411-939c-4a67-a663-ea604e1a047d)

![image](https://github.com/typst/typst/assets/16662647/1b0073d4-c032-4936-9edb-106fa59066ef)

If using SimSun, adding an extra digit will also trigger this.

```
#set text(font: "SimSun")

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abcde），松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（abc00），松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急(000000),松黃貫誰。

課有手冬，朱得過已誰卜服見以大您即乙太邊良，因且行肉因和拉幸，念姐遠米巴急（88888），松黃貫誰。
```

![image](https://github.com/typst/typst/assets/16662647/3aa57231-857a-481d-8e9b-8a7a01e13bd8)

**Comment by YDX-2147483647** [comment] 2024-01-13 16:23
Thanks for explanation! 

---

> iirc typst use [`icu::segmenter`](https://docs.rs/icu/latest/icu/segmenter/index.html) to determine line break points. maybe an upstream issue

Typst has a dedicated https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/layout/inline/linebreak.rs, which I have not read carefully. But a basic test verifies that `abcd` ≠ `abc0`.

```rust
use icu_segmenter::LineSegmenter;

fn main() {
    let examples = vec![
        "念姐遠米巴急（abcd），松黃貫誰。",
        "念姐遠米巴急（abc0），松黃貫誰。",
        "念姐遠米巴急（0000），松黃貫誰。",
        "念姐遠米巴急（8888），松黃貫誰。",
    ];

    let segmenter = LineSegmenter::new_auto();

    examples.iter().for_each(|line| {
        let breakpoints: Vec<usize> = segmenter.segment_str(line).collect();
        println!("{}\n{:?}", line, breakpoints);
    });
}
```

```
念姐遠米巴急（abcd），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 31, 34, 37, 40, 46]    
念姐遠米巴急（abc0），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
念姐遠米巴急（0000），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
念姐遠米巴急（8888），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
```

**Comment by Enter-tainer** [comment] 2024-01-13 16:26
I just did the same thing!
```
breakpoints: [0, 3, 6, 9, 12, 15, 18, 31, 34, 37, 40, 46]
|念姐遠|米巴急|（ab|cd）|，松黃|貫誰。|
```

**Comment by Enter-tainer** [comment] 2024-01-13 16:26
It seems indeed to be an upstream issue

**Comment by Enter-tainer** [comment] 2024-01-13 16:34
`，` is U+FF0C, which belongs to [CL](https://www.unicode.org/reports/tr14/#CL): Close Punctuation (XB). Per https://www.unicode.org/reports/tr14/#LB15b there shouldn't be a break point before it

**Comment by Enter-tainer** [comment] 2024-01-13 16:35
@YDX-2147483647 will you open an issue to upstream repo? Or I do that?

**Comment by Enter-tainer** [comment] 2024-01-13 17:40
Wait. I just found that [LB15b](https://www.unicode.org/reports/tr14/#LB15b) actually doesn't mention this case. I feels like it actually doesn't care about Chinese line break prohibition rules.

We might need to support this in typst's side. Per CLREQ[https://www.w3.org/TR/clreq/#prohibition_rules_for_line_start_end] we can filter linebreak points produced by icu, by removing invalid ones.

cc @peng1999 What do you think of this?

Also interestingly, icu doesn't produce a breakpoint after `，`. IDK why.

**Comment by Enter-tainer** [comment] 2024-01-13 17:42
Forgive me, this is actually LB13 https://www.unicode.org/reports/tr14/#LB13. linebreaks are not allowed before CL. So it's still an upstream issue!

**Comment by Enter-tainer** [comment] 2024-01-13 17:48
@zz5840 can you show us how you get `念姐遠米巴急` ? This looks like a random string but it seems that only this string can trigger icu's bug. Is it comes from fuzz testing or something?

**Comment by zz5840** [comment] 2024-01-13 17:50
@laurmaedje Yeah, I just generate it from a Chinese lorem string generator. But I actually encounter this issue when dealing with my document.

**Comment by Enter-tainer** [comment] 2024-01-13 17:53
okay, that's very interesting!

**Comment by zz5840** [comment] 2024-01-13 18:02
@Enter-tainer It's a very common issue.

![image](https://github.com/typst/typst/assets/16662647/4e32e646-0e87-4b1f-b0c0-603fa24e4bef)

<details>
<summary>Code</summary>

```
#set text(font: "SimSun")
参赛选手：福明煦（100）、钟离君博（100）、巢海亦（100）、曲文昂（100）、皇甫静美（100）、丁弘壮（100）
```

</details>

**Comment by Enter-tainer** [comment] 2024-01-13 18:03
```
breakpoints: [0, 3, 6, 9, 15, 18, 21, 24, 33, 36, 39, 42, 45, 48, 57, 60, 63, 66, 69, 78, 81, 84, 87, 90, 99, 102, 105, 108, 111, 114, 123, 126, 129, 132, 135, 144]
|参赛选|手：福|明煦（|100）、钟|离君博|（10|0）、|巢海亦（100）、|曲文昂|（10|0）、|皇甫静|美（1|00）、丁弘壮（1|00）|
```

**Comment by YDX-2147483647** [comment] 2024-01-14 14:22
> ```rust
>     // pretty print test str and break points
>     for (i, c) in test_str.chars().enumerate() {
>         if breakpoints.contains(&i) {
> ```

Well, it seems that breakpoints are counted in bytes (`usize`), but `i` represents `chars()`. This explains why there're more breakpoints than `|`s.

The following version might be better.

```rust
use icu_segmenter::LineSegmenter;

fn main() {
    let examples = vec![
        "念姐遠米巴急（abcd），松黃貫誰。",
        "念姐遠米巴急（abc0），松黃貫誰。",
        "念姐遠米巴急（0000），松黃貫誰。",
        "念姐遠米巴急（8888），松黃貫誰。",
    ];

    let segmenter = LineSegmenter::new_auto();

    examples.iter().for_each(|line| {
        let breakpoints: Vec<usize> = segmenter.segment_str(line).collect();
        println!("{}\n{:?}", line, breakpoints);

        for i in 1..breakpoints.len() {
            print!(
                "|{}",
                line.get(breakpoints[i - 1]..breakpoints[i])
                    .expect("Breakpoints should be at characters' boundaries")
            );
        }
        println!("|");
    });
}
```

```
念姐遠米巴急（abcd），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 31, 34, 37, 40, 46]    
|念|姐|遠|米|巴|急|（abcd），|松|黃|貫|誰。|    
念姐遠米巴急（abc0），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
|念|姐|遠|米|巴|急|（abc0）|，|松|黃|貫|誰。|   
念姐遠米巴急（0000），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
|念|姐|遠|米|巴|急|（0000）|，|松|黃|貫|誰。|   
念姐遠米巴急（8888），松黃貫誰。
[0, 3, 6, 9, 12, 15, 18, 28, 31, 34, 37, 40, 46]
|念|姐|遠|米|巴|急|（8888）|，|松|黃|貫|誰。|   
```

**Comment by Enter-tainer** [comment] 2024-01-14 14:27
ty for figure out this! can you post this code piece to the upstream issue?

**Comment by YDX-2147483647** [comment] 2024-01-16 03:44
An upstream maintainer explains in https://github.com/unicode-org/icu4x/issues/4523#issuecomment-1892793516 that it was fixed by https://github.com/unicode-org/icu4x/pull/4389, but not released in [v1.4.0 (Nov 16, 2023)](https://github.com/unicode-org/icu4x/releases/tag/icu%401.4.0) yet. We can verify it by rerunning [the basic test above](https://github.com/typst/typst/issues/3082#issuecomment-1890966770) with the following `Cargo.toml`.

```toml
[dependencies]
icu_segmenter = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7" }
```

However, typst can't compile with `99802d7`. Maybe a breaking change?

```
error[E0277]: `Rc<Box<[u8]>>` cannot be sent between threads safely
   --> crates\typst\src\layout\inline\linebreak.rs:42:19
    |
42  | static SEGMENTER: Lazy<LineSegmenter> = Lazy::new(|| {
    |                   ^^^^^^^^^^^^^^^^^^^ `Rc<Box<[u8]>>` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `Rc<Box<[u8]>>`
    = note: required for `yoke::cartable_ptr::CartableOptionPointer<Rc<Box<[u8]>>>` to implement `Sync`
```

So I suggest we wait until icu's next release.

**Comment by peng1999** [comment] 2024-01-16 04:14
> Maybe a breaking change?

No it's not. The error happens because some version mismatch. You should upgrade all icu related crates to the same git version to get it working.

**Comment by YDX-2147483647** [comment] 2024-01-16 05:43
> You should upgrade all icu related crates to the same git version

Yes! Now it compiles.

```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -48,11 +48,11 @@ hayagriva = "0.5.1"
 heck = "0.4"
 hypher = "0.1.4"
 iai = { git = "https://github.com/typst/iai", rev = "3f0f927" }
-icu_properties = { version = "1.4", features = ["serde"] }
-icu_provider = { version = "1.4", features = ["sync"] }
-icu_provider_adapters = "1.4"
-icu_provider_blob = "1.4"
-icu_segmenter = { version = "1.4", features = ["serde"] }
+icu_properties = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7", features = ["serde"] }
+icu_provider = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7", features = ["sync"] }
+icu_provider_adapters = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7" }
+icu_provider_blob = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7" }
+icu_segmenter = { git = "https://github.com/unicode-org/icu4x", rev = "99802d7", features = ["serde"] }
 if_chain = "1"
 image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
 include_dir = "0.7"
```

Unfortunately `cargo run -- compile test.typ` on https://github.com/typst/typst/commit/f57c34a7 (current main) still gives:

![](https://github.com/typst/typst/assets/73375426/cc2e53f4-2681-4f1b-b5bb-d922618f4af7)

Maybe we should regenerate https://github.com/typst/typst/tree/f57c34a7ce7bd09d7c2f2d19f37645ad30493afd/crates/typst/assets?

https://github.com/typst/typst/blob/f57c34a7ce7bd09d7c2f2d19f37645ad30493afd/crates/typst/src/layout/inline/linebreak.rs#L13-L39

**Comment by peng1999** [comment] 2024-01-16 06:44
> Maybe we should regenerate https://github.com/typst/typst/tree/f57c34a7ce7bd09d7c2f2d19f37645ad30493afd/crates/typst/assets?

Yes. Regenerate with the latest icu4x/datagen is enough for fixing this issue. No upgrades for crates is actually needed. But be aware that you should generate two data with different code base: one official and one patched. You can now use this [rebased patch](https://github.com/peng1999/icu4x/commit/5b9a39906f2b54a1a885e7991a92ec55645992e9).

**Comment by YDX-2147483647** [comment] 2024-01-16 12:04
> Regenerate with the latest icu4x/datagen is enough for fixing this issue.

Hmm I can't reproduce it, no matter upgrading icu or not. Could you check my procedure?

```shell
cargo install icu_datagen
icu4x-datagen --locales full --format blob --keys-for-bin target/debug/typst.exe --out crates/typst/assets/icudata.postcard --overwrite
# icu4x-datagen will download files from GitHub.

cargo install icu_datagen --git https://github.com/peng1999/icu4x --branch zh-line-gen --root .
./bin/icu4x-datagen --locales zh ja --format blob --keys segmenter/line@1 --out crates/typst/assets/cj_linebreak_data.postcard --overwrite
# It will use cache this time.

cargo run -- compile test.typ
# cargo recompiles automatically. (~15 min)
```

```shell
$ sha256sum crates/typst/assets/*
167f7f995a176ab82d1cc06100f473aac89322f6b957df1a0ad0a67faafe133d *crates\typst\assets\cj_linebreak_data.postcard
4e51b7bc519a88933876a464b7d41e83171f70c80765ba3e4516e141a7fd92c5 *crates\typst\assets\icudata.postcard
```

---

Nonetheless, here we may face the same problem as in #3171: Keeping update a binary can bloat the repo. (though only ~400 kB for now, and https://github.com/unicode-org/icu4x/issues/3284 may remove the burden in the future)

<details>
<summary>
ICU4X recommends either a <code>build.rs</code>, or check in + CI to update
</summary>

https://github.com/unicode-org/icu4x/blob/99802d74f5d58213677a5e0319fd5a1450518711/docs/tutorials/data_management.md?plain=1#L33C1-L47

> ## Should you check in data to your repository?
>
> You can check in the generated data to your version control system, or you can add it to a build script. There are pros and cons of both approaches.
>
> You should check in the generated data if:
>
> 1. You want fully reproducible, deterministic builds
> 2. You want to reduce build-time dependencies
>
> You should generate it automatically at build time if:
>
> 1. You want to automatically download the latest CLDR/Unicode data
> 2. It is difficult to add large files to your VCS
>
> If you check in the generated data, it is recommended that you configure a job in continuous integration that verifies that the data in your repository reflects the latest CLDR/Unicode releases; otherwise, your app may drift out of date.

</details>

**Comment by peng1999** [comment] 2024-01-16 14:04
> Nonetheless, here we may face the same problem as in #3171: Keeping update a binary can bloat the repo. (though only ~400 kB for now, and [unicode-org/icu4x#3284](https://github.com/unicode-org/icu4x/issues/3284) may remove the burden in the future)

Using `build.rs` to generate data may works. But since we includes a customized data, we should maintain a fork of icu4x and rebase to the latest upstream regularly, until https://github.com/unicode-org/icu4x/issues/3284 resolves.

@laurmaedje What do you prefer? Be it 1) just keeping the status quo and commit new versions of icudata into repo (since they are small and will not be updated regularly), or 2) using `build.rs` to generate data and keep a icu4x fork under typst organization, or 3) using the same infrastructure proposed in #3171, or something else?

**Comment by laurmaedje** [comment] 2024-01-16 14:35
@peng1999 I'm leaning towards option 3.

**Closed** 2024-03-06 14:38 UTC
Labels: bug, text
