### ISSUE TITLE
Raw (monospace) text in table having issues overflowing in next cell

### ISSUE THREAD

**Issue by mattharrison** [typst/typst#4747] opened 2024-08-13 23:55 UTC
### Description

I'm writing a book and I have a table describing methods. Long method names sporadically don't jump to the next line. I'm not sure how to handle this. In LaTeX I would insert blank spaces in the text so it would break there.

Here is an example: 

```typ
#figure(
  align(left)[#table(
    columns: (41.76%, 58.24%),
    align: (auto,auto,),
    table.header([Método], [Descripción],),
    table.hline(),
    [`pd.Series(data=None, index=None, dtype=None, name=None, copy=False)`], [Crear
    una serie a partir de `data` (secuencia, diccionario o escalar).],
    [`s.index`], [Acceder al índice de la serie.],
    [`s.astype(dtype, errors='raise')`], [Convertir una serie a `dtype`.
    Para ignorar errores (y devolver el objeto original), use
    `errors='ignore'`.],
    [`s[boolean_array]`], [Devolver valores de `s` donde `boolean_array`
    es `True`.],
    [`s.cat.ordered`], [Determinar si una serie categórica está
    ordenada.],
    [`s.cat.reorder_categories( new_categories, ordered=False)`], [Añadir
    categorías (potencialmente ordenadas) a la serie. `new_categories`
    debe incluir todas las categorías.],
    [`s.cat.categories`], [Devolver las categorías de una serie
    categórica.],
    [`s.cat.add_categories(new_categories)`], [Añadir nuevas categorías
    a una serie categórica.],
  )]
  , caption: [Tabla de funcionalidades exploradas en este capítulo.]
  , kind: table
  )
```

My issue is the lines `    [`s.cat.reorder_categories( new_categories, ordered=False)`], ` and `    [`s.cat.add_categories( new_categories)`], [Añadir nuevas `.

Note that I added spaces after the `(` but it is not breaking. You can see the results here:

![Screenshot 2024-08-13 at 5 54 27 PM](https://github.com/user-attachments/assets/2d35c974-1172-4279-8525-a80b8d3207fd)

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-08-14 00:14
Duplicate of https://github.com/typst/typst/issues/674

You can use the workaround mentioned in the issue. Here's how I did it for your table, below.

Note that I also
1. Removed `#align(left)`, used `align: left` inside the table instead;
2. Removed `kind: table` as it is now redundant and the table is automatically detected;
3. Used raw blocks directly in code mode instead of in a (redundant) markup `[ ]` block.

```typ
#figure(
  {
    // Show rule inside a scope to ensure it only applies to this table
    show table.cell.where(x: 0): it => {
      show regex("\w"): it => sym.zws + it
      it
    }
    table(
      columns: (41.76%, 58.24%),
      align: left,
      table.header([Método], [Descripción],),
      table.hline(),
      ```pd.Series(data=None, index=None, dtype=None, name=None, copy=False)```, [Crear
      una serie a partir de `data` (secuencia, diccionario o escalar).],
      ```s.index```, [Acceder al índice de la serie.],
      ```s.astype(dtype, errors='raise')```, [Convertir una serie a `dtype`.
      Para ignorar errores (y devolver el objeto original), use
      `errors='ignore'`.],
      ```s[boolean_array]```, [Devolver valores de `s` donde `boolean_array`
      es `True`.],
      ```s.cat.ordered```, [Determinar si una serie categórica está
      ordenada.],
      ```s.cat.reorder_categories( new_categories, ordered=False)```, [Añadir
      categorías (potencialmente ordenadas) a la serie. `new_categories`
      debe incluir todas las categorías.],
      ```s.cat.categories```, [Devolver las categorías de una serie
      categórica.],
      ```s.cat.add_categories(new_categories)```, [Añadir nuevas categorías
      a una serie categórica.],
    )
  },
  caption: [Tabla de funcionalidades exploradas en este capítulo.]
)
```
![image](https://github.com/user-attachments/assets/02f63db0-d037-4174-b7cb-39d3d5830848)

**Closed by PgBiel** 2024-08-14 00:14 UTC
Labels: bug

**Comment by mattharrison** [comment] 2024-08-14 00:25
I don't want it to break it arbitrary places. I want it to break on a space.

**Comment by PgBiel** [comment] 2024-08-14 01:23
You can drop `regex( )` in this case and write just `show " ": ...` instead.

Although I thought prepending sym.zws to " " would be redundant, but... maybe not here?

**Comment by mattharrison** [comment] 2024-08-14 01:29
Hence, I filed the bug. I have a space in the code text, and it isn't breaking consistently there.

**Comment by PgBiel** [comment] 2024-08-14 01:33
I think we can reopen but addressing specifically that then.

**Comment by mattharrison** [comment] 2024-08-14 02:03
That would be awesome. 👍

**Comment by Enivex** [comment] 2024-08-14 10:08
Have you verified that this is still broken on main? There was a similar issue that was closed.

**Comment by git001** [comment] 2024-08-14 10:35
@LaurenzV  Any plans to release a new Version?

**Comment by Enivex** [comment] 2024-08-14 11:22
> @LaurenzV Any plans to release a new Version?

Are you lost?

**Comment by laurmaedje** [comment] 2024-08-15 12:36
Doesn't seem to be specific to raw. I'm not sure why the Unicode linebreaking algorithm is doing here:
```typ
#block(width: 4cm, fill: aqua, "abcdefghijklm( whyistherenobreakpointbeforethis)")
```

**Comment by khaledhosny** [comment] 2024-08-15 13:30
It seems that Unicode line breaking algorithm does not consider space after open parenthesis as a line break opportunity. Space after closing parenthesis is considered a break opportunity. At least according to the implementation here:
https://util.unicode.org/UnicodeJsps/breaks.jsp

**Comment by Enivex** [comment] 2024-08-15 13:59
I guess that's reasonable for actual body text, but it's a different question for raw I think
