### ISSUE TITLE
Outline entry body should never contain lazy content

### ISSUE THREAD

**Issue by N3xed** [typst/typst#2356] opened 2023-10-10 23:19 UTC
### Description

I want to the numbering of a figure to depend on the current top level heading. This is possible with the following code:
```typst
#set figure(numbering: (a) => {
    locate(loc => {
        let c = counter(heading).at(loc).first()
        numbering("1.1", c, a)
    })
})
```

The problem is, that in the outline, since the content returned from the lambda is lazy, the locate will be evaluated again at the outline location and result in a different figure number. This makes it impossible to use any global state (e.g. `state`, `counter`, some queries, ...). Also note that the same effect occurs when referencing labeled figures.

As an alternative, it could be made possible to set multiple levels of the `figure` counter. I think currently, the level of the figure counter that is incremented on a new figure is fixed to level 1. In my view, it makes much more sense that only the biggest level is incremented on a new figure. This would make the following possible:

```typst
#set heading(numbering: (..nums) => {
    if nums.pos().len() == 1 {
        let c = nums.pos().first()
        counter(figure.where(kind: image)).update((c, 0))
        counter(figure.where(kind: table)).update((c, 0))
    }
    numbering("1.1", ..nums)
})
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-10-11 08:57
Duplicate of https://github.com/typst/typst/issues/1057

**Closed by laurmaedje** 2023-10-11 08:57 UTC
Labels: bug
