### ISSUE TITLE
Feature request: `get` or similar complement to `set`

### ISSUE THREAD

**Issue by ntjess** [typst/typst#1882] opened 2023-08-08 00:04 UTC
### Description

It would be wonderful if we could `get` elemental defaults that were `set` in a parent scope. As it stands, is there any way to e.g. determine a page's margins?

It would be also helpful to call `header.get("numbering')`, `rect.get("stroke.paint")`, etc.

### Use Case

I'm putting together a package that adds margin notes, and it would be great to simply say 
```typst
let note-width = page.get("margin.left") * 90%
```

Or whatever syntax is preferrable.

**Comment by PgBiel** [comment] 2023-08-08 04:46
Duplicate of https://github.com/typst/typst/issues/763

**Comment by LaurenzV** [comment] 2023-08-08 07:07
As mentioned above, there already is an issue that tracks that, feel free to share any other ideas for that feature there!

**Closed by LaurenzV** 2023-08-08 07:07 UTC
Labels: duplicate, feature request, scripting, styling

**Comment by ntjess** [comment] 2023-08-08 10:50
Oops, sorry about that. Not sure what I searched that missed this initially 👍
