### ISSUE TITLE
The compiler seems to have encountered infinite recursion

### ISSUE THREAD

**Issue by Junyi-99** [typst/typst#2560] opened 2023-11-02 07:08 UTC
### Description

It's easy to reproduce:

<img width="401" alt="image" src="https://github.com/typst/typst/assets/14367694/0bc55964-7bba-40a0-85ab-4dc8004409d7">

```typst
#show "XXX" : text(red)[XXX]

The project has XXX main contributions:
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by istudyatuni** [comment] 2023-11-02 07:17
#229

**Comment by LaurenzV** [comment] 2023-11-02 07:20
As mentioned, there already exists an issue for that. Duplicate of #229.

**Closed by LaurenzV** 2023-11-02 07:20 UTC
Labels: bug, duplicate
