### ISSUE TITLE
Better kerning in math mode

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#880] opened 2023-04-18 23:12 UTC
Code: 
```
$L_2^(-1)[0 .. 1]$
```
Result:
![image](https://user-images.githubusercontent.com/71727937/232924055-9305c46a-856a-47fc-a247-54390916f137.png)

[Keming](https://www.reddit.com/r/keming/wiki/index/)--too much space after the dot.

**Comment by ParadaCarleton** [comment] 2023-04-19 03:45
Another example:
```
$lambda, W, L$
```
![image](https://user-images.githubusercontent.com/71727937/232961650-8987d4a4-5906-484a-84f8-9020e5b38039.png)

**Comment by Enivex** [comment] 2023-04-19 11:43
> Another example; here, the comma is too far separated W:
> 
> ```
> $lambda, W, L$
> ```
> 
> ![image](https://user-images.githubusercontent.com/71727937/232961650-8987d4a4-5906-484a-84f8-9020e5b38039.png)

It looks the same in LaTeX. What you actually want is `$\lambda$, $W$, $L$`, because punctuation should ideally be in text mode and not math. This is what LuaLaTeX with unicode math gives me
![image](https://user-images.githubusercontent.com/2191754/233063834-129099ad-3a74-486f-ad5e-a01c21261a8c.png)
for those two alternatives. The bottom one obviously looks much nicer.

However in typst `$\lambda$, $W$, $L$` has the same spacing problem as `$\lambda, W, L$`.

**Comment by damaxwell** [comment] 2023-08-05 01:02
So, I dug into this a bit.  Here's the test file:

```
\documentclass[12pt]{article}
\usepackage{unicode-math}
\begin{document}

\noindent $W, L$\\
$W$, $L$\\
$W$F

\end{document}
```

Using xelatex:
<img width="263" alt="image" src="https://github.com/typst/typst/assets/918465/d8cf3bb8-9897-41d6-83e0-97e3b62b2306">
  
Omit the unicode math part and using pdflatex:
<img width="263" alt="image" src="https://github.com/typst/typst/assets/918465/51b8f74c-66f0-48d9-9cc8-075d0ceee6f8">

Back to unicode math, now with lualatex:
<img width="263" alt="image" src="https://github.com/typst/typst/assets/918465/1c897323-188c-47c2-89bf-352703e9369b">

Oh, and Typst:

<img width="263" alt="image" src="https://github.com/typst/typst/assets/918465/44eafb14-9dc9-4bbe-b732-9e0505b92c43">

Observations:
1. Typst and xetex are the same.
2. pdflatex omits the italic correction for W before the punctuation, which looks good.  It's an outlier, and I need to look into why that happens.  Keep in mind, it's using a different font, though.
3. All of xelatex, pdflatex and Typst include the italic correction at the end of the math.
4. lualatex omits the italic correction at the end of a math block.  It gets better spacing for the comma, but allows collisions .

It's hard to say that Typst's current behavior with keeping the italic correction with the math block is a bug when it agrees with standard tex variants, and that lualatex gets the win at the cost of something else.  It's then a design choice, which needs to be made (should we keep the italic correction and call this not a bug, drop the italic correction as a feature and take on the (limited) risk of collisions as in lualatex, or try to do something even smarter than the TeX flavors (in which case I would label this a feature request, not a bug).

The failure to kern the comma in math mode for all three engines using the unicode math font is suspicious and makes me wonder if that's not a bug but a font limitation.  I'll look into why pdflatex is getting the win here.

**Comment by damaxwell** [comment] 2023-08-06 06:29
Here's the scoop. New Computer Modern Math and its predecessor Latin Modern have no kerning information.  The GPOS table is empty.  The MATH table in an opentype math font can have a kerning table, but it's this funny cut-in table for the four corners of a glyph to optimize sub/super script placement.  Regardless, it's AWOL in both of these fonts.  

By contrast, the original TeX Computer Modern Math Italic font has a few kerns listed in its TFM file. Most are punctuation (comma, period following a character) but also some design choices (d kerns tightly to f because of differential notation presumably). This information seems to be lost in the transition to  OTF.  I posted on [tex stackexchange](https://tex.stackexchange.com/questions/692788/opentype-math-font-kern)  to try to confirm this; the answers weren't definitive, but there seems to be an impression that OTF doesn't support kerning and math.  Instead, in contex, e.g., you can manually specify kerning pairs if you want.  I wrote to one of the original designers of Latin Modern to try to get a definitive answer.  Regardless of what I hear back, the font files have zero kerning information in them (not GSUB, not MATH).

Given that #1855 dealt with the original issue above, I think we have two options:
1) We observe that Typst give the same output as XeTeX (has italic correction at the end of math, leads to poorly spaced comma, but never collision with a following upright). It also gives the same output as  LaTeX , except that it doesn't kern within math because the kerns aren't in the font.  So, if we're happy with this behavior, we close this issue.
2) Decide that the LuaLaTeX policy of omitting the italic correction is better.  This is different from TeX and can sometimes leads to collisions.  But it has merits.  If we want this, we leave this issue open and close it once this new italic correction policy has been merged from a PR.

Either way, we should open a feature request issue that there should be some mechanism for a person to specify pairwise kerns for a math font if they really want them.

**Comment by Trebor-Huang** [comment] 2023-11-02 08:39
For the record, I noticed that `overline(V)_alpha` leads to bad kerning, as opposed to `V_alpha`.

**Comment by pca006132** [comment] 2023-11-24 09:31
It would also be nice if "a', b" can have better kerning. `f_(b', b) wide f_(b'#h(-0.2em), b)`
![image](https://github.com/typst/typst/assets/12198657/98d17a4b-52b8-4469-a9ec-0c39507bcb33)

I wanted to try to use selector to select "',", but it does not work. Manually writing the negative space everywhere is just too tedious and hurts readability...

**Comment by Enivex** [comment] 2024-06-24 13:29
> Another one: too much space before the last `A` in
> 
> ```typst
> $ A (X_i - overline(X))(X_i - overline(X))^T A^T $
> ```
> 
> ![image](https://github.com/typst/typst/assets/2412819/b7fb4bfe-23df-49b6-8d61-308d0e65cc41)
> 
> LaTeX also puts too much space but it looks better, maybe by virtue of having the first `T` lower (which also looks better I think independently of the kerning issue):
> ![image](https://github.com/typst/typst/assets/2412819/fbca8fd2-c01a-4e15-8703-4445ed3f69e0)

This would only be a like for like comparison if you also used scaling delimiters in LaTeX

**Comment by knuesel** [comment] 2024-06-24 14:11
Ah right! The Latex version with scaling delimiters:

![image](https://github.com/typst/typst/assets/2412819/1d1289a4-e68b-41d9-8b49-995e6adfd18b)

And typst wihtout scaling delimiters:

![image](https://github.com/typst/typst/assets/2412819/e328aaa0-3f25-4e70-8101-783409a89c61)

so Latex is no better actually, maybe even a bit worse

**Comment by Enivex** [comment] 2024-10-23 20:42
The issue in the original post, and the one posted by @Trebor-Huang have both been solved. The rest are a combination of several things (font issues, personal preferences), and aren't necessarily directly actionable. I think it would be better if new issues were opened for more specific things.

**Closed by Enivex** 2024-10-23 20:42 UTC
Labels: feature request, math, waiting-on-design
