### ISSUE TITLE
Web app: Insufficient permissions to upload files in shared project

### ISSUE THREAD

**Issue by pothos-dev** [typst/typst#860] opened 2023-04-17 19:24 UTC
Hi, I have created a project in the https://typst.app and shared it with my colleague via the Share link (read + write).

They are able to change the text of the project, but cannot upload files. If they try, they are shown this error message:
```
Cannot upload file {filename}: You do not have sufficient permissions to access this project.
```

However, I am unable to find any settings to give them this permissions. Is this a bug or am I just too blind to find the setting? :)

**Comment by reknih** [comment] 2023-04-19 14:40
I just tried and was not able to reproduce the issue. You can check and reassign the permissions of project members by clicking the share button. Did your colleague use the project with or without an account?

**Comment by laurmaedje** [comment] 2023-05-22 09:48
Closing due to inactivity.

**Closed by laurmaedje** 2023-05-22 09:48 UTC
Labels: bug, web app
