### ISSUE TITLE
Citations in Captions messes with the ordering

### ISSUE THREAD

**Issue by julianmueller** [typst/typst#3994] opened 2024-04-24 10:45 UTC
### Description

I think I discovered some unwanted behaviour... 

I have citations in my file, which get correctly ordered by appearance in the bibliography. But I also sometimes need to use a reference in the caption of a figure (as I did not create it, but rather copy it and reference to it). By doing this, the "reference marker" ([x]) is also displayed in my list of figures, which is at the start of the document. Therefore the first appearance of the citation is before all the others, marking it as "[1]", even though the actual figure is way after all the other citations.

### Use Case

I'd prefer, if there was an option to "sanitize" the caption text, that gets put into the outlines, so that the citation order is consistent to the actual appearance order in the main document body:

```typst
#outline(target: figure.where(kind: image), sanitize: true)
```

which results in:

> **This** is _a very nice_ caption, originally by @Einstein1900
> This is a very nice caption, originally by Einstein

This could also be used to get rid of other formatting, such as strong, emphasis etc, that is rendered in the actual caption, but ommited in the outline.

**Comment by laurmaedje** [comment] 2024-04-29 10:07
Duplicate of https://github.com/typst/typst/issues/1880. See [here](https://github.com/typst/typst/issues/1295#issuecomment-1853762154) for a way to have short captions right now.

**Closed by laurmaedje** 2024-04-29 10:07 UTC
Labels: feature request
