### ISSUE TITLE
No anti-aliasing option for images

### ISSUE THREAD

**Issue by aziis98** [typst/typst#4567] opened 2024-07-16 21:31 UTC
### Description

Currently there isn't any option to change the anti-aliasing/sampling of displayed images. I'm trying to display some very small images (9x9 pixels) and they look blurry when I make them larger

![image](https://github.com/user-attachments/assets/ff2db6c0-fbcc-4132-9bd0-6e8f05c6a583)

### Use Case

When displaying some very small images at reasonable size or for pixel-perfect image display

**Comment by Enivex** [comment] 2024-07-16 21:36
This is essentially a duplicate of https://github.com/typst/typst/issues/1400 (though they want to force the opposite)

In the meantime you'd be better off using vector graphics for this.

**Closed** 2024-07-16 21:36 UTC
Labels: feature request
