### ISSUE TITLE
Inconsistent spacing with underbrace

### ISSUE THREAD

**Issue by knuesel** [typst/typst#5334] opened 2024-10-30 08:27 UTC
### Description

```typ
#grid(
  columns: 2,
  gutter: 1em,
  $norm(a) cos(b)$,
  $norm(a) cos(b + c)$,
  $norm(a) underbrace(cos(b), x)$,
  $norm(a) underbrace(cos(b + c), x)$,
)
```

gives

![image](https://github.com/user-attachments/assets/9aabc7ab-1331-4cf6-b458-ae422c49c83d)

The case on the left might make sense (I guess the extra space comes from the nearest brace size being a bit larger than the content).

The case on the right however just looks wrong?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by mkorje** [comment] 2024-10-30 11:26
This is a duplicate of #1022.

This is because the spacing information is lost when it gets wrapped in the `underbrace` function. It has been fixed for some functions, but not all. See the linked issue.

**Closed** 2024-10-30 11:33 UTC
Labels: bug
