### ISSUE TITLE
Wrong spacing in recursive heading show rule

### ISSUE THREAD

**Issue by Jacques-z** [typst/typst#2932] opened 2023-12-13 01:08 UTC
### Description

```typst
#let chiline() = {v(-3pt); line(length: 100%); v(-5pt)}
= first
#chiline()

#[
= second
#chiline()
]

#show heading: h => [
  #h 
  #chiline()
]

= third
```
I expexted them rendered identically, but it turned out that the third line is far away from the heading.
I believe that this is a bug, not an intended behaviour of `show` rule.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Jacques-z** [comment] 2023-12-14 12:37
I think this one reveals the real reason:
**The style is inherited**
```typst
= first
hi

#show heading: h => text{
  h 
  [hi]
}

= third
```

That makes sense. 
So
- The title of this issue needs to be changed, but I have no idea
- Are there any method like resetting the style to `text`, or copying the style of outer `text`?

**Comment by laurmaedje** [comment] 2023-12-14 13:17
The `text` in your previous example makes it invalid syntax. The `text` is also unnecessary in the original example.

**Comment by Jacques-z** [comment] 2023-12-14 13:40
Sorry for that! I simplified it without compiling TAT
Corrected them both.

**Comment by laurmaedje** [comment] 2024-02-02 11:38
The reason for this happening is that headings have a built-in styling that reduces spacing below them, as can be seen below:

```typ
= A
b

a

b
```
The spacing between a and b is less than that between c and d:
![Bildschirmfoto 2024-02-02 um 12 31 58](https://github.com/typst/typst/assets/17899797/d4c7cb74-3a79-4556-bbe1-09843ebc048a)

This reduced spacing only applies around the full heading though. Within the heading, and that's what happens in your example, the relevant spacing is between the heading's _body text_ and a line. This spacing is not affected. The solution to override all these built-in spacing is to use _weak_ vertical spacing, which eats up the other automatic spacing. Using this, I would write your example like this:

```typ
#show heading: it => {
  it
  v(5pt, weak: true)
  line(length: 100%)
}

= Heading
Hello
```

That way, the spacing below the heading is respected (and reduced) as usual, but now related to the line.

While things are a bit confusing in this example, they are consistent and generally working as intended, so I'm gonna go ahead and close this.

**Closed by laurmaedje** 2024-02-02 11:38 UTC
Labels: bug, styling
