### ISSUE TITLE
Unexpected behavior of setting page numbering style

### ISSUE THREAD

**Issue by crimestop** [typst/typst#4363] opened 2024-06-10 05:48 UTC
### Description

To my knowledge, if I set the numbering style of a page, a weak page break will be triggered, and the new numbering style will be valid in the new page. However, if we update the page counter in between a page-break and a setting-page-numbering-style command, something weird might happen. 
The example code is
```
#set page(height: 100pt)
#set page(numbering: "i")
#lorem(100)
#pagebreak()
#counter(page).update(1)
#set page(numbering: "1")
#lorem(100)
#pagebreak()
#lorem(100)
```
The rendered pdf is 
<img width="583" alt="image" src="https://github.com/typst/typst/assets/29431901/1b665833-d5cc-449a-b89c-f622aa5f2e90">

The new numbering style seems only valid after the next page break. Is this a feature or a bug or an undefined behavior?
BTW, it seems all right if we switch the 5th and the 6th line.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by HeMuling** [comment] 2024-07-01 18:01
try this:
```
#set page(
  footer: context [
    #set align(center)
    #set text(FooterSize)
    #counter(page).display("i")
  ]
)
```
and a few pages later, do:
```
#set page(
  footer: context [
    #set align(center)
    #set text(FooterSize)
    #counter(page).display(n => n - 4)
  ]
)
```
where `4` is the number of previous pages that you use a different style, so that it begins with 1

**Comment by HeMuling** [comment] 2024-07-01 18:31
however I noticed that, the approach mentioned above will not change the page number in outline, there for I propose the method below:

```
#set page(numbering: (..numbers) => {
  return numbering("i", numbers.pos().at(0) - 1)
})
```
where the `-1` is used when you want to set the second page as your 'i', considering the cover page.

and then:
```
#set page(numbering: (..numbers) => {
  return numbers.pos().at(0) - 4
})
```
where `-4` is the pages number where you use a different style, and this method works grate for outline:

<img width="591" alt="image" src="https://github.com/typst/typst/assets/74801533/b9409c2d-528e-4754-93c8-4a69d99c8c5c">

**Comment by laurmaedje** [comment] 2024-08-22 13:24
Duplicate of #2987

**Closed by laurmaedje** 2024-08-22 13:24 UTC
Labels: bug, styling
