### ISSUE TITLE
`#align` broken when using inline math inside math environment

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#1608] opened 2023-06-28 17:48 UTC
### Description

![image](https://github.com/typst/typst/assets/71727937/afa886e1-4c0b-436b-8c86-53c2417dc415)
Code:
```
Dividing this by $A(t)$, we get the average time spent by a customer in the system up to time $t$:
$
W(t) = (integral_0^t L(s) dd(s)) / A(t)  \


#align(left)[
Now consider a busy period, which starts when an arrival occurs to an empty system and ends when the system becomes empty again. Let $T$ be the length of a busy period, and
]  \

integral_0^T L(s) dd(s) = W(T) N
$
```
Replacing `$T$` with just `T` causes the code to behave as expected:
![image](https://github.com/typst/typst/assets/71727937/9a57def6-1001-4985-a961-28e642016285)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-06-28 19:33
Whatever is happening here is certainly not ideal, but from what I can gather here, it would be best to split things up into two display equations instead of putting text into one big equation. Like this:
```
Dividing this by $A(t)$, we get the average time spent by a customer in the system up to time $t$:
$ W(t) = (integral_0^t L(s) dd(s)) / A(t) $

Now consider a busy period, which starts when an arrival occurs to an empty system and ends when the system becomes empty again. Let T be the length of a busy period, and
$ integral_0^T L(s) dd(s) = W(T) N $
```

**Comment by ParadaCarleton** [comment] 2023-06-28 22:08
> Whatever is happening here is certainly not ideal, but from what I can gather here, it would be best to split things up into two display equations instead of putting text into one big equation. Like this:

See #1079 for what I'm trying to do in general.

**Comment by damaxwell** [comment] 2023-08-05 01:31
The odd behavior here was caused by math mode passing the giant text object in the `align` off to the standard formatter with a paragraph width equal to the document's paragraph width. When the T isn't in math, then you get lucky: the paragraph fits, but just by chance.  Once the T is put into math mode, there are now three objects in a line: a large blob of text, a single math character, and a medium blob of text.  The blobs of text are typeset as paragraphs each of the width of the document paragraph, and then set together left-to-right with their baselines aligned.

It's not reasonable to be doing paragraph width layout of text in math mode, precisely because you don't know where the chunk of text will land.  In one of my PR's last month (not sure which one), I saw this odd behavior and changed the text layout to be infinitely long; this was documented in the PR notes.  Now Typst gives:

<img width="1055" alt="image" src="https://github.com/typst/typst/assets/918465/9476f4a5-1070-4302-8377-2455dc659334">

Change the T from math to not and there is no change in the layout aside from the T.  Unless there is a better idea about what to do about laying out giant blocks of text in math mode, I'd be inclined to call this now "works as advertised" and close the issue.

**Closed** 2023-08-05 09:28 UTC
Labels: bug, layout, math
