### ISSUE TITLE
Repeated usage of prose citation results in full author string.

### ISSUE THREAD

**Issue by mainrs** [typst/typst#4111] opened 2024-05-10 11:43 UTC
### Description

Using the prose option twice results in the second usage using the full author name list. This is definitely not what I would have expected `typst` to generate. I was expecting the same as in the first usage.

### Reproduction URL

https://typst.app/project/r2o9pcR1HpNDXU4PcM6Nve

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-05-10 14:11
Duplicate of https://github.com/typst/typst/issues/3699

**Closed by Enivex** 2024-05-10 14:11 UTC
Labels: bug
