### ISSUE TITLE
Configurable layout iteration maximum (as debugging tool)

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#4694] opened 2024-08-06 14:25 UTC
### Description

Manually limiting the layout iteration count could be beneficially used as a debugging tool to look at the state of the document in the first, second, third iteration etc. 

In line with the current limit of 5 iterations, the iteration maximum could take values between (and including) 1 and 5. 

The feature could be added in form of a CLI argument under the name `max-layout-iterations` or similar. For debugging purposes, it would of course be more direct to be able to change this setting right in the document, but I can also see some reasons against that. 

### Use Case

This rather simple feature would prove especially useful for package authors in order to optimize more complex rules.

**Comment by Enivex** [comment] 2024-08-06 14:45
I'll consider this a duplicate of https://github.com/typst/typst/issues/4528

You can obviously add your thoughts there

**Closed** 2024-08-06 14:45 UTC
Labels: feature request
