### ISSUE TITLE
Citation in caption does not work with outline

### ISSUE THREAD

**Issue by thng292** [typst/typst#796] opened 2023-04-14 05:45 UTC
I got this error when trying to use the "@" in figure's caption
```
[12:38:59] compiled with errors

thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 65535', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\elsa-1.8.0\src\vec.rs:231:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The code
```
#figure(
    image("asset\minimax_tree.png", width: 80%),
    caption: [Minimax tree @Minimax]
)
```

I have tried to use "#cite", but it said
```
[12:42:00] compiled with errors

error: bibliography does not contain this key
    ┌─ Seminar_Report.typ:864:28
    │
    │     caption: [Minimax tree #cite("Minimax")]
    │       
```

The code `#cite("Minimax")` still work out side of the caption

I'm using the 23/04/11 release

**Comment by PgBiel** [comment] 2023-04-14 05:51
I can't seem to be able to reproduce; can you share a minimal working example? Thanks.

**Comment by thng292** [comment] 2023-04-14 06:02
This happend when I try to make an outline `outline`
```
#outline(target: figure.where(kind: image))

#figure(
    image("HCMUS_Logo.png"),
    caption: [HCMUS Logo @Minimax],
)
#bibliography("ReportBib.yml")
```
Sorry for my mistake

**Comment by leo848** [comment] 2023-04-14 17:08
Minimal repro:

File `doc.typ`
```
#outline()
= Heading @name
#bibliography("bib.bib")
```

File `bib.bib`
```
@misc{name,}
```

--- 

Now, run `typst doc.typ`

Expected output: nothing, compiles properly into `doc.pdf`

Actual output: 

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 65535', /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/elsa-1.8.0/src/vec.rs:231:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PgBiel** [comment] 2023-04-15 02:15
Upon doing some debugging, it seems that it is erroring due to an invalid span attached to an error produced by `CiteElem::show`:

https://github.com/typst/typst/blob/1e948f7fa29395cfc2bd704bfdbe6019229ba500/library/src/meta/bibliography.rs#L351-L352

**Comment by PgBiel** [comment] 2023-04-15 03:14
Alright, found the culprit:
https://github.com/typst/typst/blob/1e948f7fa29395cfc2bd704bfdbe6019229ba500/library/src/meta/reference.rs#L162

The span isn't being properly set here

**Comment by PgBiel** [comment] 2023-04-15 03:40
So, fixing that will prevent the compiler from crashing, but the unexpected error will still happen - it seems to be related to the inner workings of `query` and `location`. Still, the error is definitely better than the (unhelpful) compiler error.

**Comment by vangola-silver** [comment] 2023-05-21 10:21
Are there any workarounds know for this issue?

**Comment by laurmaedje** [comment] 2023-05-22 09:53
Closing in favor #785, which has the same underlying problem.

**Closed by laurmaedje** 2023-05-22 09:53 UTC
Labels: bug, meta
