### ISSUE TITLE
Single and double smartquotes clash when placed together

### ISSUE THREAD

**Issue by mizukarada** [typst/typst#1541] opened 2023-06-21 02:22 UTC
### Description

Single and double smartquotes clash when placed together.

### Reproduction
```typst
"'test' statement"
```

Preview:
I circled the bugs.

<img width="421" alt="Untitled" src="https://github.com/typst/typst/assets/111034657/fc43bb8a-76c9-4b81-81d1-3fe90f100546">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment] 2023-06-21 05:02
Duplicate of #1379.

**Closed** 2023-06-21 07:10 UTC
Labels: bug
