### ISSUE TITLE
Improve typesetting for mathematics in French

### ISSUE THREAD

**Issue by vsannier** [typst/typst#5285] opened 2024-10-23 19:46 UTC
### Description

According to French typographic conventions, the symbols ≤ and ≥ must be slanted and all capital letters must be capitalized (not just Greek letters as is currently the case). I propose that the following rules be applied when the language of the text is French.

```
#show sym.lt.eq: sym.lt.eq.slant
#show sym.gt.eq: sym.gt.eq.slant

#show math.equation: it => {
  show regex(`\b[A-Z]\b`.text): math.upright
  it
}
```

### Use Case

It would allow people who don't know the details of French conventions to still write documents that satisfy them.

**Comment by MDLC01** [comment] 2024-10-23 20:11
To be honest, as a French person, I think I only see ≤ and ≥ in French documents. I also don't think I ever saw capital Latin letters being typeset upright.
Where do those conventions come from? Are you sure this isn't just outdated conventions dating back to before everyone used LaTeX, and therefore the same conventions as what is the default in LaTeX.

**Comment by Enivex** [comment] 2024-10-23 20:25
Like other times this has come up, the conventions are rarely as simple as "French uses this" or "German uses this". It can vary between field and personal preference.

**Comment by Enivex** [comment] 2024-10-23 20:27
In any case, this is a duplicate of https://github.com/typst/typst/issues/3238

**Closed by Enivex** 2024-10-23 20:27 UTC
Labels: feature request

**Comment by vsannier** [comment] 2024-10-23 20:34
@MDLC01 You may find more information here:

* [frenchmath – Typesetting mathematics according to French rules](https://ctan.org/pkg/frenchmath?lang=en) on the Comprehensive TeX Archive Network (CTAN),
* [Kp-Fonts](https://ctan.mines-albi.fr/fonts/kpfonts/doc/kpfonts.pdf) on the CTAN, see in particular its `frenchstyle` option,
* [Règles françaises de typographie mathématique](http://sgalex.free.fr/typo-maths_fr.pdf) by Alexandre André,
* [Composition des textes scientifiques](https://euler.ac-versailles.fr/IMG/pdf/typo2.pdf),
* a few questions on the TeX Stack Exchange [159973](https://tex.stackexchange.com/questions/159973/french-math-style-with-default-font), [617040](https://tex.stackexchange.com/questions/617040/how-to-make-uppercase-roman-letters-upright-in-context) (with the `french` tag), [4155](https://tex.stackexchange.com/questions/4155/can-i-make-all-my-math-upright), [251225](https://tex.stackexchange.com/questions/251225/how-to-make-all-roman-capital-letters-as-mathroman-inside-math-environments) (with French being discussed in the comments of the accepted answer).

These conventions are also respected in the books I have on hand (_Fonctions d'une variable réelle_ (2007) and _Topologie algébrique_ (2016) by Nicolas Bourbaki).

@Enivex I'm not saying ‘French use this’, but merely that these conventions are widely observed by publishers such as Hermann and Springer and are recommended by all the mathematical typography guides I've looked up.

**Comment by MDLC01** [comment] 2024-10-25 07:15
Thanks for those references! I'll take a look at them.
