### ISSUE TITLE
Bold function cannot enter new line and breaks if the sentence is too long

### ISSUE THREAD

**Issue by s-suraj-08** [typst/typst#2875] opened 2023-12-05 11:43 UTC
### Description

The math bold function does not perform wrap around of a sentence. It cuts the sentence short and fails to display if the sentence is bigger than one line

### Reproduction URL

https://typst.app/project/wx9qZ5S2q5tS3_LmR2Guht

### Browsers

Chrome

### OS

Windows

**Comment by Enivex** [comment] 2023-12-06 09:39
Duplicate of https://github.com/typst/typst/issues/826

**Closed** 2023-12-06 09:39 UTC
Labels: feature request, math
