### ISSUE TITLE
Lexer: Ignore first and last newline in content blocks [ ]

### ISSUE THREAD

**Issue by jgpr-code** [typst/typst#3946] opened 2024-04-17 06:35 UTC
### Description

When creating long content blocks it is common that they start with `[\n`. Currently the lexer will replace this first `\n` just like all other `\n` as a space. The same is true for the last `\n <indent> ]` for the ending of a content block.

Basically, I don't want to be forced to put `[` and `]` on the same lines as my actual content to avoid those additional spaces.

Maybe this can be changed/fixed by a small change to the `Lexer::markup` function such that `[\n => SyntaxKind::LeftBracket` and `\n <whitespace of spaces and/or tabs> ] => SyntaxKind::RightBracket`

### Use Case

My use case can be described with following example:
```typ
#let echo(body) = [#body] // a dummy function
!#echo[
  Very long content
  that goes over
  multiple lines
]!
```
will result in `! Very long content that goes over multiple lines !`
However
```typ
#let echo(body) = [#body] // a dummy function
!#echo[Very long content
  that goes over
  multiple lines]!
```
while looking a lot more ugly from a formatting perspective it will produce `!Very long content that goes over multiple lines!` without the spaces at the beginning and the end

**Comment by wrzian** [comment] 2024-04-18 04:14
This isn't too hard to implement, although should not be done by the lexer. The location is `typst-syntax/parser.rs::content_block`, and it would look something like:
```rust
// after we eat the opening bracket
while p.current().is_trivia() { p.eat(); }
// trivia is a name for whitespace and comment tokens.
```
Note: this code is almost certainly wrong in some small way --  and it doesn't handle the closing bracket space -- but matches the general idea.

I only added the code above for the start of content blocks and this changed a number of tests. It seems the main usage of whitespace in content blocks is as part of a separator for a joining element. Below are some examples of what was affected.

If we restricted the removal of beginning/ending spaces to require at least one newline among the spaces, that would solve your use case while still allowing `#[ ]`, etc. to act as a space for joining content. Only the `emph-syntax` test would still be affected.

However, it would also be inconsistent, since if you added *more* spacing by typing a newline in your separator, you would end up with *fewer* spaces (none) in the final content. Maybe spaces without anything else could coalesce to act as just one space, but then if you added actual content, you would also remove that spacing. It's tricky.

```typ
--- array-join-content ---
// Test joining content.
#([One], [Two], [Three]).join([, ], last: [ and ]).

--- figure-caption-separator ---
// Test custom separator for figure caption
#set figure.caption(separator: [ --- ])

#figure(
  table(columns: 2)[a][b],
  caption: [The table with custom separator.],
)

--- numbering-symbol-and-roman ---
#for i in range(0, 9) {
  numbering("*", i)
  [ and ]
  numbering("I.a", i, i)
  [ for #i \ ]
}

--- emph-syntax ---
// (irrelevant sections removed)
// Can contain paragraph in nested content block.
_Still #[

] emphasized._

--- code-block-basic-syntax ---

// Evaluates to join of none, [My ] and the two loop bodies.
#{
  let parts = ("my fri", "end.")
  [Hello, ]
  for s in parts [#s]
}

// Evaluates to join of the content and strings.
#{
  [How]
  if true {
    " are"
  }
  [ ]
  if false [Nope]
  [you] + "?"
}

--- text-font-just-a-space ---
// Test that a run consisting only of whitespace isn't trimmed.
A#text(font: "IBM Plex Serif")[ ]B
```
(from a number of files in the test suite)

I'm personally leaning slightly against this, although I do see the frustration. I mostly just got [nerd-sniped](https://xkcd.com/356/) into seeing if it was that easy to change in the lexer.

**Comment by bluebear94** [comment] 2024-04-28 20:50
We could alternatively provide a way to suppress trailing spaces until the next non-space character as with (La)TeX’s `%`; this would at least only be needed in content blocks like these since Typst code isn’t whitespace-sensitive.

**Comment by laurmaedje** [comment] 2024-07-15 18:44
Duplicate of https://github.com/typst/typst/issues/1382, see the discussion there.

**Closed by laurmaedje** 2024-07-15 18:44 UTC
Labels: syntax, proposal

**Comment by memeplex** [comment] 2024-08-07 15:00
I'm experiencing a similar issue with a function that produces a slanted fraction. I followed the discussion in #1382. But I still have a question:

```typst
#let foo = [bar//
]

#foo.
```

will render "bar ." not "bar."

Why isn't the newline ignored after a comment?

**Comment by laurmaedje** [comment] 2024-08-07 15:10
Because the comment ends before the newline. This was intentional because using comments for this always felt like a hack to me in LaTeX.

**Comment by memeplex** [comment] 2024-08-07 15:20
So at least for now the sanctioned solutions are to either format content like:

```typst
#let x = [line 1
  line 2
  line 3]
```

or use:

```typst
#let x = [
  #h(0pt, weak: true)
  line 1
  line 2
  line 3
  #h(0pt, weak: true)
]
```

?

I feel that neither is a great solution for short inline "macros" that want their surrounding space removed.

Commenting out whitespace may be a hack but it's certainly handy.

**Comment by laurmaedje** [comment] 2024-08-07 15:25
What also happens fairly often within whitespace-sensitive stuff like this is that rewriting it in code mode is better. Example:
```typ
[
 #set text(family: "Signature")
 #city, the #date
 #v(20pt)
 #line(to: (4cm, 0pt))
]
```
=>
```typ
#{
 set text(family: "Signature")
 [#city, the #date]
 v(20pt)
 line(to: (4cm, 0pt))
}
```
Obviously doesn't apply always, but this "block flip" pattern is definitely underused.

**Comment by memeplex** [comment] 2024-08-07 15:31
I already agree with your points in this and the other discussion.

It's not a heuristic to remove whitespace what I'm asking for but a more convenient way of explicitly suppressing it.

For example, in jinja2 templates, which manipulates its own kind of "content blocks", there is `{% ... %}` but also `{%- ... %}`, `{% ... -%}` and `{%- ... -%}`.

If you dislike the LaTeX way, perhaps adding a short standard function like `nw` (as in "no whitespace") that simply puts `#h(0pt, weak: true)`  would be enough?

**Comment by laurmaedje** [comment] 2024-08-07 15:48
Note that if really needed you _can_ use block comments instead of line comments.

Pretty ugly, but works:
```typ
#let x = [/*
*/line 1
  line 2
  line 3/*
*/]
```
