### ISSUE TITLE
`measure(" ")` returns zero width

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3606] opened 2024-03-10 15:49 UTC
### Description

```typ
#context measure(" ").width // => 0pt
#context (measure("a b").width - measure("ab").width) // => 2.26pt
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-10 20:49
Duplicate of https://github.com/typst/typst/issues/597

**Closed by laurmaedje** 2024-03-10 20:49 UTC
Labels: bug
