### ISSUE TITLE
rondom generator?

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#1429] opened 2023-06-06 17:27 UTC
### Description

I have a few years back designed a little stamp using LuaLaTeX, with a bit of realism, by way of slightly rotating the box in both directions, make ing the edges just a little smudgy. Then I like to vary the location and rotation of the stamp just a little bit so that it doesn't look printed if you compare two papers.

Is there or will there be a random number generator?

### Use Case

I can of course try and circumvent this with a Makefile, but there might be other uses for a RNG.

**Comment by laurmaedje** [comment] 2023-06-06 20:27
Duplicate of #984 (while that one has a specific design proposal, it is also a suitable place to discuss this feature request in general).

**Closed by laurmaedje** 2023-06-06 20:27 UTC
Labels: feature request

**Comment by ondohotola** [comment] 2023-06-07 05:25
thanks
