### ISSUE TITLE
Support passing template argument by command line argument

### ISSUE THREAD

**Issue by lzm0** [typst/typst#1932] opened 2023-08-14 16:04 UTC
### Description

It would be nice if we could pass arguments to a template through the command line directly instead of importing the template in a separate typst file. Something like this:
```bash
typst --arg "name=John" resume.typ
```

### Use Case

Using a typst template without creating another typst file.

**Comment by laurmaedje** [comment] 2023-08-19 16:19
Duplicate of https://github.com/typst/typst/issues/295

**Closed by laurmaedje** 2023-08-19 16:19 UTC
Labels: feature request, cli
