### ISSUE TITLE
Allow trailing commas in math mode argument lists

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#1078] opened 2023-05-02 23:44 UTC
### Description

It seems like in some cases, passing trailing content blocks in math mode would be useful, especially when a function has a particular argument that could be quite long.

### Use Case

Example of a function in math mode I'd like to pass a trailing content block to:
```
#let integrate(body, respect, over: []) = $integral_#over #body dd(#respect)$

$
integrate(x, RR)[
  pretend there is an extremely long function here that would be awkward to pass as an argument
]
$
```

**Comment by tingerrr** [comment] 2023-10-12 11:11
I believe the issue was renamed incorrectly and is a duplicate of #2366.

**Comment by laurmaedje** [comment] 2023-10-12 11:17
Okay, closing in favor of #2366.

**Closed by laurmaedje** 2023-10-12 11:17 UTC
Labels: feature request, math, syntax
