### ISSUE TITLE
Some unique svg files cannot be compiled to pdf

### ISSUE THREAD

**Issue by Super-wyc** [typst/typst#3898] opened 2024-04-08 11:30 UTC
### Description

As shown in title, the export .svg from this website(https://carbon.now.sh/) will be blank in the compiled PDF.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-04-08 11:33
I suspect the exported SVGs aren't proper SVGs, but thinly veiled websites.

@LaurenzV

**Comment by LaurenzV** [comment] 2024-04-08 11:40
Yeah, the SVG is basically just a `foreignObject`. Try opening it in Inkscape or Adobe Illustrator and you'll see that it doesn't work either, it basically can only be opened with a web browser... So this is basically a duplicate of #1421. @laurmaedje maybe you could rename the other issue to something like "SVGs with `foreignObject` don't render correctly" and then we can close this as a duplicate (I think I cannot rename issues).

**Closed** 2024-04-08 11:50 UTC
Labels: bug, duplicate, svg
