### ISSUE TITLE
Panic (0.11 rc1) "slice index starts at 21 but ends at 1

### ISSUE THREAD

**Issue by JuliDi** [typst/typst#3618] opened 2024-03-11 09:52 UTC
### Description

When I compile my document with v0.11 rc1 instead of v0.10 I now get

```
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\alloc\src\vec\mod.rs:2084:36:
slice index starts at 21 but ends at 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with `RUST_BACKTRACE=full` gives me a stacktrace, but that looks a bit useless to me:
```
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\alloc\src\vec\mod.rs:2084:36:
slice index starts at 21 but ends at 1
stack backtrace:
   0:     0x7ff7f8d73029 - <unknown>
   1:     0x7ff7f8a0069d - <unknown>
   2:     0x7ff7f8d6e551 - <unknown>
   3:     0x7ff7f8d72e5a - <unknown>
   4:     0x7ff7f8d757b9 - <unknown>
   5:     0x7ff7f8d75475 - <unknown>
   6:     0x7ff7f8d75d34 - <unknown>
   7:     0x7ff7f8d75c09 - <unknown>
   8:     0x7ff7f8d73bd9 - <unknown>
   9:     0x7ff7f8d75882 - <unknown>
  10:     0x7ff7f97a4a77 - <unknown>
  11:     0x7ff7f97a5134 - <unknown>
  12:     0x7ff7f93129cb - <unknown>
  13:     0x7ff7f9229b55 - <unknown>
  14:     0x7ff7f933e0c0 - <unknown>
  15:     0x7ff7f939d8b8 - <unknown>
  16:     0x7ff7f9226fca - <unknown>
  17:     0x7ff7f945670a - <unknown>
  18:     0x7ff7f9574a3a - <unknown>
  19:     0x7ff7f9559195 - <unknown>
  20:     0x7ff7f94dadf6 - <unknown>
  21:     0x7ff7f8d67ede - <unknown>
  22:     0x7ff7f95775dc - <unknown>
  23:     0x7ff7f97a1a6c - <unknown>
  24:     0x7fffc12a257d - BaseThreadInitThunk
  25:     0x7fffc28caa58 - RtlUserThreadStart
  ```

Unfortunately, I cannot determine how to reproduce the issue from scratch. When I start deleting sections in my document, the panic just randomly disappears. It can be as little as adding/removing a blank line (i.e., a new paragraph) to "toggle" the error.

I am happy to provide more information and help debugging this if anyone can tell me what information to provide or what to try (I cannot share the entire document, though). I could run a debug build with backtracing later on my private PC if that helps.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-11 10:06
Might be fixed by https://github.com/typst/typst/pull/3607

**Comment by laurmaedje** [comment] 2024-03-11 10:58
#3607 is merged. If you could try again with Typst built from main, that'd be great.

**Comment by laurmaedje** [comment] 2024-03-11 12:03
It is pretty surely that same issue that #3607 intended to fix, so I'll close this. Please reopen if you can still reproduce it!

**Closed by laurmaedje** 2024-03-11 12:03 UTC
Labels: bug, crash, urgent

**Comment by JuliDi** [comment] 2024-03-11 13:03
I will give it a shot tonight. Thanks for the help!

**Comment by JuliDi** [comment] 2024-03-11 19:55
With the current main branch d01ccffad6470ad49d4e47b5c0884dfd23305961 the bug is fixed 🎉
