### ISSUE TITLE
Better font detection

### ISSUE THREAD

**Issue by ok-nick** [typst/typst#116] opened 2023-03-22 05:31 UTC
`typst` predefines these paths for font detection:
1. `/usr/share/fonts`
2. `/usr/local/share/fonts`
3. `$HOME/.local/share/fonts`

The last one is obtained from the `dirs` crate.

Sometimes fonts are stored in other directories, like on `NixOS`, for example, where fonts are stored in a totally separate directory.  I'm not familiar with font detection, however, I believe the "conventional" way to go about this is by using the `fontconfig` library, as used by `gimp` and many other programs. There are a couple of other Rust alternatives I scoped out but they seem all either unmaintained or immature.

**Comment by hcsch** [comment] 2023-03-22 05:33
Hey, just a heads-up, this is probably a duplicate of #100 ^^

**Comment by ok-nick** [comment] 2023-03-22 07:21
Yep, thanks!

**Closed** 2023-03-22 07:21 UTC
