### ISSUE TITLE
Wrong #include file is read after renaming

### ISSUE THREAD

**Issue by deffi** [typst/typst#2754] opened 2023-11-24 10:21 UTC
### Summary

- `main.typ` includes `a.typ`
- `a.typ` is renamed to `b.typ` and `main.typ` is updated
- The compiler still tries to read `a.typ` and compilation fails

### Details

`main.typ`:
```typst
#include "a.typ"
```

`a.typ`:
```typst
Hello
```

Start `typst watch main.typ`:
```
watching main.typ
writing to main.pdf

[...] compiled successfully in 3.46ms
```

While Typst is still running, rename `a.typ` to `b.typ`. Predictably, compilation fails:
```
error: file not found (searched at /.../a.typ)
  ┌─ main.typ:1:9
  │
1 │ #include "a.typ"
  │          ^^^^^^^
```
Update `main.typ`:
```typst
#include "b.typ"
```

Now, compilation should succeed again. Instead:
```
error: file not found (searched at /.../a.typ)
  ┌─ main.typ:1:9
  │
1 │ #include "b.typ"
  │          ^^^^^^^
```

Note the discrepancy *in the error message*: `#include "b.typ"`, but `searched at /.../a.typ`

When the compiler is re-started without any further file changes, compilation succeeds again.

The same thing happens with `#import` in place of `#include`.

### Version

Typst 0.9.0

Operating system:
- Windows 10
- Ubuntu Linux (WSL on Windows 10)

**Comment by laurmaedje** [comment] 2023-11-24 10:36
Duplicate of https://github.com/typst/typst/issues/2601 most likely. If you can also reproduce this with Typst built from the main branch, that'd be good to know.

**Closed by laurmaedje** 2023-11-24 10:36 UTC
Labels: bug

**Comment by deffi** [comment] 2023-11-24 17:24
I tested it with 2f795b5 on Windows 11 and it seems like the bug has indeed been fixed.
