### ISSUE TITLE
`page.header` & `footer` get bold unexpectedly for empty page with heading

### ISSUE THREAD

**Issue by LingkKang** [typst/typst#4749] opened 2024-08-14 04:46 UTC
### Description

The rendered pdf of following code will have the header in bold:

```typst
#set page(header: [this is header])
= This is heading
```

![image](https://github.com/user-attachments/assets/d97a547e-117f-4f60-bc23-68a204798d21)

This also happens to different level of heading and `page.footer()`.

---

However, if we add some plain text, header / footer will displayed normally.

``` typst
#set page(header: [this is header])
#lorem(10)
= This is heading
```

``` typst
#set page(header: [this is header])
= This is heading
#lorem(10)
```

![image](https://github.com/user-attachments/assets/2bda1dee-eba8-41fc-a44f-f8f42115dd09)

---

`typst` version: `typst 0.11.1 (50115102)`

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-08-14 04:50
Duplicate of https://github.com/typst/typst/issues/241

**Closed** 2024-08-14 04:50 UTC
Labels: bug
