### ISSUE TITLE
`#show figure: set block(breakable: false)` makes `image` inside `figure` smaller than expected (relative)

### ISSUE THREAD

**Issue by FlandiaYingman** [typst/typst#3703] opened 2024-03-17 09:32 UTC
### Description

When `#show figure: set block(breakable: false)` and specifying the image size via percentage, the image becomes smaller than the size expected to be. Though, I am not sure if it is an intended behavior.

(Please check the re-production)

### Reproduction URL

https://typst.app/project/rLPxEuI1ES-XjIUTarxg_c

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-03-22 15:21
Duplicate of https://github.com/typst/typst/issues/728

**Closed by laurmaedje** 2024-03-22 15:21 UTC
Labels: bug, layout

**Comment by FlandiaYingman** [comment] 2024-03-22 15:35
@laurmaedje 
I am not sure but I think this is not a duplicate of #728, because this bug appears only in 0.11.0.

**Comment by laurmaedje** [comment] 2024-03-22 15:57
Your reproduction changes between 0.10 and 0.11 because #351 was fixed. The bug only occurs with `#show figure: set block(breakable: true)` because blocks are only measured (producing the bug in #728) when they are breakable.
