### ISSUE TITLE
Long lines (with no spaces) are not broken (text wrapping issues)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2216] opened 2023-09-23 12:50 UTC
### Description

If a long line has spaces, Typst (v0.8) will break/wrap the line where the spaces are. But if there are no (or not enough) spaces, then this will happen:

````typ
#show raw.where(block: true): set block(stroke: black, inset: 0.3em, radius: 0.4em)

```
Very long lineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
```

Very long lineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
````

![image](https://github.com/typst/typst/assets/37143421/8349f326-3be9-4c1a-807f-55b7d927aa73)

When I used `minted` in LaTeX (with `tcolorbox`) I had this config:

```latex
\usepackage{dingbat} % For minted breakline character (goes before amssymb)
breaksymbolleft=\raisebox{0.8ex}{\small\reflectbox{\carriagereturn}},
breaksymbolright=\small\carriagereturn
```

But it only works with spaces (specific tokens). Instead I can do this to `breakanywhere`:

```latex
\documentclass[a4paper]{article}
\usepackage{minted}
\usepackage{graphicx} % For \reflectbox{}
\usepackage{dingbat} % For minted breakline character (goes before amssymb)
\begin{document}
\begin{minted}[
  breaklines,
  breakanywhere,
  frame=single,
  breakanywheresymbolpre=\small\carriagereturn,
  breakanywheresymbolpost=\raisebox{0.8ex}{\small\reflectbox{\carriagereturn}},
  breaksymbolleft={},
  breaksymbolright={},
]{text}
Very long lineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
\end{minted}

Very long
lineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
\end{document}
```
Which produces this wrapping effect:

![image](https://github.com/typst/typst/assets/37143421/27f9ad1b-91ba-47ed-b9e5-bf52124b1d98)

 Although plain text also can't be broken, but this is probably super rare, since only source code can contain long lines without spaces.

I think something like `#block(break-anywhere: true)` can be added which would either fix only raw text, or both. It would be nice if similar (pre/post, right/left) symbols can be added and be customizable.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-09-23 13:04
Duplicate of https://github.com/typst/typst/issues/674 as this affects plain text and code alike.

**Closed by laurmaedje** 2023-09-23 13:04 UTC
Labels: bug
