### ISSUE TITLE
Incorrect dot color when changing text color in list.

### ISSUE THREAD

**Issue by Ownezx** [typst/typst#5404] opened 2024-11-12 04:13 UTC
### Description

When trying to change color mid list, the color of the dot of the first indent stays in the color of the initial color instead of changing color when a #set text(color) is called.

Expected behaviour : the dot should be the same color as the text following it.

Example :
```typst
#set text(black)
- test 
  - test
#set text(red)
- test
 - test
- test
```
leads to
<img width="150" alt="image" src="https://github.com/user-attachments/assets/bc9e6aa3-0fad-43b7-afa9-083f0e600284">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by wznmickey** [comment] 2024-11-12 20:13
Seems that now a level of list could only one color.

**Comment by Enivex** [comment] 2024-11-13 00:51
Duplicate of https://github.com/typst/typst/issues/619

**Closed by Enivex** 2024-11-13 00:51 UTC
Labels: bug
