### ISSUE TITLE
`show` rules recursively expand and crash

### ISSUE THREAD

**Issue by tnevins-klein** [typst/typst#742] opened 2023-04-12 00:25 UTC
Hi!

While attempting to create a show rule to remove all styles from a page object (except the body), I came across a weird edge case. I had the following setup:
```typst
#show page: p => {
    page(body: p)
}
```
However, when attempting to run this with the latest versions of the Typst web clients and CLI, the process idles until crashing. I suspect this because the `show` rule for page is being on its own result, leading to infinite recursion. 

### Proposal
There isn't to my knowledge, a way to unset a `show` rule, or otherwise refer to the original `page` function. This severely limits the effectiveness of `show` rules, because it means that re-constructing an object of the same type is practically impossible. One possibility is to override the behavior of:
```typst
#show <...>: none
```
to unset the show rules in the current scope (or perhaps more granular control over active `show` rules? perhaps a method to retrieve them?). This line's effect, that the relevant object is not displayed, is already possible, as in:
```typst
#show <...>: o => {}
```
A better solution might be to rearchitect evaluation so that show rules are not evaluated on their own output. I don't fully understand the language architecture, so this may or may not be feasible.

Many thanks.

**Comment by SUPERCILEX** [comment] 2023-04-12 00:47
Duplicate of https://github.com/typst/typst/issues/229. Everyone's running into the same issue lol. :)

**Closed** 2023-04-12 01:28 UTC
