### ISSUE TITLE
Outline will not right-align page number if title exactly fills the line

### ISSUE THREAD

**Issue by reknih** [typst/typst#2464] opened 2023-10-21 18:55 UTC
### Description

The title describes the issue. The page number will instead appear on the left on the next line.

<img width="473" alt="Screenshot" src="https://github.com/typst/typst/assets/3874949/aca28a0c-9bc4-4c4b-9645-3c90345dccd0">

```typ
#set page("a6")
#outline()

= Hello world this is my really long heading that it
```

### Reproduction URL

https://typst.app/project/r2tUo9LGKP4MxM5vEiom_E

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-10-21 21:13
Duplicate of https://github.com/typst/typst/issues/2048

**Closed by laurmaedje** 2023-10-21 21:13 UTC
Labels: bug, layout, meta
