### ISSUE TITLE
No Heading Alone at the end of the page with math equation

### ISSUE THREAD

**Issue by pauladam94** [typst/typst#1724] opened 2023-07-14 21:29 UTC
### Description

No Heading should be alone at the end of the page. It is a default Latex feature, should be also a Typst's one.
When there is text after a heading, I think it works. Even if I think I can find an example with text after the heading that does the same behavior.

However, I put here an example with an equation after a heading. And the heading is alone at the end of the page. If there is a way to fix it (without #pagebreak()) I am interested.

### Smallest example of it
```typst
#set text(size : 15pt)
#outline(title: [])

= Heading
#lorem(250)
= TITLE ALONE AT THE END OF THE PAGE

$ forall x in RR $

== Heading
= Heading
== Heading
== Heading
```

I put this in feature because it is not really a bug because it's just not supported right now.

**Comment by laurmaedje** [comment] 2023-07-17 09:28
Duplicate of https://github.com/typst/typst/issues/1724

**Closed by laurmaedje** 2023-07-17 09:28 UTC
Labels: feature request
