### ISSUE TITLE
Requesting latest stable version in Crates

### ISSUE THREAD

**Issue by legendjaks** [typst/typst#3558] opened 2024-03-06 07:25 UTC
### Description

I am planning a open-source HTTP server that uses `typst` to generate PDF. For that I need the latest `typst` crates, but the `typst` version which is available in [crates](https://crates.io) is 0.1.1.
Kindly publish the latest version.

### Use Case

Users who want to supply the `typst` template via Web API and get the PDF in response.

**Comment by laurmaedje** [comment] 2024-03-06 07:48
Duplicate of #2450. The good news is that we plan to publish the upcoming 0.11 release to crates.io.

**Closed by laurmaedje** 2024-03-06 07:48 UTC
Labels: feature request
