### ISSUE TITLE
Web app slow in mainland China

### ISSUE THREAD

**Issue by tbbbk** [typst/typst#527] opened 2023-04-02 11:59 UTC
It's so slow when use it in China mainland :(

**Comment by imbrem** [comment] 2023-04-02 14:11
Have you tried running the binary locally?

**Comment by im-Kitsch** [comment] 2023-04-03 14:16
> It's so slow when use it in China mainland :(

You should send complain to gov rather software.

**Comment by user202729** [comment] 2023-04-03 16:11
I'm not sure if the webapp runs Rust in browser with Emscripten or something similar, but if it doesn't then the problem seems inevitable whenever your Internet connection is slow.

**Comment by GaugeAndGravity** [comment] 2023-04-03 17:58
Just use VScode locally

**Comment by ondohotola** [comment] 2023-04-22 10:38
You are aware of the Great Firewall (防火长城) right?

[https://en.wikipedia.org/wiki/Great_Firewall](https://en.wikipedia.org/wiki/Great_Firewall)

**Comment by im-Kitsch** [comment] 2023-04-23 13:48
> You are aware of the Great Firewall (防火长城) right

Yes, exactly.

**Comment by im-Kitsch** [comment] 2023-04-23 15:41
> 

I would say again that "you should send complain to gov rather software" and explain why. I don't think it's off-topic. 

**If you say "so slow", at least I think you should compare compling speed of web app with/without a realiable and fast enough VPN.**  Only after that the possibility of the Great Firewall is excluded. We could track if there is other problem relates to this issues. And 99% slowness of accessing out-of-china website is caused by GFW.

As I know, overleaf is also problematic in China, people say that it become offline frequently. But if you open VPN and then it works smoothly. 

Due to censorship in PR China (https://en.wikipedia.org/wiki/Internet_censorship_in_China), (https://en.wikipedia.org/wiki/Great_Firewall), the acces to website out of china is problematic. Websites like google are unaccessible, websites like github is unavaiable frequently. Typst.app couldn't be an "exception".

I would reiterate, no one can avoid the influence of gov censorship policy when people use online service in China, since the censorship is very extreme and strict. Though open-source code is irrelavent to policitcs, polictics hinders your project. As to an extreme example,  which begins from last yest, all "public" repo in gitee(one chinese github) have to be censored, before passing cencsorship, your repo will be changed as "private", so as to ensure there is no content against policy. As I know(I am not sure), if you expect a good experience in China, typst.app should do things like: apply  ICP license(internet content provider license), host your server in China and let your service under monitoring/censorship/management of gov. 

When you can access typst.app in China it's already very "fortunate".   "404 not found" for a website is more common/normal in mainland China.  For out-of-china website, do not count on the any things like "speed" in China mainland without VPN. And if you track the trend of chinese policy, this problem could only be worse and worse in future 10 years.

**Comment by tbbbk** [comment] 2023-04-23 16:16
> 
Dry for that when i make this complaint, i browsed it without VPN. It's not the typst's fault

**Comment by laurmaedje** [comment] 2023-04-24 09:34
In case this is resolved / can't fix from our side, please close the issue.

**Closed** 2023-04-24 13:11 UTC
Labels: web app

**Comment by xsro** [comment] 2023-06-18 12:11
Anyway, is it possible to create a site for Chinese users like overleaf's [cn.overleaf.com](https://cn.overleaf.cn)
