### ISSUE TITLE
Enum numbers shift with large inline equations

### ISSUE THREAD

**Issue by lvjr** [typst/typst#3830] opened 2024-03-30 04:41 UTC
### Description

Enum numbers will shifts when there are some large inline equations:

```typ
+ Text Text Text Four $display(integral)_0^1 (1 + x) f^2 (x) d x$
+ Text Text Text One $display(integral)_0^1 (1 + x) f^2 (x) d x$
```
<img width="341" alt="image" src="https://github.com/typst/typst/assets/4239949/614a057a-cabc-4809-b338-6e708a3b6d1e">

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-04-01 15:13
Duplicate of https://github.com/typst/typst/issues/1204

**Closed by laurmaedje** 2024-04-01 15:13 UTC
Labels: bug
