### ISSUE TITLE
Headings are not justified in some cases

### ISSUE THREAD

**Issue by Vanishine** [typst/typst#5479] opened 2024-11-27 05:14 UTC
### Description

```typ
#[
  #set par(justify: true)
  #set text(12pt, font: "Inter")

  // not justified as expected
  = Thomas' Calculus #lorem(18)
]

#line(length: 100%)

#[
  #set par(justify: true)
  #set text(12pt, font: "Inter")
  #show heading: it => it.body

  // however, this works
  = Thomas' Calculus #lorem(18)
]
```

![image](https://github.com/user-attachments/assets/347630a8-dbae-4bd0-b6b7-a15929437071)

### Operating system

Windows

### Typst version

- [x] I am using the latest version of Typst

**Comment by xkevio** [comment] 2024-11-27 09:16
Maybe similar to #5472? At least doesn't seem to be a regression (if it is not affected by https://github.com/typst/webapp-issues/issues/487)

**Comment by Enivex** [comment] 2024-11-27 15:47
I'll close this as a duplicate of #5472 .

**Closed** 2024-11-27 15:47 UTC
Labels: bug, duplicate
