### ISSUE TITLE
Footnotes should be able to break apart `tight: false` lists/enums/terms

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3093] opened 2023-12-28 13:13 UTC
### Description

When writing
```typ
#set page(height: 5em)
- A very long list item#footnote[with a footnote in it]

- And another list item after it
```
The footnote gets moved down to the next page. I think this is undesirable, especially for non-`tight` lists.

### Use Case

Long lists  with long items that need footnotes within the same page

**Comment by PgBiel** [comment] 2023-12-28 13:14
Duplicate of #2449

**Closed** 2023-12-28 13:18 UTC
Labels: feature request
