### ISSUE TITLE
Update of 0.8.0 broke .bib bibliography

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [typst/typst#2134] opened 2023-09-13 20:26 UTC
### Description

Before the update I was able to compile without errors. Now without any changes to the files, I get the error _the document does not contain a bibliography_ for the bibliography file.

I do not know how I can provide debug information here from the web interface. Feel free to guide me.

### Reproduction URL

https://typst.app/project/re8lWAFWY209_nuYoX_6ab

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-09-13 20:48
That's really strange. It seems to work if I remove the weak pagebreak in front of the bibliography.

**Comment by laurmaedje** [comment] 2023-09-13 20:54
Looks like it is caused by this PR: https://github.com/typst/typst/pull/1929

**Comment by laurmaedje** [comment] 2023-09-14 11:36
Fixed via https://github.com/typst/typst/pull/2141

**Closed by laurmaedje** 2023-09-14 11:36 UTC
Labels: bug
