### ISSUE TITLE
Block sticky parameter doesn't work at the start of block

### ISSUE THREAD

**Issue by davystrong** [typst/typst#5296] opened 2024-10-25 15:35 UTC
### Description

Maybe I don't understand how the `block.sticky` parameter should work but it doesn't work as I expected inside a block. This sample correctly moves to the next page:

```typst
#lorem(650)

#{
  block(fill: red, sticky: true, [block1])
  block(fill: blue, [block1])
}
```

While this sample splits between two pages:

```typst
#lorem(650)

#block(fill: green,
  {
    block(fill: red, sticky: true, [block1])
    block(fill: blue, [block1])
  }
)
```

This is annoying, for example, with the [gentle-clues](https://typst.app/universe/package/gentle-clues/) package. I was trying to prevent the header from splitting from the content but the sticky parameter is ignored inside the wrapper block.

### Operating system

MacOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by davystrong** [comment] 2024-10-25 15:41
Note that the obvious solution, setting breakable to false, isn't sufficient as I do want the block to break, I just don't want it to break that early (similar to how a paragraph shouldn't break after a single line).

**Comment by PgBiel** [comment] 2024-12-12 21:11
Upon further investigation, sticky _does_ work inside blocks, as seen here:

```typ
#set page(height: 3cm)

#block[
  abc
  #v(0.8cm)
  == H

  b

  c
]
```
![H sent to the next page](https://github.com/user-attachments/assets/ff69d74c-b64a-4a4b-9834-ece55234be48)

The problem arises when the sticky block (in this case, the heading) is the first thing (more specifically, frame - ignoring spacing) in the block:

```typ
#set page(height: 3cm)

abc

#block[
  #v(0.8cm)
  == H

  b

  c
]
```

![H on a separate page from b](https://github.com/user-attachments/assets/bc2cbc31-144b-43e6-8ad2-5e1a26411d10)

As it turns out, the fact that this happens within a block is a red herring. **The same happens outside of blocks:**

```typ
#set page(height: 3cm)
#v(1.5cm)

== A

b
```

![A and b are in separate pages](https://github.com/user-attachments/assets/4ff75160-d1af-449b-99ff-61823b699251)

This is specifically due to the `stickable` check in the code. By default, the distributor used to layout a flow (like the root flow of the document, or the block's flow) starts with `stickable: false`:

https://github.com/typst/typst/blob/521ceae889f15f2a93683ab776cd86a423e5dbed/crates/typst-layout/src/flow/distribute.rs#L12-L21

And this matters because, when distributing a frame, we only "attach" the sticky block to the next frame in the flow if `stickable` is set to `true`, as seen in the snippet below. In the same snippet, we also see **the only way to change `stickable` to `true`:** to **place a non-sticky frame.**  Therefore, **any sticky blocks at the beginning of flow distribution are stripped of their sticky effect,** since there are no non-sticky frames before them (because there are no frames before them).

https://github.com/typst/typst/blob/521ceae889f15f2a93683ab776cd86a423e5dbed/crates/typst-layout/src/flow/distribute.rs#L306-L324

Given that the docs for `stickable` describe the parameter with "Whether there was at least one proper block. Otherwise, sticky blocks are disabled (or else they'd keep being migrated).", this suggests that `stickable` might be too conservative as is. I believe `regions.may_progress()` should also be considered in the decision of whether to disable the sticky behavior for a block: in the cases shown above, moving to the next region would indeed have improved the lack of space.

**Comment by PgBiel** [comment] 2024-12-13 00:13
Alright. It's not so simple: while checking for `(self.stickable || self.regions.may_progress())` for stickiness does solve the problem in this issue (with a single sticky block before a frame), it affects _multiple consecutive_ sticky blocks differently, since a single sticky block already turns `self.regions.may_progress()` true for the next blocks, so all sticky blocks but the first in the sequence become sticky, leading to multiple pages where the first sticky block is alone until either we reach a page where all of the remaining sticky blocks fit, or only one sticky block remains. This is shown by how the `block-sticky-many` test's output changed (left = before (current), right = after the proposed change):

```typ
#set page(height: 80pt)
#set block(sticky: true)
#block[A]
#block[B]
#block[C]
#block[D]
E
#block[F]
#block[G]
```

![block-sticky-many test: page with A B C, page with D E, page with F G (before), page with A, page with B, page with C D E, page with F G (after)](https://github.com/user-attachments/assets/351507cd-2b90-4035-9a07-54077b81898f)

Indeed, `self.stickable` would become largely redundant with this change, since `self.stickable` already implies `self.regions.may_progress()` (assuming a frame with non-zero height was placed to enable stickiness).

So, we have to make a decision on what is the expected behavior here. At first, the behavior to the right doesn't seem _that_ unreasonable from a stricter perspective where Typst should try its hardest to keep as many sticky blocks as possible in the same page as the first non-sticky block after them. However, **it is not ideal** because, as shown by the pre-change test result, it would already be impossible to keep all of them in the same page as the attached frame anyway, so the pagebreaks _between_ sticky blocks are totally excessive. (Note, however, that **infinite loops are still prevented,** regardless of this weirdness.)

On the other hand, the current (pre-change) behavior always causes all sticky blocks before the first non-sticky frame to have stickiness disabled, so, by removing sticky block `D`, we end up seeing zero sticky blocks in the same page as the non-sticky frame, which is also not the best since "C" would clearly fit there, maybe even "B" as well.

![page 1 = A B C, page 2 = E F G](https://github.com/user-attachments/assets/fc438603-4062-4c9a-b23c-237b82aebe44)

Now, with the current snapshot system - where we revert to the first sticky block in a sequence of them if the region ended in the middle of or after the sequence -, it sounds like a bit of a larger challenge to determine at which sticky block we would "make the cut" and try again in the next region in the situation above, or, in other words, to determine the ideal amount of sticky blocks to migrate. We'd like to maximize the amount of sticky blocks staying with the frame, but the non-sticky frame might also be placed several pages ahead with too many sticky blocks, so that could require some annoying amount of lookahead.

With that in mind, if we agree that the new test output is not ideal, I see two possible improvements for now:

1. Apply the `regions.may_progress()` fix, but **for the whole sequence of sticky blocks at once.** That is, **if the first sticky block is disabled, then all consecutive ones are as well.** However, this still makes it possible to unnecessarily orphan the next non-sticky frame (as shown above, where you can remove `D` and `E` is orphaned). That is, it preserves the current behavior for that particular case.
2. Don't apply it for the whole sequence at once (so, only the first sticky block in a sequence is disabled), but apply the following heuristic: in the event of a region break **after a sticky block** (that is, we have a sticky snapshot), we use some form of lookahead to determine whether **another sticky block is about to come** (that is, if **the next frame is sticky**). If so, **don't restore the snapshot.** That way, we don't unnecessarily create pagebreaks between sticky blocks, but also allow further sticky blocks to stay with the frame. (However, it won't maximize the amount of sticky blocks together with the frame, but that's not so bad.)

      - The main problem with this approach is that this could potentially **require an unbounded amount of lookahead** on each region break, since flow children that aren't frames are irrelevant for this check, which could degrade performance particularly if, for some reason, someone places sticky blocks with a bunch of irrelevant children afterwards, such as `#place` or `#v`. Although this could potentially be mitigated with some smart caching at collection time.
      - In addition, it won't fully prevent orphaning if sticky + non-sticky > page height, but that's impossible to prevent anyway. (There was a recent discussion on Discord about a related situation[^1].)

I think 1 is the simplest approach for now, so, since it wouldn't regress anything, we could start with it and later experiment with more sophisticated approaches. I'll begin preparing my PR with that in mind, but I'm open to switching approaches at any time.

[^1]: Discussion about sticky + non-sticky height being larger than the page: https://discord.com/channels/1054443721975922748/1310848449671069737

**Closed** 2024-12-17 09:45 UTC
Labels: bug, layout, urgent
