### ISSUE TITLE
Inline math with display size has wrong height in table

### ISSUE THREAD

**Issue by Leoongithub** [typst/typst#3194] opened 2024-01-15 03:02 UTC
### Description

The following example should explain:
```
#table(columns:1,
$1/2$,
$ 1/2 $,
$display(1/2)$,
)
#table(columns:1,
$cases(1,2)$,
$ cases(1,2) $,
$display(cases(1,2))$,
)
```
![image](https://github.com/typst/typst/assets/10937162/2a15225c-4d32-4185-97a3-f609a361a82a)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-01-15 11:23
Duplicate of https://github.com/typst/typst/issues/1028

**Closed by laurmaedje** 2024-01-15 11:23 UTC
Labels: bug
