### ISSUE TITLE
layout-function produces newline

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1604] opened 2023-06-28 10:14 UTC
### Description

I just wanted to check the layout size, but noticed, that this introduces a newline. Check this:
```
A#layout(size=>"X")B
```
It should just produce "AXB", but each letter is on a separate line.

### Reproduction URL

https://typst.app/project/rlpBh_MdCUk0DkGzcrEnIC

### Operating system

Web app, Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-06-29 04:38
This is intentional; most elements (such as `layout`) have block-level display instead of inline. To force an element to be inline, wrap it in a `box`, like so:

`A#box(layout(size=>"X"))B`

**Comment by Beiri22** [comment] 2023-06-29 04:52
I will try that, thank you. It was unexpected to me to have such side effects on a method. Feels like latex 😆. I mean, a user could also be explicit and wrap it inside a block or better, supply an optional parameter.

Maybe you could consider a parameter, defaulting to block mode, to avoid an extra layer of boxes?

**Comment by Beiri22** [comment] 2023-06-29 10:31
@PgBiel the newlines vanish; but in my case it's not applicable:
I want to print some content right aligned at the end of a line if space is available or at the end of the next line. Within this box I cannot trigger a linebreak.

```
#let formatCredits(credits) = {
    let content = [(#credits Punkte)]
    locate(location=>
        box(layout(size=>
            style(styles=>
                if(location.position().x + measure(content, styles).width > size.width) {
                    linebreak()
                }
            )
        ))
    )
    h(1fr)
    content
}
```

**Comment by laurmaedje** [comment] 2023-06-29 10:46
Unfortunately, what you're trying to do isn't possibly with `layout`. It is always a separate block because it does not integrate with paragraph layout. Elements in a paragraph fundamentally don't know the remaining available space because they need to be movable so that the paragraph can determine the best line breaks and justification. What you're trying to do has come up before and I don't think there is a satisfying solution, currently.

**Comment by Beiri22** [comment] 2023-06-29 17:08
I just need the width of the surrounding container to decide on the line break. I thought that was, what layout does. As far as I see, the documentation does not indicate any need for a separate block.

The thing is: In latex I just had to do the following to make it work. Is there any equivalent in typst?
```latex
	% Etwas Platz, dann rechts rücken
	% Strut erlaubt, dass es auch auf einer leeren neuen Zeile hinter rückt
	\quad\strut\nobreakspace\hfill
	
	% Eigentliche Punktzahl in der Klammer
	\mbox{(\int_to_arabic:n{#1}~Punkt \int_compare:nNnF {#1} = {1} {e})}
```

**Comment by laurmaedje** [comment] 2023-11-14 20:59
Duplicate of https://github.com/typst/typst/issues/409

**Closed by laurmaedje** 2023-11-14 20:59 UTC
Labels: bug, layout
