### ISSUE TITLE
Feature Request: support compilation to HTML and other formats

### ISSUE THREAD

**Issue by admercs** [typst/typst#612] opened 2023-04-05 23:03 UTC
Feature request: add flags to the `typst compile` command that allow targeting additional output formats including HTML. This could be accomplished internally or by adding `typ` document format support to `pandoc`.

**Comment by Enivex** [comment] 2023-04-05 23:13
https://github.com/typst/typst/issues/114

**Comment by laurmaedje** [comment] 2023-04-06 08:17
This is indeed a duplicate of #114 and #188. The plan is to support HTML and EPUB.

**Closed by laurmaedje** 2023-04-06 08:17 UTC
