### ISSUE TITLE
Font selection improvements

### ISSUE THREAD

**Issue by inferiorhumanorgans** [typst/typst#4709] opened 2024-08-08 23:20 UTC
### Description

Two nice to haves:

1.) The ability to select a font by its PostScript name

2.) Warning when a fallback font is used (or when no fallback fonts are specified).

### Use Case

Currently font selection is a bit wonky.  Some families get collapsed but others don't.  E.g. Arial Black and Arial Narrow appear to be collapsed into Arial despite having different family names (but e.g. Arial Hebrew isn't).  I didn't see any obvious indication (in the exceptions or documentation, otherwise) of how this actually happens.

Some fonts e.g. Bell Centennial have font weights with wildly non-standard weight names (e.g. Address, Name & Number, Sub-Caption, and Bold Listing).  Locally I've got a couple fonts where they have different styles (given unique names) but with identical weight and stretch values.

I can see the utility of this behavior, but it'd also be nice to have a way of saying "use THIS font", so being able to use the Postscript or Unique name would be great here.

As for the warnings, they'd simplify debugging the above.

**Comment by PgBiel** [comment] 2024-08-09 03:51
Duplicate of https://github.com/typst/typst/issues/2098 and https://github.com/typst/typst/issues/2818

Regarding debugging when fallback fonts are used, this is achievable today through `#set text(fallback: false)`.

**Closed by PgBiel** 2024-08-09 03:51 UTC
Labels: feature request
