### ISSUE TITLE
PDF is different for identical document (only on Linux)

### ISSUE THREAD

**Issue by deffi** [typst/typst#2796] opened 2023-11-29 13:21 UTC
### Description

`test.typ`:

```typst
#let my-document(doc) = {
    set page(numbering: "1")
    set document(date: none)
    doc
}

#show: doc => my-document(doc)

Hello
```

When compiled twice with the Windows version of Typst, the resulting PDFs are identical. When compiled twice with the Linux version (native Ubuntu or Ubuntu in WSL), the resulting PDFs are different (this is not due to a timestamp in the PDF metadata; that is disabled by the `set document(date: none)` line):

```
$ diff test_1.pdf test_2.pdf
210c210
< <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="xmp-writer"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:xmp="http://ns.adobe.com/xap/1.0/"  xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"  xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"  xmlns:pdf="http://ns.adobe.com/pdf/1.3/" ><xmp:CreatorTool>Typst 0.9.0</xmp:CreatorTool><xmpTPg:NPages>1</xmpTPg:NPages><dc:format>application/pdf</dc:format><dc:language><rdf:Bag><rdf:li>en</rdf:li></rdf:Bag></dc:language><xmpMM:DocumentID>A4q+JjDntuH275pfiPYktw==</xmpMM:DocumentID><xmpMM:InstanceID>p+BzxY1p6I4ye2Wad1QVUA==</xmpMM:InstanceID><xmpMM:RenditionClass>proof</xmpMM:RenditionClass><pdf:PDFVersion>1.7</pdf:PDFVersion></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="r"?>
---
> <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="xmp-writer"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:xmp="http://ns.adobe.com/xap/1.0/"  xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"  xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"  xmlns:pdf="http://ns.adobe.com/pdf/1.3/" ><xmp:CreatorTool>Typst 0.9.0</xmp:CreatorTool><xmpTPg:NPages>1</xmpTPg:NPages><dc:format>application/pdf</dc:format><dc:language><rdf:Bag><rdf:li>en</rdf:li></rdf:Bag></dc:language><xmpMM:DocumentID>A4q+JjDntuH275pfiPYktw==</xmpMM:DocumentID><xmpMM:InstanceID>FevYEvFqZ50QovRc/u8sjg==</xmpMM:InstanceID><xmpMM:RenditionClass>proof</xmpMM:RenditionClass><pdf:PDFVersion>1.7</pdf:PDFVersion></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="r"?>
251c251
<   /ID [(A4q+JjDntuH275pfiPYktw==) (p+BzxY1p6I4ye2Wad1QVUA==)]
---
>   /ID [(A4q+JjDntuH275pfiPYktw==) (FevYEvFqZ50QovRc/u8sjg==)]
```

The only difference is the second string in `/ID`, which also appears as `xmpMM:InstanceID` above.

When the `set page(numbering: "1")` line is removed in `test.typ`, the resulting PDF files are identical even with the Linux version.

There are several use cases where this becomes an issue; for example, automated checks whether a document has changed and therefore needs to be re-released.

Shell script to run the test (specify the Typst executable as the first argument):

```bash
#!/bin/bash

[[ -n "$1" ]] || { echo "Usage: $0 path/to/typst"; exit 1; }

"$1" c test.typ && mv test.pdf test_1.pdf && "$1" c test.typ && mv test.pdf test_2.pdf && diff test_1.pdf test_2.pdf
diff test_1.pdf test_2.pdf
 ```

### Operating system

- Windows 10 22H2
- Ubuntu 20.04 (WSL on Windows 10)
- Ubuntu 22.04 (native)

### Typst version

Typst 0.9.0 (7bb4f6df) in both cases.

**Comment by laurmaedje** [comment] 2023-11-29 14:09
Duplicate of https://github.com/typst/typst/issues/2536. This is fixed on main.

**Closed by laurmaedje** 2023-11-29 14:09 UTC
Labels: bug

**Comment by deffi** [comment] 2023-11-29 14:53
Ah shoot, I checked all issues with the "pdf" label, but obviously that was insufficient. My bad!

**Comment by laurmaedje** [comment] 2023-11-29 14:59
my bad, the label was missing there
