### ISSUE TITLE
How write same LaTex command: \uwave?

### ISSUE THREAD

**Issue by yangyixuan** [typst/typst#5208] opened 2024-10-15 08:15 UTC
### Description

LaTex: \uwave
\uwave{Wavy underline}
![145866601_1_20181002050754308](https://github.com/user-attachments/assets/79513bef-cb74-487e-bab3-0013e2f83a83)

### Use Case

Chinese punctuation marks

**Comment by laurmaedje** [comment] 2024-10-15 08:57
Duplicate of https://github.com/typst/typst/issues/2835

**Closed by laurmaedje** 2024-10-15 08:57 UTC
Labels: feature request
