### ISSUE TITLE
Error with slice Method on Strings Containing Multi-Byte Characters

### ISSUE THREAD

**Issue by Jeomhps** [typst/typst#4308] opened 2024-05-31 07:47 UTC
## Description:
Hello,

I am relatively new to coding packages using Typst, so I apologize in advance if this is not actually a bug.

I encountered an issue when trying to slice a string that contains multi-byte characters. Here is a minimal example to demonstrate the problem:

```typst
#let my-string = "Août"
#let month = my-string.slice(0, 3)
```
When I compile this, I get the following error message:

```shell
String index 3 is not a character boundary
```

It appears that the slice method does not handle multi-byte characters correctly, as "Août" (a French word) causes this issue. This error does not occur with strings containing only single-byte characters.

## Steps to Reproduce:

1. Define a string containing multi-byte characters, such as "Août".
1. Attempt to slice the string using slice(0, 3).

## Environment:

    Typst version: 0.11.1
    Operating system: Windows and webapp

### Typst version

- [X] I am using the latest version of Typst

**Comment by JamesxX** [comment] 2024-05-31 08:07
You may want to first convert your string to an array with `codepoints` and slice array

**Comment by Jeomhps** [comment] 2024-05-31 08:34
Hi, thank you for answering. It works ! Shall I close this issue ?

```typst
#let my-string = "Août"
#let my-modified-string = my-string.codepoints()
#let month = my-modified-string.slice(0, 3).join()

#month //Output : Aoû
```

**Comment by JamesxX** [comment] 2024-05-31 08:36
Probably worth keeping it open because I thought it should work like this at first glance

**Comment by Enter-tainer** [comment] 2024-05-31 09:12
the behavior is the same as rust's string

**Comment by Jeomhps** [comment] 2024-05-31 09:44
I see, so it's intended ?

**Comment by laurmaedje** [comment] 2024-05-31 13:45
This is working as intended in principle. All string operations use byte indices. While not the most user-friendly, making all indexing `O(n)` (with char-level indexing) would be too bad in my opinion. Indexing into a string directly with an integer that isn't derived from some string length is also a rather rare / typically wrong operation.

If we come up with an efficient implementation of character-level indexing in the future, we can reconsider things. But for now, I'll close this.

**Closed by laurmaedje** 2024-05-31 13:45 UTC
Labels: bug
