### ISSUE TITLE
Alignment passes through block limits

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4744] opened 2024-08-13 17:11 UTC
### Description

Perhaps this is intended to be so, but I find it rather weird.

First, if a list is centered not only the list is in the center of its container but also its items are centered, while the bullets are left aligned. I don't like it but that might be intentional (?).

```typst
#align(center, [
- xxx
- xxxxxx
])
```

Then I wanted to disable that behavior so I wrapped the list inside a block, but it keeps doing the same:

```typst
#align(center, block([
- xxx
- xxxxxx
]))
```

The only way to revert the centering was to explicitly align the list left inside the block:

```typst
#align(center, block(align(left, [
- xxx
- xxxxxx
])))
```
I don't think it's right for the alignment to pass through the block (or box) limit. TBH neither do I think it is right for it to pass through the list limits.

In fact, there are two separate issues here:
1. Alignment passing through the block: you don't even need lists for this.
2. Alignment passing through lists: ends up in left-aligned bullets + centered text that may be desired or not.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-08-13 19:19
Duplicate of https://github.com/typst/typst/issues/3605

**Closed by laurmaedje** 2024-08-13 19:19 UTC
Labels: bug
