### ISSUE TITLE
Allow function as parameter to where()

### ISSUE THREAD

**Issue by noahjutz** [typst/typst#4950] opened 2024-09-13 09:06 UTC
### Description

The signature of the where function is currently

```
self.where(..any) -> selector
```

I want it to be

```
self.where(..any or function) -> selector
```

### Use Case

Currently, selecting with a range of parameters is difficult.

```
table.cell.where(x: 0)
table.cell.where(x: 2)
table.cell.where(x: 4)
// ...
```

it would be much easier like this:

```
table.cell.where(cell => calc.rem(cell.x, 2) == 0)
```

**Comment by laurmaedje** [comment] 2024-09-13 10:11
This has come up a few times before. Copying an [earlier response](https://discord.com/channels/1054443721975922748/1088371867913572452/1259107612021096499) of mine:

I can see the appeal, but it's a can of worms to implement:

- The introspector would need to start running arbitrary code (which is more or less impossible since it's tracked for memoization)
- We lose all hope of writing acceleration structures for faster style matching during realization
- Once content = type, selectors will become type patterns and then type checking would again mean running arbitrary code

**Comment by Andrew15-5** [comment] 2024-09-19 09:37
Linking back to a post where this was mentioned: https://forum.typst.app/t/how-do-make-a-reference-that-inserts-name-of-section-and-page-number/461/5.

**Comment by laurmaedje** [comment] 2024-09-22 11:55
I will close this as it is not really feasible.

**Closed by laurmaedje** 2024-09-22 11:55 UTC
Labels: feature request, introspection

**Comment by Nikilauz** [comment] 2026-06-16 15:19
What about accepting regexes as value for parameters fed to `where`? I stumbled upon this trying to find a method to inverse the selection of `where` (e.g. to make every caption italic except for a custom `kind` - sure, I can also just overide for that kind, so I do not open a new issue (; ), so adding a `not` modifier for the `where` selector object would achieve the same...

**Comment by laurmaedje** [comment] 2026-07-06 09:52
> What about accepting regexes as value for parameters fed to where?

I could see something like that down the road. I would like to turn selectors into type patterns more generally and then you could also have "or" patterns or things like that in where selectors. However, the issue is that there is some ambiguity. E.g. what if you want to match for that particular regex value itself using `where`? This example is a bit unrealistic, but there are real examples. See https://github.com/typst/typst/pull/6903 for more details.
