### ISSUE TITLE
Bad math alignment while combined with lists

### ISSUE THREAD

**Issue by ay-tony** [typst/typst#2573] opened 2023-11-03 10:40 UTC
### Description

When typing the math formulas in displayed style in list, I found that the formulas are not displayed at center of lines.

```typst
+ #lorem(5) $ a = a $
```

![image](https://github.com/typst/typst/assets/25659764/bb72aaa2-cd04-41b4-ab1f-766d81b89781)

```typst
+ #lorem(7) $ a = a $
```
![image](https://github.com/typst/typst/assets/25659764/b1b7a7dd-86c8-4e37-9f1e-d0494bfbe4d7)

```typst
+ #lorem(20) $ a = a $
```

![image](https://github.com/typst/typst/assets/25659764/60aebb11-5c51-4218-9d76-b347c875a753)

What I supposed is to render the math at center position of the line, no matter how long the contents in list are.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment] 2023-11-03 10:41
Looks like a duplicate of #529

**Closed** 2023-11-03 10:44 UTC
Labels: bug, duplicate
