### ISSUE TITLE
Custom Element Functions

### ISSUE THREAD

**Issue by genericusername3** [typst/typst#2607] opened 2023-11-07 15:24 UTC
### Description

As already _kinda_ requested and stated to be planned at some point in #478, I think it would be handy to allow for element functions defined in typst code, as well as allowing for settable parameters for them.

I'm creating this issue not because I'm impatient, but because I didn't find anything since #478 (March) and I want to know whether there's already any concrete plans to implement this (which I would guess isn't a small task whatsoever) and whether I can help (though I'm a little short on time right now, on account of the thesis where this came up)

### Use Case

In my specific case, for instance, I'd want to write an element for abbreviations that can be configured on when to show the written-out form with a `set` rule, like so:

```typ
#set abbrev(show-long: "first")

#abbrev([ETA], long: [Estimated Time of Arrival])
bla bla bla
#abbrev([ETA], long: [Estimated Time of Arrival])
```

which would produce `ETA (Estimated Time of Arrival) bla bla bla ETA`

**Comment by Enivex** [comment] 2023-11-07 15:34
Duplicate of https://github.com/typst/typst/issues/147

**Closed** 2023-11-07 15:34 UTC
Labels: duplicate, feature request

**Comment by laurmaedje** [comment] 2023-11-07 15:37
Here are some more details about the current plans: https://laurmaedje.github.io/posts/types-and-context/
