### ISSUE TITLE
Support multiple font styles with the same style(italic), weight, and stretch

### ISSUE THREAD

**Issue by cskeeters** [typst/typst#5280] opened 2024-10-23 04:54 UTC
### Description

When a font family has a Regular and a Display Regular font style:
1) With the font Novela, Typst is choosing "Display Regular" as the regular font, I assume because it matches Normal (non-italic), Weight 400, and FontStretch(1000) based on `typst --varients`.  I suspect this issue is not Novela specific, just using it as an example.
2) Is it possible to select a style by name "Display Regular" distinct from "Regular"?

FYI: Novela is a static (non-variable) font.

I'm trying to work around this issue but using fontforge to rename the Display fonts to be their own distinct family.

### Use Case

Users that have fonts with large numbers of styles that want to use reasonable defaults and utilize uncommon styles in the family.

**Comment by laurmaedje** [comment] 2024-10-23 08:12
Duplicate of #2098.

**Closed by laurmaedje** 2024-10-23 08:12 UTC
Labels: feature request

**Comment by alerque** [comment] 2024-10-23 08:35
This might be an urgent issue for the default font. Typst does not bundle it but anybody who has Libertinus Serif installed locally is likely to also have the Display variant. Lots of people may be getting the wrong font by default.

**Comment by laurmaedje** [comment] 2024-10-23 08:40
Thanks for the heads-up!

**Comment by alerque** [comment] 2024-10-23 08:57
I just did a quick check locally and at least as I understood this issue report it does not affect *Libertinus Serif Display*:

``typst
#text(font: "Libertinus Serif")[Libertinus Serif]

#text(font: "Libertinus Serif Display")[Libertinus Serif Display]
```

![image](https://github.com/user-attachments/assets/f387d3aa-54b1-42be-8578-5039c60b532d)

**Comment by cskeeters** [comment] 2024-10-23 21:37
If anyone else wants to correct Novela specifically, they can use this.

https://github.com/cskeeters/novela-typst
