### ISSUE TITLE
Updating page counter breaks `#set page()`

### ISSUE THREAD

**Issue by avalsch** [typst/typst#3167] opened 2024-01-10 15:59 UTC
### Description

Tested on Arch Linux using the latest version of typst.

```
$ typst --version
typst 0.10.0 (70ca0d25)
```

Updating the page counter breaks using `#set page()`.

For example, the following code:

```typst
#set page(height: auto)

#counter(page).update(3)

#set page(header: [ Header ])

#lorem(10)
```

Expected behavior:
The header is shown.
![image](https://github.com/typst/typst/assets/87724551/57a561b0-4ba3-484e-8ed9-6a13d760bb7c)

Actual behavior:
The header is not shown.
![image](https://github.com/typst/typst/assets/87724551/918fae1c-edbc-4921-babb-c35e7dec8d07)

This issue does not seem to be present for set rules before the counter update, however this breaks code which relies on reading the page counter, ex:

```typst
#set page(header: counter(page).display())
```

May be related to #2987 ?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-01-15 11:32
Is this a duplicate of https://github.com/typst/typst/issues/2987?

**Closed** 2024-02-01 13:52 UTC
Labels: bug, styling
