### ISSUE TITLE
State is not safe across modules

### ISSUE THREAD

**Issue by timjs** [typst/typst#3202] opened 2024-01-15 21:10 UTC
### Description

With the current design of [`state`](https://typst.app/docs/reference/introspection/state/), it is possible for modules to _leak_ internals and letting other modules interfere with their internal invariants.

Say we have two modules, `lib1.typ` and `lib2.typ`, both from different authors, that by accident both use the same identifier for their state or counter:
```typst
// lib1.typ
#let s = state("counter", 0) // naively uses "counter" as key
#let c = {
  s.update(n => n + 1)
  s.display()
}
```
```typst
// lib2.typ
#let s = state("counter", 0) // does the same thing
#let c = {
  s.update(n => n + 1)
  s.display()
}
```

Now, when a third party (an end user or other library author) uses both `lib1.typ` and `lib2.typ`, the counters interfere:
```typst
#import "lib1.typ": c as c1
#import "lib2.typ": c as c2
#c1 #c1 #c2 #c1
```
This results in "1 2 3 4" instead of "1 2 1 3".

The obvious solution would be to prefix both counters with a _percieved_ unique name. I wrote _percieved_ because in the end one can never be a 100% sure another library won't use the same name.

Therefore, it would be good to prohibit this at the language level.

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-01-16 08:59
Duplicate of https://github.com/typst/typst/issues/2425

**Closed by laurmaedje** 2024-01-16 08:59 UTC
Labels: bug
