### ISSUE TITLE
Compiler crash: Two RTL `#text`s in a single grid cell fail to wrap into next line

### ISSUE THREAD

**Issue by xyl1t** [typst/typst#5276] opened 2024-10-22 14:47 UTC
### Description

My use case: I have a two column grid/table, on the left is LTR text (Russian), on the right RTL (Arabic).

When I need to use a different font on the RTL side, I use `#text(font: "...")[]`, but it causes the compiler to crash when there are multiple RTL `#text`s in one cell and when the total of the two contents is too long to fit into a single line (i.e. it crashes when it tries to wrap into a new line). 

But even if it fits into a single line, the content of the second `#text` is rendered as crossed rectangles, unless I specify the font.

Note that this does not happen when the two `#text`'s are in separate paragraphs (but still in the same cell). It crashes only when one goes right after the other in one paragraph.

### Reproduction URL

https://typst.app/project/r-K9kAm1znoQ-0eEJA4zf_

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-12-11 15:58
Closing as a duplicate of https://github.com/typst/typst/issues/5490 because that one is more minimal.

**Closed by laurmaedje** 2024-12-11 15:58 UTC
Labels: bug, layout, crash, urgent, regression
