### ISSUE TITLE
Hyphenating right after parentheses symbol

### ISSUE THREAD

**Issue by Karmac** [typst/typst#2579] opened 2023-11-03 17:27 UTC
### Description

Hi,

It seems that Typst applies hyphens between the opening parentheses symbol ( and the following letter (at least in es-ES lang, don't know if there are special rules that may apply). 

![image](https://github.com/typst/typst/assets/638179/87d7b2bf-cf25-4efd-bd10-d307ce2dc046)

I'm using Typst v0.8.0. Thanks.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by gfpj** [comment] 2023-11-03 18:39
I think it is even worse, and last time I checked, Typst did not check what is in TeX `lefthyphenmin` and `righthyphenmin`.
If those would be checked, the problem would go away.

**Comment by alerque** [comment] 2023-11-03 19:21
Just checking for a minimum length will not fix this, there are cases where parenthesis can appear inside words. For example in English you might have `the banana(s)` or Turkish may have `patates(ler)imiz`. Similar issues apply to other symbols in words. The entire pattern system needs to take into account more than just letters and lengths. The current approach is a bit naive.

**Comment by gfpj** [comment] 2023-11-03 19:25
Just checking for a minimum length will fix this under the assumption that a normal word tokenizer is implemented and working.

**Comment by alerque** [comment] 2023-11-03 19:34
I think your idea of a "normal" word tokenizer is a little naive. I'll post a new issue with another example because it happens to be *similar* but not the same problem as noted here.

**Comment by gfpj** [comment] 2023-11-03 19:39
The problem is obviously language-dependent. But for all languages there is a simple solution that fits 99.9% of all cases.
Especially, LaTeX gets it working, so there exists a clear solution that is working.

**Comment by laurmaedje** [comment] 2023-11-14 15:51
Duplicate of https://github.com/typst/typst/issues/2168

**Closed by laurmaedje** 2023-11-14 15:51 UTC
Labels: bug, text
