### ISSUE TITLE
Wrong formula direction when direction of text is rtl

### ISSUE THREAD

**Issue by mojtaba82** [typst/typst#3775] opened 2024-03-23 19:42 UTC
### Description

when text direction is right to left, math formula also become right to left.
```
#set text(
  lang: "fa",
  dir: auto
)
فرمول ریاضی باید چپ به راست باشد $3x+2y=5$ در حالیکه راست به چپ است
```
![image](https://github.com/typst/typst/assets/4151722/8e12076b-b150-4f7d-b313-ba5a17175a09)

### Reproduction URL

https://typst.app/project/pU2ks46YMlxU1dOlnBpNwJ

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-03-23 19:44
Duplicate of https://github.com/typst/typst/issues/3696

**Closed** 2024-03-23 19:44 UTC
Labels: bug, duplicate
