### ISSUE TITLE
If a page ends with a heading, the page number has the style of the heading.

### ISSUE THREAD

**Issue by matj1** [typst/typst#4022] opened 2024-04-26 12:11 UTC
### Description

If a page with a number ends with a heading, the page number too is large and bold (or however else headings are displayed).

It manifests in this example:

``` typst
#set page(numbering: "1", number-align: top)
= thick number
#pagebreak()
= thin number
if there is something under the heading
```

![Snímek obrazovky z 2024-04-26 14-06-55](https://github.com/typst/typst/assets/22873928/00e4e56d-6de6-4c50-86a5-174139a7de8f)  
![Snímek obrazovky z 2024-04-26 14-07-10](https://github.com/typst/typst/assets/22873928/181aed7f-020e-4f16-bb8c-7b6102e4e871)

I expect that the number would not take the style of headings. It seems that the heading is not ended properly.

### Reproduction URL

https://typst.app/project/pVTEcA738PFjlwKgbr30PB

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment] 2024-04-28 03:55
It turns out it's not just the heading whose style can affect the page number's style. In fact, whatever style belonging to the last element on the page's proper (that is, excluding the page marginals) can affect the page number's style.

```typ
#set page(numbering: "1", number-align: center)
= thick number
#pagebreak()
= thin number
text under the heading
#pagebreak()
*thick text*
#pagebreak()
_italic text_
#pagebreak()
#text(fill: red, [red text])
```

<img width="200" src="https://github.com/typst/typst/assets/18319900/e694708a-69a9-4c54-8a96-dfaea6664f9f">

**Comment by Leedehai** [comment] 2024-04-28 04:13
Looks like a dupe of #241. Not an easy fix, though one superficial/"gloss-over"/"brutal force" solution would be replacing page.rs `typst::layout::page::Packed<PageElem>::layout()`'s
```rs
                let sub = content
                    .clone()
                    .styled(AlignElem::set_alignment(align))
                    .layout(engine, styles, pod)?
                    .into_frame();
```
with
```rs
                let sub = content
                    .clone()
                    .styled(AlignElem::set_alignment(align))
                    .layout(engine, StyleChain::new(&Styles::new()), pod)? // Use a brand-new StyleChain!
                    .into_frame();
```
<img width="200"  src="https://github.com/typst/typst/assets/18319900/3859b16d-6b8f-4a12-9749-a513df77ce59">

**Closed** 2024-04-29 09:46 UTC
Labels: bug

**Comment by laurmaedje** [comment] 2024-04-29 09:49
> Not an easy fix it seems, though one solution would be replacing page.rs ...

That would break other things (the capability to change global styles from Rust, e.g. in the tests, but it would also mean that headers/footers would never respect a global `#set text(font: ..)`). But #241 is on my radar as I'm working on the realization and I'll try to fix it.
