### ISSUE TITLE
Set page numbering unfriendly to Germans

### ISSUE THREAD

**Issue by JamesxX** [typst/typst#2428] opened 2023-10-18 18:33 UTC
### Description

If a German typographer want to set their page numbering to the German equivalent of "Page 1 of X",  they would likely write the following:

```typst
#set page(numbering: "Seite 1 von 1")
```

However, the `i` of Seite is being interpreted as a roman numeral, which on page 3 would look like `Seiiite 5`,

The workaround would be to use a function instead
```typst
#set page(numbering: (cur, max) => [Seite #cur von #max])
```

but it would be nice to be able to escape characters, perhaps with a backslash.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-10-18 18:41
Duplicate of https://github.com/typst/typst/issues/1177

**Closed by Enivex** 2023-10-18 18:41 UTC
Labels: bug
