### ISSUE TITLE
Stack trace within `context` block omits parent function calls

### ISSUE THREAD

**Issue by Aaron-Rumpler** [typst/typst#5423] opened 2024-11-15 08:17 UTC
### Description

When an error is thrown (by `panic` for example) inside a `context` block, the stack trace only includes the call stack within the `context` block itself. Any outer function call(s) that led to the context block are omitted. This makes it tricky to determine what call caused the error.

```typst
#let error(message) = {panic(message)}

#let do_something() = context {
  error("False Alarm")
}

#do_something()
```

```
error: panicked with: "False Alarm"
  ┌─ main.typ:1:23
  │
1 │ #let error(message) = {panic(message)}
  │                        ^^^^^^^^^^^^^^

help: error occurred in this call of function `error`
  ┌─ main.typ:4:2
  │
4 │   error("False Alarm")
  │   ^^^^^^^^^^^^^^^^^^^^
  ```

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Aaron-Rumpler** [comment] 2024-11-15 08:18
Related: https://github.com/typst/typst/issues/1747#issuecomment-1762012620

**Comment by laurmaedje** [comment] 2024-11-15 10:26
Unfortunately, it is a bit trickier than I thought in https://github.com/typst/typst/issues/1747#issuecomment-1762012620 because accessing the stack trace where the context is created is an impure operation, which isn't really allowed.

In any case, this is a duplicate of #1747.

**Closed by laurmaedje** 2024-11-15 10:26 UTC
Labels: bug
