### ISSUE TITLE
SVG files with gradients or masks are rendered incorrectly

### ISSUE THREAD

**Issue by dsosec** [typst/typst#1852] opened 2023-08-03 13:48 UTC
### Description

SVG supports the [`<radialGradient>` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient), which allows SVG files to render a smooth gradient between multiple colors.  Furthermore, the [`<mask>` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask) allows selective hiding of elements.

Typst renders both of these incorrectly. I have created an [SVG image](https://github.com/typst/typst/assets/89640712/f446e4f0-7a19-45f6-890d-6166bfd3072a), which uses both `<mask>` and `<radialGradient>` elements. This [PNG image](https://github.com/typst/typst/assets/89640712/86d62ab1-4409-4705-92a7-cf081c0bad68) shows how the file should be rendered.

The following screenshot shows how Typst renders the SVG file incorrectly, next to how it should be:

<img width="256" alt="Incorrect Render" src="https://github.com/typst/typst/assets/89640712/49778304-f49e-445d-826d-cb76e91da33e"> 
<img width="251" alt="Correct Render" src="https://github.com/typst/typst/assets/89640712/8048d19e-dd01-4a97-8ac8-c34b8fc29688">

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-08-03 13:53
Have you tried this on main? There have been significant improvements to SVG rendering post 0.6 (the latest release)

**Comment by dsosec** [comment] 2023-08-03 14:03
@Enivex I'll install Rust, compile from main and try it. Internet is slow here, so it might take a while

**Comment by LaurenzV** [comment] 2023-08-03 15:53
<img width="805" alt="image" src="https://github.com/typst/typst/assets/47084093/8ffab5c4-3148-43ee-bd27-d2ad9af00bd1">
That's how it looks like if I render it as a PDF with svg2pdf with the corrected version. I think that Typst somehow wrongly calculates the transformations because the viewbox contains a negative value, but only a guess from my side. I'll see if I can look into it in the coming days.

**Comment by bluebear94** [comment] 2023-08-04 04:40
@LaurenzV I can’t reproduce this issue (on 028d2f53):

![Typst output for latest main](https://github.com/typst/typst/assets/2975203/08531542-4019-4abb-9ed8-0fa8f1f2f8cd)

**Comment by dsosec** [comment] 2023-08-04 04:51
@LaurenzV When updating the SVG file to include the modified fillUrl, it renders fine in the current version of Typst in the Web App:

![image](https://github.com/typst/typst/assets/89640712/478055cc-a94b-40c1-9293-5c51a8937d23)

I'm not sure if this issue should remain open then or not, since it was a botched SVG file.

**Comment by LaurenzV** [comment] 2023-08-04 06:46
It render fine on the webapp, but not on the CLI (which contains a newer version of the SVG coversion program). So once the web app will get updated to the newest version, it also won't work in the web app anymore. I know what the issue is, but not sure if I will be able to fix it today.

**Comment by LaurenzV** [comment] 2023-08-04 06:48
@bluebear94 Hm that's weird, in my case, it doesn't work.

**Comment by bluebear94** [comment] 2023-08-04 07:19
It might actually be because I tried it in the test harness instead of on the command line.

**Comment by LaurenzV** [comment] 2023-08-07 16:36
It also works fine now in v0.7 of the web app, so I'm closing this.

**Closed by LaurenzV** 2023-08-07 16:36 UTC
Labels: bug
