### ISSUE TITLE
Any plans for interoperability with LaTeX?

### ISSUE THREAD

**Issue by jcpaik** [typst/typst#358] opened 2023-03-27 04:17 UTC
This system is really great. The world needed a system like this.

However, I think the lack of interoperability with LaTeX is stopping typst from dominating the world. Every major conferences and journals still expect LaTeX-formatted documents from the author. So for researchers it's hard to use typst as the main tool for writing. Nor I don't think publishers are willing to change their paper typesetting system completely. Potential users will greatly benefit from a transpiler targeted to LaTeX.

**Comment by user202729** [comment] 2023-03-27 05:23
Duplicate of #149

**Closed** 2023-03-27 05:24 UTC
