### ISSUE TITLE
show regex stackoverflow

### ISSUE THREAD

**Issue by taooceros** [typst/typst#2418] opened 2023-10-17 16:12 UTC
### Description

The following code will stackoverflow

```typst
#show regex("%\S+"): it => [
  #it.text bbb
]

%ssss
```

`thread 'main' has overflowed its stack`

Without the `.text` it works

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-10-17 16:16
Duplicate of https://github.com/typst/typst/issues/229

**Closed by Enivex** 2023-10-17 16:16 UTC
Labels: bug

**Comment by taooceros** [comment] 2023-10-17 16:27
but why does it happen only with `.text`?  I doubt this may be a slightly different issue?
