### ISSUE TITLE
Superscript with Unicode delimiters don't get scaled

### ISSUE THREAD

**Issue by lumi-a** [typst/typst#4565] opened 2024-07-16 12:38 UTC
### Description

When using unicode-delimiters like `⌈ ⌉` to delimit superscript-content, those delimiters aren't scaled to match the content. This is not the case when wrapping the whole thing in another pair of `( )` parentheses, or when using the `math.ceil` function.
```typst
$2^⌈∫_0^1x⌉ + 2^(⌈∫_0^1x⌉) + 2^ceil(∫_0^1x)$
```
![image](https://github.com/user-attachments/assets/69d7d631-fe3c-43f8-94a5-855ffb50d823)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-07-16 12:46
Duplicate of https://github.com/typst/typst/issues/2979

**Closed by Enivex** 2024-07-16 12:46 UTC
Labels: bug
