### ISSUE TITLE
Wrong colours in PDF export in some viewers

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2257] opened 2023-09-28 15:34 UTC
### Description

The error was introduced in #2171

In PDF export, at least `luma` colours are off in some viewers. PNG and SVG is fine.

This example document:
```
#set page(height: auto, width: auto, margin: 5mm)
#rect(width: 2cm, height: 2cm, fill: luma(70%))
#rect(width: 2cm, height: 2cm, fill: rgb("#b3b3b3"))
```
In `0.8.0` stable displays fine in all tested viewers.
![image](https://github.com/typst/typst/assets/38019254/98f9649c-e75f-44e6-9719-7d28133994b2)

After #2171 in some viewers, the `luma` is tinted red.
![image](https://github.com/typst/typst/assets/38019254/9b2f5029-14f1-40a8-8db1-00fe8da9c8a1)

This was tested and failed in Okular and Libre Office Draw. Many more viewers show the correct output. The two that failed share the same renderer, poppler, as pointed out by @Dherse in discord. So it's probably an issue with poppler and ICC profiles and not typst, but I thought an opening an issue was not a bad idea.

Also, the second rect, the RGB colour is a little bit off and display `#b4b4b4` instead of `#b3b3b3`. I can't notice this, only with a colour tool, and it's maybe related to #1927 or a rounding error with ICC profiles. This is not related to this issue.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment] 2023-09-28 16:41
Regarding the error, I would consider an error of 1 to be acceptable, at the end of the day there are rounding errors, and there are the limitations of the ICC profiles, I have tested a bunch of them (about 12 now) and they all give the same output for a given color in all working readers (so not poppler) which tells me that they all work and are all pretty much equivalent. Without ICC however, you are at the mercy of the reader and each reader will give a slightly different output which imo is worse than a 0x00 becoming a 0x01 🤷‍♂️  What I also find reassuring, is that the sRGB and gray profiles provide the same color given a grayscale color so `rgb(x, x, x)` or `luma(x)`.

With regards to poppler, we have coverage of basically most readers (side node: I would expect Acrobat, the Apple one, and Chromium to be the biggest ones although I don't have an exact figure), we even have good support in PDF.js (I have much to say about pdf.js ~~but not today~~), and only poppler seems to be an issue, I would therefore report the bug there although I think somebody had done it (maybe @Enivex but I may recall incorrectly). So in my opinion, poppler has a bug, poppler needs to fix it. ICC profiles have existed since 2 years before I was born, I think it's safe to say that there is no excuse for a reader **29 YEARS** later not to (this goes for you too pdf.js 😠). If it's a conscious desire of the poppler devs not to support it then so be it, but at least it shouldn't be buggy, and if that bug is intended behaviour then they need to give the spec a second read.

Colors and ICC profiles, as previously mentioned, are not new, the fact that some readers manage to f it up is beyond me and shows either a lack of interest in documents looking at they should\* or simply laziness. Yes laziness, some of those readers are not hobby projects, they are serious, large projects with large teams, looking at PDF.js with its 365 contributors and over 17k commits, yet they do not answer me when I offer to implement a missing (yet small) part of the spec on GitHub.

To be clear, I am ranting but it's not targeted at you @Zheoni, it is targeted at terrible readers that do not support features **older than me**. I am very sorry if this feels overly aggressive, I want you to know that I am deeply thankful for your time and patience in opening this issue and letting me explain in details, "on the record" so-to-speak some of the issues at hand. This is a major reasons why gradients have taken **months**. It's not that gradients are particularly hard, it's that PDF readers are terrible (don't think Chromium, the Apple one, and Acrobat are scot free, I have lots to say about them too 😠)

# Rant about pdf.js

Pdf.js is a terrible PDF reader and nobody should use it 😅 

It has no support for ICC profiles (again, THEY ARE 29 YEARS OLD), it has poor support for pattern/shadings which has caused me tremendous headaches when creating gradients (that have yet to be merged), it has horrendous support for PostScript functions, and the one area of the freaking spec they decide to be sticklers about is something nobody else cares about (well done pdf.js). It's ungodly slow (wait 'till you're trying my beautiful conic gradients and PDF.js decides to become the slowest program ever written). Therefore, stay away for your own sanity (and mine).

I also offered to implement some feature into pdf.js bumping an issue that has been outstanding for **9 years** N-I-N-E and I never even got an answer when I offered to fix it and asking for pointers as to where to have a look.

**Comment by laurmaedje** [comment] 2023-09-29 13:04
Fixed by https://github.com/typst/typst/pull/2262

**Closed by laurmaedje** 2023-09-29 13:04 UTC
Labels: bug, visualize
