### ISSUE TITLE
Packaging and semver

### ISSUE THREAD

**Issue by kpcyrd** [typst/typst#157] opened 2023-03-22 15:12 UTC
hi!

I've looked into packaging this (considering the popularity) but noticed there are currently only two tags:

- `22-03-21`
- `22-03-21-2`

The dash `-` character is a reserved character in Arch Linux and some other distros and can't be used. It also seems the version format is `YY-MM-DD` except the year is off-by-one and the number of components is inconsistent because of the "only one release per day" issue.

If I got to make a wishlist I would recommend:

- use dots `.` as a separator
- use a fixed number of version components (`1.0.0`, `1.0.1`) instead of a dynamic number (`1.0`, `1.0.1`)
- [`semver`](https://semver.org/) is very common at this point, but [`0ver`](https://0ver.org/) would also work

Thanks!

**Comment by thecaralice** [comment] 2023-03-26 23:38
0ver is a joke isn't it

**Comment by alerque** [comment] 2023-03-27 12:38
The joke is kind of on all the projects that use it, so giving a name to something everybody is doing just helps clarify what's what.

In any case this is a Rust project and everything Cargo/Crates related has semversion baked in. You don't really have a decision to make here, you guys need to stick a semversion tag on this ASAP and move on. It can start with `v0.0.1` if you don't want to give the impression it is done, or `v0.1.0` which in my opinion better reflects the status, but **start proper versioning already.** This is already a mess in the wild and it will only get worse with the popularity driving it into more distros.

**Comment by laurmaedje** [comment] 2023-03-27 18:02
I have thought about this a bit: If we were to adopt semver, would that be just for the language or for the compiler and its constituting crates? What exactly would be considered breakage? Breakage to the compiler or to the language or to any of the two? 

For now, one could reasonably say either of the two, but in a distant future where the Typst language is mostly stable, the compiler would most probably still have breaking changes quite often. Then, it would be strange to version both in unisono. 

A more practical stance would be to say that only language changes are breaking. But then what would be the versions of the crates release to crates.io? Does it even make sense to release the compiler to crates.io?

I looked at a few other projects and, for instance, in both rust-analyzer and rustc the compiler crates have the version number set to 0.0.0 like Typst right now. And rust-analyzer also uses tag names like 2023-03-27 instead of version numbers. Also, both aren't published to crates.io as normal crates, but in `rustc_ap_...` and `ra_ap_...` form with very high version numbers.

**Comment by kpcyrd** [comment] 2023-03-27 18:41
Arch Linux distributes rust-analyzer 2023-03-27 like this:

```
% pacman -Ss rust-analyzer
community/rust-analyzer 20230320-1
    Rust compiler front-end for IDEs
```

Effectively the dashes are stripped away and combined to one big number. This breaks in unexpected ways for versions like `22-03-21-2`, the additional digit multiplies everything by 10, breaking the version comparison of the update manager because `231231 < 2203212`. It's really just causing problems down the road.

Given the situation you're describing I suggest starting with `0.1.0` and then incrementing the middle number until you've reached the point you want to commit to a 1.0.0 and stabilize your markup language (no breaking changes without a 2.0.0). Up until then you can basically do whatever and make breaking changes to your markup language all you want, Rust only cares about this if you expose a public api as a library for other creates (which people are probably going to request at some point).

**Comment by laurmaedje** [comment] 2023-03-27 18:55
Thanks for the information! The thing is that the `typst` crate does expose a public API and some people requested that it is released to crates.io. I'm wondering if that makes sense and, if so, which version number to use for the compiler.

**Comment by alerque** [comment] 2023-03-29 08:35
I do understand the dilemma. I've been through this for years with [SILE](https://sile-typesetter.org/); versioning is hard when you have all of an input language, CLI tooling, library API calls, and potential variations in output—all of which could be considered "breaking" or not by different people for different reasons. Does changing a default font setting that causes document reflows constitute a breaking change? What about when you fix a bug in language hyphenation that reflows only some documents that could be considered broken to start with?

I'll sketch out what we've settled on that seems to work relatively well:

* We're following semer. I think this is even more of a given for Rust than for the C / Lua mix we're dealing with, but it's a pretty good system anyway.
* Changes to the CLI or API usage such as deprecating interfaces, removing CLI args, etc. are considered breaking major changes. Adding new interfaces / features is a non-breaking minor changes, and bug fixes of course can be just patch releases.
* Document reflows are not automatically considered breaking, but we try hard to lump major breaking ones into releases that are marked as breaking anyway. For example we're working on changing our default leading algorithm, and that is being put off until the next breaking release for other reasons, but when we fixed an issue with line length calculations and ligatures that did cause some minor reflows that was just a patch release since the document changes were *expected* as the result of bug fixes. It is a lot easier to reason about adding/removing/changing API interfaces than whether rendered document differences are breaking, but we try to manage expectations a bit.

We're still in the "zero" phase of semver, so all out versions are offset one field. In semver's MAJOR.MINOR.PATCH we are releasing breaking changes as new MINOR field bumps and everything else as PATCH bumps. When we decide we are feature complete enough to call it v1.0.0, then we'll start incrementing MAJOR for breaking changes only, MINOR for new features/tweaks, and PATCH for bug fixes.

Our input language is pretty stable since we can read regular XML or a dedicated variant with a syntax that looks Tex-like but is actually easy to map to an AST like XML. We also support addons that add inputters (like Markdown) so versioning our input format hasn't really been as much of a consideration as it would be for this project.

I suggest starting from where you are at with `v0.1.0`, doing what we're doing with breaking changes to the API in the second field, everything else in the third, and not going to `v1.0.0` until you figure out what to do about versioning the input language syntax. At the point you stabilize that you'll probably want to put something in the document that identifies newer versions of the document syntax, but I wouldn't mess with that until you figure out how you want to make compatibility guarantees in v1+.

**Comment by mpizenberg** [comment] 2023-04-01 15:29
If parts of the compiler are published as a library that can be reused by the community, it makes sense that these parts are following semver, in the usual sense. "Do this lib changes make my code fail compilation?"

Regarding the compiler itself, we can similarly consider a semver (different from the library) where changes are related to breakage of the consumers of the compiler, i.e. people writing documents. Does my document still compile? no then it's a major change, if yes, does the compiler provides new features to the language? yes then it's a minor change, or no then it's just a patch (performance, ...). I don't think I'd consider appearance changes (layouts, font, ...) in the versioning scheme. Regarding appearance changes, there are so many possible breakage that I'd just suggest saving in the generated document the exact version of the compiler that was used to generate it if people want to reproduce.

**Comment by alerque** [comment] 2023-04-05 10:02
I see the versioning got changed. Much appreciated.

It would be nice to state what schema you are following though. With [semver](https://semver.org/) all three segments (X.Y.Z) should be included all the time, so the current two segment tag v0.1 would have been v0.1.0.

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers

Since Cargo / crates.io uses semver that is probably what you should stick to. For distro packaging we can cope with the dropped segment (which some other schemes like [Haskell PVP](https://pvp.haskell.org/) use, but again please state what scheme you are following (even if it's one you make up your own rules) so we all know what to expect.

**Comment by laurmaedje** [comment] 2023-04-05 14:40
@alerque Any particular place where you would like me to add a note about the versioning scheme?

**Comment by alerque** [comment] 2023-04-05 14:57
Probably dropping it in the GitHub Release notes for the first version actually using SemVer would do the job for most distro packagers. If there is a technical notes aimed at packagers somewhere that could work too. Honestly since Cargo enforces it though semver is just assumed for Rust projects and the only questions about how to handle it arise when the project *isn't* following it. If you start following semver I doubt anybody will think twice about the issue again.

**Comment by alerque** [comment] 2023-04-05 14:57
(and with that, this issue can probably be closed)

**Comment by laurmaedje** [comment] 2023-04-05 15:07
I added a note to the latest release.

**Closed by laurmaedje** 2023-04-05 15:07 UTC
Labels: devops
