### ISSUE TITLE
`show-set` rules are not overwriteable like `set` rules

### ISSUE THREAD

**Issue by glambrechts** [typst/typst#2723] opened 2023-11-20 14:30 UTC
### Description

I don't know if the current behaviour is intend or not.

But similar to how it possible to change settings with `set` rules,
```typst
hello
#set text(fill: red)
hello
#set text(fill: black)
hello
```
it would be great to be able to do the same with `show-set` rules.
```typst
$(a + b)$
#show math.equation: set text(fill: red)
$(a + b)$
#show math.equation: set text(fill: black)
$(a + b)$
```
![show](https://github.com/typst/typst/assets/57069365/de7bb7fb-560d-485d-9a12-76fe66252ef1)

However, it seems that after a `show-set` rule was set, it is impossible to change it locally.
This is true even in a restricted scope: the following code does not work either.
```typst
$(a + b)$
#show math.equation: set text(fill: red)
$(a + b)$
#{
  show math.equation: set text(fill: black)
  $(a + b)$
}
```

### Use Case

It would be particularly useful in order to still be able to custom styling after having imported a package or a template that plays with `show-set` rules.

**Comment by laurmaedje** [comment] 2023-11-20 15:59
Duplicate of https://github.com/typst/typst/issues/351

**Closed by laurmaedje** 2023-11-20 15:59 UTC
Labels: feature request
