### ISSUE TITLE
`regex` seems broke text `tracking`

### ISSUE THREAD

**Issue by Daillusorisch** [typst/typst#5466] opened 2024-11-25 07:12 UTC
### Description

```typst
#show regex("[\p{scx:Han}]"): it => it 
#set text(tracking: 16pt)
*利用Typst中西文混排不同字体*
```
Compare the results between with and without the regex rule.
![with regex](https://github.com/user-attachments/assets/45b62324-4bf7-4dda-b897-95263825b05b)

![without regex](https://github.com/user-attachments/assets/c4136652-8c1d-40a3-a421-355259efb932)

Moreover, you can not use regex to set tracking. You can see the font setting have taken effect, but tracking has not.

![with tracking settings](https://github.com/user-attachments/assets/fef44525-3f85-4227-9750-bde0ecf326c0)

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by TS53** [comment] 2024-11-25 17:48
This is a duplicate of https://github.com/typst/typst/issues/5353, I think. At the point where some show rule matches, the tracking breaks.

**Comment by laurmaedje** [comment] 2024-11-25 19:09
It is indeed a duplicate. When writing a regex show rule on a script, I'd highly recommend to add a `+` to the regex so that you don't get each char separately.

**Closed by laurmaedje** 2024-11-25 19:09 UTC
Labels: bug
