### ISSUE TITLE
`style` should return `any` instead of `content`

### ISSUE THREAD

**Issue by iwilare** [typst/typst#2382] opened 2023-10-13 09:07 UTC
### Description

It would be desirable for `style` to return rather than whatever the inner function returns, rather than something with type `content`. Is there any technical reason why this is the case?

### Use Case

A simple use case is to obtain the length of the some content.
For example, the following raises an error `cannot add content and integer`:

```typst
#let a = style(s => measure("Hello", s).width)

#(a + 3)
```

**Comment by MDLC01** [comment] 2023-10-13 09:20
The problem is that `style` must return something as soon as it is called. Currently, it returns content that is not "resolved" until later on. But if style could return anything, it would have to be known whenever `style` is called (not when the passed callback is called).

The solution in your case is
```typst
#let a = style(s => {
  let a = measure("Hello", s).width
  a + 3
)
```
which illustrates that the expression `#(a + 3)` must be computed every time the function passed to `style` is called.

**Comment by iwilare** [comment] 2023-10-13 10:00
I see; my true use case actually involves a function which, ideally, should return a dictionary with some content and some length which is not directly related to the content itself. The `style` function is necessary to compute the length itself, but the problem now becomes that I cannot return the dictionary, since it is going to be "wrapped" as `content`. Here are some solutions I was thinking about:

- Is it possible to unwrap the `content` returned by style, and get the data returned by the inner function?
- Alternatively, is it possible to directly attach some metadata to the content, so that this can be retrieved later/used by other functions?

Elaborating on this last point, it would be extremely useful to be able to have some data (e.g. a dictionary) which contains data but is displayed as content when it's placed in a block; is there any way to do this, currently? Another solution would be to attach or wrap additional fields to something with type `content`.

**Comment by Dherse** [comment] 2023-10-13 14:11
I can point you towards @laurmaedje's [blog post](https://laurmaedje.github.io/posts/types-and-context/) where he discusses the future where we might have a concept of `context` which would allow this to be possible. But it won't be a whole before we have that.

> Is it possible to unwrap the content returned by style, and get the data returned by the inner function?

AFAIK no

> Alternatively, is it possible to directly attach some metadata to the content, so that this can be retrieved later/used by other functions?

Content can just be reused by storing it in a variable and calling it if that's what you mean?

**Comment by iwilare** [comment] 2023-10-13 14:32
By the second bullet point I meant more like effectively adding an extra field to something which has type `content` and then be able to refer to it. Again, this wouldn't be a problem because we could just make `style`  a dictionary with two fields, one with content and one with data. But I think the existence of that blog post answers my questions more or less, thanks :)

**Comment by francoisthire** [comment] 2023-10-14 09:29
I have a similar issue.

I want to define a function like `get_width` that would give me the `width` of the content given in parameters and then print a line of this length.

A snippet of what I was expected to write:

```typst
#let foo = ["something"]

#let get_width(body) = style(style => measure(body,style).width)

#line(length: get_width(foo))
```

I feel like I cannot write such a `get_width` function. Instead, I have to parameterize all my commands by a type `style` parameter and only do the printing at the end by calling the `style` function. This is a bit sad in terms of modularity.

**Comment by Enivex** [comment] 2023-10-14 14:14
> I have a similar issue.
> 
> I want to define a function like `get_width` that would give me the `width` of the content given in parameters and then print a line of this length.
> 
> A snippet of what I was expected to write:
> 
> ```typst
> #let foo = ["something"]
> 
> #let get_width(body) = style(style => measure(body,style).width)
> 
> #line(length: get_width(foo))
> ```
> 
> I feel like I cannot write such a `get_width` function. Instead, I have to parameterize all my commands by a type `style` parameter and only do the printing at the end by calling the `style` function. This is a bit sad in terms of modularity.

What you're trying to do is indeed not possible (by design), but you can you do the following:

```
#let foo = ["something"]
#let myline(body) = {
  style(style => {
    line(length: measure(body,style).width)
  })
}

#foo
#myline(foo)
```

![image](https://github.com/typst/typst/assets/2191754/033e8e99-5265-4509-b16a-d3d7aadb8fa2)

**Comment by laurmaedje** [comment] 2023-10-14 14:18
It's not the most intuitive right now, but that will hopefully improve with the context proposal. Since aside from that, it's working as intended and also working like this for good reason, I'm going to close this.

**Closed by laurmaedje** 2023-10-14 14:18 UTC
Labels: feature request, meta

**Comment by francoisthire** [comment] 2023-10-14 21:10
Maybe we could improve the documentation to better reflect this.
