### ISSUE TITLE
Allow the Grid layout to populate cells in column-major order

### ISSUE THREAD

**Issue by alping** [typst/typst#4199] opened 2024-05-20 15:20 UTC
### Description

Currently the Grid Function populates its cells in row-major order, with no option to change this to column-major order.

> The cells are populated in row-major order.

https://typst.app/docs/reference/layout/grid/

This makes it difficult to have layouts like this (e.g. for a poster):

![grid-layout](https://github.com/typst/typst/assets/11225857/ce188909-6db8-4cab-aadc-77d27a80776f)

To achieve this layout now, cells 2 and 3 need to be swapped in the Grid layout, making the content of those cells appear out of order in the source code and the table of contents in the exported PDF:

```typst
#set page(margin: 1cm, fill: rgb("#eeeeee"))
#set align(center + horizon)
#set text(size: 2cm)
#set grid.cell(fill: white, stroke: black + 1mm)

// Row-major order
#block(
  grid(
  columns: (1fr, 1fr),
  rows: (5cm, 1fr, 5cm),
  gutter: 1cm,
  heading[1],
  grid.cell(rowspan: 2, heading[2]),
  grid.cell(rowspan: 2, heading[3]),
  heading[4],
))

#pagebreak()

// What the output would look like with column-major order.
// To achieve this now, cell 2 and 3 need to be swapped, making
// the content of those cells appear out of order in the source
// code and the table of contents in the exported PDF.
#block(
  grid(
  columns: (1fr, 1fr),
  rows: (5cm, 1fr, 5cm),
  gutter: 1cm,
  heading[1],
  grid.cell(rowspan: 2, heading[3]),
  grid.cell(rowspan: 2, heading[2]),
  heading[4],
))
```

This would be fixed by adding a parameter `order: row | column` (default to `row`) to the Grid function.

### Use Case

The option to have column-major order in the Grid layout would allow for more types of layouts while preserving a logical order of the contents in the source code and the table of contents of the exported PDF.

**Comment by Enivex** [comment] 2024-05-20 15:25
The request for column-major order is essentially a duplicate of https://github.com/typst/typst/issues/2442

That being said, I don't think a grid is a natural tool for layouting the poster in your picture. You would be better off using https://typst.app/docs/reference/layout/columns/

**Closed by Enivex** 2024-05-20 15:25 UTC
Labels: feature request

**Comment by alping** [comment] 2024-05-20 15:52
Thanks for the reply. I see how this is similar to #2442, although here for the Grid layout.

To me (coming from web design), Grid seems like the perfect tool for making a layout for a poster. Any suggestion for how I can achieve the same with columns? The closest I could get was:

```typst
#set page(margin: 1cm, fill: rgb("#eeeeee"))
#set align(center + horizon)
#set text(size: 2cm)

#columns(2, gutter: 1cm)[
  #set block(width: 100%, breakable: false, fill: white, stroke: black + 1mm)
  
  #block(height: 5cm, heading[1])
  #block(height: 100% - 5cm - 1cm - 2cm, heading[2])
  #block(height: 100% - 5cm - 1cm - 2cm, heading[3])
  #block(height: 5cm, heading[4])
]
```

But then the vertical space between the blocks is not uniform with the rest of the white space and the block definition inside the columns layout messes with the heading blocks.

**Comment by Enivex** [comment] 2024-05-20 15:55
> Thanks for the reply. I see how this is similar to #2442, although here for the Grid layout.
> 
> To me (coming from web design), Grid seems like the perfect tool for making a layout for a poster. Any suggestion for how I can achieve the same with columns? The closest I could get was:
> 
> ```typst
> #set page(margin: 1cm, fill: rgb("#eeeeee"))
> #set align(center + horizon)
> #set text(size: 2cm)
> 
> #columns(2, gutter: 1cm)[
>   #set block(width: 100%, breakable: false, fill: white, stroke: black + 1mm)
>   
>   #block(height: 5cm, heading[1])
>   #block(height: 100% - 5cm - 1cm - 2cm, heading[2])
>   #block(height: 100% - 5cm - 1cm - 2cm, heading[3])
>   #block(height: 5cm, heading[4])
> ]
> ```
> 
> But then the vertical space between the blocks is not uniform with the rest of the white space and the block definition inside the columns layout messes with the heading blocks.

I would suggest you make a thread in the support channel on the Discord

**Comment by laurmaedje** [comment] 2024-05-20 16:11
If the four rectangles are essentially separate and distinct, I think that grid is probably the right tool. If they are somewhat continuous and the whole thing might stretch across more pages, columns could be better.

**Comment by laurmaedje** [comment] 2024-05-20 18:01
Note that you can also override grid cell positions manually with x/y. That way, you can use whatever source order you want.

**Comment by laurmaedje** [comment] 2024-05-20 21:39
> However, the outline/table of contents is still in the wrong order. Not that important for a poster of course.

That's an interesting observation. cc @PgBiel

**Comment by PgBiel** [comment] 2024-05-21 02:25
> > However, the outline/table of contents is still in the wrong order. Not that important for a poster of course.
> 
> That's an interesting observation. cc @PgBiel

This is definitely something I didn't consider when column-major cell specification was first requested. The only related feature (besides specifying cells in a different order in the source) I could think of at the time would be to have the grid "pagebreak to the right" when adding columns. But changing the order in which cells are laid out could be useful as well (for outline, counters, and so on).

I wonder if it could be made generic enough to be able to freely specify the order in which grid cells are placed. Sounds like this would require some sort of z-index parameter to work properly though.

**Comment by PgBiel** [comment] 2024-05-21 02:27
With that said, reordering in the source without specifying x/y parameters to each cell is possible, but requires making a custom function which divides the cells into arrays of columns (e.g. `(([first at col0], [second at col1]), ([first at col2], [second at col2]), ...)`) and uses `array.zip(..columns)` to transpose them into rows. You can then use `table(..transposed.flatten())` to pass the cells to the table / grid.

But this won't fix the aforementioned layout order problem.
