### ISSUE TITLE
Show rules for specific list level 

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4676] opened 2024-08-04 23:38 UTC
### Description

From the following example I reckon that lists don't have enough structure exposed to effectively match different levels in show rules, or even to match just the top level and programmatically find the target level from there.

A depth count attribute will make show rule matching trivial, while a parent reference will make it at least possible without ambiguities.

```
#show list: it => [#it.fields() #it]
- First item on level 1
  - second item on level 2
  - third item on level 2
```
![page-1](https://github.com/user-attachments/assets/817f6000-1132-439e-b2dc-936c39fda5fa)

### Use Case

Motivated by https://discord.com/channels/1054443721975922748/1088371919725793360/1269790642704351262

**Comment by memeplex** [comment] 2024-08-04 23:42
Perhaps relevant https://github.com/typst/typst/issues/1926

**Comment by Enivex** [comment] 2024-08-05 06:38
Duplicate of https://github.com/typst/typst/issues/4520

**Closed by Enivex** 2024-08-05 06:38 UTC
Labels: feature request
