### ISSUE TITLE
Inconsistency with `#show regex(...)`

### ISSUE THREAD

**Issue by zakhenry** [typst/typst#3855] opened 2024-04-03 06:51 UTC
### Description

I might be wrong here, but I think with the following I would expect all text in the document that matches the regex to have the rules applied, but instead the regex is only applied to elements that are output from variables

```
= show regex issue

#show regex("\d\d?:\d\d[pa]m"): it => [
  #set text(fill: red)
  *#it*
]

#let time = "12:35pm"

- 12:35pm - not highlighted
- #time - highlighted

== no colon


#show regex("\d\d?\d\d[pa]m"): it => [
  #set text(fill: green)
  *#it*
]

#let time2 = "1235pm"

- 1235pm - highlighted
- #time2 - highlighted
```

oddly, the issue goes away if my regex doesn't have a colon in it, which to my knowledge is not a char that needs to be escaped (and that doesn't help anyway)

### Reproduction URL

https://typst.app/project/rFRgkVamhUWSIH0xY8yPQ6

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by yagshi** [comment] 2024-04-03 07:47
I have the same problem.  Actually, simple pattern match also produces the similar result.  Only colon-with-any-character seems to cause.  
typst 0.11.0 (b3615ccd)
```
#show "A;": a => text(red, a)
#show "A:": a => text(red, a)
A;A:
```
![colon_problem](https://github.com/typst/typst/assets/2875122/2a340327-bcfb-4e09-a323-21563ee3c77b)

**Comment by laurmaedje** [comment] 2024-04-03 08:49
Duplicate of https://github.com/typst/typst/issues/86

**Closed by laurmaedje** 2024-04-03 08:49 UTC
Labels: bug

**Comment by MasterTemple** [comment] 2024-08-27 04:59
I have the same issue inside a `#show regex()` function with the colon `:`, but it works with other characters.
I have also noticed that the dot/period `.` is interpreted as `\.` and not a wild-card.
Here is the example code
```typ
#let re = regex("Age (\d+)")  // matches "Age 47"
#let re = regex("Age: (\d+)") // matches nothing
#let re = regex("Age. (\d+)") // matches only "Age. 47"

#show re: it => {
  let age = it.text.match(re).captures.at(0)
  [#age years old]
}

Age 47

Age: 47

Age. 47
```
