### ISSUE TITLE
It seems that the CJK character length causes a bug when using the auto parameter

### ISSUE THREAD

**Issue by Rsweater** [typst/typst#5516] opened 2024-12-04 02:09 UTC
### Description

**Description:** As shown in the two images below, when I set `width: 6cm`, the grid is in the center due to `align(center)`. However, when I set it to `width: auto`, the grid flies straight to left on page. I assume this is because CJK characters are 3 characters long by default, but the auto parameter might be standardized to 1 character?
![image](https://github.com/user-attachments/assets/0146c321-467e-495c-a60f-544f74437dba)
![image](https://github.com/user-attachments/assets/76d841e6-0626-4874-96ef-9a1cefa1de0c)

**Comparison:** although the English characters don't seem to be in the center either, there's no problem with them flying directly to the edge of the page.
![Code exe_20241204_100757](https://github.com/user-attachments/assets/73d55928-c7c4-42f3-a8df-4b18a2871dce)

This is the address of the relevant code: 
https://github.com/Rsweater/cug-thesis-typst/blob/d9f234f20127248fd47d35ef05b32a802247dd1d/pages/postgraduate/titlepage.typ#L121

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2024-12-04 05:09
it would be easier to fix(if it's a bug) if you can provide a minimal reproduction of the bug.

> I assume this is because CJK characters are 3 characters long by default, but the auto parameter might be standardized to 1 character?

this is not how `auto` works afaik.

**Comment by Rsweater** [comment] 2024-12-04 06:17
Sorry, 
1. could you go into more detail about the reproduction issue: what kind of display is desired? 
2. the comparison picture above is to illustrate the problem when English characters don't fly straight to the edge of the page. Unfortunately, the screenshot shows the code incorrectly, it should be the one below. 
![局部截取_20241204_141710](https://github.com/user-attachments/assets/8411d2a2-231f-4db5-b13e-fdf092295d2e)

Doubtful, the role of this `auto` should be adaptive content length? But why do Chinese characters fly to the edge of the page when there is still plenty of room for them to be displayed in the PDF, but English characters do not?
![录屏_20241204_141555](https://github.com/user-attachments/assets/db12df9a-baf6-4606-9293-a079849fbeb9)
![录屏_20241204_141631](https://github.com/user-attachments/assets/2a5a348a-5f4b-4381-ac32-f63c5857afb4)

**Comment by PgBiel** [comment] 2024-12-04 06:23
@Enter-tainer is requesting a minimal code example which you can paste here so we can play with it and test. It should showcase a situation where the only difference between the two samples is whether CJK characters are present and the "left alignment" you mention occurs. If you can reproduce it that way, it _could_ be a bug in Typst. If not, it's probably because of what you're doing in your particular document (which we don't have access to).

There's way too much going on in your picture, so lots of things we don't see (such as show rules) could be affecting the grid. But in particular, I noticed that you are using functions such as `info-style`. Those functions could be inserting blocks, spacing and other elements which have a larger width than 6cm, therefore `auto` - which simply measures the width of each cell in each column and uses the largest reported width - ends up reporting a larger measured width for those cells due to what `info-style` and others returned. Without all definitions, it is not possible to tell.

So, an ideal minimal example would remove `info-style` and have basically only two grids with English and CJK text. Maybe a bit of styling if you want help debugging the styling itself, but not much more than that.

**Comment by Rsweater** [comment] 2024-12-04 06:49
Thanks ~ Thanks for being so patient in responding to my issue. 
a minimal code example：https://typst.app/project/w7oZcSijuVmJAxDFlD6m9b
```
#set text(font: ("New Computer Modern", "Noto Serif CJK SC"), lang: "zh")
#let info-style(
  body, 
  weight: "regular",
  size: 16pt,
  align-type: left
) = {
  rect(
    width: 100%, 
    stroke: none,
    text(size: size, 
      weight: weight,
      align(align-type, body)
    )
  )
}

#set align(center+horizon)
#block(width: auto, height: auto,grid(
  align: (center, left),
  columns: (4.33cm, 6cm),
  rows: (1.25cm, auto, 1.25cm, auto, auto),
  info-style("姓名：", align-type: right),
  info-style("张三"),
  info-style("专业学位类型：", align-type: right),
  info-style("工程硕士"),
  info-style("Supervisor：", align-type: right),
  info-style("Li Si"),
))

#set align(center+horizon)
#block(width: auto, height: auto,grid(
  align: (center, left),
  columns: (4.33cm, auto),
  rows: (1.25cm, auto, 1.25cm, auto, auto),
  info-style("姓名：", align-type: right),
  info-style("张三"),
  info-style("专业学位类型：", align-type: right),
  info-style("工程硕士"),
  info-style("Supervisor：", align-type: right),
  info-style("Li Si"),
))

```

**Comment by Rsweater** [comment] 2024-12-04 06:54
> @Enter-tainer @PgBiel Thanks ~ Thanks for being so patient in responding to my issue. a minimal code example：https://typst.app/project/w7oZcSijuVmJAxDFlD6m9b
> 
> ```
> #set text(font: ("New Computer Modern", "Noto Serif CJK SC"), lang: "zh")
> #let info-style(
>   body, 
>   weight: "regular",
>   size: 16pt,
>   align-type: left
> ) = {
>   rect(
>     width: 100%, 
>     stroke: none,
>     text(size: size, 
>       weight: weight,
>       align(align-type, body)
>     )
>   )
> }
> 
> #set align(center+horizon)
> #block(width: auto, height: auto,grid(
>   align: (center, left),
>   columns: (4.33cm, 6cm),
>   rows: (1.25cm, auto, 1.25cm, auto, auto),
>   info-style("姓名：", align-type: right),
>   info-style("张三"),
>   info-style("专业学位类型：", align-type: right),
>   info-style("工程硕士"),
>   info-style("Supervisor：", align-type: right),
>   info-style("Li Si"),
> ))
> 
> #set align(center+horizon)
> #block(width: auto, height: auto,grid(
>   align: (center, left),
>   columns: (4.33cm, auto),
>   rows: (1.25cm, auto, 1.25cm, auto, auto),
>   info-style("姓名：", align-type: right),
>   info-style("张三"),
>   info-style("专业学位类型：", align-type: right),
>   info-style("工程硕士"),
>   info-style("Supervisor：", align-type: right),
>   info-style("Li Si"),
> ))
> ```

oh~ my god. Surprisingly, it is a rect problem, originally thought that rect in width: 100%, can be realized full of spaces, equivalent to Word directly inside the table to fill in the content of the effect. Sorry, this is a personal oversight~

There's nothing wrong with the one below：
```
#set text(font: ("New Computer Modern", "Noto Serif CJK SC"), lang: "zh")
#let info-style(
  body, 
  weight: "regular",
  size: 16pt,
  align-type: left
) = {
    text(size: size, 
      weight: weight,
      align(align-type, body)
    )
}

#set align(center+horizon)
#block(width: auto, height: auto,grid(
  align: (center, left),
  columns: (4.33cm, 6cm),
  rows: (1.25cm, auto, 1.25cm, auto, auto),
  info-style("姓名：", align-type: right),
  info-style("张三"),
  info-style("专业学位类型：", align-type: right),
  info-style("工程硕士"),
  info-style("Supervisor：", align-type: right),
  info-style("Li Si"),
))

#set align(center+horizon)
#block(width: auto, height: auto,grid(
  align: (center, left),
  columns: (4.33cm, auto),
  rows: (1.25cm, auto, 1.25cm, auto, auto),
  info-style("姓名：", align-type: right),
  info-style("张三"),
  info-style("专业学位类型：", align-type: right),
  info-style("工程硕士"),
  info-style("Supervisor：", align-type: right),
  info-style("Li Si"),
))

```

**Comment by PgBiel** [comment] 2024-12-04 06:59
Thanks for the example! That's much better.

The problem is precisely that: you are using a rect of width 100%. Now, note that `auto` measures the width of each cell. Therefore, the width of an `auto` column depends on the width of each cell in the column. However, for your cell to fit the whole column with 100%, it would depend on the width of the column, but that depends on the width of the cell, so it's circular at first (need to pick one).

By default, Typst solves this by setting 100% to mean the full width of the page inside an auto column, and equal to the column width in fixed-size columns. This is a good default in general when using `grid` as a more lightweight abstraction, that is, when you're just taking something that's already there and adding it to a grid. But, in theory, it's also possible for auto column measurement to simply ignore certain kinds of cells when measuring the column, breaking the circularity and allowing them to be laid out later with 100% = column width. This is what was proposed in https://github.com/typst/typst/issues/4000, but it's currently blocked as a proper decision wasn't made yet.

In the meantime, you can use a fixed size column as you were doing.

**Comment by PgBiel** [comment] 2024-12-04 07:01
Since this isn't a bug, I'll be closing for now, but don't hesitate to ask for further help in our support channels, such as our [forum](https://forum.typst.app) or Discord (link at https://typst.app).

**Closed by PgBiel** 2024-12-04 07:01 UTC
Labels: bug

**Comment by Rsweater** [comment] 2024-12-04 07:28
@PgBiel Thank you very much for your detailed Q&A! 
Good luck!
