### ISSUE TITLE
Indentation in Edge case with emphasis and hypen

### ISSUE THREAD

**Issue by testunde** [typst/typst#2085] opened 2023-09-08 14:49 UTC
### Description

The following:
```typst
#show: rest => columns(2, rest)
#set par(justify: true)
#set text(size: 10pt)

#lorem(14) _ABCD-1_, #lorem(30)
```

Produces:
![Unbenannt](https://github.com/typst/typst/assets/1365300/1e87d83f-8108-4d53-8d61-3e2409abad2c)

Note the indentation after the "ABCD-1," part of the text. This should not be happen, or am I missing something?

Also happens with `#text[#lorem(14) _ABCD-1_, #lorem(30)]`.

### Reproduction URL

https://typst.app/project/rWe09ZnFzv4hggqWtRMGbx

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-09-08 14:50
Duplicate of https://github.com/typst/typst/issues/1794

This has been fixed on main

**Closed by Enivex** 2023-09-08 14:50 UTC
Labels: bug

**Comment by testunde** [comment] 2023-09-08 14:53
Ah yes, sorry for not looking thoroughly enough through the issues >.<

Thanks for You work!
