### ISSUE TITLE
Ability to set comma as a decimal separator for numbers in math mode

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5272] opened 2024-10-21 20:17 UTC
### Description

Current behavior:

```typ
$0.5$

#set text(lang: "ru")
$0,5$
```

![image](https://github.com/user-attachments/assets/f0bff75e-e178-401f-a554-8b7b7e872622)

I want to set language to Russian and get:

```typ
$0class("normal", ",")5$

#show math.equation: it => {
  show regex(","): math.class.with("normal")
  // show "0,5": none
  it
}
// #show "0,5": none

$0,5$
```

![image](https://github.com/user-attachments/assets/02d7c224-494a-4b58-ab50-f05c58801f69)

There could be a `0.5` in code and `0,5` in output as a middle ground, but this would be weird to write period, while you would usually write comma.

### Use Case

Better math support/typesetting for different standards/formats/countries (e.g., Russia).

**Comment by Enivex** [comment] 2024-10-21 20:28
Duplicate of https://github.com/typst/typst/issues/1093

**Closed by Enivex** 2024-10-21 20:28 UTC
Labels: feature request
