### ISSUE TITLE
Links in footnotes run off the page when justify is set to true

### ISSUE THREAD

**Issue by lachlan2k** [typst/typst#2424] opened 2023-10-17 21:13 UTC
### Description

As per title, links in footnotes run off the page when justify is set to true.

Reproduction code:
```typ
#set par(justify: true)

This is a test#footnote[https://example.com/Loremipsumdolorsitamet,consecteturadipiscingelit,seddoeiusmodtemporincididuntutlaboreetdoloremagnamaliquamquaeratvoluptatem.].
```

Screenshot of issue:
![image](https://github.com/typst/typst/assets/4683714/efed87cd-0f75-488c-8b0b-1f5a95300fb6)

For anyone needing a temporary workaround:
```typ
#show footnote.entry: set par(justify: false)
```

Thanks for your time!

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2023-10-17 21:26
Duplicate of https://github.com/typst/typst/issues/1271

(It's not really specific to footnotes)

**Closed by Enivex** 2023-10-17 21:26 UTC
Labels: bug
