### ISSUE TITLE
The figure numbering and its reference are inconsistent.

### ISSUE THREAD

**Issue by LIIHWF** [typst/typst#2980] opened 2023-12-16 10:35 UTC
### Description

I need a numbering style for tables, images, and raws (in the figure context) of the form "1.1". For example, the first table in the second section should be numbered as Table 2.1

I implemented the numbering style in the following way:

```
show heading.where(level: 1): it => {
  it
  counter(figure.where(kind: table)).update(0)
}

show heading.where(level: 1): it => {
  it
  counter(figure.where(kind: image)).update(0)
}

show heading.where(level: 1): it => {
  it
  counter(figure.where(kind: raw)).update(0)
}

set figure(numbering: (..nums) => 
  [#counter(heading).display((..heading_nums) => heading_nums.pos().at(0))\.#nums.pos().at(0)]
)
```

Then, I wrote the following text:

```
= Section 1

The reference to Table A: @tab-a

#figure(
  caption: [The table in section 1],
  table([Table A])
)<tab-a>

= Section 2

The reference to Table B: @tab-b

#figure(
  caption: [The table in section 2],
  table([Table B])
)<tab-b>
```

However, I got the following result. **Note that the reference shown in the red box is inconsistent with the real numbering**.

<img width="533" alt="Screenshot 2023-12-16 at 18 32 37" src="https://github.com/typst/typst/assets/17021693/572c5843-d8c2-4f79-b87a-9ff47f5e9d7e">

It seems to be normal when I remove the reference to Table A.

<img width="524" alt="image" src="https://github.com/typst/typst/assets/17021693/07dabc9c-27b0-489d-a0fc-7a05b8561b1d">

### Reproduction URL

https://typst.app/project/rz1aunoNRDy8QhgxYqMBb3

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by lkndl** [comment] 2023-12-16 15:40
I don't have a *real* fix but I find this very funny. Using [this](https://typst.app/docs/reference/model/ref/), here  is a workaround to insert after `set figure`:
```rs
show ref: it => {
  let el = it.element
  if el != none and el.has("kind") and el.kind in (table, image, raw) {
    // Override references.
    [#counter(heading).at(el.location()).first()\.#counter(figure.where(kind: el.kind)).at(el.location()).first()]
  } else {
    // Other references as usual.
    it
  }
}
  ```

**Comment by LIIHWF** [comment] 2023-12-16 16:12
@lkndl, thanks for your code! It works for me.

Just out of interest, I want to know whether the inconsistency is due to some flaw in the system. My implementation of the numbering may not be the best practice. But in any case, the reference should be consistent with the label. I would greatly appreciate it if anyone could explain or fix this issue.

**Comment by EpicEricEE** [comment] 2023-12-16 16:29
With `counter(heading).display(...)`, typst shows the numbering at the position where it is called. When the reference is displayed, it gets the `numbering` argument from the figure and evaluates that function at the reference location (and not at the figure location). See also #1057, #1896 and #2652.

There is a package for doing what you want though, it's called [`i-figured`](https://github.com/RubixDev/typst-i-figured?tab=readme-ov-file#usage).

**Comment by LIIHWF** [comment] 2023-12-16 17:29
@EpicEricEE Thanks for your explanation! I think the issue has been discussed in #1896.

The issue may be the nature of the Typst language. But I still hope this issue can be fixed in some way. The inconsistency between the text of reference and the label is really weird as a typesetting system.

**Comment by laurmaedje** [comment] 2023-12-16 20:44
Closing as duplicate of https://github.com/typst/typst/issues/1057

**Closed by laurmaedje** 2023-12-16 20:44 UTC
Labels: bug
