### ISSUE TITLE
Ability to specify spacing between (heading and heading) & (heading and text) 

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4281] opened 2024-05-29 02:17 UTC
### Description

I have requirements (based on GOST standard, but I wasn't able to find every statement in the standard) to add 2 intervals between adjacent `heading`s and 3 or 4 intervals between `heading` and a "text" (GOST R 7.0.11-2011 section 5.3.5 states only "3" and not "4").

Currently, you can only change spacing between `heading` and "everything". As was suggested by others this can be solved by adding more customizable selectors such as `heading.adjacent-with(heading)` or `heading.previous-neighbor(not heading)`. I don't really care about details as long as I can fulfill the requirements.

I essentially need:

```typ
#show heading.next(heading): set heading(below: 0pt) // If they will accumulate.
#show heading.previous(heading): set heading(above: 2em) // Considering `1em` is distance between baselines, which it isn't for now.

#show heading.previous(not heading): set heading(above: 3em) // `not heading` means "text".
#show heading.next(not heading): set heading(below: 3em)
```

Related: #3127, #4224, https://github.com/typst/typst/issues/159#issuecomment-1609939896

### Use Case

Greatly improves spacing around `heading`s in documents. Very important, at least in Russia.

**Comment by GGP305** [comment] 2024-06-03 09:01
Hey there! I just wanted to let you know that i've kind of solved my issue which was similar to yours.

I was trying to add spacing befor each 2nd level heading _except_ the first one (to avoid extra spacing after the chapter title.

I was able to do this with the following show rule:
```typst
#show heading.where(level: 2): h => {
  context{
    let elems = query(selector(heading).before(here()), )

    if elems.at(elems.len() - 2).level >= 2 {
      v(25pt)
    }
  }
  h
}
```

If you tinker a little bit with the parameters of the query and the filtering i think you should be able to acomplish this quite easily

**Comment by Andrew15-5** [comment] 2024-06-03 09:21
I already solved this myself. I just don't like to build hacks to achieve a very common styling.

I think your snippet doesn't account for the fact that above there could be text instead of heading, and that's the core of my problem.

**Comment by Enivex** [comment] 2024-06-03 10:45
I consider this to be a duplicate of https://github.com/typst/typst/issues/1699 (really a special case of)

**Closed** 2024-06-03 10:45 UTC
Labels: duplicate, feature request

**Comment by Andrew15-5** [comment] 2024-06-03 11:20
Shouldn't this be marked as completed? If the #1699 will be completed, then this will also be completed automatically.

**Comment by Enivex** [comment] 2024-06-03 11:23
> Shouldn't this be marked as completed? If the #1699 will be completed, then this will also be completed automatically.

Unfortunately GitHub has only two different ways of closing an issue: completed and not planned. Neither are optimal, but duplicate typically falls under the second.

**Comment by Andrew15-5** [comment] 2024-06-03 12:19
> > Shouldn't this be marked as completed?

> Unfortunately GitHub has only two different ways of closing an issue: completed and not planned.

Why "unfortunately" when I said what you've said?

> Neither are optimal, but duplicate typically falls under the second.

I saw many times that issues are closed as completed and marked as duplicate. It feels weird that it's "not planned" and yet the planning continues in another issue.

**Comment by Enivex** [comment] 2024-06-03 12:29
> Why "unfortunately" when I said what you've said?

Unfortunately because it would be useful to have more granular reasons

> I saw many times that issues are closed as completed and marked as duplicate. It feels weird that it's "not planned" and yet the planning continues in another issue.

Feel free to check https://github.com/typst/typst/issues?q=is%3Aissue+label%3Aduplicate+is%3Aclosed . The vast, vast majority of them are "note planned".

**Comment by alexanderkoller** [comment] 2024-06-19 20:06
Have either of you figured out a workaround that works with the current version of Typst?

I am specifically interested in the use case where I want the padding below the level-1 heading to be reduced if it is immediately followed by a level-2 heading. This is something that seems to happen a lot in LaTeX styles, which I would like to replicate in Typst.

One can easily adapt @GGP305 's code snippet to add negative padding on top of the level-2 heading if the most recent heading is level-1 (just add an else clause), but then (as @Andrew15-5 says), the negative padding is also added on top of the level-2 heading if there is some text between it and the level-1 heading, e.g.

```
= Big heading

Some text.

== Small heading
```

Do we know of a way to only add padding above a heading if the heading is immediately preceded by another heading? Or do we have to wait for completion of #1699? And do we have any sense of when that might be?

**Comment by Andrew15-5** [comment] 2024-06-19 21:05
This is my latest (dirty) version of how I accomplished what I needed:

<details><summary>snippet</summary>

```typ
#let sequence = [].func()
#let space = [ ].func()
#let styled = [#set text(red)].func()

#let template(doc) = {
  // show heading: set block(above: leading * 3, below: leading * 3)
  // show heading: set block(spacing: leading * 2)
  show heading: set block(spacing: 0pt)
  // show heading: set block(above: leading * 2, below: leading * 2)
  let heading-heading-leading = 2em
  let heading-heading-leading = 2em - 0.65em
  // let heading-text-leading = 3em
  let heading-text-leading = 3em - 0.75em
  let heading-text-leading = 3em - 0.75em - 0.75em
  let heading-text-leading = 4em - 0.75em - 0.75em

  show outline: it => {
    show heading: set block(spacing: heading-text-leading + 0.75em)
    it
  }
  let heading-and-text-spacing(body, heading-above: false, text-above: false) = {
    if body.func() == sequence {
      for (i, element) in body.children.enumerate() {
        if element.func() == sequence {
          heading-and-text-spacing(element, heading-above: heading-above, text-above: text-above)
        } else if element.func() == styled {
          heading-and-text-spacing(element, heading-above: heading-above, text-above: text-above)
          // } else if element.func() == heading {
        } else if element.func() == heading or (element.func() == align and element.body.func() == heading) {
          if heading-above {
            v(heading-heading-leading)
          } else if text-above {
            text-above = false
            v(heading-text-leading)
          }
          heading-above = true
          element
          // } else if element.func() in (text, parbreak, enum.item) {
        } else if element.func() in (text, enum.item, list.item) {
          if heading-above {
            heading-above = false
            v(heading-text-leading)
          }
          text-above = true
          element
        } else if element.func() in (parbreak,) {
          if heading-above {
            heading-above = false
            v(heading-text-leading)
          }
          element
        } else {
          element
        }
      }
    } else if body.func() == styled {
      styled(
        heading-and-text-spacing(body.child, heading-above: heading-above, text-above: text-above),
        body.styles,
      )
    } else {
      body
    }
  }
  show: heading-and-text-spacing

  doc
}
```

</details>

One important note is that it only works with flat project structure. I was able to put each chapter/1st level headings into a separate file, but only because all of them start from a new page (separated by a `#pagebreak()`). But when I tried to sort out 2nd level headings, the merge places had the wrong spacings. All because `#include` creates a nested `content` block and therefor isolates each part. This probably can be fixed by returning the latest variables' state after each function call, but this would further complicate the code.

This solution highly overlaps with this one: https://github.com/typst/typst/issues/311#issuecomment-2104447655. That's why I mismatched the two and mentioned both even though I started and wanted to only mention one of them: https://github.com/typst/typst/issues/311#issuecomment-2175809156.

**Comment by medanaee** [comment] 2026-05-05 13:37
A temporary workaround for this issue:

```
  show heading: it => {
    it
    context {
      let next_elements = query(selector(heading)
      .or(par)
      .or(list)
      .or(enum)
      .or(terms)
      .or(table)
      .or(figure)
      .or(image)
      .or(raw)
      .or(outline)
      .after(here()))         
      
      if next_elements.len() > 0 {
        let next_el = next_elements.at(0)
        
        if next_el.func() == heading and next_el.level in (1, 2) {
          v(-10pt)
        }
      }
    }
  }
```
