### ISSUE TITLE
Incorrect spacing of lists after headings

### ISSUE THREAD

**Issue by ad-si** [typst/typst#3711] opened 2024-03-18 14:29 UTC
### Description

For paragraphs the emmpty newline after the heading doesn't make a difference, but for lists it does.

```typst
#show heading: set block(below: 2em)

= Heading
Just some text.

= Heading

Just some text.

= BUG Heading
+ Item 1
+ Item 2

= Heading

+ Item 1
+ Item 2
```

Yields:

![image](https://github.com/typst/typst/assets/36796532/bb12654e-79ab-41a0-9d20-3e629177200e)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-03-24 22:41
Duplicate of https://github.com/typst/typst/issues/1850

**Closed** 2024-03-24 22:41 UTC
Labels: bug, duplicate
