### ISSUE TITLE
Header style improperly affects default page numbering

### ISSUE THREAD

**Issue by lazyeights** [typst/typst#4722] opened 2024-08-10 19:36 UTC
### Description

If the first page has a header but no other content, the page number takes on the styling of the header. 

Example:

```typst
#set page(height: 100pt, width: 100pt)
#set page(numbering: "1")
= Header no text
#pagebreak()
= Header with text
#lorem(5)
= Header no text
```

Produces:
![CleanShot 2024-08-10 at 14 35 27](https://github.com/user-attachments/assets/c6472bb7-5600-48be-902e-0d8bedd77b14)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-08-10 20:14
Duplicate of #241

**Closed by PgBiel** 2024-08-10 20:14 UTC
Labels: bug
