### ISSUE TITLE
write any document as a booklet

### ISSUE THREAD

**Issue by paul2t** [typst/typst#5092] opened 2024-10-01 19:33 UTC
### Description

It would be nice to be able to easily change a document to a booklet.
I know there is already the bookletic package, but it requires to wrap all the pages in an array.
I don't know if it is already possible in typst to automatically split the document by pages and reorder the pages in a page twice as big. If it is, I would really like to know how to do that.
I also know, that some printer offer that possibility, but not all. And some people are not that tech savy and would prefer to have a simple pdf document to print without thinking about the settings.

I could try to implement it if you think this is a good idea.
Looking at the code, I'm not sure at which level it would be best to implement such a feature.
It could be a property on the document : https://github.com/typst/typst/blob/698ae870e789aa9423a091e43f957ac677bae4f6/crates/typst/src/model/document.rs#L91
That will then impact how the pdf is created : https://github.com/typst/typst/blob/698ae870e789aa9423a091e43f957ac677bae4f6/crates/typst-pdf/src/lib.rs#L51

Or it could be at a higher level, in the way the document is created.
I haven't found where it is yet, but I'm sure it is somewhere.
But if it's everywhere, then I guess my first idea should be the only viable solution to my problem.

What do you think ?
Is this a good idea ?
Where would you implement it ?

### Use Case

Users could share documents that are booklet ready. To send to other (not so tech savy) people to print.

**Comment by bastienvoirin** [comment] 2024-10-04 09:11
A booklet option would be great indeed, even for tech-savvy people.

# RFC

## Page option

I think it would make more sense to implement it as a `page` option
- instead of a `document` option, as "this function is only used with [set rules](https://typst.app/docs/reference/styling/#set-rules) to specify document _metadata_" (https://typst.app/docs/reference/model/document/, added emphasis);
- not only changing how PDF files are created, but every other output file format by [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Something like
```typ
// Reorder the pages, in pages twice as wide
#set page(booklet: true)
```

to add to

https://github.com/typst/typst/blob/60f9f66950f1fbef3d6042533e768b9ee933dd24/crates/typst/src/layout/page.rs#L42

as

```rust
/// Whether the document is rendered as a booklet.
#[default(false)]
#[ghost]
pub booklet: bool,
```

which would change the page ordering and layout logic in [crates/typst/src/layout/pages](https://github.com/typst/typst/tree/main/crates/typst/src/layout/pages).

## Pagebreak option

I also think that we should add variants to the

```typ
#pagebreak(to: "...")
```

parameter to account for the base-4 structure of booklet paper sheets (2 pages per side) instead of the only base-2 options currently available, `even` and `odd`. For instance, add something akin to

```typ
#pagebreak(to: "fourth")
```

to go to the back cover. I'm not sure about the naming of the four options to add, though.

## Page reordering algorithm

Per the [Bookletic](https://github.com/harrellbm/Bookletic) package by @harrellbm:

https://github.com/harrellbm/Bookletic/blob/11465e419c03259bf84a9c36c1987bd4c2392d2f/src/lib.typ#L129-L154

---

I can _draft_ a Pull Request for someone to take over, as I'm afraid I'm only able to implement the front-end of those `page(booklet: bool)` and `pagebreak(to: "base-4-destination")` options without the page reordering and layout logic 😅

**Comment by bastienvoirin** [comment] 2024-10-04 11:35
On second thought, I think that the option to lay pages side by side on paper sheets twice as wide should stand alone as a separate feature, and only the page reordering actually falls under this booklet feature request.

**Comment by bastienvoirin** [comment] 2024-10-04 12:10
Duplicate of #187 and #332, which were closed as not planned/out of scope.
Duplicate of #2458, which is still open.

**Comment by harrellbm** [comment] 2024-10-04 14:13
I have implemented a package that formats content into a booklet and handles signature page ordering. 

Here is the repo and you can find it in the package list in the typst site as well. 

[https://github.com/harrellbm/Bookletic.git](https://github.com/harrellbm/Bookletic.git)

I have not made it to addressing auto page breaking yet but this at least is a start and would love any contribution you would be willing to add!

**Comment by harrellbm** [comment] 2024-10-04 14:48
Hey guys I'm the author of the bookletic package. I would love to see something like this easier to use. 

I have started looking at adding auto page breaking to the package but don't know exactly what that functionality should look like so if you guys have feedback I'd like the package to be something usable at least until something more final can be implemented

**Comment by Enivex** [comment] 2024-10-05 02:54
The following was closed for being out of scope. I'm not sure why this one would've any different.

https://github.com/typst/typst/issues/3320

**Comment by bastienvoirin** [comment] 2024-10-05 09:04
> Hey guys I'm the author of the bookletic package. I would love to see something like this easier to use.
> 
> I have started looking at adding auto page breaking to the package but don't know exactly what that functionality should look like so if you guys have feedback I'd like the package to be something usable at least until something more final can be implemented

Hi @harrellbm, thank you for your package! I've pondered a bit about automatic slicing of content into pages that we can reorder, but I didn't find a way. I don't know if it could be done with a [WebAssembly plugin](https://typst.app/docs/reference/foundations/plugin/).

> The following was closed for being out of scope. I'm not sure why this one would've any different.
> 
> #3320

Hi @Enivex,

(I think you meant #332, c.f. my previous comment)

I know that Typst is not meant to cover the entire workflow from typesetting to printing, but page reordering came up 4 times now (5, if I count my own interest) and seems like those _small_ quality-of-life features which make perfect sense in the _typesetting_ process with little overhead in terms of code complexity and performance. But feel free to close this issue and #2458 if page reordering really is out of scope.

However I think we should at least implement the base-4 `pagebreak(to: "...")` variants I proposed in the second section of [this comment](https://github.com/typst/typst/issues/5092#issuecomment-2393236951) to allow content alignment at the paper sheet level for books and booklets. I've already drafted those new page parities [here](https://github.com/typst/typst/compare/main...bastienvoirin:typst:main) (I can remove the `page(booklet: bool)` front-end).

**Comment by harrellbm** [comment] 2024-10-05 14:01
@bastienvoirin I have been thinking about the problem of auto page breaking for a while and the best typst native solution I have come up with is: 

1. Iterate over the content and split each discrete item into a block or box. Making sure to set the width to the to the correct size so that we can use the height later. 
2. Go block by block and "pack" them into pages using the height of each block and the height of the page minus margins. 
3. Once a page can't accept another block start a new page 

It's not a beautiful solution and would have some idiosyncrasies like never splitting whole paragraphs. It also introduces a layer of block containers which I'm not sure of the implications with that many being added to the content.

**Comment by laurmaedje** [comment] 2024-10-06 10:31
> I know that Typst is not meant to cover the entire workflow from typesetting to printing, but page reordering came up 4 times now (5, if I count my own interest) and seems like those small quality-of-life features which make perfect sense in the typesetting process with little overhead in terms of code complexity and performance.

It's fair to say that this has come up a number of times. I'll discuss with @reknih whether we will reconsider the request.

**Comment by laurmaedje** [comment] 2024-10-07 10:11
We've decided to reopen https://github.com/typst/typst/issues/187, but are not 100% decided yet whether we really want the feature, so the issue is more to track the possiblity of it happening. I think that _if_ we would add it, then because doing it in Typst can do something that doing it externally can't, like placing across multiple spreads. Otherwise, the benefit is relatively small. (At least for users that are already in the CLI, where such tools are available.) 

Overall, I think this would require a good and flexible design and not just the first thing that comes to mind. There are many things with higher priority, so I personally can't invest time into such a design.

**Closed** 2024-10-07 10:12 UTC
Labels: duplicate, feature request
