### ISSUE TITLE
More Math Symbol Naming

### ISSUE THREAD

**Issue by m4dh0rs3** [typst/typst#5251] opened 2024-10-19 15:36 UTC
### Description

> Typst math syntax is cleaner and faster to type compared to TeX, with a few exceptions for me (listed). Especially with the first two, every Typst user will stumble on those.

Faster to type and known from TeX:
- $\cap, \cup$ (`$sect, union$`) should (also) be `$cap, cup$`
- $\prod$ (`$product$`) should (also) be `$prod$`
- $\sim$ (`$tilde$`) should (also) be `$sim$`

Other Issues:
- $\therefore$ (`$therefore$`) may (also) be `$dots.tri$` or similar
- (See pic) (`$eq.est$`) should (also) be `$eq.hat$` or `$hat(eq)$` should look better
![eq_hat](https://github.com/user-attachments/assets/6ae1826b-14ce-4cd2-9270-047807134cc5)

Generally, math symbol naming consistency is a mess. Possible naming concepts:
- Established (TeX) like `cap` vs. new `sect`
- Written out like `product` vs. shortend like `sect`
- Semantic definitions like `union`
- Unicode Names

### Use Case

I argue for using established names from TeX and the dot-separator syntax. TeX symbol names are fast to type out and well known, and the dot-separator syntax does not change that. All symbols shouldn't be renamed now, as this will break backwards compatibility. On the other hand, adding aliases to this many symbols will take up more namespaces. I suggest aliasing popular names (especially the first two listed). Additionally, when there is a new issue to add some unsupported symbol, name the symbol like TeX does.

This would improve usability for users migrating from (La)TeX.

**Comment by Enivex** [comment] 2024-10-19 15:45
There's plenty of discussion going on regarding symbol naming on the Discord. I suggest you seek out the relevant forge there.

Renaming `sect` is one that is almost definitely going to happen (it's a terrible name), but I doubt it'll end up being `cap`. There's no general wish to align with LaTeX' naming just for the sake of it, except when it makes sense to do so.

**Comment by Enivex** [comment] 2024-10-19 15:47
I'll close this for being too general and non-actionable.

**Closed by Enivex** 2024-10-19 15:47 UTC
Labels: feature request

**Comment by MDLC01** [comment] 2024-10-19 17:19
Regarding the individual suggestions, thanks for your input; we will take them into account. For `hat(eq)`, feel free to open another issue (although I'm not sure what can be done).

Concerning the "mess" that is math symbol naming consistency, you raise multiple points which I will try to answer below.

- TeX does not always have good names. We may chose to align with TeX when the names are well chosen, but we won't add a bad name just because TeX did it before.
- The most common symbols have shortened names (e.g., `eq` for =) because it would be annoying to have to type the full name every time. For lesser used symbols, it is better to have full words as names to prevent ambiguity, and because it isn't too problematic having to type a full word once in a while.
- We try to use semantic names when appropriate (e.g., `eq.est` for ≙). The problem is that the same symbol may have different meaning across different fields. For this reason, only the most commonly used symbols, or highly specific symbols that are only used in one field, have semantic names.
- Unicode names can also be inconsistent sometimes. They may be good starting points (e.g., `eq.est` for U+2259 ESTIMATES).

When naming a symbol, the TeX and Unicode names are considered, as well as its uses. In general, I feel like symbol names are fairly consistent, even though I agree there are still possible improvements.

If you have more to say about symbol naming that doesn't fit in GitHub issues (which are less practical for discussion), please consider [sharing your thoughts on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1297225222562513007). We also have a document where we keep track of all the symbol we plan to name in the future: https://typst.app/project/riXtMSim5zLCo7DWngIFbT.
