### ISSUE TITLE
SVG images are translated lossy

### ISSUE THREAD

**Issue by ghost** [typst/typst#368] opened 2023-03-27 10:31 UTC
That's maybe expected, but if so, should be added to the docs.

[Here](https://upload.wikimedia.org/wikipedia/commons/6/62/Coat_of_Arms_of_the_Edinburgh_City_Council.svg) is an example figure.

Compiling

```typ
#image("fig.svg")
```

Will look a bit different compared to the original (tested with different viewers):
![svg rendering](https://user-images.githubusercontent.com/107212151/227916376-761ad5c7-1463-4bd8-aaaf-4d026d84403a.PNG)

**Comment by reknih** [comment] 2023-05-03 09:45
Does the current commit still have this issue?

**Comment by laurmaedje** [comment] 2023-05-03 09:53
Does not panic for me anymore, but still has some (new?) issues.

**Comment by LaurenzV** [comment] 2023-05-18 09:37
I didn't see anything else wrong apart from the warnings that are printed to the console, which shouldn't cause any bugs in the rendered image though (I raised an issue [here](https://github.com/RazrFalcon/resvg/issues/621), so this should be fixed soon). Did you notice any other visual inaccuracies apart from that?

**Comment by Dherse** [comment] 2023-06-09 23:46
From what I can tell, there is also a problem where SVGs can cause a memory leak in some scenarios. I don't have a minimum reproducible example as I simply don't have time to make one, but there seems to be something wrong when removing SVGs from a typst file :x

**Comment by LaurenzV** [comment] 2023-07-21 18:25
Will be fixed once [this PR](https://github.com/typst/svg2pdf/pull/34) gets merged and upstreamed.

**Comment by LaurenzV** [comment] 2023-07-22 04:47
Okay, it's still not quite fixed unfortunately. It displays fine on Chrome and Acrobat, but still has a couple of issues when opened in Firefox and Safari. Not sure if this is something we can fix on our side, but I'll see what can be done.

**Closed** 2023-09-04 11:24 UTC
Labels: bug, visualize, svg
