### ISSUE TITLE
Allow selectors in `gradient`/`pattern`'s `relative` argument

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3011] opened 2023-12-19 10:04 UTC
### Description

Currently there are two modes; `relative: "self"` and `relative: "parent"`. I think being able to more flexibly state exactly the scope which you want your pattern to 'bind' to using selectors would be a great addition.

### Use Case

Consider these made up examples:
- `set table.cell(fill: pattern(blah blah, relative: table))`
- `line(stroke: gradient(blah blah), relative: page)`

Or how this would likely revolutionise the abilities to use strokes in drawing applications such as CeTZ

**Comment by laurmaedje** [comment] 2023-12-19 10:07
Duplicate of https://github.com/typst/typst/issues/2544. Feel free to repost your proposal there!

**Closed by laurmaedje** 2023-12-19 10:07 UTC
Labels: feature request
