### ISSUE TITLE
`figure` does not account of caption when laying out children

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#4703] opened 2024-08-08 07:36 UTC
### Description

It seems that figure as a container doesn't properly account of the additional caption when laying out its children. The following snippet will have its caption protrude into the footer:

```typst
#set page(numbering: "1 / 1")

#show: block.with(stroke: red)

#figure(
  grid(rows: (1fr, 1fr), columns: (1fr)),
  caption: [
    If this caption is long enough, it will go straight into the page footer, possibly directly over the numbering.
  ],
)
```

I'd say that's unintended, but I'm not sure.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-08-08 07:44
It's not related to the figure. It's that using `1fr`-sized grid rows within an automatically sized unbreakable container will mess up stuff. Example:
```typ
#set page(numbering: "1 / 1")
#block(stroke: red, breakable: false)[
  #grid(rows: (1fr, 1fr), columns: (1fr))
  This is also in the footer.
]
```

**Comment by laurmaedje** [comment] 2024-08-08 07:45
I'll close this as a duplicate of https://github.com/typst/typst/issues/2571.

**Closed by laurmaedje** 2024-08-08 07:45 UTC
Labels: bug
