### ISSUE TITLE
Font selection not behaving as expected

### ISSUE THREAD

**Issue by inferiorhumanorgans** [typst/typst#4726] opened 2024-08-11 00:01 UTC
### Description

On macOS 14 if I:

- install Google's Roboto (12 variants)
- install the Roboto Condensed variable font file
- deactivate Roboto Condensed "family" via FontBook.app

Then run this document through typst:

```
#set text(font: "Roboto", weight: 200)
#show heading.where(level: 3): set text(weight: 400)
=== heading3 should be full width roboto
```

I get this output:

```
$ ~/typst/typst fonts --variants
Roboto
- Style: Normal, Weight: 500, Stretch: FontStretch(1000)
- Style: Normal, Weight: 300, Stretch: FontStretch(1000)
- Style: Normal, Weight: 400, Stretch: FontStretch(1000)
- Style: Normal, Weight: 400, Stretch: FontStretch(1000)
- Style: Italic, Weight: 500, Stretch: FontStretch(1000)
- Style: Italic, Weight: 250, Stretch: FontStretch(1000)
- Style: Italic, Weight: 700, Stretch: FontStretch(1000)
- Style: Italic, Weight: 300, Stretch: FontStretch(1000)
- Style: Italic, Weight: 400, Stretch: FontStretch(1000)
- Style: Italic, Weight: 900, Stretch: FontStretch(1000)
- Style: Normal, Weight: 700, Stretch: FontStretch(1000)
- Style: Normal, Weight: 250, Stretch: FontStretch(1000)
- Style: Normal, Weight: 900, Stretch: FontStretch(1000)

$ otfinfo --variable ~/Library/Fonts/RobotoCondensed-VariableFont_wght.ttf
Axis 0:                 wght
Axis 0 name:            Weight
Axis 0 range:           100 900
Axis 0 default:         400
Instance 0 name:        Thin
Instance 0 position:    100
Instance 1 name:        ExtraLight
Instance 1 position:    200
Instance 2 name:        Light
Instance 2 position:    300
Instance 3 name:        Regular
Instance 3 position:    400
Instance 4 name:        Medium
Instance 4 position:    500
Instance 5 name:        SemiBold
Instance 5 position:    600
Instance 6 name:        Bold
Instance 6 position:    700
Instance 7 name:        ExtraBold
Instance 7 position:    800
Instance 8 name:        Black
Instance 8 position:    900

$ pdffonts roboto.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
CFDWGU+RobotoCondensed-Regular       CID TrueType      Identity-H       yes yes yes      4  0
```

Two things are notable:

1.) Robto Condensed shouldn't be available at all, but there it is as the duplicate 400 weight entry.

2.) Roboto Condensed is a variable font file and (unless deactivated) should be available at multiple weights, not just 400.  FontBook.app lists 9 available variants for Roboto Condensed.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-08-11 00:45
Closing as a duplicate of #185. Consider using a non-variable version of the font for the time being.

**Closed by PgBiel** 2024-08-11 00:45 UTC
Labels: bug

**Comment by inferiorhumanorgans** [comment] 2024-08-11 00:58
That doesn't solve the issue of typst pulling in deactivated fonts.

**Comment by PgBiel** [comment] 2024-08-11 01:14
What does "deactivate" entail? As far as Typst knows, if the font file exists, it can be used. Do you have more information on this?
