### ISSUE TITLE
Closures only fail to compile once called

### ISSUE THREAD

**Issue by Heinenen** [typst/typst#3204] opened 2024-01-16 11:33 UTC
### Description

Looking at the following code, IMO `a)` should not compile, because it captures a variable `asdf` that is known to not exist in the surrounding code.
`a)` only fails to compile once the closure is used, as seen in `b)`.
The thing I think is better already works if the binding doesn't define a closure but a "normal" variable, as seen in `c)`.
```typ
// a)
// this compiles
#let x() = {
  asdf
}
```

```typ
// b) 
// this doesn't compile
#let x() = {
  asdf
}
#x()
```

```typ
// c) 
// this doesn't compile
#let x = {
  asdf
}
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment] 2024-01-16 11:43
This is known, there was a PR that was aimed at address this: #2319.
This is also somewhat of a duplicate of #316

**Comment by laurmaedje** [comment] 2024-01-16 13:55
I've renamed #316 to broaden it. Closing as duplicate.

**Closed by laurmaedje** 2024-01-16 13:55 UTC
Labels: bug
