### ISSUE TITLE
SVGs exported from draw.io do not render text properly in Typst

### ISSUE THREAD

**Issue by JamesxX** [typst/typst#4482] opened 2024-07-01 10:29 UTC
### Description

I created a diagram with text using draw.io, which I then import into Typst. There seems to be an issue w.r.t text rendering, shown below:

Draw.io:
![image](https://github.com/typst/typst/assets/6299280/2be76ac6-0a55-479b-9009-06e4da15958d)

Exported SVG seen through Edge browser:
![image](https://github.com/typst/typst/assets/6299280/eb33746e-be20-4663-89b3-d3a0b8d8b42b)

Exported SVG seen through Typst (webapp)
![image](https://github.com/typst/typst/assets/6299280/394c936d-2b28-4e66-b547-39bd74ddf2a3)

SVG itself:
![instrumentation](https://github.com/typst/typst/assets/6299280/f9147bf0-458e-499f-8366-4b244da561b6)

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2024-07-01 10:42
Probably a duplicate of https://github.com/typst/typst/issues/1421.

**Closed** 2024-07-01 10:56 UTC
Labels: bug, duplicate

**Comment by freundTech** [comment] 2024-07-01 11:01
Note that the svg you attached also doesn't render properly in both Chrome and Firefox. At least when opened individually.

(It looks fine here in this issue, but when I right-click, open in new tab it's completely broken)

![Screenshot from 2024-07-01 13-01-14](https://github.com/typst/typst/assets/9515067/f6426a9f-d4c5-43df-9a64-b8018aeccc72)

**Comment by JamesxX** [comment] 2024-07-01 11:50
That's odd as it works on my android chrome

**Comment by gabrielalexandrelopes** [comment] 2024-07-30 12:05
I was having the same problem, specially with the math typesetting. Just updated drawio to version v24.7.5 and now the problem is gone. The equations and text are rendered correctly!

**Comment by gabrielalexandrelopes** [comment] 2024-07-30 14:34
actually, I retract my previous comment. The problem is still there. In DrawIO it looks like this:

<img width="609" alt="Screenshot 2024-07-30 at 14 00 45" src="https://github.com/user-attachments/assets/a754acc8-cf64-4f3c-8c26-da134090d279">

In VSCode with preview it show correctly as:

<img width="928" alt="Screenshot 2024-07-30 at 16 32 09" src="https://github.com/user-attachments/assets/7d74d05f-cbce-4e50-a69a-4c0acf790f62">

but after compiling in typst and opening the PDF in macOS Preview it looks like this:

<img width="696" alt="Screenshot 2024-07-30 at 16 29 06" src="https://github.com/user-attachments/assets/97635b93-da1b-4e97-8e0e-a424b11e94f0">

**Comment by gabrielalexandrelopes** [comment] 2024-07-30 14:41
I see, its related to this: https://www.drawio.com/doc/faq/svg-export-text-problems
