### ISSUE TITLE
Suggestion: More principled lr() allowing for inner delimiters

### ISSUE THREAD

**Issue by schuelermine** [typst/typst#1006] opened 2023-04-27 08:09 UTC
### Description

I suggest making lr() take the delimiters as separate arguments: `$ lr("(", a^2, ")")$`, or introducing a function delim that does this. This would allow for easy integration of middle delimiters: `$ delim("{", x, "|", x in NN, "}") $`, which is a feature I also suggest.

### Use Case

In set theory, set comprehensions are often written with a middle bar which should resize to the size of the outer delimiters.

**Comment by Leedehai** [comment] 2023-04-28 17:32
Thanks for the suggestion! Appears to be a duplicate of https://github.com/typst/typst/issues/240, though, which had a lengthier discussion

**Closed** 2023-04-28 18:19 UTC
Labels: feature request
