### ISSUE TITLE
Table Bug

### ISSUE THREAD

**Issue by JL710** [typst/typst#1180] opened 2023-05-11 20:39 UTC
### Description

Here, the table create lines on the page before. I think the code + the image says enough.

```
#v(67em)

#table(columns: 2, [1], [2])
```
![Screenshot 2023-05-11 223729](https://github.com/typst/typst/assets/76447362/6b63a712-7e67-4dcb-9d7d-57c6069c50ae)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-05-11 20:40
Duplicate of https://github.com/typst/typst/issues/183

**Closed** 2023-05-11 20:43 UTC
Labels: bug
