### ISSUE TITLE
SVG images render with borders between transparent areas

### ISSUE THREAD

**Issue by har7an** [typst/typst#3133] opened 2024-01-05 07:54 UTC
### Description

Hello,

we're trying to generate reports with typst that contain SVG images of data we're plotting at work. The (heatmap) plots are created with `Plots.jl`, written in the Julia language. We're creating the plots such that specific values don't appear, i.e. individual patches of the plot have no background (they're transparent in SVG). Below you can see one such plot:

![plot](https://github.com/typst/typst/assets/99636919/0ffc4031-56f0-4725-aa67-8262e3cd467d)

And here's the MWE to compile it to a document:

```typst
= MWE

#image("plot.svg")
```

And here's a screenshot of the resulting PDF:

![image](https://github.com/typst/typst/assets/99636919/a864ab32-7dce-4287-9936-c264b31dfa2a)

As you can (hopefully) see, it seems that during compilation a thin black/gray border is introduced to separate the transparent areas from the colored patches. This border is not part of the original SVG and also distracts from the actual data in our case. Is there a way to remove this border?

For the moment we can work around this issue by manually converting the SVG to PNG/JPEG and including that in our document. This, however, defeats the purpose of using lossless image formats in the first place.

I tried this with the following releases:

- 0.9.0
- 0.10.0
- latest main ([d651c6e](https://github.com/typst/typst/commit/d651c6e0e6f7df62ebfdd85f23864097607feb46))

All produced the same result.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2024-01-05 08:38
I'll look into it more closely when I have the time. But it seems like I get the same result when converting it with an [online converter](https://cloudconvert.com/svg-to-pdf), so not sure what's up with that.

For now, it's indeed best to just convert it to a raster image. As far as I can see, the SVG basically jus consists of an embedded image anyway (so there are no vector graphics in it at all), so there shouldn't be any loss in quality if you embed it directly.

Here's the plain image that is embedded (and funnily enough, it seems to contain black patches as well... So not sure what is going on, will look hopefully be able to look into it in a couple of weeks):
![image](https://github.com/typst/typst/assets/47084093/a5bf53ba-76c9-47cb-9a6a-d3e9c314b4d7)

**Comment by LaurenzV** [comment] 2024-01-06 22:54
I looked some more into it, and I'm afraid this isn't a bug from our side and we can't really fix this.

I tried converting the SVG with different converters, tried embedding it in LaTeX, and I even tried to convert the embedded image to PDF directly via Word and Adobe Acrobat, no matter how I converted it, those grey lines showed up all the time. The issue is that the transparent pixels have an RGBA value of (0, 0, 0, 0) (so they have an opacity of 0, but are still black), and for some reason some PDF viewers produce those weird artifacts at some zoom levels because of this. But this isn't something that can be worked around from our side.

I don't know how Julia and this plotting library works, but the only workaround I see is to somehow ensure that the transparent pixels in the embedded SVG are encoded as (255, 255, 255, 0), so a white transparent. Then you wouldn't see this, since the background is white as well.

Sorry! :( But since there's not much we can do about this, I'll close this issue.

**Closed by LaurenzV** 2024-01-06 22:54 UTC
Labels: bug, svg

**Comment by har7an** [comment] 2024-01-09 09:34
@LaurenzV Thank you for the swift and in-depth reply!

I see, I wasn't aware that the colored area is merely an embedded image, sorry for that. We have changed our plotting code to fill these gaps with a solid white color, now the images come out as expected.

Thank you for the thorough research!
