### ISSUE TITLE
Bibliography keys (inconsistently) not found in footnote citations

### ISSUE THREAD

**Issue by wbfe01** [typst/typst#1597] opened 2023-06-27 17:58 UTC
### Description

When using citations in footnotes  (as in `#footnote[Some text #cite("reference_name")]`), sometimes for some footnotes the compiler fails with `bibliography does not contain this key`, even though the bibliography clearly contains the key. When I move the citation out of the footnote everything works. Sometimes if I just move the whole footnote to another location in the document without changing it or if I change some completely different part of the document, it suddenly works or the error pops up for another footnote where it worked before.

This results in error messages like this (where `citation_reference` is the same both times).

```
error: bibliography does not contain this key
     ┌─ document.typ:2569:223
     │
2569 │ #cite("citation_reference") some text#footnote[some more text (#cite("citation_reference")).]. 
     │                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The issue seems to be related to #785, which is resolved now, but I still get the errors with a fresh build of the newest version from main.

If I log `works.citations.get(&location)` in `impl Show for CiteElem` in `bibliography.rs` I get `None` for these cases. 

Unfortunately I can't provide the full code that reproduces this because it's a quite large document and (as described above) the errors can't be isolated but depend on the rest of the document.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment] 2023-06-27 21:49
Does the same issue arise before 33803b16148ec064ccabc9bffd4a9383b969e23e?

**Comment by wbfe01** [comment] 2023-06-28 06:17
@MDLC01 Yes, it happens in 9ef4643ba104acc08cd3a4fce8cfea72253654b1 (the one before 33803b16148ec064ccabc9bffd4a9383b969e23e) as well as in 1321862cd54eb4abefb5d435285e3de9e0848c4c (the one that introduced footnotes).

**Comment by wbfe01** [comment] 2023-07-02 19:58
Here's a (admittedly random) setup that reproduces the bug (using typst 0.6.0):

A typst file that contains this line 82 times:

```
Texttexttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext texttext#footnote[Texttext texttext texttext(#cite("test")).] Text text text text.
```
followed by:
```
#bibliography("literaturetest.bib", style: "chicago-author-date")
```

The `literaturetest.bib` file contains:
```
@book{test,
  title = {Test},
  author = {test},
  date = {2000},
}
```
The `bibliography does not contain this key` error occurs on line 81. Strangely enough, if I remove line 82 everything works.

**Comment by laurmaedje** [comment] 2023-07-02 20:07
Great, thanks for the reproduction! That makes this issue a lot more actionable.

**Comment by wbfe01** [comment] 2023-07-12 21:59
Here's a very bad hack that at least seems to get closer to the source of issue. I changed the `show` implementation for `CiteElem` so that it sets `location.disambiguator = 0`, checks if `works.citations.get(&location)` is `None` and if it is it sets `location.disambiguator = 1`. I don't really understand how the disambiguator works, but this stops the error messages in the test file from above as well as in the original (very large) document I initially had problems with. It even seems that the resulting citations and references in the pdf are correct (but I might be missing something). I thought I'd let you know, maybe this helps you get closer to a proper solution!

**Comment by Zheoni** [comment] 2023-09-21 03:36
This still happens to me in the latest commit. The places and document modifications which made it fail have changed, but some bibliography keys, sometimes, are still missing. I can't share the document. If I found a minimal example I will post it here.

**Comment by ja-he** [comment] 2023-10-14 15:51
I ran into this issue as well on a footnote that was right at a pagebreak (so the typsetting system had to check if it fit, realize it didn't and move the footnote and the place it was referenced onto the next page).

I checked out 18666c0 and for me the issue is resolved there, whereas its parent still has the issue.

Thanks for the apparent fix @laurmaedje, looking forward to seeing it merged :+1:

**Comment by ja-he** [comment] 2023-10-14 15:57
Just realized it is merged as 72d8a9c89aa9306518edd6484d2097d40ab28d19, I think this could be closed right?

**Comment by laurmaedje** [comment] 2023-10-14 17:40
It was closed, but two people stated that they had still issues on the latest commit, so I reopened it.

**Comment by ja-he** [comment] 2023-10-15 00:05
ah my bad you're right, I got confused by the way GitHub showed the mention in the same commit again after those. sorry

**Comment by wbfe01** [comment] 2023-11-05 11:09
@laurmaedje I upgraded to 0.9.0 and don't have any issues anymore. I don't know if it's the same for the others who had problems with this, but it seems like something in the the recent updates to the citation system did the trick.

**Comment by reknih** [comment] 2023-11-23 15:06
This seems to be fixed. Please tell us if it still happens for you @Zheoni et al

**Closed by reknih** 2023-11-23 15:06 UTC
Labels: bug, meta, bibliography, needs-investigation
