### ISSUE TITLE
Display math mode in numbered list causes numbers to be out of alignment

### ISSUE THREAD

**Issue by notaduck448** [typst/typst#3384] opened 2024-02-08 04:21 UTC
### Description

When using display math mode inside of a numbered list, and the math takes up space vertically more than one line, the numbers get shifted upwards from where they should be.

Here's a picture of what happens:

![image](https://github.com/typst/typst/assets/31483425/62dd72df-330e-4525-b4f6-22ca65e19f42)

And this is the code:

```
#set enum(numbering: "(a)")

Let $vb(A) = display(mat(cos(theta), -sin(theta); sin(theta), cos(theta)))$.

+ Show that $vb(A)^2 = display(mat(cos(2 theta), -sin(2 theta); sin(2 theta), cos(2 theta)))$

+ Prove, by induction, that $vb(A)^n = display(mat(cos(n theta), -sin(n theta); sin(n theta), cos(n theta)))$
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-02-14 11:57
Duplicate of https://github.com/typst/typst/issues/1204

**Closed by laurmaedje** 2024-02-14 11:57 UTC
Labels: bug
