### ISSUE TITLE
Can't see $X$ uppercase letter in math mode

### ISSUE THREAD

**Issue by adriandelgado** [typst/typst#2397] opened 2023-10-16 04:40 UTC
### Description

On a blank document `$Y$` o `$Z$` shows a math variable as expected but `$X$` shows nothing.

Note: I can't reproduce the bug on the web app. I install the compiler using cargo (latest commit).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment] 2023-10-16 05:20
Where are you looking at the document? If you manually compile it from scratch does it still not work?

**Comment by Enter-tainer** [comment] 2023-10-16 05:48
It is super weird but i confirmed this on my machine.

commit: a59666369b946c3a8b62db363659cbfca35f0a26
```
> cat test.typ
$X$ $Y$
```

[test.pdf](https://github.com/typst/typst/files/12912545/test.pdf)

**Comment by Dherse** [comment] 2023-10-16 07:50
I can reproduce it on earlier commit: d3b62bd so it's definitely older.

**Comment by Dherse** [comment] 2023-10-16 07:57
I ran a git bisect, and it was caused by the following commit: 7dc74b7 by @laurmaedje

**Comment by laurmaedje** [comment] 2023-10-17 21:28
Will be fixed once pdf-writer is bumped. Fix is here: https://github.com/typst/pdf-writer/commit/ea7fe33b956912f18f48b42b1ea9681c0dff610c

**Closed** 2023-10-24 13:23 UTC
Labels: bug, math, pdf, upstream
