### ISSUE TITLE
Parametrize module construction

### ISSUE THREAD

**Issue by Myriad-Dreamin** [typst/typst#4789] opened 2024-08-19 14:27 UTC
### Description

A module (source file) can be viewed as body of some function. In this sense, constructing module could allow receiving parameters. This box is already opened by `sys.inputs`. Honestly, I feel it is not perfect to feed `sys.inputs` by reconstructing entire `typst::Library`, thus reimplemented `sys.inputs` could be another use case. 

Proposed syntax (the concrete syntax can be improved):

Parametrized import, passing a dictionary after set:

```typ
#import "@preview/touying:10.0.0": slides set (
  aspect-ratio: "16-9", numbering: ("1.", "1.1"),
)

#show: slides

= Animation

== Simple Animation

We can use `#pause` to #pause display something later.
```

Parametrized import, allowing variable or spreading:

```typ
#let options = (aspect-ratio: "16-9", numbering: ("1.", "1.1"))
#import "@preview/touying:10.0.0": slides set options
#import "@preview/touying:10.0.0": slides set (: ..options1, ..options2)
```

Parametrized include:

```typ
// an e-book main file aggregating chapters.
#include "chapter1.typ" set (importee: "e-book")
```

Using module parameters:

```typ
#let aspect-ratio = sys.inputs.at("aspect-ratio", default: "16-9")
#let importee = sys.inputs.at("e-book", default: none)
```

### Use Case

- package options.
- specialize included content by parent file.
- reimplementing `sys.inputs`.

**Comment by PgBiel** [comment] 2024-08-19 14:40
Duplicate of https://github.com/typst/typst/issues/2403

**Closed** 2024-08-19 14:40 UTC
Labels: feature request
