### ISSUE TITLE
A page containing only a `raw` element has its header and footer in monospace font

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2314] opened 2023-10-04 19:56 UTC
### Description

When a page contains only a `raw` element, its header and footer use a monospace font.

More generally, the header and footer of a page that contains a single visible element will "inherit" from the style of said element.

### Reproduction URL

https://typst.app/project/rxLV7oWr482O7eZ_L5gzSg

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-10-05 08:21
Duplicate of https://github.com/typst/typst/issues/241

**Closed by laurmaedje** 2023-10-05 08:21 UTC
Labels: bug
