### ISSUE TITLE
Watch mode broken in 0.6

### ISSUE THREAD

**Issue by th4s** [typst/typst#1693] opened 2023-07-11 12:55 UTC
### Description

For some reason watching a file for changes with `typst w file.typ` does not always work with the 0.6 version. After downgrading to 0.5 it works again flawlessly, so I suspect that this has to do something with the compiler and not my pdf viewer or editor. 

Used software: Arch Linux, Zathura, Neovim

btw. awesome project :rocket:

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-07-11 13:17
Duplicate of https://github.com/typst/typst/issues/1651. The bug is fixed on main.

**Closed by laurmaedje** 2023-07-11 13:17 UTC
Labels: bug
