### ISSUE TITLE
Allow `#let math.ident = ...` and `sym.ident = ...` bindings

### ISSUE THREAD

**Issue by yaksher** [typst/typst#2635] opened 2023-11-09 21:49 UTC
### Description

Allow binding to `math.` and `sym.` to define custom functions only available directly in math mode.

### Use Case

Useful for when you have lots custom functions for math mode and don't want them polluting the non-math namespace.

**Comment by Enivex** [comment] 2023-11-09 23:48
Duplicate of https://github.com/typst/typst/issues/1749

**Closed by Enivex** 2023-11-09 23:48 UTC
Labels: feature request
