### ISSUE TITLE
How to make a local template globally available in my computer?

### ISSUE THREAD

**Issue by zcorn2017** [typst/typst#776] opened 2023-04-13 12:59 UTC
If I have made a template file by myself, is there any directory (e.g. /usr/bin for shell) for storing it and making it globally available (Importing directly the template file from anywhere without any prefix in the path)?

Thanks in advance.

**Comment by laurmaedje** [comment] 2023-04-13 13:28
Duplicate of #764.

**Closed by laurmaedje** 2023-04-13 13:28 UTC
