### ISSUE TITLE
`/ToUnicode` in PDF can be wrong if a glyph is mapped from multiple code points

### ISSUE THREAD

**Issue by YDX-2147483647** [typst/typst#4582] opened 2024-07-18 11:41 UTC
### Description

Compile the following on typst.app, download PDF, and copy the text.

```typst
#set text(lang: "zh", region: "CN", font: "Noto Serif CJK SC")
力量
```

You will get 力量 (U+F98A U+F97E in CJK *Compatibility* Ideographs), instead of [力量](https://util.unicode.org/UnicodeJsps/confusables.jsp?a=%E5%8A%9B%E9%87%8F) (U+529B U+91CF in CJK *Unified* Ideographs).

CJK Compatibility Ideographs often look bizarre, because they fallback to the system font.

Screenshot of `notepad.exe`:
![notepad screenshot](https://github.com/user-attachments/assets/b6adf4b2-f701-43d1-931d-d82fda6c2acb)

Continues #3416/#3435
Might relate to https://github.com/typst/webapp-issues/issues/48

## Cause

`/ToUnicode` in PDF maps glyphs to Unicode code points, making it possible to copy and search text.
However, sometimes **a glyph** in a font is shared by **multiple code points**.
There are 3 code points mapping to the glyph cid11384 in `SourceHanSerifCN-Regular.otf` (downloaded from [Region Specific Subset OTFs Simplified Chinese (简体中文)](https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/14_SourceHanSerifCN.zip)):

- ⼒ ([U+2F12 KANGXI RADICAL POWER](https://util.unicode.org/UnicodeJsps/character.jsp?a=2F12)): cid11384
- 力 ([U+529B CJK UNIFIED IDEOGRAPH-529B](https://util.unicode.org/UnicodeJsps/character.jsp?a=529B)): cid11384
- 力 ([U+F98A CJK COMPATIBILITY IDEOGRAPH-F98A](https://util.unicode.org/UnicodeJsps/character.jsp?a=F98A)): cid11384

<details>
<summary>(generated by a Python script)</summary>

```python
from unicodedata import name

from fontTools.ttLib import TTFont

font = TTFont("SourceHanSerifCN-Regular.otf")
cmap = font["cmap"].getBestCmap()

the_character = "\u529b"
the_glyph = cmap[ord(the_character)]

for c, g in cmap.items():
    if g == the_glyph:
        print(f"{chr(c)} (U+{c:X} {name(chr(c))}): {g}")

print("---")

for c in "⼒力力":
    print(f"{c} (U+{ord(c):X} {name(c)}): {ord(c) in cmap = }")
```

</details>

Only one code point can be written to `/ToUnicode`, and Typst chooses U+F98A 力 (CJK compatibility).

## Adobe’s implementation

Adobe explicitly maps the glyph to the most used one, U+529B 力 (CJK unified).

[To UVS, Or Not To UVS - CJK Type Blog | Adobe](https://ccjktype.fonts.adobe.com/2019/05/to-uvs-or-not-to-uvs.html):

> A ToUnicode mapping file does exactly what its name suggests: it maps CIDs to Unicode code points, or to code point sequences. Unlike CMap resources that map Unicode code points to CIDs, or 'cmap' tables that map code points to GIDs that may also be CIDs, a ToUnicode mapping file specifies the inverse mapping. Some omissions and ambiguities can arise, either because a glyph is represented as a sequence, or it is mapped from multiple code points.

> An excellent example of the latter is Adobe-Japan1-7 CID+1200, which is mapped from U+2F00 ⼀ KANGXI RADICAL ONE and U+4E00 一 (a CJK Unified Ideograph). If CID+1200 is included in a PDF, one would naturally expect U+4E00 一 to be copied, not U+2F00 ⼀ as its use is more obscure. The Adobe-Japan1-UCS2 ToUnicode mapping file **makes this mapping preference explicit** (04b0 is the zero-padded hexadecimal form of decimal 1200):
>
> ```
> <04b0> <4e00>
> ```

https://github.com/adobe-type-tools/cmap-resources/blob/f5cf3bca7fdfeaceb77aa82847e974f2306c20b4/Adobe-GB1-6/cid2code.txt#L27-L29:

> There may be cases of single CIDs being referenced in multiple encoding points within a single CMap file.
> These cases are comma-delimited, within the same column.

CMap

- Chinese (https://github.com/adobe-type-tools/cmap-resources/blob/f5cf3bca7fdfeaceb77aa82847e974f2306c20b4/Adobe-GB1-6/cid2code.txt#L2629C60-L2629C69):

  ```
  CID	…	UniGB-UCS2
  2543	…	2f12,529b
  ```

- Korean (https://github.com/adobe-type-tools/cmap-resources/blob/f5cf3bca7fdfeaceb77aa82847e974f2306c20b4/Adobe-KR-9/cid2code.txt#L14627C28-L14627C43):

  ```
  CID	…	UniAKR-UTF16
  14593	…	2f12,529b,f98a	
  ```

`/ToUnicode`

- Chinese (https://github.com/adobe-type-tools/mapping-resources-pdf/blob/2dd5e53fb74a01718b9dfd448a0d1cce6fff2aa5/pdf2unicode/Adobe-GB1-UCS2#L1862):

  ```
  <09ef> <529b>
  # <09ef> is 2543 in hex.
  ```

- Korean (https://github.com/adobe-type-tools/mapping-resources-pdf/blob/2dd5e53fb74a01718b9dfd448a0d1cce6fff2aa5/pdf2unicode/Adobe-KR-UCS2#L3525):

  ```
  <3901> <529b>
  # <3901> is 14593 in hex.
  ```

## Further example

```typst
#set page(height: auto, width: 30em)
#set text(lang: "zh", region: "CN", fallback: false)

#let fonts = (
  // "Linux Libertine", // no glyph
  // "Noto Serif", // no glyph
  "Noto Serif CJK SC",
  "Noto Sans CJK SC",
)

#for f in fonts {
  text(font: f)[
    #f

    - ⼒ U+2F12 Kangxi radical
    - 力 U+529B CJK unified
    - 力 U+F98A CJK compatibility

    地球发动机是人类建造的力量最大的机器，比如我们所在的华北794号，全功率运行时能向大地产生150亿吨的推力。

    #pagebreak()
  ]
}
```

Screenshot of the result in a nerd font:
![](https://github.com/user-attachments/assets/90fc79d1-e8d7-4d5b-a409-c55d024ae276)

> [!NOTE]
> This issue cannot be repoduced with `testit cjk --pdf` and https://github.com/typst/typst/blob/42754477886f6a12afbabfd2a64d8c787a57bc03/tests/suite/layout/inline/cjk.typ, because https://github.com/typst/typst-dev-assets/blob/48a924d9de82b631bc775124a69384c8d860db04/files/fonts/NotoSerifCJKsc-Regular.otf does not contain U+2F12 ⼒ (Kangxi radical) and U+F98A 力 (CJK compatibility).

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2024-07-18 11:52
https://zhuanlan.zhihu.com/p/704523436

related discussion(in chinese) by the author of pLaTeX-ng.

**Comment by YDX-2147483647** [comment] 2024-07-18 11:58
Besides, https://itextpdf.com/sites/default/files/2018-12/PP_Advanced_typography_in_PDF-compressed.pdf mentioned a transposed problem:

![IMG_9454](https://github.com/user-attachments/assets/02e8aa8b-e9ea-4a98-9b7d-9d6ce15eb58a)

But I cannot read this language, and have not idea if Typst supports it.

**Comment by LaurenzV** [comment] 2024-07-18 13:15
Somewhat relevant issues: https://github.com/typst/typst/issues/526 https://github.com/typst/typst/issues/4225

**Comment by laurmaedje** [comment] 2024-07-18 13:27
Isn't this a direct duplicate of #4225?

**Comment by LaurenzV** [comment] 2024-07-18 13:40
Not sure, but since this issue is pretty descriptive I think it makes sense to keep it open.

**Comment by laurmaedje** [comment] 2024-07-18 14:23
Yeah, I agree that this issue is very well written. Perhaps we could close the other one instead.

**Comment by YDX-2147483647** [comment] 2024-07-18 14:43
> Isn't this a direct duplicate of #4225?

Well, I think Chinese and devanagari are two distinct issue.

- Here is a normalization problem. Same glyph, different code points. Nothing relies on advanced OpenType features.
- #4225 is more complicated. Single code point, multiple glyphs + OpenType magic (gsub & gpos I guess?) + reordering.

The slide I posted above (https://github.com/typst/typst/issues/4582#issuecomment-2236318013) describes #4225. (I unhide it from off-topic now.)

**Comment by laurmaedje** [comment] 2024-07-18 15:00
Okay, I guess we can keep both issues open. But I think a proper solution will fix both. Probably it is writing `/ToUnicode` for one (e.g. the most common) and then using `/ActualText` everywhere else.

**Comment by YDX-2147483647** [comment] 2024-07-18 15:07
A rough example in European languages might be helpful.

- Chinese: We write _Apple_ in English, but Typst gives _Αpple_, where _Α_ is U+391 GREEK CAPITAL LETTER ALPHA instead of U+41 LATIN CAPITAL LETTER A.
- Indic: We write _Äpfel_ in German, but Typst gives _Af¨pel_.

**Comment by YDX-2147483647** [comment] 2024-07-19 04:11
### How the code point is chosen now

Among Kangxi radical (⼒), CJK unified (力), CJK compatibility (力), Typst tends to choose CJK compatibility.
But Apple, Microsoft, and Adobe products tend to choose Kangxi radical, according to the Chinese article mentioned in https://github.com/typst/typst/issues/4582#issuecomment-2236307948 and [a Japanese report of 有限会社サイパック](https://www.cypac.co.jp/m/153).

Typst chooses CJK compatibility because it has larger Unicode code point number.

When `write_normal_text()`, Typst records the code point that occurs *first* for each glyph. Later in `improve_glyph_sets()`, Typst replaces code points from the font's cmap table. If a glyph is mapped from multiple code points, it gets replaced multiple times, and the *largest* code point wins at last.

https://github.com/typst/typst/blob/42754477886f6a12afbabfd2a64d8c787a57bc03/crates/typst-pdf/src/page.rs#L55

https://github.com/typst/typst/blob/42754477886f6a12afbabfd2a64d8c787a57bc03/crates/typst-pdf/src/font.rs#L237

```rust
for subtable in ttf.tables().cmap.into_iter().flat_map(|table| table.subtables) {
    …

    //+ println!("{subtable:?}");
    subtable.codepoints(|n| {
        let Some(c) = std::char::from_u32(n) else { return };
        …

        let Some(GlyphId(g)) = ttf.glyph_index(c) else { return };
        if glyph_set.contains_key(&g) {
            //+ if g == 9885 {
            //+     println!("{g:?}: {:?} → {c:?}", glyph_set.get(&g));
            //+ }
            glyph_set.insert(g, c.into());
        }
    });
}
```

```rust
Subtable { platform_id: Unicode, encoding_id: 3, format: SegmentMappingToDeltaValues(Subtable4 { ... }) }
9885: Some("⼒") → '⼒'  # Kangxi radical (occurs first) → Kangxi radical
9885: Some("⼒") → '力'  # Kangxi radical → CJK unified
9885: Some("力") → '力'  # CJK unified → CJK compatibility
Subtable { platform_id: Unicode, encoding_id: 4, format: SegmentedCoverage(Subtable12 { ... }) }
9885: Some("力") → '⼒'  # CJK compatibility → Kangxi radical
9885: Some("⼒") → '力'  # Kangxi radical → CJK unified
9885: Some("力") → '力'  # CJK unified → CJK compatibility
Subtable { platform_id: Unicode, encoding_id: 5, format: UnicodeVariationSequences(Subtable14 { ... }) }
Subtable { platform_id: Windows, encoding_id: 1, format: SegmentMappingToDeltaValues(Subtable4 { ... }) }
9885: Some("力") → '⼒'  # Same as last loop
9885: Some("⼒") → '力'
9885: Some("力") → '力'
Subtable { platform_id: Windows, encoding_id: 10, format: SegmentedCoverage(Subtable12 { ... }) }
9885: Some("力") → '⼒'  # Same as last loop
9885: Some("⼒") → '力'
9885: Some("力") → '力'
```

OpenType offers tables for many platforms and encodings (Windows/Unicode, full repertoire / BMP, etc.), and Typst iterates all of them.

<details>
<summary>Details on those tables</summary>

[`getBestCmap` - cmap: Character to Glyph Index Mapping Table — fontTools Documentation](https://fonttools.readthedocs.io/en/latest/ttLib/tables/_c_m_a_p.html#fontTools.ttLib.tables._c_m_a_p.table__c_m_a_p.getBestCmap): (updated according to [cmap - Character To Glyph Index Mapping Table (OpenType 1.9.1) - Typography | Microsoft Learn](https://learn.microsoft.com/en-us/typography/opentype/spec/cmap))

> By default it will search for the following (platform ID, platform encoding ID) pairs in order:
>
> ```
> (3, 10), # Windows Unicode full repertoire		[format 12 subtable]		d
> (0, 6),  # Unicode full repertoire (format 13 subtable)
> (0, 4),  # Unicode 2.0 full repertoire			[format 10 or 12 subtable]	b
> (3, 1),  # Windows Unicode BMP					[format 4 subtable]			c
> (0, 3),  # Unicode 2.0 BMP						[format 4 or 6 subtable]	a
> (0, 2),  # ISO/IEC 10646 semantics				[deprecated]
> (0, 1),  # Unicode 1.1 semantics				[deprecated]
> (0, 0)   # Unicode 1.0 semantics				[deprecated]
> ```
>
> This particular order matches what [HarfBuzz](https://harfbuzz.github.io/) uses to choose what subtable to use by default. This order prefers the largest-repertoire subtable, and among those, prefers the Windows-platform over the Unicode-platform as the former has wider support.

[`ttf\_parser::cmap` - Rust](https://docs.rs/ttf-parser/latest/ttf_parser/cmap/):

> - A [format 0](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-0-byte-encoding-table) subtable.
> - A [format 2](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-2-high-byte-mapping-through-table) subtable.
> - A [format 4](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values) subtable.
> - A [format 6](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-6-trimmed-table-mapping) subtable.
> - A [format 10](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-10-trimmed-array) subtable.
> - A [format 12](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-12-segmented-coverage) subtable.
> - A [format 13](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-13-segmented-coverage) subtable.
> - A [format 14](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-14-unicode-variation-sequences) subtable.

</details>

**Closed** 2024-07-20 14:20 UTC
Labels: bug, pdf
