### ISSUE TITLE
SVG renders with weird gaps in PDF export

### ISSUE THREAD

**Issue by GoldsteinE** [typst/typst#4214] opened 2024-05-21 19:55 UTC
### Description

This SVG
![weird](https://github.com/typst/typst/assets/12019211/b534cd92-e2a9-4f61-ae63-7fd8e211a05e)
renders like this 
![screenshot](https://github.com/typst/typst/assets/12019211/a563204a-03bb-4c93-b43e-f1bae86c67e9)
in PDF export (notably not in web preview nor in PNG export).

### Reproduction URL

https://typst.app/project/rX20c4Hxx56g8RFJIQF0TA

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2024-05-21 19:57
Hi, this seems to be a duplicate of https://github.com/typst/typst/issues/4110

**Comment by GoldsteinE** [comment] 2024-05-21 20:01
Yeah, I think so. This reproduces with rsvg-convert, so probably not a Typst bug. Thanks for the pointer! I guess I’ll just use PNG.

**Comment by LaurenzV** [comment] 2024-05-21 20:06
Similar issues have been reported quite often, so look like it does happen a lot... I wish there were something I could do against it, but I don't think there is...

**Closed** 2024-05-21 21:49 UTC
Labels: bug
