### ISSUE TITLE
Ability to handle raw svg strings with #image

### ISSUE THREAD

**Issue by taylorh140** [typst/typst#1638] opened 2023-07-01 04:12 UTC
### Description

a way of feeding raw images into typst to be rendered. 
so to make things compatible (no breaks) you could introduce a type to the image function where the default is "path"

#image("./File.jpg")
but you could also say explicitly:
#image("./File.jpg",from:"path")

or you could use raw svg
#image("<svg ....>",from:"svg")

### Use Case

I can use svg generated from plugins and display it.

**Comment by laurmaedje** [comment] 2023-07-03 07:36
Duplicate of #1084.

**Closed by laurmaedje** 2023-07-03 07:36 UTC
Labels: feature request
