### ISSUE TITLE
Make apostrophes fit tightly

### ISSUE THREAD

**Issue by StrangeGirlMurph** [typst/typst#1426] opened 2023-06-06 09:26 UTC
### Description

The way LaTeX deals with apostrophes is way prettier in my opinion. I would love to see typst adapt this too!
Apostrophes should be positioned like superscripts.

Typst: `$ a_1', a'_1 $`
![image](https://github.com/typst/typst/assets/62220780/1e7b5be9-dc5d-4fbd-9ba9-fc2706899b98)

LaTeX: `$$ a_1', a'_1$$`
![image](https://github.com/typst/typst/assets/62220780/f8b2889a-8829-44d9-95f8-2d82d98cc7c3)

Typst: `$ a_1^'' $`
![image](https://github.com/typst/typst/assets/62220780/947361b1-f950-4271-809a-52d4fd94ce69)
As you can see using `^'` isn't really a solution. The spacing is off and the apostrophe is positioned to high.

### Use Case

It's just about beauty.

**Comment by Enivex** [comment] 2023-06-06 09:43
Duplicate of https://github.com/typst/typst/issues/439

**Closed** 2023-06-06 09:43 UTC
Labels: feature request
