### ISSUE TITLE
show par: set block doesn't override as expected

### ISSUE THREAD

**Issue by ror3d** [typst/typst#1965] opened 2023-08-20 13:46 UTC
### Description

My Typst compiler version is 0.7.0.

Multiple instances of the `show` directive are not executed in the expected order.

My document has a `show par: set block(...)` at the beginning, but I want to override it in a later section, but this doesn't appear to be possible, because it looks as if they are taken into account in the reverse order given, either that or only the first one is ever taken into account.

For example:

```
#show par: set block(below: 4em)
#show par: set block(below: 1em)

#lorem(30)

#lorem(30)
```

Produces 

![image](https://github.com/typst/typst/assets/1844478/bad52bb0-ee68-466b-aaeb-68cd723b4732)

instead of the expected 1em separation.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2023-08-20 14:03
Duplicate of #351.

**Comment by LaurenzV** [comment] 2023-08-20 14:04
Duplicate of #351.

**Closed by LaurenzV** 2023-08-20 14:04 UTC
Labels: bug, duplicate
