### ISSUE TITLE
bug: Auto-scroll does not work for Chinese characters

### ISSUE THREAD

**Issue by HeMuling** [typst/typst#882] opened 2023-04-19 05:01 UTC
Auto-scroll doesn't work for Chinese characters. When typing, it scrolls to the first page or the previous page.

The issue happens no matter the document language is `zh` or `en`.

The auto-scroll works well when type a small amount of Chinese characters among English characters, but fails when type (both English and Chinese characters) among a large number of Chinese characters.

**Comment by Enivex** [comment] 2023-04-19 13:27
Is this a duplicate of https://github.com/typst/typst/issues/879 ?

**Comment by HeMuling** [comment] 2023-04-19 13:45
> Is this a duplicate of #879 ?


I have no idea what is forward search, but I think they are different bugs

**Comment by Enivex** [comment] 2023-04-19 13:47
Forward search is the feature that makes the preview jump to where you're typing in the source.

**Comment by HeMuling** [comment] 2023-04-19 13:54
> Forward search is the feature that makes the preview jump to where you're typing in the source.

ah, that case it’s duplicate

**Comment by HeMuling** [comment] 2023-04-19 13:54
Duplicate of https://github.com/typst/typst/issues/879

**Comment by reknih** [comment] 2023-04-19 14:36
I forgot to convert between UTF-8 and UTF-16 indices. This is now fixed.

**Closed by reknih** 2023-04-19 14:36 UTC
Labels: bug, duplicate, web app, ide
