### ISSUE TITLE
Join multiple citations when using `@label` syntax.

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1712] opened 2023-07-13 12:34 UTC
### Description

Make `@a@b@c` the same as `#cite("a", "b", "c")` i.e., join them depending on the citation style to, e.g., `[32, 33, 4]`.

### Use Case

Citing multiple source at once, avoiding having to either write the explicit function call or accept the additional brackets.

**Comment by laurmaedje** [comment] 2023-07-17 09:27
Duplicate of https://github.com/typst/typst/issues/1606

**Closed by laurmaedje** 2023-07-17 09:27 UTC
Labels: feature request
