### ISSUE TITLE
Cannot parbreak after an image/equation

### ISSUE THREAD

**Issue by whooie** [typst/typst#2350] opened 2023-10-10 02:14 UTC
### Description

Am I missing something about how parbreaks work? It looks like it's impossible to end a paragraph using an equation or image, even when using `parbreak`, unless there's some kind of text inserted after.

Minimal example:

```typst
#set page(width: 6in, height: auto)
#set par(first-line-indent: 1cm)

#lorem(20)

#lorem(20) // this paragraph has an indent
#align(center, image("image.png", width: 35%))
#parbreak()

#lorem(20) // this one doesn't
$ a^2 + b^2 = c^2 $
#parbreak()

#lorem(20) // neither does this one
```

![noparbreak](https://github.com/typst/typst/assets/15965124/b9c6d0d8-fd74-48bc-b8ed-c7b6bae7eb60)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-10-10 05:38
You don't have to insert explicit `parbreak()` calls if all you want is to create new paragraphs (for that, just insert an empty line). With that said, the current paragraph indentation algorithms will only indent _consecutive paragraphs of text_, so adding something with a block-like (i.e., non-inline) display - which is almost any element in Typst, other than those related to text markup, such as `strong` - will (in my understanding) cause Typst to understand you broke the paragraph flow and thus not indent the next paragraph (as that'd be the "first" paragraph). Possible solutions here include:

1. Manually re-indenting the following paragraph, e.g. by writing `#h(1em)` (replacing `1em` by your actual paragraph indentation) before its first word.
2. Wrapping the block-like content which is breaking the two paragraph sequences apart inside a `box`, thus forcing it to become an inline element (even if not visually, with the appropriate settings). Using a box with a width of 100% should allow you to simulate block-like display of elements recognized as inline (since `box` is always considered inline).

For instance, in your case, both solutions are presented below (I replaced your image with a rectangle to make the example more portable):

```typ
#set page(width: 6in, height: auto)
#set par(first-line-indent: 1cm)

#lorem(20)

#lorem(20) // this paragraph has an indent
#box(width: 100%, align(center, rect(width: 32pt, height: 32pt, fill: red)))

#lorem(20) // this one doesn't
$ a^2 + b^2 = c^2 $

#h(1cm) #lorem(20) // neither does this one
```

The above produces:

![image](https://github.com/typst/typst/assets/9021226/789f3b99-66c4-4a99-90de-cd7b89dcb665)

**Comment by laurmaedje** [comment] 2023-10-10 09:02
Duplicate of https://github.com/typst/typst/issues/311

**Closed by laurmaedje** 2023-10-10 09:02 UTC
Labels: bug
