### ISSUE TITLE
High inline equation interfere with each other

### ISSUE THREAD

**Issue by Enter-tainer** [typst/typst#3748] opened 2024-03-21 13:07 UTC
### Description

```
#lorem(20) $1/(1/(1/(1/123456)))$ #lorem(14) $12345667/1/1/1/1/1/1/1$
```
<img width="688" alt="image" src="https://github.com/typst/typst/assets/25521218/35caf4f2-743f-48e2-98ab-9395cb22491a">

### Reproduction URL

https://typst.app/project/r1o6cuKzep5LSFWlJHXSi4

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2024-03-21 13:10
I've searched issues and don't find a duplicate. I think this is a long existing problem and the standard response to this is "don't use `display` in inline equation". 😇 

It seems that typst attempt to increase line height but still failed to do it correct. I think it would make sense to fix it

**Comment by Enter-tainer** [comment] 2024-03-21 13:17
Comparing with overleaf: 
<img width="544" alt="image" src="https://github.com/typst/typst/assets/25521218/18b79cdc-9732-4230-b2ad-e43b29f7c19c">

```tex
\documentclass{article}
\usepackage{graphicx} % Required for inserting images

\title{test}
\date{March 2024}

\begin{document}

\maketitle

\section{Introduction}

Lorem Ipsum is simply dummy text of the $\frac{1}{\frac{1}{\frac{1}{\frac{1}{123456}}}}$ printing and typesetting industry. Lorem Ipsum has been the industry's $\frac{\frac{\frac{\frac{123456}{1}}{1}}{1}}{1}$ standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.


\end{document}

```

**Comment by Enter-tainer** [comment] 2024-03-21 13:23
The frac tower can be reduced to 3/2 layers and still reproduce the problem:

```typ
#lorem(20) $1/(1/123456)$ #lorem(14) $12345667/1/1$
```

<img width="705" alt="image" src="https://github.com/typst/typst/assets/25521218/8593bd63-5dfc-46cb-827a-59f9a9e9c56b">

```typ
#lorem(20) $1/123456$ #lorem(14) $12345667/1/1$
```
<img width="685" alt="image" src="https://github.com/typst/typst/assets/25521218/5c0075fa-0d2e-4e8d-9c23-d85fa70db7f9">

**Comment by Enter-tainer** [comment] 2024-03-21 13:29
<img width="614" alt="image" src="https://github.com/typst/typst/assets/25521218/f98f65d8-d647-44f7-9bd9-a99333a7114b">

By adding a 0.1pt stroke, it seems that the bbox(or is it?) of these 2 frac tower is a little bit off. Idk if this is the root cause

```
#lorem(20) #box(stroke: 0.1pt)[$1/(1/(1/(1/123456)))$] #lorem(14) #box(stroke: 0.1pt)[$12345667/1/1/1/1/1/1/1$]
```

**Comment by laurmaedje** [comment] 2024-03-21 13:43
Duplicate of https://github.com/typst/typst/issues/1028. Feel free to report relevant information there.

**Closed by laurmaedje** 2024-03-21 13:43 UTC
Labels: bug
