### ISSUE TITLE
pdf support as a vector graphic format (like LaTeX)

### ISSUE THREAD

**Issue by edrihan** [typst/typst#4614] opened 2024-07-24 22:12 UTC
### Description

I'm interested in using Typst with graphics. I'm wondering if it will be possible to support .pdf as a vector format so that the following code works:

`#image("vector_graphic.pdf")`

### Use Case

A lot of times, if you're starting from scratch, you could just use `.svg` as a vector format. But let's say my assets are already rendered as `.pdf`. I'd like to be able to use the assets as-is, without having to convert them to `.svg`. I'm using `.pdf` files because another library I'm using as part of my workflow is compatible with them, and not with `.svg`

**Comment by LaurenzV** [comment] 2024-07-24 22:18
Duplicate of #145.

**Closed by LaurenzV** 2024-07-24 22:18 UTC
Labels: feature request
