### ISSUE TITLE
SVG with ICC colors is not rendered correctly

### ISSUE THREAD

**Issue by Wongboo** [typst/typst#3974] opened 2024-04-21 13:50 UTC
### Description

svg rendered weired
<img width="461" alt="截屏2024-04-21 21 49 45" src="https://github.com/typst/typst/assets/44860323/ce8a711f-fa9d-4993-b26d-290eacdcc7d7">
<img width="754" alt="截屏2024-04-21 21 50 15" src="https://github.com/typst/typst/assets/44860323/e9a88661-4133-40cf-8bab-02b4c7d1418c">

### Reproduction URL

https://typst.app/project/ph2HV071Y0tJ1lVojf8ytt

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2024-04-21 14:23
The project does not seem to be accessible, can you post the SVG here?

**Comment by Wongboo** [comment] 2024-04-22 02:14
https://typst.app/project/wW5kE31GRsDhL6TcmJ0eIg this can be seen and edited.

**Comment by LaurenzV** [comment] 2024-04-22 06:41
Ah I see now... The problem is that your SVG seems to use icc colors, which is currently not supported by the upstream crate. So if you somehow have control over that, you should try to change it so it uses "normal" rgb colors. But a bug nevertheless.

**Comment by Wongboo** [comment] 2024-04-22 06:55
Thank you for your reply! I now see how the problem happens.
BTW, Is there any CLI tool to convert icc to rgb? inkscape seems can't.

**Comment by LaurenzV** [comment] 2024-04-22 06:58
Not that I know of, unfortunately. :(

**Comment by Enivex** [comment] 2024-04-22 10:30
> Ah I see now... The problem is that your SVG seems to use icc colors, which is currently not supported by the upstream crate. So if you somehow have control over that, you should try to change it so it uses "normal" rgb colors. But a bug nevertheless.

Is this a duplicate of https://github.com/typst/typst/issues/3781 ?

**Comment by LaurenzV** [comment] 2024-04-22 10:40
No, this is a different issue.

**Comment by joneuhauser** [comment] 2024-08-30 11:23
@Wongboo et al. Martin from the Inkscape project is currently working on full ICC support for Inkscape. This is an enormous project, but as soon as https://gitlab.com/inkscape/extensions/-/merge_requests/646 is completed it should be trivial to do what you need.

**Closed** 2024-12-18 17:26 UTC
Labels: bug, svg, upstream
