### ISSUE TITLE
Expose Language and Region in current Styles

### ISSUE THREAD

**Issue by Drodt** [typst/typst#2062] opened 2023-09-04 06:14 UTC
### Description

At the moment, as far as I can see, there is no way to discover what the currently active language at any location is. The `style` function only exposes measurements, but not the `lang` or `region` property for text elements.

My proposal would be to expose `TextElem::lang_in` and `TextElem::region_in` to the user/developer. I suggest to either add `lang(styles)` and `region(styles)` functions, or have these as fields on `styles`.

### Use Case

Some packages might add items that are dependent on the current language. For instance, a smart quotes package or a package which adds some caption or heading. Exposing the language empowers package developers.

**Comment by laurmaedje** [comment] 2023-09-04 07:11
Duplicate of #763

**Closed by laurmaedje** 2023-09-04 07:11 UTC
Labels: feature request
