### ISSUE TITLE
`#show regex` not handling all cases

### ISSUE THREAD

**Issue by japgolly** [typst/typst#4793] opened 2024-08-20 06:26 UTC
### Description

This code

```
#show regex("\\(.*\\)"): it => text(red)[#it]

(123)

(...)

(a b c)

(. x .)

(x)

( x)

(x )

( x )

(.)

( .)

(. )

( . )

(qwe)
```

is being rendered like this:
<img width="99" alt="Screenshot 2024-08-20 at 4 26 26 PM" src="https://github.com/user-attachments/assets/ae827426-68d6-4568-8be8-785231741ced">

All the lines should be in red.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by japgolly** [comment] 2024-08-20 06:32
Even without regex, this doesn't work. In the following example, nothing is shown in red.

```
#show "(...)": it => text(red)[#it]
#show "( . . . )": it => text(red)[#it]
#show "(. . .)": it => text(red)[#it]

(...) ( . . . ) (. . .)
```

**Comment by flokl** [comment] 2024-08-20 06:35
This is a known issue. The exaples that don't work consist of multiple text nodes and those can't be mached. Duplicate of Duplicate of #86.

**Closed** 2024-08-20 06:50 UTC
Labels: bug
