### ISSUE TITLE
Adjust superscript and subscript baselines for lr-scaled characters

### ISSUE THREAD

**Issue by jkunimune** [typst/typst#4204] opened 2024-05-21 04:08 UTC
### Description

Superscripts and subscripts move up or down, respectively, when they are attached to a naturally tall character like `sym.integral`, or to parentheses that have been scaled up.  But they don't adjust for other characters that are made tall using `#lr`.  It seems to me that they should.

![Superscripts and subscripts on a variety of characters, demonstrating how they fail to spread out appropriately for the scaled-up pipe](https://github.com/typst/typst/assets/5607801/4a5c5e81-c609-4ec3-bb04-d8fd694c0cc9)

### Use case

I'm mainly thinking of the use of | to mean "evaluated at".  If I want to do something like this:
![dy/dx | x=0](https://github.com/typst/typst/assets/5607801/595776f0-39a4-40e9-b049-5eea13c98ebe)
I need the "x=0" to move to the bottom of the bar or else it looks very awkward.

### Example Typst project

https://typst.app/project/rENbxvHSopJ6MM04mIyQNL

**Comment by Enter-tainer** [comment] 2024-05-21 06:06
<img width="87" alt="image" src="https://github.com/typst/typst/assets/25521218/18ca83f6-13b0-4415-bf3c-a6bdd6ca4025">
$
lr((dif x)/(dif y)|)_(x=0)
$

**Comment by Enivex** [comment] 2024-05-21 09:30
Duplicate of https://github.com/typst/typst/issues/2342

But yes, see @Enter-tainer comment

**Closed** 2024-05-21 09:30 UTC
Labels: feature request
