### ISSUE TITLE
measure function does not measure paragraphs correctly

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#679] opened 2023-04-08 18:45 UTC
Code that uses measure function:
```
#let part(title: "", body) = style(styles => {
  let body = {
    heading(
      level: 2,
      numbering: (..nums) => numbering("(a)", nums.pos().last()),
      title
    )

    set enum(numbering: "i.")

    body
  }

  grid(
    columns: 2,
    gutter: 0.5em,
    line(angle: 90deg, length: measure(body, styles).height),
    body,
  )
})
```

Render:
```
#part[
  + #lorem(100)
]
```

![image](https://user-images.githubusercontent.com/9490724/230737844-991d79c2-c812-4c9e-84d2-92e8af930421.png)

The line should extend the entire length of the list.

**Comment by SUPERCILEX** [comment] 2023-04-09 21:05
Oh actually this has nothing to do with lists, `#part[#lorem(100)]` is just as broken.

**Comment by SUPERCILEX** [comment] 2023-04-09 21:17
Simpler example:
```
#style(styles => grid(
  columns: 2,
  line(angle: 90deg, length: measure(lorem(1000), styles).height),
  lorem(1000),
))
```

**Comment by laurmaedje** [comment] 2023-04-10 08:52
This is actually working as intended because measure always measures in an infinite space. As it can be freely used in the script, it doesn't know how much horizontal space will be available. #557 was recently merged, which allows you to get the available width/height. You can then use that as the width of a block and measure that block's height. I'll make sure to add some documentation to `measure` before `layout` goes live.

**Comment by SUPERCILEX** [comment] 2023-04-10 16:21
That sounds perfect, thanks! I'll leave this open for the docs.

**Closed** 2023-04-23 12:37 UTC
Labels: docs
