### ISSUE TITLE
In Math Mode, single letters wrapped in quotes are not displayed in Text font

### ISSUE THREAD

**Issue by pothos-dev** [typst/typst#980] opened 2023-04-25 14:51 UTC
### Description

In Math Mode (enclosed in $), we can write non-mathy symbols by wrapping them in quotes.

One usecase is to add units to numbers, like so:
```
$ Delta h = -((100"m"))/(sin^2 (50"gon")) (2"mgon") $
```
![image](https://user-images.githubusercontent.com/15155173/234315231-e5ef77df-5f48-4c87-be2d-4493ceea2032.png)

As you see in the image, text strings that consist of single letters only are rendered in the Math Font, not in the Text Font. Typst seems to interpret these as single letter variable names.

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by PgBiel** [comment] 2023-04-25 14:53
Duplicate of https://github.com/typst/typst/issues/274

Try using something like `"m "` or `upright(m)` as a workaround for now.

**Comment by Enivex** [comment] 2023-04-25 15:08
I think you mean upright. The text font isn't used for text of any length in math mode.

https://github.com/typst/typst/issues/366

**Closed** 2023-04-25 19:53 UTC
Labels: bug, duplicate
