### ISSUE TITLE
Inconsistant dictonary iteration behavior with content vs. expression

### ISSUE THREAD

**Issue by nitz** [typst/typst#2700] opened 2023-11-16 17:05 UTC
### Description

The automatic joining functionality of looping through a dictionary works in an inconsistent and unexpected way depending on if content or expressions are returned.

The behavior of returning expressions from the loop has the ability to "lose" iterations depending on the type of expression returned. In particular, returning a dictionary causes the iteration to _only_ return the final dictionary, and all earlier ones are lost. I think this behavior is at best confusing and rarely what an author intends.

Screenshot:
![image](https://github.com/typst/typst/assets/602691/fdb2fa07-bd51-4d53-9786-53330b8834e1)

Source:
```
// dummy data
#let myDict = (
  a: "foo",
  b: "bar",
  c: "baz",
  d: "qux",
)

// a function that makes a dictionary out of the two parameters
#let makeXY(x, y) = {
  (x: x, y: y)
}

\#1. Printing keys and values #linebreak()
Works as expected.

#for (k, v) in myDict {
  k + ": " + v + linebreak()
}

\#2. Printing "XY" content from keys and values #linebreak()
Works as expected.

#for (k, v) in myDict {
  [ #makeXY(k, v) #linebreak() ]
}

\#3. Outputting a single *array* expression from keys and values #linebreak()
Works as expected.

#for (k, v) in myDict {
  (k,)
}

\#4. Outputting "XY" *dictionary* expression from keys and values #linebreak()
Only last element shown, does not work as expected.

#for (k, v) in myDict {
  makeXY(k, v)
}

\#5. Outputting "XY" *array* expression from keys and values #linebreak()
Works as expected, but this is the behavior I had assumed \#4 would produce.

#for (k, v) in myDict {
  (makeXY(k, v),)
}
```

Cheers and thanks a heap!

### Reproduction URL

https://typst.app/project/rxNys3KjfbyLESBX0KE-s-

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2023-11-16 17:41
A dictionary can only have one value per key. If every iteration produces a dictionary with the same key, only the last one will remain.

Do you want literally "x" as the key or rather the value of the variable x? In the latter case, you need to manually create an empty dictionary with `(:)` and call `.insert` on it with the pair. In the next Typst version (already on main), this will become easier as you can just write `((key): value)` to force the key to be evaluated.

**Comment by nitz** [comment] 2023-11-16 18:18
The case where I ran into this I was trying to produce an array of dictionaries (like in example 5.)

From my point of view, each iteration of the loop was returning a single dictionary object and I had expected them to all be returned as a single array. Similar to how in example 1, each value is present (despite being all joined into a single object.)

While the explanation of `A dictionary can only have one value per key.` makes perfect sense, I think it was how the loop's "join" behavior works with the dictionary that was the gotcha for me:

In none of the other cases (be it content, or array) is there any chance for any of the previously iterated values to be overwritten. Only in the dictionary loop returning a dictionary is there the potential for the overwriting of previous results.

Does my explanation make sense or do I sound completely out of left field? 😂

**Comment by laurmaedje** [comment] 2023-11-16 21:20
I see what you mean. There are some ideas and plans which impact joining. Those might alleviate this issue by having joining always perform the content-like join instead of having special behaviour for arrays and dictionaries.

That said, for now it does work as intended for now, so I'm gonna close this.

**Closed by laurmaedje** 2023-11-16 21:20 UTC
Labels: bug
