### ISSUE TITLE
Error : `expected closing paren` using `lr`

### ISSUE THREAD

**Issue by Doublonmousse** [typst/typst#3183] opened 2024-01-12 18:24 UTC
### Description
# `error: expected closing paren` when using `lr`

The following code 
```
$
lr(] 1/2, 3/2]) //is a correct syntax
$ 
```
will work but the following other ones will not :
```
$
lr([1/2,3/2[)
$

// other examples (minimal examples here, would fail if one opening paren doesn't have its corresponding closing partner)
$
lr({ ) //same thing with {
$

$
lr(() //same thing with (
$
```

With the following set of errors from the compiler 
```
error: expected closing paren
   ┌─ lr closin paren.typ:10:13
   │
10 │ lr([1/2,3/2[)
   │              ^

error: expected closing paren
   ┌─ lr closin paren.typ:15:6
   │
15 │ lr({ ) //same thing with {
   │       ^

error: expected closing paren
   ┌─ lr closin paren.typ:19:5
   │
19 │ lr(() //same thing with (
   │      ^

```

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment] 2024-01-12 21:41
Any kind of visible opening delimiter matches any kind of closing delimiter in math. So `[)` is a matching automatic lr group.

For a function call however, only a closing parenthesis can terminate the argument list.

For this reason, `lr(]])` works, but in `lr([[)` the closing paren is matched with the second opening bracket.

It can always be fixed by escaping the brackets.

**Comment by Doublonmousse** [comment] 2024-01-12 22:22
Oh I had absolutely no idea that `$lr(\[ \[)$` would even work and I was stuck.

The thing is the $]a,b], [a,b[$ notation is very commonly used for intervals in France whereas this would usually be denoted $(a,b],[a,b)$ in other countries so having only this exact combination not work when the other intervals do is very confusing (also applies to subscript, `$1_]a,b]$` and `$1_]a,b[$` will not put the interval in subscript but other combinations will, although in this case the fix is pretty simple).

Although changing the opening/closing delimiter logic to accommodate the French interval notation might prove challenging (`[ [` is two opening brackets in the current system that may or not match depending on context !).  But I'm not sure `[ [` is less common used than `{ )` and `( }` (these two are also matched under this logic).

The other possible thing would be to have a more helpful error message when this error is raised in the presence of a `lr` environment proposing to escape the delimiters (as all of these errors are raised upon not finding the closing paren for the opened `lr` environment)

**Comment by laurmaedje** [comment] 2024-01-15 11:33
We can further discuss whether we can somehow improve the rules or diagnostics, but since it's right now working as intended, I'm gonna close this for now.

**Closed by laurmaedje** 2024-01-15 11:33 UTC
Labels: bug
