### ISSUE TITLE
Norm delimiter width inconsistent?

### ISSUE THREAD

**Issue by gabrfarina** [typst/typst#611] opened 2023-04-05 20:14 UTC
While playing around with some math, I noticed that the width of the delimiters of norm are inconsistent: for large content, they seem to get scaled horizontally in an undesirable way.

I've included the output from Typst and Latex:
<img width="250" alt="Screenshot 2023-04-05 at 1 39 05 PM" src="https://user-images.githubusercontent.com/737249/230198904-fcfe1777-0c5a-4f22-b433-7c40d82b7d2c.png">
<img width="280" alt="Screenshot 2023-04-05 at 1 42 25 PM" src="https://user-images.githubusercontent.com/737249/230198934-58a410ba-1a9c-4fdc-aa8c-9d62bdca90f6.png">

Also, the size of x and y in the vector are reduced compared to the first norm, but I assume that is desired behavior?

I tried to look into the code for `glyph.stretch_vertical` in `library/src/match/stretch.rs` but I could not spot where the behavior for this might be arising.

Do you know what would be needed to fix this? I'm happy to try to take a crack at it if it's not too complicated 🙂

**Comment by laurmaedje** [comment] 2023-04-06 14:09
The reduces size might result from this being inline math in Typst and display math in TeX? I'm unsure whether this is something we can fix. It might just be how the stretched symbol looks in the font.

**Comment by gabrfarina** [comment] 2023-04-06 14:14
Thanks! I tried to move from inline to block, and the behavior is the same as inline (with the stretched symbols growing larger horizontally. The vertical bars also seem to be thicker.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/737249/230403487-8f7683b7-542a-47c6-b578-0e9638c3cb87.png">

**Comment by Enivex** [comment] 2023-04-06 23:32
What does your actual typst code look like?

**Comment by Enivex** [comment] 2023-04-07 00:08
I can confirm that something is weird

Compare Typst
![image](https://user-images.githubusercontent.com/2191754/230514295-4a68c64b-5c7d-47bf-addf-4eae56a71a92.png)

with LaTeX
![image](https://user-images.githubusercontent.com/2191754/230514331-442c7076-c20a-4984-b402-b5f9457c1d21.png)

In Typst it's like the delimiter is just scaled up. The same thing happens with abs(), and possibly other delimiters.

Compare Typst
![image](https://user-images.githubusercontent.com/2191754/230515132-5fcd6b94-5c63-4557-ae60-f4ed8d1142ff.png)

with LaTeX
![image](https://user-images.githubusercontent.com/2191754/230515144-af87ec98-198c-4f46-bddf-a6a3f46cf112.png)

**Comment by Enivex** [comment] 2023-05-25 19:06
I'm closing this issue, because it's a font issue and not a typst issue.

However I can confirm that the maintainer is working on improving this.

**Closed by Enivex** 2023-05-25 19:06 UTC
Labels: math

**Comment by Leedehai** [comment] 2023-12-06 17:11
It's fixed after https://github.com/typst/typst/pull/2764 is merged.
