### ISSUE TITLE
Quotes in equation are ignored if single character is placed within them

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#960] opened 2023-04-24 10:13 UTC
### Description

![image](https://user-images.githubusercontent.com/9490724/233967303-387a7c61-8ad1-482f-ae1a-84e93ea5bd4e.png)

```
$"a"$
$"aa"$
```

The variable is formatted like a math variable instead of a plain letter which is the point of using quotes.

**Comment by laurmaedje** [comment] 2023-04-24 10:48
Duplicate of #274.

**Closed by laurmaedje** 2023-04-24 10:48 UTC
Labels: bug
