### ISSUE TITLE
Item label and item content are not in same baseline

### ISSUE THREAD

**Issue by mojtaba82** [typst/typst#3942] opened 2024-04-16 10:24 UTC
### Description

Item label and item content are not in same baseline
```
#enum(
  enum.item(1,[
    I am in
    #set text(size: 1.5em, fill: blue)
    Item 1 #lorem(10)
  ])
)
```
![image](https://github.com/typst/typst/assets/4151722/a13aa230-ee04-4681-9065-e18abb7d511b)
 But in latex it work correctly
![image](https://github.com/typst/typst/assets/4151722/83ee3a15-e5fe-4314-a4db-45caf62250fb)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment] 2024-04-16 10:58
Looks like a duplicate of #1204

**Closed** 2024-04-16 11:27 UTC
Labels: bug, duplicate
