### ISSUE TITLE
Paragraph after the list or heading is not indexed properly

### ISSUE THREAD

**Issue by MikuAndRabbit** [typst/typst#1505] opened 2023-06-15 12:16 UTC
### Description

The first paragraph after an ordered list does not indent properly. Here is an example.

Code:
Look at [Test - Web APP](https://typst.app/project/r_Gwgky-2x_fvHC45VQKqb)

Preview:
The paragraphs circled in red are not indented properly.
![](https://github.com/typst/typst/assets/52323820/9e358c91-4e44-4e9c-8019-b9c429a28056)

### Reproduction URL

https://typst.app/project/r_Gwgky-2x_fvHC45VQKqb

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment] 2023-06-15 12:19
Do #311 and #1410 describe your issue?

**Comment by MikuAndRabbit** [comment] 2023-06-15 12:23
> Do #311 and #1410 describe your issue?

Yes, these two issues are the same as the one I described. I didn't notice these two issues before.

**Comment by alerque** [comment] 2023-06-15 12:23
"Properly" here is entirely a matter of style. Many/most style guides I am familiar with in English would inhibit indentation just like this. I know a few others and some languages like French don't do this. Obviously what you want is a way to disable it, but this behavior is not entirely wrong.

**Comment by MikuAndRabbit** [comment] 2023-06-15 12:30
> "Properly" here is entirely a matter of style. Many/most style guides I am familiar with in English would inhibit indentation just like this. I know a few others and some languages like French don't do this. Obviously what you want is a way to disable it, but this behavior is not entirely wrong.

You are correct that there are indeed many genres that do not indent the first paragraph after the HEADING (e.g. some papers). Since I am not a native English speaker, this may be caused by my poor wording.

My point is that if I set `set par(first-line-indent: 2em,)`, then this setting should take effect for all paragraphs. As for these cases where the first paragraph after the title is not indented, it should be set separately or a new par parameter should be specified to achieve this.

**Comment by reknih** [comment] 2023-07-03 08:45
Closed as a duplicate of #311

**Closed by reknih** 2023-07-03 08:45 UTC
Labels: bug, duplicate
