### ISSUE TITLE
Tooltip overlapping link

### ISSUE THREAD

**Issue by m4rt1n0** [typst/typst#5356] opened 2024-11-02 19:50 UTC
### Description

Some tooltips in the online documentation can overlap links, preventing the user from clicking on them unless the page is refreshed. See the documentation for the `body` parameter of the `figure` element for an example: https://typst.app/docs/reference/model/figure/#parameters-body

At first the user can normally click on the link.

![2024-11-02_15-56](https://github.com/user-attachments/assets/2043bae7-0243-453a-a662-9640de3a733f)

The HTML element for the tooltip uses `display: none` from `div[role="tooltip"]` to be invisible and non-interactive.

![2024-11-02_15-57](https://github.com/user-attachments/assets/8efbd1ad-08cf-4593-8e08-2617dfae7922)

If the user touches or hovers over the question mark, the tooltip appears.

![2024-11-02_15-58](https://github.com/user-attachments/assets/aafe8d91-b995-46c6-8ac3-63a572c3f933)

The HTML element now has an inline `display: block` which prevents the user from being able to click the link below it, which is expected while the tooltip is shown.

![2024-11-02_15-58_1](https://github.com/user-attachments/assets/c8522257-a479-4503-ae9c-acd88108a2e7)

Once it's shown, the visibility is toggled by changing the `opacity` attribute but `display: block` remains unchanged, making the tooltip stay interactive even when it's no longer visible. Using `visibility: visible` and `visibility: hidden` might solve this issue, as `hidden` makes the element non-interactive.

**Comment by MDLC01** [comment] 2024-11-02 21:11
Looks like a duplicate of typst/webapp-issues#301.

**Closed** 2024-11-03 09:31 UTC
Labels: docs
