### ISSUE TITLE
Text wrapping issue in typst - long lines of text are not automatically wrapped.

### ISSUE THREAD

**Issue by Swizzzer** [typst/typst#2910] opened 2023-12-11 10:50 UTC
### Description

When a line of text is too long, the pdf compiled by typst does not split it, resulting in the line exceeding the page boundaries when displayed.

### Reproduction URL

https://typst.app/project/pj9n7Xn8-UvijRkmjKcVGV

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment] 2023-12-11 11:04
Failed to initialize: You do not have sufficient permissions to access this project.

**Comment by laurmaedje** [comment] 2023-12-11 11:26
The posted reproduction is not a share link and can only be opened by the owner.

Duplicate of https://github.com/typst/typst/issues/674

**Closed by laurmaedje** 2023-12-11 11:26 UTC
Labels: bug
