### ISSUE TITLE
Header utilizes heading font when there is no paragraph

### ISSUE THREAD

**Issue by m-kru** [typst/typst#4206] opened 2024-05-21 07:39 UTC
### Description

Header (and probably footer) utilizes heading font when there is no paragraph.

`typst 0.11.1 (50115102)`

```typst
#set page(
  header: [
    Left
    #h(1fr)
    Right
  ]
)

#set heading(
  numbering: "1.1.1"
)

= Heading
```

![image](https://github.com/typst/typst/assets/26227737/0f53e3fd-a0d2-42b1-a8c1-17e6638b02d6)

**Comment by laurmaedje** [comment] 2024-05-21 09:22
Duplicate of https://github.com/typst/typst/issues/241

**Closed by laurmaedje** 2024-05-21 09:22 UTC
Labels: bug
