### ISSUE TITLE
Typst 0.11: repetitive citing overrides 'et al' style

### ISSUE THREAD

**Issue by M000S** [typst/typst#3749] opened 2024-03-21 14:30 UTC
### Description

The newest version changed the citation format in-text when I reference one source multiple times and the source has more than one author.

main.typ:
```
Cited once. @ref1

And Cited twice. @ref1
```

library.bib:
```
@article{ref1,
  author = { Firstname Lastname and Firstname2 Lastname2 and Firstname3 Lastname3 and Firstname4 Lastname4},
  title = {Testtitle}
}
```

v0.10.0 (Webapp):
![image](https://github.com/typst/typst/assets/91196779/c027f1f7-a442-4719-9932-0381bf6f44b9)

v0.11.0 (Webapp):
![image](https://github.com/typst/typst/assets/91196779/35065211-0477-4514-9703-1e12c3ae505d)

### Reproduction URL

https://typst.app/project/pkFnYhP75otsHRI6e6cgR7

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment] 2024-03-21 14:52
Duplicate of https://github.com/typst/typst/issues/3699

**Closed** 2024-03-21 14:52 UTC
Labels: bug, duplicate
