### ISSUE TITLE
Emphasizing content also affects header

### ISSUE THREAD

**Issue by Entoryvekum** [typst/typst#1954] opened 2023-08-18 03:47 UTC
### Description

The code below is sopposed to generate a page with its header in normal weight and content in bold, however the emphasis also affects the header.
```
#set page(header: [header])
#text(weight: "bold",[content])
```
![图片](https://github.com/typst/typst/assets/20198566/eaf56c8c-6cb0-4c46-938d-2b511a4a1c17)

This behavior can also be obseved when setting the text to italic as long as there's only a single emphasized line in the page. If any text are put above, below, before, after the piece of text that is emphasized, the page generated is normal.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment] 2023-08-18 07:50
Duplicate of #241.

**Closed by LaurenzV** 2023-08-18 07:50 UTC
Labels: bug, duplicate
