### ISSUE TITLE
Missing () in function call leads to no effect.

### ISSUE THREAD

**Issue by m-kru** [typst/typst#1405] opened 2023-06-04 07:25 UTC
### Description

`#pagebreak` does not break the page and no error is reported that `()` is missing at the end. I am not sure what is the desired behavior, but in my humble opinion ignoring is the worst possible solution. I can see two alternative solutions:

1. `#foo` should be treated the same as `#foo()` - no argument vector is treated the same as empty argument vector.
2. Report an error during parsing - `file: XX: missing () for foo`.

### Use Case

The change of behavior is useful because with current behavior nothing changes if someone forgets to add `()` at the end of function call.

**Comment by andrewragy** [comment] 2023-06-04 08:28
I don't think that's an issue. The behavior aligns with the behavior of other programming languages. If the function isn't called using parentheses, then the function itself is returned.

**Comment by andrewragy** [comment] 2023-06-04 08:33
This is useful in some instances such as this:
```
#let values = (1, 7, 4, -3, 2)
#values.find(calc.even) 
```
where the `calc.even` function is passed to the find method of the array

**Comment by m-kru** [comment] 2023-06-04 08:35
Except, typst is not a programming language, but a typesetting system. I understand your example. However, `#pagebreak` has no effect. In such a case maybe typst should error when instruction has no effect,  `#values.find(calc.even)` has effect.

**Comment by PgBiel** [comment] 2023-06-04 18:07
> Except, typst is not a programming language, but a typesetting system.

The `#` character enters Typst's code mode, which effectively constitutes a programming language, and has all the usual capabilities of one. However, when a warning system is added, this could be a good candidate for a warning ("did you mean ..."). For now, something like a hard error would be excessive, but automatically calling the function doesn't make much sense also.

Note that this is necessary because `pagebreak` is an element (effectively a "class" from programming languages), so you have to construct it with `()`, using the appropriate parameters (e.g. `(weak: true)`).
As an alternative to what you desire, you can pre-construct it and just repeat the constructed pagebreak, like so:

```js
#let break = pagebreak()

#lorem(30)
#break  // this will break the page - no () needed
#lorem(30)
```

**Comment by m-kru** [comment] 2023-06-05 07:46
For user typst  is typesetting system. It has its own internal programming language. However, the internal programming language can't be more important than the user experience of typesetting. It is like when "the tail is wagging the dog".

**Comment by m-kru** [comment] 2023-06-05 07:47
I just think user somehow should be notified that some action has no effect.

**Comment by user202729** [comment] 2023-06-09 16:22
Duplicate of #694

**Closed** 2023-06-10 12:01 UTC
Labels: duplicate, feature request, syntax
